### DISCUSSION TITLE
Expose udp ports

### DISCUSSION THREAD

**Discussion by tinchoz49** [coollabsio/coolify#1014] [Q&A] [answered]
Hey guys,

I'm trying to deploy a turn server and I need to expose `udp` ports from my docker app. Is it possible to do this with the `Exposed Port` option?

**Comment by tinchoz49** [comment, marked as answer]
Ok, this is completely possible using the docker-compose.yml builder. I've got the TURN server working. This is such an amazing project 😲 !!

**Comment by signalwerk** [comment]
@tinchoz49 can you probably share how you did it?

I take a docker-compose and define in it the ports:

```yaml
...
  samba:
    build: ./docker/smb/
    container_name: samba
    restart: unless-stopped
    environment:
      TZ: "Europe/Zurich"
    networks:
      - default
    ports:
      - "137:137/udp" # advertise shares (NMBD)
      - "138:138/udp" # advertise shares (NMBD)
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
...
```

But then I can't connect to it. Do I need to do something else? The firewall should be ok.
