### DISCUSSION TITLE
Reverse proxy settings for external services

### DISCUSSION THREAD

**Discussion by swissbyte** [coollabsio/coolify#1483] [Feature Requests]
Hello

the idea is quite simple:
Imagine, that you run coolify as an lxc on proxmox and forward all traffic on port 80 and 443 to coolify. Now you also ha e some other lxc containers running and you would like to make them available from the internet too.

For this it would be great to habe a section available in the webui where we can add additional reverse proxy settings like with this project:

https://nginxproxymanager.com/

this would be awesome 😍😍😍😍

or do you see a way how to achieve this already today?

thanks

**Comment by fusuyfusuy** [comment]
i would love to see this implemented. currently a workaround is using traefik file providers. terminal into `coolify-proxy` container to `/traefik/dynamic` directory. create a new file for example `external-routers.yaml` and add your route like this:

```
http:
  routers:
    route-http:
      rule: "Host(`<enter-custom-domain>`)"
      entryPoints:
        - "http"
      middlewares:
        - "redirect-to-https"
      service: "route-service"
    
    route-https:
      rule: "Host(`<enter-same-custom-domain>`)"
      entryPoints:
        - "https"
      middlewares:
        - "gzip"
      service: "route-service"
      tls: true

  services:
    route-service:
      loadBalancer:
        servers:
          - url: "<remote-host-url>"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: "https"
    gzip:
      compress: true
```

you can remove https section if you do not want traefik to auto redirect to https.

edit:
You can use this scripts from your host machine to easily add routes:
`add-route.sh`
```sh
#!/bin/bash

# add-external-route.sh
# Usage: ./add-external-route.sh domain.home http://192.168.1.100:8080

set -e

DOMAIN="$1"
REMOTE_URL="$2"
DYNAMIC_DIR="/traefik/dynamic"
CONTAINER_NAME="coolify-proxy"

if [ -z "$DOMAIN" ] || [ -z "$REMOTE_URL" ]; then
    echo "Usage: $0 <domain> <remote_url>"
    echo "Example: $0 printer.home http://192.168.1.100:5380"
    exit 1
fi

# Check if container exists and is running
if ! docker ps --format "table {{.Names}}" | grep -q "^${CONTAINER_NAME}$"; then
    echo "Error: Container '${CONTAINER_NAME}' not found or not running"
    echo "Available containers:"
    docker ps --format "table {{.Names}}\t{{.Status}}"
    exit 1
fi

# Clean domain name for filename
FILENAME=$(echo "$DOMAIN" | sed 's/\./-/g')
FILEPATH="$DYNAMIC_DIR/${FILENAME}.yml"

# Create dynamic directory inside container
docker exec "$CONTAINER_NAME" mkdir -p "$DYNAMIC_DIR"

# Generate Traefik config inside container
docker exec "$CONTAINER_NAME" sh -c "cat > '$FILEPATH' << 'EOF'
http:
  routers:
    ${FILENAME}-router:
      rule: \"Host(\`${DOMAIN}\`)\"
      entryPoints:
        - \"http\"
      service: \"${FILENAME}-service\"

  services:
    ${FILENAME}-service:
      loadBalancer:
        servers:
          - url: \"${REMOTE_URL}\"
EOF"

echo "✓ Created route: $DOMAIN -> $REMOTE_URL"
echo "✓ Config saved to: $CONTAINER_NAME:$FILEPATH"
echo "✓ Traefik will auto-reload in ~5 seconds"

# Show the created file
echo ""
echo "Created config:"
docker exec "$CONTAINER_NAME" cat "$FILEPATH"
```

`list-route.sh`
```sh
#!/bin/bash
# list-external-routes.sh

CONTAINER_NAME="coolify-proxy"
DYNAMIC_DIR="/traefik/dynamic"

echo "External routes in $CONTAINER_NAME:"
docker exec "$CONTAINER_NAME" find "$DYNAMIC_DIR" -name "*.yml" 2>/dev/null | while read file; do
    domain=$(docker exec "$CONTAINER_NAME" grep -o "Host(\`[^)]*\`)" "$file" | sed 's/Host(`//; s/`)//')
    url=$(docker exec "$CONTAINER_NAME" grep -o "url: .*" "$file" | sed 's/url: "//; s/"//')
    echo "  $domain -> $url"
done || echo "  No routes found or directory doesn't exist"
```

`rm-route.sh`
```sh
#!/bin/bash
# remove-external-route.sh

DOMAIN="$1"
DYNAMIC_DIR="/traefik/dynamic"
CONTAINER_NAME="coolify-proxy"

if [ -z "$DOMAIN" ]; then
    echo "Usage: $0 <domain>"
    exit 1
fi

FILENAME=$(echo "$DOMAIN" | sed 's/\./-/g')
FILEPATH="$DYNAMIC_DIR/${FILENAME}.yml"

if docker exec "$CONTAINER_NAME" test -f "$FILEPATH"; then
    docker exec "$CONTAINER_NAME" rm "$FILEPATH"
    echo "✓ Removed route for $DOMAIN"
else
    echo "⚠ Route for $DOMAIN not found"
fi
```
