### DISCUSSION TITLE
App scaling

### DISCUSSION THREAD

**Discussion by guestisp** [coollabsio/coolify#1579] [Feature Requests]
Hi all
I thing that app scaling is something missing in coolify (or i didn't find anything similiar).

Would be great having the ability to scale an app over multiple hosts by setting the required number of instances, via web configuration or CLI.

In example, if you have a multi-node setup, setting `3` to an ipothetical `app_count` paramenter, would spin up `3` instances over 3 different hosts (if hosts are less than the required number of instances, 2 or more instances should be placed over the same host, like 2 in host 1, and 1 in host2)

**Comment by srinisubramanian** [comment]
This is a very important feature to get Coolify to handle a lot more use cases.  Similar to docker compose scale, the setting should control the instances deployed and to servers.  Ideally this should be a min - max setting so that when the load is negligible the app or docker instances can be scaled down also.

**Comment by AlejandroAkbal** [comment]
Yeah, one of my free services is very popular, and it's getting hammered, being slow for everyone, cache is implemented, but its not enough

Scaling is necessary in my case, even in the same VPS, just adding more service containers

**Reply by Wulfheart** [reply]
Is it [this](https://r34.app/?domain=safebooru.org) one? :D

**Reply by takayumi** [reply]
How did you address your VPS scaling issues @AlejandroAkbal? Also, nice app - it's a good showcase of how to scale Coolify (if you're still using it).

**Reply by AlejandroAkbal** [reply]
Yes I'm still building it ☺️

I handled scaling by getting a beefier and using all the CPUs. 
But this is application side, not Coolify or multiple containers

So technically what I'm doing is spawning a process/thread per CPU, inside the same docker container

Coolify could have made this easier for me by scaling docker containers, but the correct and robust solution is scaling inside in the application side (for my case)
I'm sure once I reach more popularity I would need to scale horizontally with more beefy servers, and hopefully Coolify Swarm is useful then

**Reply by takayumi** [reply]
Interesting! I'm personally using Docker Compose with `replicas` to scale it via Coolify alone.

How did you manage the process/thread spawning in the same Docker container? Are you using specific flags or options in Coolify to enable that?

Do you have any open-source examples by any chance?

**Reply by AlejandroAkbal** [reply]
It really depends on your project, for mine, it's Vue / Node, so it works on the Nuxt framework which already handles this for me, I just have to enable it, usually NodeJS uses PM2 and clusters for this. So depending on your code language and framework the solution will be different 

Here is some examples: https://github.com/Rule-34/API/blob/main/src/cluster.service.ts

And https://nitro.build/deploy/runtimes/node#cluster-mode

Nothing special from Coolify on my end

**Comment by mo9a7i** [comment]
+1 for this feature.

**Comment by Andreas-Sujono** [comment]
need this feature +1

**Comment by maietta** [comment]
Scaling an app isn't always as straight forward as it might appear. Would this only apply to Docker Swarm configurations? How would the load balancing work in a scenario where apps could be scaled across hosts?

There are a lot of questions that need to be first asked before even considering this.

Like how would querying for server IP's work with the API if this was enabled? Would apps be limited to Docker Swarm? Would the schedular still work -- it would have to pick 1 of the instances to interact with, not all of them, etc.

**Reply by DavesBorges** [reply]
> Would this only apply to Docker Swarm configurations? How would the load balancing work in a scenario where apps could be scaled across hosts?

Docker swarm already handles load balancing across hosts unless you are refering to some kind of coolify specific load balancing.

> Would apps be limited to Docker Swarm? 

Docker compose can accomplish has kind of similar feature for a single host environment, but at that point it's better to use docker swarm for single host environments anyway.


> Like how would querying for server IP's work with the API if this was enabled?

I'm assuming that docker swarm is used in this case, the server ip would be the master node IP. I believe coolify uses volume so it will need to set a constraint in the coolify swarm service to only run on the master node.

One thing that will probably need to be workout is the health check with traffeik, because we might have 3 instances in which 2 are healthy and one is unhealthy.

 I'm probably missing some other edge case

**Comment by ImBIOS** [comment]
My current plan, for my projects which need scaling. I'm using cloud engineering in cloud provider.
But I need this +1 for my medium traffic projects.

**Comment by Jagatpratap** [comment]
I also want this feature +1

**Comment by snoozedDev** [comment]
+1 for multiple container instances. Would also help with smooth container updates.
I miss that from my brief experience with railway.

**Comment by AymenElmehdhaoui** [comment]
+1

**Comment by robertherber** [comment]
This is the reason we're staying with Caprover for now. This together with having to manually configure traefik for SSL - but that's a one-time thing so we can live with that.

**Reply by Boscop** [reply]
@robertherber I'm using CapRover but I'd prefer a PaaS that lets me deploy docker-compose.yml files, but still allows scaling like CapRover. Do you know which PaaS does this? :)

**Reply by robertherber** [reply]
I'm afraid not! That sounds like a great feature though, for self-hosting things that require more advanced infra setups. 

Although I don't think Caprover supports Docker Compose specifically some of the one-click apps do spin up related service dependencies (databases etc) automatically.

**Reply by Boscop** [reply]
> Although I don't think Caprover supports Docker Compose specifically some of the one-click apps do spin up related service dependencies (databases etc) automatically.

Yeah, but it doesn't directly support docker-compose.yml files (it has its own files which follow a similar format), so it's not a drop-in solution..
E.g. I've been trying to figure out how to deploy EdgeDB on CapRover (which is not in the set of one-click apps) and it would be easy with docker compose: 
https://docs.edgedb.com/guides/deployment/docker#docker-compose

**Comment by jtwebman** [comment]
My guess is you could still do this in a very manual way. Just setup the app multiple times and then setup an Nginx the load balances over those IP addresses and ports. Doesn't auto scale or anything like that but would let you have two hosts for the same app.

**Reply by jtwebman** [reply]
Also looks like you can use Hetzner load balancer and firewall as well if you wanted. https://coolify.io/docs/knowledge-base/how-to/hetzner-loadbalancing

**Comment by lindesvard** [comment]
This is an important feature for me as well, since I want to manage how many bullmq workers I want to spin up (on a single server). A feature CapRover does pretty well!

**Comment by nerdlibfront** [comment]
I also need that for the projects that need redundancy.
It is possible if you don't need zero downtime. One can use the multi server feature and map ports to host ports. Then e.g. the hetzner loadbalancer can be used to split the traffic to the instances.
This approach has caveats though:
1. Zero Downtime deployment is not possible (as container ports are mapped to host ports)
2. multiple containers per server are not possible (which is needed if you have e.g. a node application and want to utilize more cpus) as you only have one port which receives traffic (at least thats the case with hetzner loadbalancer).

Maybe i missed something, but for now i can't see how i could achieve zero downtime with the coolify multi server functionality.

**Reply by jtwebman** [reply]
You can do both. 

1. The zero downtime just comes down to you would have to manually spin up another third one with the new changes then add it to the mix once it is healthy, set the old proxy to drain, and then reload nginx (nginx -s reload). Then you can wait about 30 seconds for the connections to drain or write code the gratefully drains requests process shutdown when getting the kill command. Then kill that old version docker container. Then remove the old proxy from the nginx config and reload. This is what K8s is doing for you but it is a bunch of work to do manually. You could do a blue green style deployment and that way you keep switch back on the ports and could write a bash script to do it for you. Google around I am sure there are examples. We did it all the time back in 2010s. Also here is how you can do it with hetzner load balancer if you are using them over your own nginx: https://community.hetzner.com/tutorials/load-balancer-blue-green-deployments
2. Easy you just have to have different internal ports or use a cluster tool like PM2. PM2 can also do zero downtime deployments if it is just the one server.

Though I do agree this tool having a basic load balancer and doing this stuff for you would be nice but it will be a bunch of work for them to do this and still be flexible for all the different possible stuff, like supporting web sockets, or just multiple ports. [CapRover](https://caprover.com/) is also a good solution to not have to do this manually.

**Reply by nerdlibfront** [reply]
I know that CapRover does it, but i don't want to switch to another solution without giving coolify a chance here. And after all this is the discussion thread for the app scaling feature which isn't there yet as it seems :)

Thanks for your input on how to do it manually or with additional setup of other technologies, i will definitely have a look.

**Reply by IGIAG** [reply]
+1

**Comment by Trubador** [comment]
I got it working with the follow docker compose by declaring each replica as its own service:

````yaml

version: '3.8'

services:
  github-actions-runner-1:
    build: .
    image: myimage:latest  # Replace with your actual image
    container_name: github-actions-runner-1
    environment:
      RUNNER_URL: https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}
      GITHUB_PAT: ${GITHUB_PAT}
      GITHUB_OWNER: ${GITHUB_OWNER}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: github-actions-runner-1
      RUNNER_WORK_DIRECTORY: /actions-runner
      RUNNER_LABELS: "docker,local,github-actions-runner,coolify"
      SERVICE_NAME: github-actions-runner-1
      COOLIFY_BRANCH: "main"
    restart: always
    labels:
      - "coolify.managed=true"
      - "coolify.version=4.0.0-beta.360"
      - "coolify.applicationId=55"
      - "coolify.type=application"
      - "coolify.name=github-actions-runner-1"
    networks:
      default:

  github-actions-runner-2:
    build: .
    image: myimage:latest
    container_name: github-actions-runner-2
    environment:
      RUNNER_URL: https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}
      GITHUB_PAT: ${GITHUB_PAT}
      GITHUB_OWNER: ${GITHUB_OWNER}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: github-actions-runner-2
      RUNNER_WORK_DIRECTORY: /actions-runner
      RUNNER_LABELS: "docker,local,github-actions-runner,coolify"
      SERVICE_NAME: github-actions-runner-2
      COOLIFY_BRANCH: "main"
    restart: always
    labels:
      - "coolify.managed=true"
      - "coolify.version=4.0.0-beta.360"
      - "coolify.applicationId=55"
      - "coolify.type=application"
      - "coolify.name=github-actions-runner-2"
    networks:
      default:

  github-actions-runner-3:
    build: .
    image: myimage:latest
    container_name: github-actions-runner-3
    environment:
      RUNNER_URL: https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}
      GITHUB_PAT: ${GITHUB_PAT}
      GITHUB_OWNER: ${GITHUB_OWNER}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: github-actions-runner-3
      RUNNER_WORK_DIRECTORY: /actions-runner
      RUNNER_LABELS: "docker,local,github-actions-runner,coolify"
      SERVICE_NAME: github-actions-runner-3
      COOLIFY_BRANCH: "main"
    restart: always
    labels:
      - "coolify.managed=true"
      - "coolify.version=4.0.0-beta.360"
      - "coolify.applicationId=55"
      - "coolify.type=application"
      - "coolify.name=github-actions-runner-3"
    networks:
      default:

networks:
  default:
    name: coolify-network  # Reference the Coolify-managed network
    external: true
````

**Reply by mcansky** [reply]
thanks for sharing this @Trubador 

can a similar approach be used for http services? can we tell the proxy to use 2 or more services as different hosts for 1 single hostname ?

**Reply by Trubador** [reply]
> thanks for sharing this @Trubador 
> 
> 
> 
> can a similar approach be used for http services? can we tell the proxy to use 2 or more services as different hosts for 1 single hostname ?

I think it should be possible but I am no export on Traefik routing so I can't say for sure.

**Comment by SegoviaDiego** [comment]
My team recently pulled off a full VPS Cluster deployment using Coolify, replicating an infrastructure we previously ran on AWS EKS (kubernetes, ~$5k/m) for just ~$100/m on AWS Lightsail + Coolify (yep 50x cheaper).

This is all possible thanks to @piotr-woojcik PR adding docker network aliases: #4741 🙌 

This was a huge milestone for us and not easy to figure out because there's almost no documentation on this. So I’m sharing our approach in case it helps others trying to build something similar.

We based our setup on this diagram from the Coolify docs (which sadly didn’t include any reproducible steps):

<img width="1327" height="438" alt="image" src="https://github.com/user-attachments/assets/c429fa8a-8f16-44b7-87c4-5f3abbb521f8" />

### Glossary:
- Pod: A service instance.
- Main load balancer: A public-facing VPS that distributes traffic across your cluster.
- Worker: A private VPS that hosts multiple pods.

### Prerequisites:
- 1 VPS for the main load balancer.
- 1 or more VPS for the workers.
- A Coolify instance configured with Let’s Encrypt wildcard certificates (see setup example at the end of the post).

### Goals:
- Run multiple pods across multiple workers, all managed through Coolify.
- Distribute service traffic evenly across pods.
- Support rolling updates.
- Avoid routing traffic to failing pods.
- Enforce HTTPS with automatic Let’s Encrypt TLS certificates.
- Expose only one public entrypoint (main load balancer). All workers are protected behind firewalls and not publicly accessible.

### Architecture explanation:
1. The main load balancer receives HTTPS traffic to a domain like `backend.com/api/system/health`
2. It identifies the service using a custom header: `X-Target-Service: backend`.
3. It redirects traffic to one of the workers.
4. Each worker inspects the header and proxies the request to one of its available pods.

### Guide:
1. Configure a **UNIQUE** Docker network alias for each pod:

<img width="1951" height="652" alt="image" src="https://github.com/user-attachments/assets/303b4217-0311-440f-9d68-c2f815203870" />


3. Add traefik dynamic configs for the Main Load Balancer (listen a URL and redirect traffic):
```
http:
  middlewares:
    # This middleware injects a header in the request (not visible to users) that identifies the service inside the cluster.
    target-backend:
      headers:
        customRequestHeaders:
          X-Target-Service: backend
  routers:
    # Exposes and endpoint for users to hit
    backend-https:
      rule: 'Host(`backend.com`)'
      service: backend
      entryPoints:
        - https
      middlewares:
        - gzip
        - target-harmony-backend-prod
      tls:
        certResolver: letsencrypt
  services:
    # The loadbalancer that will distribute traffic evenly across all workers in the cluster. The weight is the amount of pods in that particular worker
    harmony-backend-prod:
      weighted:
        healthCheck: {}
        services:
          - name: backend-worker-1
            weight: 8
          - name: backend-worker-2
            weight: 10
    backend-1:
      loadBalancer:
        healthCheck:
          path: 'api/system/health'
          headers:
            X-Target-Service: backend
        servers:
# This should be a real IP address pointing to your worker. Make sure to configure the firewall so only the main load balancer can interact with it.
          - url: 'http://12.345.678.111'
    backend-2:
      loadBalancer:
        healthCheck:
          path: 'api/system/health'
          headers:
            X-Target-Service: backend
        servers:
# This should be a real IP address pointing to your worker. Make sure to configure the firewall so only the main load balancer can interact with it.
          - url: 'http://12.345.678.222'
```

4. Configure the traefik proxy for each worker:

```
http:
  routers:
    backend:
      # Define the "X-Target-Service" value for identifying the backend service.
      rule: 'Header(`X-Target-Service`, `backend`)'
      service: backend
      entryPoints:
        - http
  services:
    backend:
      loadBalancer:
        healthCheck:
          path: '/api/system/health'
        # The list of all the available pods in this worker.
        servers:
          - url: 'http://backend-1:8080'
          - url: 'http://backend-2:8080'
            ...
          - url: 'http://backend-10:8080'
```

##  Let’s Encrypt wildcard config example (with Route53)
* How to configure letscrypt for wildcard domains:
```
e.g: AWS route53 traefik proxy configuration:
    command:
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=route53'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
    labels:
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.tls.domains[0].sans=*.your-domain.com
```
