### DISCUSSION TITLE
Salesforce/Hubspot alternative - Twenty (CRM)

### DISCUSSION THREAD

**Discussion by deadcoder0904** [coollabsio/coolify#1587] [Service Template Requests]
https://github.com/twentyhq/twenty

**Comment by erikpena** [comment]
When the time comes, I was able to get this up and going in Coolify using the following `docker-compose.yml` file—

```
version: '3'
services:
  twenty-postgres:
    image: 'twentycrm/twenty-postgres:latest'
    volumes:
      - 'postgres-data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=default
  twenty-server:
    image: 'twentycrm/twenty-server:latest'
    depends_on:
      - twenty-postgres
    environment:
      # Keep the twenty:twenty because that is the default user/password set up by Twenty
      - 'PG_DATABASE_URL=[${PG_DATABASE_URL}](postgres://twenty:twenty@twenty-postgres-fkkgkkg:5432/default?connection_limit=1)'
      - 'FRONT_BASE_URL=https://frontend.example.com'
      - PORT=3001
      - ACCESS_TOKEN_SECRET=RANDOM_CHARACTERS
      - LOGIN_TOKEN_SECRET=RANDOM_CHARACTERS
      - REFRESH_TOKEN_SECRET=RANDOM_CHARACTERS
      - 'SERVER_URL=https://backend.example.com'
      - AUTH_GOOGLE_ENABLED=true
      - AUTH_GOOGLE_CLIENT_ID=
      - AUTH_GOOGLE_CLIENT_SECRET=
      - 'AUTH_GOOGLE_CALLBACK_URL=https://backend.example.com/auth/google/redirect'
      - 'FRONT_AUTH_CALLBACK_URL=https://frontend.example.com/verify'
      - STORAGE_TYPE=local
      - STORAGE_LOCAL_PATH=/data/twenty
      - TELEMETRY_ENABLED=false
      # Disable this, otherwise, it'll be setup with dummy data for demo purposes
      - SIGN_IN_PREFILLED=false
      # Currently this env var is necessary in order for the Google Auth provider to work.  I just used the following.
      - SENTRY_DSN=https://xxx@xxx.ingest.sentry.io/xxx	
    volumes:
      - 'twenty-server-storage:/data/twenty'

  twenty-front:
    image: 'twentycrm/twenty-front:latest'
    depends_on:
      - twenty-server
    environment:
      - 'REACT_APP_SERVER_BASE_URL=https://backend.example.com'
      - 'REACT_APP_SERVER_AUTH_URL=https://backend.example.com/auth'
      - 'REACT_APP_SERVER_FILES_URL=https://backend.example.com/files'
      - GENERATE_SOURCEMAP=false
volumes:
  postgres-data: null
  twenty-server-storage: null
```

You can find a more comprehensive list of env vars on [Twenty's Docs](https://docs.twenty.com/start/self-hosting/enviroment-variables).  Be forewarned though that their docs are not good and I found myself constantly testing, digging into their code, etc.  The above is all things that I got to work.

Also, after the app is added, a manual command needs to be executed to seed the database.  The following command needs to be executed on the `twenty-server` service—

```
% yarn database:init
```

**Reply by deadcoder0904** [reply]
wow, thanks @erikpena for this!

i'm wondering if [btcpayserver is this easy](https://github.com/coollabsio/coolify/discussions/1473) too given that it has a [docker specific version](https://github.com/btcpayserver/btcpayserver-docker)? would that be just as easy to add bcz it does need some reverse proxy servers like nginx/traefik?

**Reply by Abz2604** [reply]
I tried this compose file, and I keep getting a 404 error after successful deployment.

This is something I have been facing with the coolify inbuilt on-click install for twentyCRM as well

Can you help me?

**Reply by janbiasi** [reply]
@Abz2604 the preset works great; the only thing you need to do is set the server url manually as the FQDN includes a trailing slash which breaks the GraphQL client of the app. As replied in the [discussion on twenty](https://github.com/twentyhq/twenty/discussions/5219#discussioncomment-10028402), how does your effective docker compose config look like?

**Comment by nooruddin-rahmani** [comment]
Hello everyone hope you're doing great.
I am new to deploying apps and do not know the basics well.
I tried to deploy Twenty in Coolify from GitHub repo. After deploying, When I want to access Twenty, I get Bad Gateway any idea how it happens.
However when I want to deploy the pre-built one that Coolify provides it runs fine.

**Comment by ScarVite** [comment]
any news for this?

**Reply by flomero** [reply]
you can use this to deploy using docker compose:

https://gist.github.com/flomero/05b0dc85463f6b0b2fdea5901d29eb11

**Comment by SvetZitrka** [comment]
Hi, today I wanted to deploy Twenty on my VPS with Coolify. Unfortunately, nothing worked.

So, with the help of Claude and a little human effort, we created this Docker Compose.

Everything seems to be working fine. Please give us feedback on whether it works for you too.

```
services:
  # PostgreSQL databáze
  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $SERVICE_PASSWORD_POSTGRES
      POSTGRES_DB: default
    healthcheck:
      test: pg_isready -U postgres -h localhost -d default
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  # Redis cache (POVINNÝ od verze 0.23+)
  redis:
    image: redis:alpine
    restart: always
    command: ["--maxmemory-policy", "noeviction"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Init kontejner - vytvoří schémata a spustí migrace
  init:
    image: twentycrm/twenty:${TAG:-v0.52.6}
    command: |
      sh -c "
        echo 'Installing PostgreSQL client...'
        apt-get update && apt-get install -y postgresql-client || true
        echo 'Waiting for database...'
        until pg_isready -h db -U postgres -d default; do
          sleep 1
        done
        echo 'Creating schemas...'
        PGPASSWORD=$POSTGRES_PASSWORD psql -h db -U postgres -d default -c 'CREATE SCHEMA IF NOT EXISTS core; CREATE SCHEMA IF NOT EXISTS metadata;' || true
        echo 'Running migrations...'
        yarn database:migrate:prod || true
        echo 'Init completed!'
      "
    environment:
      PG_DATABASE_URL: postgres://postgres:${SERVICE_PASSWORD_POSTGRES}@db:5432/default
      POSTGRES_PASSWORD: $SERVICE_PASSWORD_POSTGRES
      REDIS_URL: redis://redis:6379
      APP_SECRET: $SERVICE_BASE64_64_APP
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: "no"

  # Twenty server
  server:
    image: twentycrm/twenty:${TAG:-v0.52.6}
    volumes:
      - server-data:/app/packages/twenty-server/.local-storage
    environment:
      # Coolify magic - automatická FQDN
      SERVICE_FQDN_SERVER_3000: ${SERVICE_FQDN_SERVER_3000}
      
      # Základní konfigurace
      NODE_PORT: 3000
      SERVER_URL: ${SERVICE_FQDN_SERVER}
      FRONT_BASE_URL: ${SERVICE_FQDN_SERVER}
      
      # Databáze
      PG_DATABASE_URL: postgres://postgres:${SERVICE_PASSWORD_POSTGRES}@db:5432/default
      
      # Redis (všechny možné formáty pro kompatibilitu)
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_STORAGE_TYPE: redis
      
      # Bezpečnostní tokeny (Coolify generuje automaticky)
      APP_SECRET: $SERVICE_BASE64_64_APP
      ACCESS_TOKEN_SECRET: $SERVICE_BASE64_32_ACCESS
      LOGIN_TOKEN_SECRET: $SERVICE_BASE64_32_LOGIN
      REFRESH_TOKEN_SECRET: $SERVICE_BASE64_32_REFRESH
      FILE_TOKEN_SECRET: $SERVICE_BASE64_32_FILE
      
      # Migrace - vypnuté, protože už proběhly v init kontejneru
      ENABLE_DB_MIGRATIONS: false
      DISABLE_DB_MIGRATIONS: true
      
      # Storage
      STORAGE_TYPE: ${STORAGE_TYPE:-local}
      
      # API Rate Limiting
      API_RATE_LIMITING_TTL: ${API_RATE_LIMITING_TTL:-100}
      API_RATE_LIMITING_LIMIT: ${API_RATE_LIMITING_LIMIT:-100}
      
      # Volitelné features
      IS_MULTIWORKSPACE_ENABLED: ${IS_MULTIWORKSPACE_ENABLED:-false}
      IS_SIGN_UP_DISABLED: ${IS_SIGN_UP_DISABLED:-false}
      
    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthz || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: always

  # Twenty worker
  worker:
    image: twentycrm/twenty:${TAG:-v0.52.6}
    volumes:
      - server-data:/app/packages/twenty-server/.local-storage
    command: ["yarn", "worker:prod"]
    environment:
      # Databáze
      PG_DATABASE_URL: postgres://postgres:${SERVICE_PASSWORD_POSTGRES}@db:5432/default
      
      # Redis
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_STORAGE_TYPE: redis
      
      # Bezpečnostní tokeny (stejné jako server)
      APP_SECRET: $SERVICE_BASE64_64_APP
      ACCESS_TOKEN_SECRET: $SERVICE_BASE64_32_ACCESS
      LOGIN_TOKEN_SECRET: $SERVICE_BASE64_32_LOGIN
      REFRESH_TOKEN_SECRET: $SERVICE_BASE64_32_REFRESH
      FILE_TOKEN_SECRET: $SERVICE_BASE64_32_FILE
      
      # Migrace vypnuté
      ENABLE_DB_MIGRATIONS: false
      DISABLE_DB_MIGRATIONS: true
      
      # Storage
      STORAGE_TYPE: ${STORAGE_TYPE:-local}
      
      # URL
      SERVER_URL: ${SERVICE_FQDN_SERVER}
      
    depends_on:
      migration:
        condition: service_completed_successfully
      server:
        condition: service_started
    restart: always

volumes:
  db-data:
  server-data:
```
