### DISCUSSION TITLE
auto-update images

### DISCUSSION THREAD

**Discussion by endquote** [coollabsio/coolify#1753] [Feature Requests]
I'm using the service template for Ghost, works great.

They release new updates all the time. I follow them from the RSS feed of the releases page. https://github.com/TryGhost/Ghost/releases

However, the docker image doesn't get updated for some time after the release, so I have to keep checking it.

I'd like the ability to automatically run the "pull latest images and restart" action on some interval, and get an email if an update was detected. 

Ideally if the update failed it would roll back, too.

**Comment by AlejandroAkbal** [comment]
Coolify could use watchtower underneath to do this

**Reply by HomingHamster** [reply]
how?

**Reply by abdulsaheel** [reply]
https://github.com/containrrr/watchtower

have a look.

**Comment by armetiz** [comment]
watchtower is now archived.

**Comment by Twest2** [comment]
It would be really nice whenever it does the nightly checks for proxy updates if it also checks if there's an update available for the containers.

**Comment by AlejandroAkbal** [comment]
Right now, even Watchtower is failing and I don't know why. LLM seemed to say that it is because Coolify is taking over. I'm actually not sure at all if it is because of that, but there is definitely something weird going on.

This is what I use to auto-update my Docker apps.

```yml
services:
  watchtower:
    image: nickfedor/watchtower
    environment:
      - 'WATCHTOWER_SCHEDULE=0 0 5 * * *'
      - WATCHTOWER_UPDATE_ON_START=true
      - WATCHTOWER_CLEANUP=true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/localtime:/etc/localtime:ro'
```
