### DISCUSSION TITLE
How do I get access to coolify generated traefik router name?

### DISCUSSION THREAD

**Discussion by sulo1337** [coollabsio/coolify#1815] [General]
I'm using traefik with custom configuration. In my configuration, I need to add these labels to my services depending on if the service is private or public.

- For private services
`traefik.http.routers.<router_name>.middlewares=private_svc` 
- For public services
`traefik.http.routers.<router_name>.middlewares=public_svc` 

My traefik config:
```yaml
http:
  middlewares:
    public_svc:
      ipWhiteList:
        sourceRange:
          - "0.0.0.0/0"
    private_svc: 
      ipWhiteList:
        sourceRange:
          - "100.64.0.0/10"
          - "127.0.0.0/8"
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"
```

I'm using docker compose as deployment because all my services are stored in a mono-repo where each folder has docker-compose.yml file which will be used to deploy the service.

However, since the label I'm trying to add includes a `<router_name>` that will be generated by coolify, I cannot statically put the label in the codebase. Is there any variable I can use to grab that generated `<router_name>`? That way, I can put the label like this in the code base:

`traefik.http.routers.$SOME_VARIABLE.middlewares=private_svc`
