### DISCUSSION TITLE
How to add plugins to Traefik in Coolify?

### DISCUSSION THREAD

**Discussion by AlejandroAkbal** [coollabsio/coolify#1818] [Improvement Requests]
I want to integrate HTTP response caching via this plugin, but I'm pretty lost on how to accomplish it

https://github.com/darkweak/souin#tr%C3%A6fik-plugin

**Comment by peaklabs-dev** [comment]
@AlejandroAkbal 
You can add this via a dynamic configuration in the coolify UI.
Something like this could work:
```yaml
http:
  middlewares:
    souin:
      plugin:
        souin:
          default_cache:
            ttl: 10s
```

**Reply by AlejandroAkbal** [reply]
Yeah, and how do you install souin?

**Reply by peaklabs-dev** [reply]
You can do it like this:
1. Add a dynamic configuration with your souin configuration named `souin.yaml`:
```yaml
default_cache:
  ttl: 10s
  allowed_http_verbs:
    - GET
    - HEAD
  cache_name: Souin
  distributed: true
```
2. Add a second dynamic configuration with the plugin (name it however you like):
```yaml
experimental:
  plugins:
    souin:
      moduleName: "github.com/darkweak/souin"
      version: "v1.7.0"
      configuration:
        yaml: "./dynamic/souin.yaml"
```
3. restart the proxy
--> The configs may not be ready as I pasted them above, please adjust it to your needs. Try it and let me know if it works.
