### DISCUSSION TITLE
Redirecting from a subdomain to a different domain

### DISCUSSION THREAD

**Discussion by Adam-Collier** [coollabsio/coolify#1889] [Feature Requests]
The use case I'm thinking here is redirecting from a subdomain cv.adamcollier.co.uk to read.cv/ajc, how would you approach this? Would this be something that coolify handles? Orr should it be handled somewhere else?

**Comment by studioluftbruecke** [comment]
Curious if there is already a solution for this...?

**Reply by djsisson** [reply]
if you're using traefik, it can be done using the redirect regexp

see here https://doc.traefik.io/traefik/middlewares/http/redirectregex/

this can be done using the dynamic files or added as labels to your service

**Reply by studioluftbruecke** [reply]
Thanks for the hint!
I also found the redirects section in the coolify docs: https://coolify.io/docs/knowledge-base/proxy/traefik/redirects

However, I have added it to the dynamic files, but can't get it to work with the dynamic file below. For testing purposes, I would simply like to redirect _https://seasons.konchord.com_ to _https://youtube.com_ but I always get "**no available server**" in my browser when calling _https://seasons.konchord.com_

**my-custom-redirect.yaml**
```
http:
  middlewares:
    redirect-otherdomain:
      redirectRegex:
        regex: '^https://seasons\.konchord\.com(.*)'
        replacement: 'https://youtube.com'
        permanent: true

**Reply by djsisson** [reply]
the middleware needs to run on a route, so you would need to add that as well if you arent adding it to an app,  
also in yaml you need double escaping

```yaml
http:
  routers:
    my-router:
      rule: "Host(`seasons.konchord.com`)"
      tls: {}
      service: dummy-service
      middlewares:
        - redirect-otherdomain

  services:
    dummy-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"  # Won’t be used, just satisfies schema

  middlewares:
    redirect-otherdomain:
      redirectRegex:
        regex: "^https?://seasons\\.konchord\\.com/(.*)"
        replacement: "https://youtube.com/${1}"
        permanent: true

  ````

**Reply by studioluftbruecke** [reply]
Amazing, that worked! ❤️

**Reply by studioluftbruecke** [reply]
Unfortunately I noticed another issue with my setup. I want to route all subdomain and all paths from konchord.com to konchord.now. Here is the yaml file:

```yaml
http:
  routers:
    my-router:
      rule: 'Host(`konchord.com`) || HostRegexp(`^.+\.konchord\.com$`)'
      tls: {  }
      service: dummy-service
      middlewares:
        - redirect-otherdomain
  services:
    dummy-service:
      loadBalancer:
        servers:
          - url: 'http://127.0.0.1'
  middlewares:
    redirect-otherdomain:
      redirectRegex:
        regex: '^(https?://)?([a-zA-Z0-9-]+\.)?konchord\.com(.*)'
        replacement: 'https://${2}konchord.now${3}'
        permanent: true
```

When I first had it set up, it was working. Then I deleted it, re-created the file, and now, it doesn't work anymore.

Is there anything wrong with the config?
Or is the order of the dynamic files relevant?

Is there anything to note regarding the DNS setup?
I am using Cloudflare... I'm thinking, does the record need to be proxied or unproxied?
