### DISCUSSION TITLE
Custom tags for log drains (set per container)

### DISCUSSION THREAD

**Discussion by jimhuds** [coollabsio/coolify#2281] [Feature Requests]
Currently log drains include container name and server, but for services we run across multiple servers, it would be nice to tag them together for easier filtering in axiom.

It would be cool if we could set a custom log drain tag per container under the advanced settings where the 'drain logs' checkbox is (or maybe custom 'Dataset Name' for axiom set on the container level - either works).

Cheers

**Comment by ReWWeR** [comment]
For now I can't add custom tag for containers where I don't use log drains setting from coolify.

For example I want to add custom tag in my Docker compose file:

```
version: '3.9'
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"
```

and I guess coolify trim it, I don't see it.

Can it be not trimed? Or even maybe it can be enabled by default?
