### DISCUSSION TITLE
Healthchecks failing for plausible

### DISCUSSION THREAD

**Discussion by jlengrand** [coollabsio/coolify#2403] [Q&A]
Hey there, 

I've deployed a [plausible](https://coolify.io/docs/resources/services/plausible) and [uptime-kuma](https://github.com/louislam/uptime-kuma?tab=readme-ov-file?utm_source%3Dcoolify.io) instances just like the documentation describes. After deployments, I get a warning saying that the healthchecks aren't functioning for plausible. No issues for uptime kuma. I can access the sites without issues.

<img width="868" alt="image" src="https://github.com/coollabsio/coolify/assets/921666/26c95dc0-e6f6-45ff-9cc6-56d592677d34">

Is this expected? Is there anything I can do about it? 

Thanks!

**Comment by jlengrand** [comment]
Diving a bit further, it looks like the trafiek config has been updated to the newer FQDN, so I'm really not sure what can be the issue here? I have no experience with trafiek, so not sure what to look for exactly.

```
services:
  plausible:
    image: 'plausible/analytics:v2.0'
    command: 'sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"'
    environment:
      - 'DATABASE_URL=postgres://postgres:$SERVICE_PASSWORD_POSTGRES@plausible_db/plausible'
      - BASE_URL=$SERVICE_FQDN_PLAUSIBLE_8000
      - SECRET_KEY_BASE=$SERVICE_BASE64_64_PLAUSIBLE
      - TOTP_VAULT_KEY=$SERVICE_REALBASE64_TOTP
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    networks:
      ago04k0: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.294
      - coolify.serviceId=4
      - coolify.type=service
      - coolify.name=plausible-ago04k0
      - coolify.pullRequestId=0
      - coolify.service.subId=5
      - coolify.service.subType=application
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-ago04k0-plausible.entryPoints=http
      - traefik.http.routers.http-0-ago04k0-plausible.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-ago04k0-plausible.rule=Host(`plausible.lengrand.quest`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ago04k0-plausible.entryPoints=https
      - traefik.http.routers.https-0-ago04k0-plausible.middlewares=gzip
      - 'traefik.http.routers.https-0-ago04k0-plausible.rule=Host(`plausible.lengrand.quest`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ago04k0-plausible.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-ago04k0-plausible.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://plausible.lengrand.quest'
      - caddy_ingress_network=ago04k0
    restart: unless-stopped
    container_name: plausible-ago04k0
  mail:
    image: bytemark/smtp
    networks:
      ago04k0: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.294
      - coolify.serviceId=4
      - coolify.type=service
      - coolify.name=mail-ago04k0
      - coolify.pullRequestId=0
      - coolify.service.subId=6
      - coolify.service.subType=application
    restart: unless-stopped
    container_name: mail-ago04k0
  plausible_db:
    image: 'postgres:14-alpine'
    volumes:
      - 'ago04k0_db-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=plausible
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
    networks:
      ago04k0: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.294
      - coolify.serviceId=4
      - coolify.type=service
      - coolify.name=plausible_db-ago04k0
      - coolify.pullRequestId=0
      - coolify.service.subId=4
      - coolify.service.subType=database
    restart: unless-stopped
    container_name: plausible_db-ago04k0
  plausible_events_db:
    image: 'clickhouse/clickhouse-server:23.3.7.5-alpine'
    volumes:
      -
        type: volume
        source: ago04k0_event-data
        target: /var/lib/clickhouse
      -
        type: bind
        source: ./clickhouse/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/logging.xml
        read_only: true
      -
        type: bind
        source: ./clickhouse/clickhouse-user-config.xml
        target: /etc/clickhouse-server/users.d/logging.xml
        read_only: true
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      ago04k0: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.294
      - coolify.serviceId=4
      - coolify.type=service
      - coolify.name=plausible_events_db-ago04k0
      - coolify.pullRequestId=0
      - coolify.service.subId=5
      - coolify.service.subType=database
    restart: unless-stopped
    container_name: plausible_events_db-ago04k0
volumes:
  ago04k0_db-data:
    name: ago04k0_db-data
  ago04k0_event-data:
    name: ago04k0_event-data
networks:
  ago04k0:
    name: ago04k0
    external: true
```
