### DISCUSSION TITLE
[Feature] Multiple Container Instances using same config

### DISCUSSION THREAD

**Discussion by victorlap** [coollabsio/coolify#2468] [Feature Requests]
Moved from issue #839 
 
> We need Laravel Queues & Scheduler(CRON) support for production deployments of Laravel applications.
> ### Why should this be worked on?
> 
> Laravel queues (see https://laravel.com/docs/9.x/queues) and scheduler (https://laravel.com/docs/9.x/scheduling) are used in almost every application. Without supporting these features Laravel deployments will not be production ready.

The problem here is that we can solve this now in two ways:
1. Where we have separate 'resources' for app, queue, and scheduler. This means that we have to keep the environment variables and other config synchronized between all three locations, not ideal.
2. Use docker compose, which blocks us from using most of the features from Coolify

**Comment by jesusantguerrero** [comment]
Well maybe a little bit late, but if others have the same issue we can address this with the second option

Add your docker file from serversideup:

https://github.com/jesusantguerrero/atmosphere/blob/master/coolify.Dockerfile

Include your docker compose with the three services and done.

https://github.com/jesusantguerrero/atmosphere/blob/master/docker-compose.coolify.yml

**Reply by victorlap** [reply]
I was under the assumption that the other services also need the `DB_*` environment variables right? Do you have this running/working at the moment?

For what it's worth I ended on something like the following myself:

```
x-shared: &shared
  build:
    context: .
    dockerfile: .docker/prod/Dockerfile
  volumes:
    - app-data:/var/www/html/storage
  environment:
    - APP_ENV=${APP_ENV}
    - APP_KEY=${APP_KEY}
    - APP_NAME=${APP_NAME}
    - APP_URL=${APP_URL}
    - ....

services:
  php:
    <<: shared

  redis:
    image: redis:6
    command: "redis-server --appendonly yes"

  task:
    <<: shared
    command: [ "php", "/var/www/html/artisan", "schedule:work" ]
    stop_signal: SIGTERM
    healthcheck:
      test: [ "CMD", "healthcheck-schedule" ]
      start_period: 10s

  horizon:
    <<: shared
    command: [ "php", "/var/www/html/artisan", "horizon" ]
    stop_signal: SIGTERM
    healthcheck:
      test: [ "CMD", "healthcheck-horizon" ]
      start_period: 10s

volumes:
  app-data:

```

**Comment by jesusantguerrero** [comment]
Yes they need it, but once you build the "app" image the other images take that one that's the same you're doing with the "shared" part but less verbose.

And yes this app is running currently, I don't have a redis or db on the docker compose because I have them running separate in coolify and multiple test projects use them.

Notice how the image of **Task** and **queue** is the same 
```
services:
  loger:
    build:
      args:
        uid: 1000
        TZ: America\New_York
      context: ./
      dockerfile: coolify.Dockerfile
    image: freesgen/loger
    container_name: loger-app
    restart: unless-stopped
    volumes:
      - ./docker-compose/web/timezone:/etc/timezone
      - ./storage:/var/www/storage
      - /var/.config/gcloud/loger/credentials.json:/var/www/credentials.json
    env_file:
      - .env
    environment:
      AUTORUN_ENABLED: true
      AUTORUN_LARAVEL_MIGRATION_ISOLATION: true
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
  task:
    image: freesgen/loger
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    environment:
      PHP_PFM_POOL_NAME: "loger_task"
    volumes:
      - /var/.config/gcloud/loger/credentials.json:/var/www/credentials.json
    depends_on:
      - loger
  queue:
    image: freesgen/loger
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    environment:
      PHP_FPM_POOL_NAME: "loger_queue"
    depends_on:
      - loger
```
