### DISCUSSION TITLE
Neo4j

### DISCUSSION THREAD

**Discussion by w7tf** [coollabsio/coolify#2489] [Service Template Requests]
Neo4j is the most adopted Graph based database in the world. 

https://neo4j.com/

Deploying it with the "Existing Docker image" option works, however there are no backup options. This is why a template similar to the database templates would be beneficial.

**Comment by imthatgin** [comment]
I too would like this!

**Comment by alexandrstudio** [comment]
same here +1

**Comment by dhargitai** [comment]
+1

**Comment by albertorizzi** [comment]
> Deploying it with the "Existing Docker image" option works, however there are no backup options. This is why a template similar to the database templates would be beneficial.

@w7tf Did you deploy [this](https://neo4j.com/docs/operations-manual/current/docker/docker-compose-standalone/#docker-compose-basic-authentication)?

**Comment by MakiBM** [comment]
+1

**Comment by janwillemwilmsen** [comment]
+1

**Reply by JorgeCosta87** [reply]
would be great

**Comment by KapyGenius** [comment]
+1

**Comment by tomswinkels** [comment]
+1

I have now created a Docker Compose file in my own Github for version 4!

```
services:
  neo4j:
    image: neo4j:4.4-enterprise
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: ${NEO4J_AUTH:-neo4j/change-me}
      NEO4J_server_default_listen_address: "0.0.0.0"
      NEO4J_dbms_memory_heap_initial__size: "512m"
      NEO4J_dbms_memory_heap_max__size: "512m"
      NEO4J_dbms_memory_pagecache_size: "256m"
      # Optioneel: meer heap/pagecache
      # NEO4J_dbms_memory_heap_max__size: 1G
      # NEO4J_dbms_memory_pagecache_size: 512m
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: {}
```
