### DISCUSSION TITLE
Discourse

### DISCUSSION THREAD

**Discussion by syedkhairi** [coollabsio/coolify#2551] [Service Template Requests]
[https://github.com/discourse/discourse](https://github.com/discourse/discourse)

**Comment by JinsoRaj** [comment]
+1 for this. 
Most popular. But missing in coolify :(

**Comment by Cristy94** [comment]
What's the best way to install it on Coolify?

Can we use the from git repo installation? https://github.com/discourse/discourse_docker.git

**Comment by Aldekein** [comment]
Since Discourse is not using Docker Compose, but an own launcher, I wasn't ready to integrate it deep. 
What I wanted and achieved is Discourse running on Coolify server, being routed through the in-built Traefik to the correct container. 

Host is running https://github.com/discourse/discourse_docker and the latest Coolify v4.0.0-beta.360.

This required only a tiny Discourse re-configuration. To do it, in `/var/discourse/containers/app.yml` I disabled the socketed server and then used labels and docker_args to set up Traefik to find the Discourse, handle HTTP->HTTPS redirection, get certificates and proxy requests from FORUM-HOSTNAME.COM to Discourse container:

```
templates:
  - "templates/postgres.template.yml"
  - "templates/redis.template.yml"
  - "templates/web.template.yml"
  ## Uncomment the next line to enable the IPv6 listener
  #- "templates/web.ipv6.template.yml"
  - "templates/web.ratelimited.template.yml"
  ## Uncomment these two lines if you wish to add Lets Encrypt (https)
#  - "templates/web.ssl.template.yml"
#  - "templates/web.letsencrypt.ssl.template.yml"
#  - "templates/web.socketed.template.yml"

## which TCP/IP ports should this container expose?
## If you want Discourse to share a port with another webserver like Apache or nginx,
## see https://meta.discourse.org/t/17247 for details
expose:
#  - "80:80"   # http
#  - "443:443" # https

docker_args:
  - '--network=coolify'

labels:
  app_name: discourse
  traefik.enable: true

  traefik.http.middlewares.discourse_redirect2https.redirectscheme.scheme: https
  traefik.http.middlewares.gzip.compress: true

  traefik.http.routers.discourse.rule: Host(`FORUM-HOSTNAME.COM`)
  traefik.http.routers.discourse.entrypoints: http
  traefik.http.routers.discourse.middlewares: discourse_redirect2https

  traefik.http.routers.discourse_secure.rule: Host(`FORUM-HOSTNAME.COM`)
  traefik.http.routers.discourse_secure.entrypoints: https
  traefik.http.routers.discourse_secure.tls: true
  traefik.http.routers.discourse_secure.tls.certresolver: letsencrypt
  traefik.http.routers.discourse_secure.middlewares: gzip
  traefik.http.services.discourse_secure.loadbalancer.server.port: 80
```

**Reply by chrislsww** [reply]
Great, thanks. Can you give a more detailed tutorial on how to install this version via Coolify? 
Do I install this via "Public Repository"?
Do I still use Nixpacks as Build Pack or Docker?
The Discourse re-configuration will be done after the successfull installation, correct? Can I also use this with Caddy as Proxy?

**Comment by Schakkalaka** [comment]
i watch it , thanks for help, Alexander

**Comment by onlinejo** [comment]
no news?

**Comment by Cristy94** [comment]
If anyone is interested, I ended up writing my own docker-compose file for Discourse, using the Bitnami Discourse image, and it seems to work. **[I wrote a short guide for running Discourse on Coolify here](https://softuts.com/running-discourse-on-coolify/)**.

**Reply by onlinejo** [reply]
nice, but you tutorials is very short lol

**Reply by Cristy94** [reply]
> nice, but you tutorials is very short lol

Isn't that a good thing?
Is there anything missing?

It's mostly about copying the docker-compose I provided and replacing the password. You should then have it up and running and can follow the Discourse initial setup/config interface from the IP/domain link you set in Coolify.

**Reply by velinxs** [reply]
Hey friend is this still good to use? Or would it be outdated? Would it handle updates?

**Reply by Cristy94** [reply]
I am still using it, just change the Discourse version to the latest bitnami tag.

**Comment by caglar1** [comment]
Please integrate this tool

**Comment by frederikheld** [comment]
+1
this would be awesome

**Comment by syedkhairi** [comment]
Fyi, I followed @Cristy94 tutorial and works perfectly. My Coolify setup running on Hetzner with Cloudflare, Traefik, then I also use Zeptomail as the mail provider.

But yeah, would be great if there's a one click setup.

`New` ➡️ `Docker Compose Empty`

```
services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:16'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=discourse_db
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 3
  redis:
    image: 'docker.io/bitnami/redis:7.4'
    ports:
      - '6379:6379'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
      interval: 5s
      retries: 10
    environment:
      - 'REDIS_PASSWORD=${SERVICE_PASSWORD_DISCOURSE}'
    volumes:
      - 'redis_data:/bitnami/redis'
  discourse:
    image: 'docker.io/bitnami/discourse:3.3.3'
    ports:
      - '3145:3000'
    volumes:
      - 'discourse_data:/bitnami/discourse'
    depends_on:
      - postgresql
      - redis
    environment:
      - SERVICE_FQDN_DISCOURSE_3000
      - 'DISCOURSE_HOST=${SERVICE_FQDN_DISCOURSE}'
      - DISCOURSE_DATABASE_HOST=postgresql
      - 'DISCOURSE_USERNAME=${SERVICE_USER_DISCOURSE}'
      - 'DISCOURSE_PASSWORD=${SERVICE_PASSWORD_DISCOURSE}'
      - 'DISCOURSE_EMAIL=${DISCOURSE_EMAIL}'
      - 'DISCOURSE_SITENAME=${DISCOURSE_SITENAME}'
      - DISCOURSE_POSTGRESQL_NAME=discourse_db
      - 'DISCOURSE_POSTGRESQL_USERNAME=${SERVICE_USER_POSTGRES}'
      - 'DISCOURSE_POSTGRESQL_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'DISCOURSE_SMTP_HOST=${DISCOURSE_SMTP_HOST}'
      - 'DISCOURSE_SMTP_PORT=${DISCOURSE_SMTP_PORT:-587}'
      - 'DISCOURSE_SMTP_USER=${DISCOURSE_SMTP_USER}'
      - 'DISCOURSE_SMTP_PASSWORD=${DISCOURSE_SMTP_PASSWORD}'
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - 'DISCOURSE_REDIS_PASSWORD=${SERVICE_PASSWORD_DISCOURSE}'
      - 'POSTGRESQL_CLIENT_POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRESQL_CLIENT_POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=discourse_db
      - 'POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm'
      - BITNAMI_DEBUG=true
  sidekiq:
    image: 'docker.io/bitnami/discourse:3.3.3'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      - 'DISCOURSE_HOST=${SERVICE_FQDN_DISCOURSE}'
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - 'DISCOURSE_DATABASE_USER=${SERVICE_USER_POSTGRES}'
      - DISCOURSE_DATABASE_NAME=discourse_db
      - 'DISCOURSE_DATABASE_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - DISCOURSE_REDIS_HOST=redis
      - 'DISCOURSE_REDIS_PASSWORD=${SERVICE_PASSWORD_DISCOURSE}'
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - 'DISCOURSE_SMTP_HOST=${DISCOURSE_SMTP_HOST}'
      - 'DISCOURSE_SMTP_PORT=${DISCOURSE_SMTP_PORT:-587}'
      - 'DISCOURSE_SMTP_USER=${DISCOURSE_SMTP_USER}'
      - 'DISCOURSE_SMTP_PASSWORD=${DISCOURSE_SMTP_PASSWORD}'
```

I guess I keep this as open as not yet included part of one-click app installs?

**Reply by frederikheld** [reply]
Thanks for sharing!

**Reply by ValentinOgier** [reply]
Hi there, bitnami updated their docker release and seems to have removed everything, do you have an alternative by any chance ? 🥲

**Reply by Cristy94** [reply]
Yeah, unfortunately they stopped updating their containers. I am still looking for an alternative Discourse Docker image.

**Comment by ValentinOgier** [comment]
Fixed using **bitnamilegacy** instead of **bitnami** since they removed their docker hubs 😬

```
services:
  postgresql:
    image: 'docker.io/bitnamilegacy/postgresql:16'
    volumes:
      - 'postgresql_data:/bitnamilegacy/postgresql'
    environment:
      - POSTGRESQL_DATABASE=discourse_db
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 3
  redis:
    image: 'docker.io/bitnamilegacy/redis:7.4'
    ports:
      - '6379:6379'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
      interval: 5s
      retries: 10
    environment:
      - 'REDIS_PASSWORD=${SERVICE_PASSWORD_DISCOURSE}'
    volumes:
      - 'redis_data:/bitnamilegacy/redis'
  discourse:
    image: 'docker.io/bitnamilegacy/discourse:3.3.3'
    ports:
      - '3145:3000'
    volumes:
      - 'discourse_data:/bitnamilegacy/discourse'
    depends_on:
      - postgresql
      - redis
    environment:
      - SERVICE_FQDN_DISCOURSE_3000
      - 'DISCOURSE_HOST=${SERVICE_FQDN_DISCOURSE}'
      - DISCOURSE_DATABASE_HOST=postgresql
      - 'DISCOURSE_USERNAME=${SERVICE_USER_DISCOURSE}'
      - 'DISCOURSE_PASSWORD=${SERVICE_PASSWORD_DISCOURSE}'
      - 'DISCOURSE_EMAIL=${DISCOURSE_EMAIL}'
      - 'DISCOURSE_SITENAME=${DISCOURSE_SITENAME}'
      - DISCOURSE_POSTGRESQL_NAME=discourse_db
      - 'DISCOURSE_POSTGRESQL_USERNAME=${SERVICE_USER_POSTGRES}'
      - 'DISCOURSE_POSTGRESQL_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'DISCOURSE_SMTP_HOST=${DISCOURSE_SMTP_HOST}'
      - 'DISCOURSE_SMTP_PORT=${DISCOURSE_SMTP_PORT:-587}'
      - 'DISCOURSE_SMTP_USER=${DISCOURSE_SMTP_USER}'
      - 'DISCOURSE_SMTP_PASSWORD=${DISCOURSE_SMTP_PASSWORD}'
      - DISCOURSE_REDIS_HOST=redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - 'DISCOURSE_REDIS_PASSWORD=${SERVICE_PASSWORD_DISCOURSE}'
      - 'POSTGRESQL_CLIENT_POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRESQL_CLIENT_POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=discourse_db
      - 'POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm'
      - bitnamilegacy_DEBUG=true
  sidekiq:
    image: 'docker.io/bitnamilegacy/discourse:3.3.3'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnamilegacy/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      - 'DISCOURSE_HOST=${SERVICE_FQDN_DISCOURSE}'
      - DISCOURSE_DATABASE_HOST=postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - 'DISCOURSE_DATABASE_USER=${SERVICE_USER_POSTGRES}'
      - DISCOURSE_DATABASE_NAME=discourse_db
      - 'DISCOURSE_DATABASE_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - DISCOURSE_REDIS_HOST=redis
      - 'DISCOURSE_REDIS_PASSWORD=${SERVICE_PASSWORD_DISCOURSE}'
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - 'DISCOURSE_SMTP_HOST=${DISCOURSE_SMTP_HOST}'
      - 'DISCOURSE_SMTP_PORT=${DISCOURSE_SMTP_PORT:-587}'
      - 'DISCOURSE_SMTP_USER=${DISCOURSE_SMTP_USER}'
      - 'DISCOURSE_SMTP_PASSWORD=${DISCOURSE_SMTP_PASSWORD}'
```
