### DISCUSSION TITLE
gRPC Support

### DISCUSSION THREAD

**Discussion by lille-morille** [coollabsio/coolify#2707] [Feature Requests]
I was wondering if it would be possible to implement gRPC support for services.

Traefik supports it, but I can't seem to get it to work using Coolify.

**Comment by shelojara** [comment]
+1 on this request, although we can make it work with h2c, we loose the automatic traefik config generation which is a shame.

**Comment by EternalC0der** [comment]
+1

**Comment by nurikk** [comment]
+1

**Reply by viisrael** [reply]
Hey guys! Did you find a way to use grpc?

**Comment by Noman-Iqbal-1** [comment]
+1

**Comment by oelhammouchi** [comment]
+1

**Comment by ABoyd002** [comment]
+1

**Comment by arika0093** [comment]
+1.

For those seeking an immediate solution: Set the label `traefik.http.services.(any_name).loadbalancer.server.scheme=h2c`.
https://doc.traefik.io/traefik/user-guides/grpc/

```yaml
services:
  my_service:
    # ...
    labels:
      - traefik.http.services.my_service_h2c.loadbalancer.server.scheme=h2c
```

However, if the auto-generated configuration includes `traefik.http.router.(ID).service=...`, this will stop working.
In that case, you need to make the `(any_name)` part match the others.

**Reply by bergonzinifrancesco** [reply]
I am using the default configuration of Traefik labels on my server and I am getting HTTP 500 errors from the reverse proxy. I have the following middlewares enabled: gzip, redirect-to-https. How can I configure Traefik to route the traffic via HTTP/2 to my Docker container? I have used `h2c` scheme on both services (http and https) and it's what has triggered the aforementioned error.

**Comment by euskadi31** [comment]
Hi, any news ?

**Comment by Noman-Iqbal-1** [comment]
+1

**Comment by simonheisstpeter** [comment]
+1

**Comment by iamashwin99** [comment]
+1

**Comment by Last8Exile** [comment]
I managed to create working solution.

First of all: I had to use `network_mode: host` in docker compose due to other requirements. May be it is not required.

1) On server (ASP.NET Core) I had to enable two separate listening ports for HTTP/1.1 and HTTP/2.

_appsettings.json_
```
  "Kestrel": {
        "Endpoints": {
            "Grpc": {
                "Url": "http://0.0.0.0:8082",
                "Protocols": "Http2"
            },
            "Http": {
                "Url": "http://0.0.0.0:8081",
                "Protocols": "Http1"
            }
        }
    }
```

2) Assign domain to the service: `https://yourdomain.com:8082`. Use the port of GRPC endpoint.
You probably can assign second domain to other port. In my case HTTP/1.1 is not needed and I only assigned domain for GRPC over HTTP/2.

3) Add h2c scheme to compose file

_docker-compose.yml_
```
services:
  tcp2udp:
    image: 'tcp2udp:latest'
    container_name: tcp2udp
    restart: unless-stopped
    network_mode: host
    labels:
      - traefik.http.services.https-0-pl71ak8wn6idqqjv6xsfab17-tcp2udp.loadbalancer.server.scheme=h2c
```
The `https-0-pl71ak8wn6idqqjv6xsfab17-tcp2udp` part was taken from Collify UI (Edit Compose File > Show Delployable Compose).
You will find something like: `- traefik.http.routers.https-0-pl71ak8wn6idqqjv6xsfab17-tcp2udp.tls=true` in autogenerated compose file.
Grab the part between `- traefik.http.routers.` and `.tls=true`. Make sure it is https one (not http).
