### DISCUSSION TITLE
Schedule a deployment at a specific time

### DISCUSSION THREAD

**Discussion by lil5** [coollabsio/coolify#2772] [Feature Requests]
This would be an option in the "Deployments" or "Scheduled Tasks" tab.

The form would contain when you would like to redeploy, and if it is a recurring or one time task.

**Scenario:**

I'd like to redeploy at 04:00 local time, to have the downtime only occur during low network activity

**Comment by marwie** [comment]
I'd love to see this too! I want to push to my production branch and re-deploy at a specific time during the day instead of immediately to not negatively impact periods with lots of user activity or interrupt other running jobs

**Reply by Julhol-droid** [reply]
Yes that would be a great feature

**Comment by shageman** [comment]
In the meantime you can make another project to do this for you. Pick a dockerfile deployment and adapt this to your use-case:

```
services:
  cronjob:
    image: alpine
    container_name: coolify-inline-cron
    command: |
      sh -c 'apk add --no-cache curl && echo "*/FREQUENCY * * * * echo \"[CRON] Running curl at \$(date)\" && curl -i -X POST -H \"Authorization: Bearer TOKEN\" https://SERVER/api/v1/deploy?uuid=UUID&force=false&force=true" > /etc/crontabs/root && crond -f -l 2'
    restart: unless-stopped
```

Adapt the cron config as needed. TOKEN is a Coolify API Token with deploy permission. You can find the UUID on the web hooks page of the service to be scheduled for deploy.

If you use API access allow listing, then be sure to add your deployment server(s) that list.
