### DISCUSSION TITLE
Deployment depends on another service

### DISCUSSION THREAD

**Discussion by nmpereira** [coollabsio/coolify#2784] [Feature Requests]
I'd love to have a way to mark the deployment of service 1 being contingent on the successful deployment of service 2.

For example if my frontend is Service 1, I would like it to deploy only after the deployment of my backend (service 2).

**Comment by carbontwelve** [comment]
This is one of my wishlist features, for the time being I am hacking together something that _ab_-uses the `depends_on` mechanism in docker compose by having a service with a healthcheck that checks status of another service on the server, e.g I have one database server shared between all applications, and so it needs to be up before they get deployed.

I'm going to test using this https://github.com/ufoscout/docker-compose-wait to wait for another container.

**Reply by alike03** [reply]
Did you test it? I am currently having this exact problem, an application has to wait for the database to be up and running.

**Reply by alike03** [reply]
I tested this myself and it works reliably.

I couldn’t find any clear guidance on doing this with docker-compose, so I tried what seemed correct. It worked as expected.

Below is the setup I used. A lightweight wait container blocks startup until the required certificate files exist, then exits successfully, allowing the main service to start.

```yaml
services:
  stalwart-wait:
    image: ghcr.io/ufoscout/docker-compose-wait:latest
    environment:
      WAIT_PATHS: /certs/dynamic/example.com/cert,/certs/dynamic/example.com/key
      WAIT_TIMEOUT: 120
      WAIT_BEFORE: 5
    volumes:
      - /data/docker/certificates:/certs:ro
    entrypoint: ["/wait"]
    restart: "no"

  stalwart:
    image: stalwartlabs/stalwart:latest
    depends_on:
      stalwart-wait:
        condition: service_completed_successfully
```
