### DISCUSSION TITLE
Docker Mail Server

### DISCUSSION THREAD

**Discussion by Nonolanlan1007** [coollabsio/coolify#2816] [Service Template Requests]
Hello, would it be possible to add docker mail server or a similar service to create an IMAP/SMTP mail server on coolify?

Thanks in advance

https://github.com/docker-mailserver/docker-mailserver

**Comment by Nonolanlan1007** [comment]
If this helps anyone integrate DMS with Coolify, I already have a working compose.yml running on my Coolify instance. I have no idea how to adapt it to Coolify, so I'll leave it to someone else. 😅

```yml
services:
  mailserver:
    image: 'ghcr.io/docker-mailserver/docker-mailserver:latest'
    hostname: mail.example.com
    ports:
      - '25:25'
      - '143:143'
      - '465:465'
      - '587:587'
      - '993:993'
    volumes:
      - './docker-data/dms/mail-data/:/var/mail/'
      - './docker-data/dms/mail-state/:/var/mail-state/'
      - './docker-data/dms/mail-logs/:/var/log/mail/'
      - './docker-data/dms/config/:/tmp/docker-mailserver/'
      - '/etc/localtime:/etc/localtime:ro'
      - '/data/coolify/proxy/acme.json:/etc/letsencrypt/acme.json:ro'
    cap_add:
      - NET_ADMIN
    environment:
      - ACCOUNT_PROVISIONER=FILE
      - AMAVIS_LOGLEVEL=0
      - CLAMAV_MESSAGE_SIZE_LIMIT=
      - DEFAULT_RELAY_HOST=
      - DMS_DEBUG=0
      - DMS_VMAIL_GID=5000
      - DMS_VMAIL_UID=5000
      - DOVECOT_AUTH_BIND=
      - DOVECOT_INET_PROTOCOLS=all
      - DOVECOT_MAILBOX_FORMAT=maildir
      - DOVECOT_PASS_FILTER=
      - DOVECOT_TLS=
      - DOVECOT_USER_FILTER=
      - ENABLE_AMAVIS=0
      - ENABLE_CLAMAV=0
      - ENABLE_DNSBL=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_FETCHMAIL=0
      - ENABLE_GETMAIL=0
      - ENABLE_IMAP=1
      - ENABLE_MANAGESIEVE=
      - ENABLE_MTA_STS=0
      - ENABLE_OAUTH2=
      - ENABLE_OPENDKIM=1
      - ENABLE_OPENDMARC=1
      - ENABLE_POLICYD_SPF=1
      - ENABLE_POP3=1
      - ENABLE_POSTGREY=0
      - ENABLE_QUOTAS=1
      - ENABLE_RSPAMD=0
      - ENABLE_RSPAMD_REDIS=
      - ENABLE_SASLAUTHD=0
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_SPAMASSASSIN_KAM=0
      - ENABLE_SRS=0
      - ENABLE_UPDATE_CHECK=1
      - FAIL2BAN_BLOCKTYPE=drop
      - FETCHMAIL_PARALLEL=0
      - FETCHMAIL_POLL=300
      - GETMAIL_POLL=5
      - LDAP_BIND_DN=
      - LDAP_BIND_PW=
      - LDAP_QUERY_FILTER_ALIAS=
      - LDAP_QUERY_FILTER_DOMAIN=
      - LDAP_QUERY_FILTER_GROUP=
      - LDAP_QUERY_FILTER_USER=
      - LDAP_SEARCH_BASE=
      - LDAP_SERVER_HOST=
      - LDAP_START_TLS=
      - LOGROTATE_COUNT=4
      - LOGROTATE_INTERVAL=weekly
      - LOGWATCH_INTERVAL=weekly
      - LOGWATCH_RECIPIENT=
      - LOGWATCH_SENDER=
      - LOG_LEVEL=info
      - MARK_SPAM_AS_READ=0
      - MOVE_SPAM_TO_JUNK=1
      - NETWORK_INTERFACE=
      - OAUTH2_INTROSPECTION_URL=
      - OVERRIDE_HOSTNAME=
      - PERMIT_DOCKER=connected-networks
      - PFLOGSUMM_RECIPIENT=
      - PFLOGSUMM_SENDER=
      - PFLOGSUMM_TRIGGER=
      - POSTFIX_DAGENT=
      - POSTFIX_INET_PROTOCOLS=all
      - POSTFIX_MAILBOX_SIZE_LIMIT=209715200
      - POSTFIX_MESSAGE_SIZE_LIMIT=
      - POSTFIX_REJECT_UNKNOWN_CLIENT_HOSTNAME=0
      - POSTGREY_AUTO_WHITELIST_CLIENTS=5
      - POSTGREY_DELAY=300
      - POSTGREY_MAX_AGE=35
      - POSTGREY_TEXT=Delayed by Postgrey
      - POSTMASTER_ADDRESS=postmaster@example.com
      - POSTSCREEN_ACTION=enforce
      - RELAY_HOST=
      - RELAY_PASSWORD=
      - RELAY_PORT=25
      - RELAY_USER=
      - REPORT_RECIPIENT=
      - REPORT_SENDER=
      - RSPAMD_CHECK_AUTHENTICATED=0
      - RSPAMD_GREYLISTING=0
      - RSPAMD_HFILTER=1
      - RSPAMD_HFILTER_HOSTNAME_UNKNOWN_SCORE=6
      - RSPAMD_LEARN=0
      - RSPAMD_NEURAL=0
      - SASLAUTHD_LDAP_AUTH_METHOD=
      - SASLAUTHD_LDAP_BIND_DN=
      - SASLAUTHD_LDAP_FILTER=
      - SASLAUTHD_LDAP_MECH=
      - SASLAUTHD_LDAP_PASSWORD=
      - SASLAUTHD_LDAP_PASSWORD_ATTR=
      - SASLAUTHD_LDAP_SEARCH_BASE=
      - SASLAUTHD_LDAP_SERVER=
      - SASLAUTHD_LDAP_START_TLS=
      - SASLAUTHD_LDAP_TLS_CACERT_DIR=
      - SASLAUTHD_LDAP_TLS_CACERT_FILE=
      - SASLAUTHD_LDAP_TLS_CHECK_PEER=
      - SASLAUTHD_MECHANISMS=
      - SASLAUTHD_MECH_OPTIONS=
      - SA_KILL=10.0
      - SA_TAG=2.0
      - SA_TAG2=6.31
      - SMTP_ONLY=
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - SPAM_SUBJECT=
      - SPOOF_PROTECTION=1
      - SRS_EXCLUDE_DOMAINS=
      - SRS_SECRET=
      - SRS_SENDER_CLASSES=envelope_sender
      - SSL_ALT_CERT_PATH=
      - SSL_ALT_KEY_PATH=
      - SSL_CERT_PATH=
      - SSL_DOMAIN=mail.example.com
      - SSL_KEY_PATH=
      - SSL_TYPE=letsencrypt
      - SUPERVISOR_LOGLEVEL=info
      - TLS_LEVEL=
      - TZ=Europe/Paris
      - UPDATE_CHECK_INTERVAL=1d
      - VIRUSMAILS_DELETE_DELAY=

  whoami:
    image: 'docker.io/traefik/whoami:latest'
```

For TLS to work with traefik, you need to create a container that uses the same FQDN as the mail server (in this case `whoami`) : 
![image](https://github.com/user-attachments/assets/61505096-a150-4f4b-abac-c3e2080610a6)
