### DISCUSSION TITLE
LIbreChat One click installation

### DISCUSSION THREAD

**Discussion by ctwhome** [coollabsio/coolify#2867] [Service Template Requests]
@andrasbacsai and @danny-avila It would be awesome to have the LibreChat template running here. https://www.librechat.ai/
It allows to use almost any common LLM with user managment, custom promts.. etc. 

There is a [docker-compose](https://github.com/danny-avila/LibreChat/blob/main/docker-compose.yml) with .env files but i can't get it to work as seen in this [discussion](https://github.com/danny-avila/LibreChat/discussions/3113#discussioncomment-10081501). 

Many thanks!

**Comment by sarvesh-astrophile** [comment]
Yes, can you help we are struggling to deploy it. Let me know if you want specific details

**Comment by afaraha8403** [comment]
Having the same issue here! Would be amazing to add this as a template...

**Comment by chymian** [comment]
@sarvesh-astrophile and @afaraha8403 
guys, did you succeed and can share a how to?

**Reply by sarvesh-astrophile** [reply]
use the hugging face still facing the issue

**Comment by stewnight** [comment]
It's not perfect, but I was able to get a few features working in a single docker-compose. Librechat is running and all, working with ChatGPT, I just need to do further testing for RAG, web search etc - But am running out of time, so sharing in case it helps:

```
services:
  librechat:
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - DOMAIN_CLIENT=http://localhost:3080
      - DOMAIN_SERVER=http://localhost:3080
      - SERVICE_FQDN_LIBRECHAT_3080
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
      - DEBUG_LOGGING=true
      - NO_INDEX=true
      - ALLOW_EMAIL_LOGIN=true
      - ALLOW_REGISTRATION=true
      - ALLOW_SOCIAL_LOGIN=false
      - ALLOW_SOCIAL_REGISTRATION=false
      - ALLOW_PASSWORD_RESET=false
      - ALLOW_UNVERIFIED_EMAIL_LOGIN=true
      - JWT_SECRET=16f8c0ef4a5d391b26034086c628469d3f9f497f08163ab9b40137092f2909ef
      - JWT_REFRESH_SECRET=eaa5191f2914e30b9387fd84e254e4ba6fc51b4654968a9b0803b456a54b8418
      - CREDS_KEY=f34be427ebb29de8d88c107a71546019685ed8b241d8f2ed00c3df97ad2566f0
      - CREDS_IV=e2341419ec3dd3d19b13a1a87fafcbfb
      - SEARCH=true
      - APP_TITLE=LibreChat
      - OPENAI_API_KEY=user_provided
      - ANTHROPIC_API_KEY=user_provided
      - GOOGLE_KEY=user_provided
      - BINGAI_TOKEN=user_provided
      - ASSISTANTS_API_KEY=user_provided
      - MISTRAL_API_KEY=user_provided
      - GROQ_API_KEY=user_provided
      - PERPLEXITY_API_KEY=user_provided
      - ANYSCALE_API_KEY=user_provided
      - TOGETHERAI_API_KEY=user_provided
      - DEEPSEEK_API_KEY=user_provided
    volumes:
      - librechat-api-images:/app/client/public/images
      - librechat-api-logs:/app/api/logs
  mongodb:
    image: "docker.io/bitnami/mongodb:5.0"
    volumes:
      - "mongodb-data:/bitnami/mongodb"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - "MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME:-rs0}"
      - "MONGODB_PORT_NUMBER=${MONGODB_PORT_NUMBER:-27017}"
      - "MONGODB_INITIAL_PRIMARY_HOST=${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}"
      - "MONGODB_INITIAL_PRIMARY_PORT_NUMBER=${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}"
      - "MONGODB_ADVERTISED_HOSTNAME=${MONGODB_ADVERTISED_HOSTNAME:-mongodb}"
      - "MONGODB_ENABLE_JOURNAL=${MONGODB_ENABLE_JOURNAL:-true}"
      - "ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}"
    healthcheck:
      test: "echo 'db.stats().ok' | mongo localhost:27017/test --quiet"
      interval: 2s
      timeout: 10s
      retries: 15

  meilisearch:
    image: "getmeili/meilisearch:latest"
    environment:
      - SERVICE_FQDN_MEILISEARCH_7700
      - "MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}"
      - "MEILI_ENV=${MEILI_ENV:-production}"
      - "MEILI_MASTER_KEY=${SERVICE_PASSWORD_MEILISEARCH}"
    volumes:
      - "meilisearch-data:/meili_data"
    restart: always
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://127.0.0.1:7700/health"
      interval: 2s
      timeout: 10s
      retries: 15

  vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
      - OPENAI_API_KEY=user_provided
    restart: always
    depends_on:
      - vectordb

volumes:
  librechat-api-images:
  librechat-api-logs:
  mongodb-data:
  meilisearch-data:
  pgdata2:
```

Please use https://www.librechat.ai/toolkit/creds_generator to generator random keys.

I will be adding ollama to this docker file for self hosted models too. 
Please let me know if there is anything I should be changing. Prob don't need meilisearch's FQDN, but I just copied from the default one-click install for the time.

**Comment by stewnight** [comment]
Made a few changes so that it is tidier inside of Coolify, I was able to create this as a new project and running it without problems after adding the creds keys. Moved all AI model keys to be a environment variable, defaulting to user provided keys. Just for ease of use.

So the only Environment variables you need to fill out are the ones you can generate here: https://www.librechat.ai/toolkit/creds_generator

I also removed the URL from meilisearch. 
The only changes that might be worthy is using ${SERVICE_PASSWORD_CRED_KEY} etc so that the keys show on the Service Stack tab of Coolify to make it more obvious - but I'd say @andrasbacsai can auto generate the keys if this does become a One Click install. I'm not very familiar yet with the default coolify variables.

Here is the latest docker-compose:

```
services:
  librechat:
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    user: "1000:1000"
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - DOMAIN_CLIENT=http://localhost:3080
      - DOMAIN_SERVER=http://localhost:3080
      - SERVICE_FQDN_LIBRECHAT_3080
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - RAG_PORT=8000
      - RAG_API_URL=http://rag_api:8000
      - DEBUG_LOGGING=true
      - NO_INDEX=true
      - ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN:-true}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-true}
      - ALLOW_SOCIAL_LOGIN=${ALLOW_SOCIAL_LOGIN:-false}
      - ALLOW_SOCIAL_REGISTRATION=${ALLOW_SOCIAL_REGISTRATION:-false}
      - ALLOW_PASSWORD_RESET=${ALLOW_PASSWORD_RESET:-false}
      - ALLOW_UNVERIFIED_EMAIL_LOGIN=${ALLOW_UNVERIFIED_EMAIL_LOGIN:-true}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      - SEARCH=true
      - APP_TITLE=${APP_TITLE:-LibreChat}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-user_provided}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-user_provided}
      - GOOGLE_KEY=${GOOGLE_KEY:-user_provided}
      - BINGAI_TOKEN=${BINGAI_TOKEN:-user_provided}
      - ASSISTANTS_API_KEY=${ASSISTANTS_API_KEY:-user_provided}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-user_provided}
      - GROQ_API_KEY=${GROQ_API_KEY:-user_provided}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-user_provided}
      - ANYSCALE_API_KEY=${ANYSCALE_API_KEY:-user_provided}
      - TOGETHERAI_API_KEY=${TOGETHERAI_API_KEY:-user_provided}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-user_provided}
    volumes:
      - librechat-api-images:/app/client/public/images
      - librechat-api-logs:/app/api/logs
  mongodb:
    image: "docker.io/bitnami/mongodb:5.0"
    volumes:
      - "mongodb-data:/bitnami/mongodb"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - "MONGODB_REPLICA_SET_NAME=rs0"
      - "MONGODB_PORT_NUMBER=27017"
      - "MONGODB_INITIAL_PRIMARY_HOST=mongodb"
      - "MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017"
      - "MONGODB_ADVERTISED_HOSTNAME=mongodb"
      - "MONGODB_ENABLE_JOURNAL=${MONGODB_ENABLE_JOURNAL:-true}"
      - "ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}"
    healthcheck:
      test: "echo 'db.stats().ok' | mongo localhost:27017/test --quiet"
      interval: 2s
      timeout: 10s
      retries: 15

  meilisearch:
    image: "getmeili/meilisearch:latest"
    environment:
      - "MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}"
      - "MEILI_ENV=production"
      - "MEILI_MASTER_KEY=${MEILI_MASTER_KEY}"
    volumes:
      - "meilisearch-data:/meili_data"
    restart: always
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://127.0.0.1:7700/health"
      interval: 2s
      timeout: 10s
      retries: 15

  vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY:-user_provided}
    restart: always
    depends_on:
      - vectordb

volumes:
  librechat-api-images:
  librechat-api-logs:
  mongodb-data:
  meilisearch-data:
  pgdata2:
```

Again, please correct me where I'm wrong as I'm still learning. I just hope this helps :)

**Reply by CaraCodeDev** [reply]
Really helpful, just noting that I cant seem to get RAG to work right, so chats cant read txt files  

Update:
I added a few things 
 environment:
      - HOST=0.0.0.0
      - PORT=3080
      - DOMAIN_CLIENT=http://localhost:3080
      - DOMAIN_SERVER=http://localhost:3080
      - SERVICE_FQDN_LIBRECHAT_3080
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - RAG_PORT=8000
      - RAG_API_URL=http://rag_api:8000
      - DEBUG_LOGGING=true
      - NO_INDEX=true.... and so on until 
      
      rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
      - OPENAI_API_KEY=sk....
      
      For my env variables
      RAG_API_URL=http://host.docker.internal:8000
      RAG_OPENAI_API_KEY=sk....
      EMBEDDINGS_PROVIDER=openai
      EMBEDDINGS_MODEL=text-embedding-3-small
      
      I pasted my open AI key everywhere. I also   made sure there were a couple dollars in my openAI fund. 
      
      And there you go, LibreChat working in Coolify

**Comment by akilicarslan** [comment]
Perfect conversation, thanks for everyone's helping here!

**Comment by alicantorun** [comment]
What happened to this template? I can't find it in the services list anymore?

**Reply by stewnight** [reply]
It was never in the service list, this is just a custom docker-compose file put together (while we pray it goes on the service list) :)

Here's my latest version (I stopped using Librechat in place of Open WebUI FYI, was less problematic): 
```

# documentation: https://docs.librechat.ai/install/configuration/dotenv.html
# slogan: Self-hosted, powerful, and privacy-focused chat UI for multiple AI models
# tags: ai,chat,gpt,claude,palm,openai,azure,huggingface,anthropic,ollama,llm
# logo: svgs/librechat.svg
# port: 3080

services:
  librechat:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    depends_on:
      mongodb:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
      vectordb:
        condition: service_healthy
      rag_api:
        condition: service_started
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - SERVICE_FQDN_LIBRECHAT_3080
      - NODE_ENV=production
      # MongoDB settings
      - MONGO_URI=mongodb://${SERVICE_USER_MONGO}:${SERVICE_PASSWORD_MONGO}@mongodb:27017/librechat?authSource=admin
      # Meilisearch settings
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${SERVICE_PASSWORD_MEILI}
      - ENABLE_MEILISEARCH=${ENABLE_MEILISEARCH:-true}
      # RAG settings
      - RAG_API_HOST=http://rag_api:8000
      - RAG_PORT=8000
      - ENABLE_RAG=${ENABLE_RAG:-true}
      # Auth settings
      - JWT_SECRET=${SERVICE_PASSWORD_JWT}
      - JWT_REFRESH_SECRET=${SERVICE_PASSWORD_64_JWT}
      - DOMAIN_CLIENT=${SERVICE_FQDN_LIBRECHAT}
      - DOMAIN_SERVER=${SERVICE_FQDN_LIBRECHAT}
      # App settings
      - ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN:-true}
      - APP_TITLE=${APP_TITLE:-LibreChat}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-true}
      - ALLOW_NO_APIKEY=${ALLOW_NO_APIKEY:-true}
      - ALLOW_UNVERIFIED_EMAIL_LOGIN=${ALLOW_UNVERIFIED_EMAIL_LOGIN:-true}
      - ALLOW_PASSWORD_RESET=${ALLOW_PASSWORD_RESET:-false}
      # Encryption settings
      - CREDS_KEY=${SERVICE_PASSWORD_64_CREDS}
      - CREDS_IV=${SERVICE_PASSWORD_CREDS}
      # API Keys
      - OPENAI_API_KEY=${SERVICE_OPENAI_API_KEY:-user_provided}
      - ANTHROPIC_API_KEY=${SERVICE_ANTHROPIC_API_KEY:-user_provided}
      - GOOGLE_KEY=${SERVICE_GOOGLE_API_KEY:-user_provided}
      - BINGAI_TOKEN=${SERVICE_BINGAI_TOKEN:-user_provided}
      - ASSISTANTS_API_KEY=${SERVICE_ASSISTANTS_API_KEY:-user_provided}
      - MISTRAL_API_KEY=${SERVICE_MISTRAL_API_KEY:-user_provided}
      - GROQ_API_KEY=${SERVICE_GROQ_API_KEY:-user_provided}
      - PERPLEXITY_API_KEY=${SERVICE_PERPLEXITY_API_KEY:-user_provided}
      - ANYSCALE_API_KEY=${SERVICE_ANYSCALE_API_KEY:-user_provided}
      - TOGETHERAI_API_KEY=${SERVICE_TOGETHERAI_API_KEY:-user_provided}
      - DEEPSEEK_API_KEY=${SERVICE_DEEPSEEK_API_KEY:-user_provided}
      # Debug settings
      - DEBUG_LOGGING=${DEBUG_LOGGING:-true}
      - NO_INDEX=${NO_INDEX:-true}
    volumes:
      - librechat-images:/app/client/public/images
      - librechat-logs:/app/api/logs
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://127.0.0.1:3080/api/health',
        ]
      interval: 5s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${SERVICE_USER_MONGO}
      - MONGO_INITDB_ROOT_PASSWORD=${SERVICE_PASSWORD_MONGO}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--eval',
          "db.runCommand('ping').ok",
          '127.0.0.1:27017/test',
          '--quiet',
        ]
      interval: 5s
      timeout: 10s
      retries: 3

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=${SERVICE_PASSWORD_MEILI}
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=production
    volumes:
      - meilisearch-data:/meili_data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:7700/health']
      interval: 2s
      timeout: 10s
      retries: 15

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - POSTGRES_DB=rag
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - DB_HOST=vectordb
      - DB_USER=${SERVICE_USER_POSTGRES}
      - DB_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - DB_NAME=rag
      - RAG_PORT=8000
      - RAG_OPENAI_API_KEY=${SERVICE_OPENAI_API_KEY:-user_provided}
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://127.0.0.1:8000/health',
        ]
      interval: 5s
      timeout: 20s
      retries: 10
    depends_on:
      vectordb:
        condition: service_healthy

  vectordb:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_DB=rag
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - vectordb-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '--username=$SERVICE_USER_POSTGRES'
        - '--host=127.0.0.1'
        - '--port=5432'
        - '--dbname=rag'
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s

volumes:
  mongodb-data:
  meilisearch-data:
  vectordb-data:
  librechat-images:
  librechat-logs:

```

**Reply by alicantorun** [reply]
Thanks for sharing this again! I could have sworn there was a LibreChat template available. I'm running one on my Coolify instances, and while migrating servers, I was looking for the LibreChat template for one-click deployment. However, I couldn’t find it—this discussion was the only relevant thing I came across. :)

**Reply by danny-avila** [reply]
I'm not an expert with coolify but I will work on contributing a 1-click deployment listed in their services.

**Reply by stewnight** [reply]
Ditto. I just read through the guide on how to commit and add 1-click templates. So will look to follow those suggestions and commit in the future. Unfortunately, focus is on another project atm.

https://coolify.io/docs/contribute/service/

**Comment by GauthierPLM** [comment]
I opened PR #5654 with @stewnight templated updated.

In the template, I embedded `librechat.yaml` based on the [official template](https://github.com/danny-avila/LibreChat/blob/main/librechat.example.yaml). I'd appreciate feedback on the following:

- Should I keep using the example `librechat.yaml` from official repo ?
- Should I only declare the volume with an empty file / only the essential nodes ?
- Should I make a « custom » version that would have good defaults for someone using Coolify (and if so, what would be good defaults)?

@danny-avila your feedback / recommendation on this would be very appreciated if you have some time. :)

**Reply by mbdev4web** [reply]
Just wanted to share my experience with the template from @stewnight.
Everything works pretty well, I just added the support for persisting the librechat.yaml file to add more configuration possibilities.
```
services:
  librechat:
    image: 'ghcr.io/danny-avila/librechat-dev-api:latest'
    depends_on:
      mongodb:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
      vectordb:
        condition: service_healthy
      rag_api:
        condition: service_started
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - SERVICE_FQDN_LIBRECHAT_3080
      - NODE_ENV=production
      - 'MONGO_URI=mongodb://${SERVICE_USER_MONGO}:${SERVICE_PASSWORD_MONGO}@mongodb:27017/librechat?authSource=admin'
      - 'MEILI_HOST=http://meilisearch:7700'
      - MEILI_NO_ANALYTICS=true
      - 'MEILI_MASTER_KEY=${SERVICE_PASSWORD_MEILI}'
      - 'ENABLE_MEILISEARCH=${ENABLE_MEILISEARCH:-true}'
      - 'RAG_API_HOST=http://rag_api:8000'
      - RAG_PORT=8000
      - 'ENABLE_RAG=${ENABLE_RAG:-true}'
      - 'JWT_SECRET=${SERVICE_PASSWORD_JWT}'
      - 'JWT_REFRESH_SECRET=${SERVICE_PASSWORD_64_JWT}'
      - 'DOMAIN_CLIENT=${SERVICE_FQDN_LIBRECHAT}'
      - 'DOMAIN_SERVER=${SERVICE_FQDN_LIBRECHAT}'
      - 'ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN:-true}'
      - 'APP_TITLE=${APP_TITLE:-LibreChat}'
      - 'ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-true}'
      - 'ALLOW_NO_APIKEY=${ALLOW_NO_APIKEY:-true}'
      - 'ALLOW_UNVERIFIED_EMAIL_LOGIN=${ALLOW_UNVERIFIED_EMAIL_LOGIN:-true}'
      - 'ALLOW_PASSWORD_RESET=${ALLOW_PASSWORD_RESET:-false}'
      - 'CREDS_KEY=${SERVICE_PASSWORD_64_CREDS}'
      - 'CREDS_IV=${SERVICE_PASSWORD_CREDS}'
      - 'OPENAI_API_KEY=${SERVICE_OPENAI_API_KEY:-user_provided}'
      - 'ANTHROPIC_API_KEY=${SERVICE_ANTHROPIC_API_KEY:-user_provided}'
      - 'GOOGLE_KEY=${SERVICE_GOOGLE_API_KEY:-user_provided}'
      - 'BINGAI_TOKEN=${SERVICE_BINGAI_TOKEN:-user_provided}'
      - 'ASSISTANTS_API_KEY=${SERVICE_ASSISTANTS_API_KEY:-user_provided}'
      - 'MISTRAL_API_KEY=${SERVICE_MISTRAL_API_KEY:-user_provided}'
      - 'GROQ_API_KEY=${SERVICE_GROQ_API_KEY:-user_provided}'
      - 'PERPLEXITY_API_KEY=${SERVICE_PERPLEXITY_API_KEY:-user_provided}'
      - 'ANYSCALE_API_KEY=${SERVICE_ANYSCALE_API_KEY:-user_provided}'
      - 'TOGETHERAI_API_KEY=${SERVICE_TOGETHERAI_API_KEY:-user_provided}'
      - 'DEEPSEEK_API_KEY=${SERVICE_DEEPSEEK_API_KEY:-user_provided}'
      - 'DEBUG_LOGGING=${DEBUG_LOGGING:-true}'
      - 'NO_INDEX=${NO_INDEX:-true}'
      - 'OPENAI_MODELS=${OPENAI_MODELS:-o3,o4-mini,gpt-4o,gpt-4.1}'
      - 'ENDPOINTS=${ENDPOINTS:-openAI,azureOpenAI,google,anthropic}'
      - 'OPENROUTER_KEY=${OPENROUTER_KEY:-user_provided}'
      - 'GOOGLE_MODELS=${GOOGLE_MODELS:-gemini-2.5-pro-exp-03-25,gemini-2.0-flash-exp}'
      - 'CONFIG_PATH=/app/custom/config/librechat.yaml'
    volumes:
      - 'librechat-images:/app/client/public/images'
      - 'librechat-uploads:/app/uploads'
      - 'librechat-logs:/app/api/logs'
      - 'librechat-config:/app/custom/config'
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--tries=1'
        - '--spider'
        - 'http://127.0.0.1:3080/api/health'
      interval: 5s
      timeout: 10s
      retries: 3
  mongodb:
    image: 'mongo:6-jammy'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${SERVICE_USER_MONGO}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${SERVICE_PASSWORD_MONGO}'
      - 'ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}'
    volumes:
      - 'mongodb-data:/data/db'
    healthcheck:
      test:
        - CMD
        - mongosh
        - '--eval'
        - "db.runCommand('ping').ok"
        - '127.0.0.1:27017/test'
        - '--quiet'
      interval: 5s
      timeout: 10s
      retries: 3
  meilisearch:
    image: 'getmeili/meilisearch:latest'
    environment:
      - 'MEILI_MASTER_KEY=${SERVICE_PASSWORD_MEILI}'
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=production
    volumes:
      - 'meilisearch-data:/meili_data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:7700/health'
      interval: 2s
      timeout: 10s
      retries: 15
  rag_api:
    image: 'ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest'
    environment:
      - POSTGRES_DB=rag
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - DB_HOST=vectordb
      - 'DB_USER=${SERVICE_USER_POSTGRES}'
      - 'DB_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - DB_NAME=rag
      - RAG_PORT=8000
      - 'RAG_OPENAI_API_KEY=${SERVICE_OPENAI_API_KEY:-user_provided}'
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--tries=1'
        - '--spider'
        - 'http://127.0.0.1:8000/health'
      interval: 5s
      timeout: 20s
      retries: 10
    depends_on:
      vectordb:
        condition: service_healthy
  vectordb:
    image: 'ankane/pgvector:latest'
    environment:
      - POSTGRES_DB=rag
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - 'vectordb-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '--username=$SERVICE_USER_POSTGRES'
        - '--host=127.0.0.1'
        - '--port=5432'
        - '--dbname=rag'
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
volumes:
  mongodb-data: null
  meilisearch-data: null
  vectordb-data: null
  librechat-images: null
  librechat-logs: null
  librechat-uploads: null
  librechat-config: null
```
Just added a librechat-config volume so you can create the yaml e.g. in such a directory:
/app/custom/config/librechat.yaml

I was easily able to add OpenRouter there
```
version: 1.2.1

endpoints:
  custom:
    - name: 'OpenRouter'
      apiKey: '${OPENROUTER_KEY}'
      baseURL: 'https://openrouter.ai/api/v1'
      models:
        default: ['meta-llama/llama-3-70b-instruct']
        fetch: true
      titleConvo: true
      titleModel: 'meta-llama/llama-3-70b-instruct'
      dropParams: ['stop']
      modelDisplayLabel: 'OpenRouter'
```
Useful to add e.g. Azure Open AI configuration
