### DISCUSSION TITLE
Coolify behind external Traefik instance

### DISCUSSION THREAD

**Discussion by Fade97** [coollabsio/coolify#2868] [Q&A]
I am currently trying to setup Coolify on my home server. I am facing issues getting it to work with my existing traefik instance.
I have Proxmox running on the server with a portainer instance running traefik. Coolify is running on its own VM. I am trying to get traffic routed through my traefik instance to Coolify but I can not get it to work.

I hope you can help me.

**Comment by leikoilja** [comment]
Hey @Fade97 , did you manage to sort it out? I'm setting up coolify in the exact same setup as yours and am starting to have issues w routing as well

**Comment by KianAnbarestani** [comment]
@Fade97 
Make sure Coolify is reachable from your Traefik VM over port 3000. Then configure a Traefik router with `Host("coolify.example.com")` and a service pointing to `http://<coolify-vm-ip>:3000`. Add proper DNS records for the domain and ensure your VMs can talk across the network. Lastly, confirm that Traefik is picking up the route and proxying correctly. Let me know if you need a full config snippet!

**Comment by benblustey** [comment]
Adding to this conversation since I was able to get Coolify to work behind my TraefikV2/Authelia hosted on unRaid Ubuntu VM. Hopefully this can help. This is my example from `fileConfig.yml`. 
```
http:
  routers:
    coolify:
      rule: "Host(`coolify.example.com`)"
      entryPoints:
      - https
      service: coolify
  services:
    coolify:
      loadBalancer:
        servers:
        - url: "http://192.168.1.22:8000"
```
I'm currently working on getting the preview URLs to render correctly.
