### DISCUSSION TITLE
Cloudflare API integration for automatic domain/subdomain creation

### DISCUSSION THREAD

**Discussion by juddisjudd** [coollabsio/coolify#2871] [Service Template Requests]
Cloudflare has an API for creating hostnames and such and it would nice to have that integrated into coolify.
I believe other registrars have this option as well.

**Comment by DearTanker** [comment]
If this feature is supported, efficiency will be greatly improved.

**Comment by RjManhas** [comment]
upvoted

**Comment by ruohki** [comment]
Supporting this is a bottomless pit. Not only do you need to keep up to cloudflare api development but also do you have to deal with people asking for godaddy, namecheap, route 53 etc... This should be a product for itself that does scan traefik labels and then does the dns setup / checking on its own. Like certbot is for certificates.

Plus in terms of cloudflare there is simple dns and also the tunnel special dns entries.

https://github.com/traefik/traefik/issues/5175

https://github.com/kubernetes-sigs/external-dns

**Comment by djsisson** [comment]
adding to the above, you can already do this by just adding the dnschallenge entry and relevant api key to the traefik config

see:
https://doc.traefik.io/traefik/https/acme/#dnschallenge
https://go-acme.github.io/lego/dns/cloudflare/

```yaml
    environment:
      CF_DNS_API_TOKEN=XXXX
    labels:
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
 ```
