### DISCUSSION TITLE
Request for Kafka Docker Template in Coolify

### DISCUSSION THREAD

**Discussion by gyancarlodasilva** [coollabsio/coolify#2889] [Feature Requests]
Hello Coolify Team,

I am writing to express my interest in having a Docker template for Apache Kafka available in Coolify. As a widely adopted streaming platform, Kafka has revolutionized real-time data processing and its inclusion as a template in Coolify would significantly enhance the platform's capabilities for data management and processing.

Here are some key benefits of adding a Kafka Docker template to Coolify:

1. **Simplified Deployment:** A Docker template for Kafka would allow users to quickly and easily deploy Kafka instances within Coolify. This would simplify the setup process and make it more accessible to a wider audience.

2. **Real-time Data Processing:** Kafka excels in handling real-time data streams, enabling businesses to process and analyze data as it arrives. Providing a Kafka template would allow Coolify users to build robust, real-time data pipelines with ease.

3. **Scalability and Fault Tolerance:** Kafka is designed to handle large volumes of data across distributed systems, offering excellent scalability and fault tolerance. This would empower Coolify to support even the most demanding data workloads.

4. **Enhanced Data Integration:** With Kafka, Coolify users could seamlessly integrate various data sources and destinations, facilitating a more cohesive data ecosystem. This would streamline data workflows and improve overall efficiency.

5. **Improved Event-Driven Architectures:** Kafka's event-driven model aligns perfectly with modern microservices architectures. By providing a Kafka template, Coolify would enable developers to build more responsive and decoupled applications.

6. **Community and Ecosystem:** Kafka boasts a vibrant community and a rich ecosystem of tools and extensions. Adding a Kafka template to Coolify would open up new possibilities for users, leveraging the extensive resources and expertise available within the Kafka community.

I believe that adding a Kafka Docker template to Coolify would provide immense value to its users, enhancing their ability to manage and utilize data effectively. Thank you for considering this request, and I look forward to the potential advancements it could bring to the platform.

**Comment by flipbytes-dk** [comment]
Couldn't agree more

**Reply by jampack** [reply]
And may be also add [Redpanda-Console](https://www.redpanda.com/redpanda-console-kafka-ui)

**Comment by Polyhistor** [comment]
2025 November, I think this is still a valuable idea ?

**Comment by a4amado** [comment]
Dec 25, We need this

**Comment by ErennBas** [comment]
feb 05 2026. we still need this

**Comment by iamsouravganguli** [comment]
Please add

**Comment by ankurmaheshsingh** [comment]
March 09 2026, we need this

**Comment by otabekgh** [comment]
still relavent 27.03.2026

**Comment by sambeaCA** [comment]
For anyone in need for Kafka on Coolify, here is a docker-compose:

```yml
# Apache Kafka 3.9 (KRaft) + Kafka UI — Coolify Docker Compose
# Usage:
#   Local:   docker compose -f kafka.yml up -d
#   Coolify: paste this file; set required env vars in Coolify UI.
#
# Coolify auto-generates:
#   - SERVICE_FQDN_KAFKAUI_8080  → public domain for Kafka UI
#   - SERVICE_PASSWORD_KAFKAUI   → admin password (persisted across deploys)
#
# Kafka broker is internal-only (no FQDN). Other stacks reach it on the
# Coolify "Predefined Network" using DNS name `kafka:9092`.
#
# KRaft mode = no ZooKeeper. CLUSTER_ID must be a stable base64 UUID;
# Coolify regenerates it once via SERVICE_BASE64_KAFKACLUSTER and persists it.

x-common: &common
  restart: unless-stopped

services:
  # ──────────────────────────────────────────────
  # Kafka broker (single-node KRaft: combined controller + broker)
  # Two listeners:
  #   INTERNAL  (PLAINTEXT, port 9092) — used by other containers
  #   CONTROLLER (port 9093)           — KRaft quorum, internal only
  # ──────────────────────────────────────────────
  kafka:
    <<: *common
    image: apache/kafka:3.9.0
    expose:
      - "9092"
    environment:
      # Node identity & roles
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      CLUSTER_ID: ${SERVICE_BASE64_KAFKACLUSTER}

      # Listeners
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Single-broker safe defaults — override for prod multi-broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_AUTO_CREATE_TOPICS_ENABLE:-true}

      # Storage
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LOG_RETENTION_HOURS: ${KAFKA_LOG_RETENTION_HOURS:-168}
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  # ──────────────────────────────────────────────
  # Kafka UI — web console (provectus)
  # Public via SERVICE_FQDN_KAFKAUI_8080
  # ──────────────────────────────────────────────
  kafka-ui:
    <<: *common
    image: provectuslabs/kafka-ui:latest
    depends_on:
      kafka:
        condition: service_healthy
    expose:
      - "8080"
    environment:
      SERVICE_FQDN_KAFKAUI_8080: ${SERVICE_FQDN_KAFKAUI_8080}
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"
      AUTH_TYPE: LOGIN_FORM
      SPRING_SECURITY_USER_NAME: ${KAFKAUI_USER:-admin}
      SPRING_SECURITY_USER_PASSWORD: ${SERVICE_PASSWORD_KAFKAUI}
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/actuator/health | grep -q UP || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  kafka-data:

```
