### DISCUSSION TITLE
Webhook from Github action provide version to deploy

### DISCUSSION THREAD

**Discussion by merlinofcha0s** [coollabsio/coolify#2924] [Feature Requests]
Hello,

Today, when using Coolify to deploy a Docker image (not with NixPack), I would still like to have automatic deployment.
It is already possible to send a webhook from GitHub action, but I didn't see anything that allows specifying the version to deploy.

Do you think it will be possible to add this feature?

Thanks.

Regards,

**Comment by Cryszon** [comment]
I've solved this by sending a separate `PATCH` request that updates the `git_commit_sha` for the resource before the deployment webhook but I agree that it would be nice to be able to specify the commit to deploy directly in the deploy hook.

**Reply by FaisalBudiono** [reply]
Can you give me an example of this? I don't even have any idea how to trigger the deployment via github action.

**Reply by Cryszon** [reply]
[Here's an example of a workflow that does this](https://github.com/ReunMedia/project-templates/blob/8e8496228c279f68add6046c62c137e5ded240bd/.github/workflows/coolify-deployment.yml).

Here's the part that updates the commit SHA and triggers the deployment:

```yml
- name: Update source commit SHA in Coolify
  uses: fjogeleit/http-request-action@v1
  with:
    url: ${{env.COOLIFY_URL}}/api/v1/applications/${{env.COOLIFY_RESOURCE_ID}}
    method: PATCH
    bearerToken: ${{env.COOLIFY_API_TOKEN}}
    data: >-
      {
      "git_commit_sha": "${{github.sha}}"
      }

- name: Trigger Coolify deployment via webhook
  uses: fjogeleit/http-request-action@v1
  with:
    url: ${{env.COOLIFY_URL}}/api/v1/deploy?uuid=${{env.COOLIFY_RESOURCE_ID}}&force=false
    method: GET
    bearerToken: ${{env.COOLIFY_API_TOKEN}}
```

Basically just run HTTP requests described in [Coolify API docs](https://coolify.io/docs/api-reference/api/operations/deploy-by-tag-or-uuid).
