### DISCUSSION TITLE
Payload CMS

### DISCUSSION THREAD

**Discussion by dmBunting** [coollabsio/coolify#2933] [Service Template Requests]
[Payload](https://payloadcms.com/) is an open source Next CMS and having a one-click deploy option would be awesome!

**Comment by loewenmichael** [comment]
Yes, agree, this is docker compose according to their documentation:

```
version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - mongo
      # - postgres
    env_file:
      - .env

  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

  # Uncomment the following to use postgres
  # postgres:
  #   restart: always
  #   image: postgres:latest
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  data:
  # pgdata:
  node_modules:
```
  
  https://payloadcms.com/docs/production/deployment#docker
