### DISCUSSION TITLE
Improve OpenAPI scheme

### DISCUSSION THREAD

**Discussion by valentinschabschneider** [coollabsio/coolify#2937] [Improvement Requests]
Currently the (I'm guessing) generated openapi scheme that is versioned at https://github.com/coollabsio/coolify/blob/main/openapi.yaml has weird `operationId`s. This currently makes it impossible to generate a `go` client with https://github.com/OpenAPITools/openapi-generator (because some start with a digit). I saw that @andrasbacsai is currently configuring the api documentation and i thought that this would be a nice addition. :)

```yaml
...
/applications:
    get:
      tags:
        - Applications
      summary: List
      description: 'List all applications.'
      operationId: 02978e79fc0b54d573b2359f2a1f7d86
...
```

```yaml
...
/applications:
    get:
      tags:
        - Applications
      summary: List
      description: 'List all applications.'
      operationId: getApplications
...
```
