### DISCUSSION TITLE
Traefik Dashboard Access

### DISCUSSION THREAD

**Discussion by nuxwin** [coollabsio/coolify#3019] [Feature Requests]
Good morning,

Coolify doesn't setup the Traefik Dashboard access by default (one dashboard per server). For each server added, it could be great to have the dashboard acces out of box, with access links made available from the Coolify UI.

For instance, in our case, we have made the following changes for each of our server to make it working :

Example for one server :

Traefik proxy docker compose configuration file modifications:

```yaml
services:
  traefik:
    container_name: coolify-proxy
    #image: 'traefik:v2.11'
    image: 'traefik:v3.1'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
    #  - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=50'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--providers.docker=true'
    labels:
      - traefik.enable=true
    #  - traefik.http.routers.traefik.entrypoints=http
    #  - traefik.http.routers.traefik.service=api@internal
    #  - traefik.http.services.traefik.loadbalancer.server.port=8080
      - coolify.managed=true
networks:
  coolify:
    external: true
```

Dynamic configuration that we added (file traefik-dashboard.yml):

```yml
http:
  middlewares:
    authentication:
      basicAuth:
        realm: traefik-dashboard
        users:
          - 'l.declercq@konzeptplus.ch:$apr1$<passwordhash>'
    gzip:
      compress: true
    content-type:
      contenttype: true
    redirect-to-https:
      redirectScheme:
        scheme: https
  routers:
    traefik-dashboard-http:
      entryPoints:
        - http
      middlewares:
        - redirect-to-https
      rule: Host(`traefik.srv01.konzeptplus-preview.ch`)
      service: noop@internal
    traefik-dashboard-https:
      entryPoints:
        - https
      middlewares:
        - authentication
        - content-type
        - gzip
      rule: Host(`traefik.srv01.konzeptplus-preview.ch`)
      service: api@internal
      tls:
        certResolver: letsencrypt
```

Result: 
![Capture d’écran 2024-08-07 à 15 45 39](https://github.com/user-attachments/assets/a6ace279-8402-491a-a427-a37d8601c2b6)
