### DISCUSSION TITLE
Update to Traefik v3.1

### DISCUSSION THREAD

**Discussion by nuxwin** [coollabsio/coolify#3044] [Feature Requests]
Good morning,

We switched to Traefik v3.1 which seem to work pretty well with Coolify out-of-box. There are only some modifcations regarding Swarm which is now provided as a dedicated provider :

```yaml
networks:
  coolify-overlay:
    external: true
services:
  traefik:
    #image: 'traefik:v2.11'
    image: 'traefik:v3.1'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify-overlay
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      # NXW addon (required by Harbor) - We should have a checkbox for that in the Coolify UI (suggestion)
      - '--entryPoints.http.forwardedHeaders.insecure'
      # NXW addon (required by Harbor) - We should have a checkbox for that in the Coolify UI (suggestion)
      - '--entryPoints.https.forwardedHeaders.insecure'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=50'
      #- '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      #- '--providers.docker.swarmMode=true'
      - '--providers.swarm.endpoint=unix:///var/run/docker.sock'
      - '--providers.swarm.exposedbydefault=false'
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.entrypoints=http
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - coolify.managed=true
      placement:
        constraints:
          - node.role==manager
```
![Capture d’écran 2024-08-10 à 06 58 45](https://github.com/user-attachments/assets/2398d287-35a7-4abc-910f-b740c3e7f48c)
