### DISCUSSION TITLE
Ente.io

### DISCUSSION THREAD

**Discussion by nank1ro** [coollabsio/coolify#3060] [Service Template Requests]
It will be nice to have Ente.io which is an end-to-end encrypted alternative to Google Photos and Apple Photos.

Self hosting docs
https://help.ente.io/self-hosting/

**Comment by RayBB** [comment]
Big +1 on this. Looking at the setup guide it shouldn't be too hard either.

**Comment by ggpepp41** [comment]
I am working on a template for ente but it requires the following issue to be resolved. 
[https://github.com/coollabsio/coolify/issues/3639](url)

**Reply by nank1ro** [reply]
@ggpepp41 do you have any updates?
Seems like it won't accept env variables with dashes.

**Reply by ggpepp41** [reply]
I submitted an issue for the dashes problem [here] (https://github.com/coollabsio/coolify/issues/3639#issue-2555139115).   The only response was moving it to triage.

**Reply by nank1ro** [reply]
Yes seems like dashes are not valid in Env variables.
Seems like an invalid format used by Ente

**Reply by ggpepp41** [reply]
Based on my research, it is not required to be supported by shell operations.   I actually use portainer for my docker deployment platform and it has no issues with the dashes. This is probably something that ente would want to address to bring their env variables to a more widely accepted standard.

**Reply by nank1ro** [reply]
do you have your implementation of Ente for coolify available somewhere? I would like to try it, maybe by forking Ente and updating the variable name to respect the format

**Reply by luckydonald** [reply]
Is there already an issue raised with ente regarding the dashes?

**Reply by Shusek** [reply]
Has anything changed since last year?

**Reply by nank1ro** [reply]
> Has anything changed since last year?
> 
> 

Nothing

**Comment by quarkcore** [comment]
i just got it to run so far ~expect that there is still struggle with my cors policy on the s3 bucket as it seems (but thats neither a coolify nor an ente thing)~

In case of storing at own remote s3 bucket instance/s the `museum.yaml` is the biggest roadblock. The config needs to be readableby the server and as far as i know there is no way of managing such a file template within coolify. Thats why in this case a self contained docker stack / compose template is like not achievable. But it should be possible if mini-io is used as the s3 storage backend (which is the case on self hosted instances by default where remote bucket replica is turned off and mini-io inside docker is the default).

For routing to the correct endpoints using the coolify traefik its seems favorable to have one subdomain for each endpoint and let coolify generate the correct traefik labels by using `https://ente.foo.bar:3000,https://ente-albums.foo.bar:3002` for the `web` service.

Running the stack with remote replica enabled doesn’t seem very practical or easy to work with. I’m not convinced it’s a great fit for a template like this. The only approach I can imagine making it work is to create a custom Docker image on top of the official ones from the ente team, which would generate the `museum.yaml` dynamically from environment variables. But honestly, even that doesn’t sound particularly smooth or straightforward and would result in extra maintenance which is likely to break.

Anyhow here is my docker compose config if someone is interested:

```
services:
  museum:
    image: ghcr.io/ente-io/server
    environment:
      - SERVICE_FQDN_ENTE
    expose:
      - 8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - '/something/on/host/museum.yaml:/museum.yaml:ro' # mount config from host
      - './data:/data:ro'
      
  web:
    image: ghcr.io/ente-io/web
    environment:
      - SERVICE_FQDN_ENTE_WEB
      - ENTE_API_ORIGIN: $SERVICE_FQDN_ENTE
      - ENTE_ALBUMS_ORIGIN: ${ENTE_ALBUMS_ORIGIN}
    expose:
      - 3000
      - 3002
      
  socat:
    image: alpine/socat
    network_mode: 'service:museum'
    depends_on:
      - museum
    command: 'TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200'
    
  postgres:
    image: 'postgres:15'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}' # injected by coolify
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}' # injected by coolify
      POSTGRES_DB: '${POSTGRES_DB}' # injected by coolify
    healthcheck:
      test: 'pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}'
      start_period: 40s
      start_interval: 1s
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
      
    # Optionally ad MiniIo service as s3 storage backend

volumes:
  postgres-data:
```
