### DISCUSSION TITLE
SSH reverse tunnel

### DISCUSSION THREAD

**Discussion by hnykda** [coollabsio/coolify#3088] [Service Template Requests]
I am using Home Assistant, and I wanted to have a reverse SSH tunnel so I can connect to it from outside the world. Here is the coolify setup I use for that:

```
services:
  homeassistant-autossh:
    image: 'linuxserver/openssh-server:latest'
    restart: unless-stopped
    ports:
      - '<MY-COOLIFY-SERVER-IP>:2244:2222'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - USER_NAME=homeassistant
      - PASSWORD_ACCESS=false
      - SUDO_ACCESS=false
      - PUBLIC_KEY_FILE=/authorized_keys
    volumes:
      - './authorized_keys:/authorized_keys'
      - './custom_config:/custom-cont-init.d:ro'
    labels:
      traefik.http.routers.homeassistant-myhome.rule: Host(`my-domain.com`)
      traefik.http.routers.homeassistant-myhome.tls.certresolver: letsencrypt
      traefik.http.routers.homeassistant-myhome.service: homeassistant-myhome
      traefik.http.services.homeassistant-myhome.loadbalancer.server.port: 8124
```

where the mounted files are:

```
[I] root@robert /d/c/s/isgow40goosk0osksc8wco8s# cd ../z8sg4so/
[I] root@robert /d/c/s/z8sg4so# ls
authorized_keys*  config/  custom_config/  docker-compose.yml  openssh_config
[I] root@robert /d/c/s/z8sg4so# cat custom_config/req.sh
#!/bin/bash
# set -e
sed -i 's/AllowTcpForwarding no/AllowTcpForwarding yes/g' /etc/ssh/sshd_config
sed -i 's/GatewayPorts no/GatewayPorts yes/g' /etc/ssh/sshd_config
[I] root@robert /d/c/s/z8sg4so# cat openssh_config
GatewayPorts clientspecified
AllowTcpForwarding yes
```

domain of the container setup to `https://<my-domain.com>`. Should work fairly generally, but e.g. with https://github.com/ThomDietrich/home-assistant-addons you need this:

```
hostname: <my-coolify-server-ip>
ssh_port: 2244
username: homeassistant
remote_forwarding:
  - 127.0.0.1:8124:172.30.232.1:8123
other_ssh_options: ""
force_keygen: false
```
