### DISCUSSION TITLE
Allow furter Traefik middlewares

### DISCUSSION THREAD

**Discussion by Signum** [coollabsio/coolify#3122] [Feature Requests]
I would like Traefik to change an header in the HTTP request before it gets passed to the container.
Traefik provides the "headers" middleware to accomplish that.

I am using a Docker-Compose deployment with Coolify v4.0.0-beta.323

```yaml
services:
  web-app1:
    labels:
      - traefik.http.middlewares.add-my-header.headers.customrequestheaders.X-Weather=Sunny
```

That middleware is visible in the "Deployable Compose". But it is not used by the Traefik router that Coolify creates:

      - traefik.http.routers.https-0-mc84kk8gwwwcgc40k80gwsow-web-app-1.middlewares=gzip

You can see that it only adds "gzip" but I would need "gzip,add-my-header".

I dug into Coolify's source code at bootstrap/helpers/docker.php and found that Coolify has code to handle "redirect" and "basicauth" middlewares. But it will ignore further middlewares.

Is there a possible workaround?

(Use case: I want to run a Wordpress _staging_ site on Coolify. Wordpress must believe that the "Host:" header is the FQDN of the actual site. But I make it available under a different FQDN externally.)
