### DISCUSSION TITLE
[Feature]: option for using the host network

### DISCUSSION THREAD

**Discussion by otahirs** [coollabsio/coolify#3146] [Feature Requests]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add option to bind the container directly to the host network. equal to the `docker run --network host ...`

ps: this option would bypass the coolify proxy, it is expected there is a custom reverse proxy setup (e.g. nginx) or that the port is meant to be directly exposed to the internet

### Why should this be worked on?

In network heavy application the docker bridge network can become the main performance bottleneck.

**Comment by maxexcloo** [comment]
Having the same issue here - was there any fix?

**Comment by matheusfillipe** [comment]
With the default installation and using caddy, the internal web apps only see the docker bridge address.
I was able to get it working for the web apps by adding `network_mode: host` and removing the network block because they are not compatible together
In the proxy server config:

```
version: '3.8'
services:
  caddy:
    container_name: coolify-proxy
    image: 'lucaslorentz/caddy-docker-proxy:2.8-alpine'
    restart: unless-stopped
    network_mode: host
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - CADDY_DOCKER_POLLING_INTERVAL=5s
      - CADDY_DOCKER_CADDYFILE_PATH=/dynamic/Caddyfile
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy/caddy/dynamic:/dynamic'
      - '/data/coolify/proxy/caddy/config:/config'
      - '/data/coolify/proxy/caddy/data:/data'
```

Now my web apps can see the real IP but this breaks access to the main coolify app itself (still have it on port 8000). Why is that so?

```
{
  "level": "error",
  "ts": 1717660262.7968147,
  "logger": "http.log.error",
  "msg": "dial tcp: lookup coolify-realtime on 127.0.0.53:53: server misbehaving",
  "request": {
     ...,
  }
  "duration": 0.001383811,
  "status": 502,
  "err_id": "ie0vnxi7e",
  "err_trace": "reverseproxy.statusError (reverseproxy.go:1267)"
}
```

For having this on non http apps, would be ideal to support `--network host` here https://coolify.io/docs/knowledge-base/docker/custom-commands

**Comment by itniels** [comment]
I second this, I tried to spin up a CoTurn Docker server, and they do state that Host network is recommended as Docker does not handle many ports well like this `3478:3478,3478:3478/udp,5349:5349,5349:5349/udp,49152-65535:49152-65535/udp` and this killed the whole server completely!

So this feature would be amazing 🙂

**Comment by MPPlexor** [comment]
Same goes for Home Assistant. See https://github.com/coollabsio/coolify/issues/1092

**Comment by pizzaandcheese** [comment]
For your coolify-proxy container to be able to see your containers setup with `network_mode: host` it must also have `network_mode: host` enabled as well. This can be done in the coolify panel by navigating to the server > proxy settings > Configuration and doing the same trick mentioned above by @matheusfillipe there.

Keep in mind that this will require all other containers proxied through coolify-proxy to also have `network_mode: host` enabled

**Comment by jonathan-reisdorf** [comment]
As others mentioned it would be awesome if we had an easy way to use the host network for some of the containers where it makes sense (some services don't work as expected on bridge network) and where no proxy is needed. One could also show a little warning when enabling said option so users are aware they are directly exposing ports etc.
I'm aware this potentially requires some reworking of the UI to disable unnecessary fields and so on, but maybe setting up a bounty for this would be an option as well?

**Comment by citelao** [comment]
Is the issue simply that `coolify-proxy` cannot access/see `network_mode: host` containers? Or are there other issues?

For context, I've been running Home Assistant in Coolify for a few weeks using a custom docker-compose file without issue (but I might not be noticing the issue). Note that I'm not using Coolify to proxy anything.

<details>
<summary>Example HASS docker-compose</summary>

```yaml
version: '3.3'
services:
  home-assistant:
    container_name: homeassistant
    privileged: true
    restart: unless-stopped
    environment:
        - TZ=America/New_York
    volumes:
        - '/home/pi/home_assistant/:/config'
        - /etc/localtime:/etc/localtime:ro
        - /run/dbus:/run/dbus:ro
    network_mode: host
    image: 'ghcr.io/home-assistant/home-assistant:2025.3'
```
</details>
