### DISCUSSION TITLE
[Improvement]: All networks/destinations in coolify are created as external -> change this to internal

### DISCUSSION THREAD

**Discussion by peaklabs-dev** [coollabsio/coolify#3164] [Improvement Requests]
### Description

All coolify services and containers are deployed on their own network (which is great). These networks are all external, which is less secure than internal. Please change the default to internal (for services in docker compose):
change this:
```yml
networks:
  y84owso:
    name: y84owso
    external: true
```
to this:
```yml
networks:
  y84owso:
    name: y84owso
    internal: true
```

### Minimal Reproduction (if possible, example repository)

Inspect a network via the ID in the command line via ssh.

### Version

v4.0.0-beta.297
