### DISCUSSION TITLE
couchDB

### DISCUSSION THREAD

**Discussion by peaklabs-dev** [coollabsio/coolify#3200] [Database Requests]
Add couchDB as a one click Database

**Comment by SlavenIvanov** [comment]
Please do!

**Comment by jcs224** [comment]
This would actually be a big addition, since there is not actually an easy/affordable way to host CouchDB outside of Cloudant or Couchbase. It's not a super-popular database but it's really a handle tool in the belt when you need it!

**Reply by SlavenIvanov** [reply]
I have submitted a PR that adds a CouchDB template. Its available now 
<img width="507" alt="image" src="https://github.com/user-attachments/assets/349d3a6f-7f01-4e0e-93b7-33b3993db206" />

**Reply by jcs224** [reply]
You, sir, are amazing :relieved: 

Where can I look at the PR? I can't seem to find it by searching..

**Comment by imjlk** [comment]
https://github.com/coollabsio/coolify/blob/4dc46b45b9b8562772b33bf06561b83aa7505380/templates/compose/budibase.yaml#L105-L118
I'm running based on the image included in the above configuration.
(budibase/couchdb, currently default version is 3.3.3)

Below is the docker compose configuration I used in coolify.

```yaml
services:
  couchdb:
    image: budibase/couchdb
    environment:
      - SERVICE_FQDN_COUCHDB
      - COUCHDB_PASSWORD=$SERVICE_PASSWORD_COUCHDB
      - COUCHDB_USER=$SERVICE_USER_COUCHDB
      - TARGETBUILD=docker-compose
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -f -u $${COUCHDB_USER}:$${COUCHDB_PASSWORD} http://localhost:5984/"]
      interval: 15s
      timeout: 15s
      retries: 3
      start_period: 10s
    container_name: couchdb #shortened name
    volumes:
      - 'couchdb-data:/opt/couchdb/data'
      - 'config:/opt/couchdb/etc/local.d'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.couchdb.rule=Host(`yourhost.tld`)"
```

Labels required for basic authentication to bypass
