### DISCUSSION TITLE
A tip: Add this service to your docker-compose.yaml of a deployed app/service for daily backups of that app

### DISCUSSION THREAD

**Discussion by hnykda** [coollabsio/coolify#3253] [General]
I deploy services with separated postgresql databases (I like to have them separated) via docker-compose. To backup them, I found this docker file that does plain old postgres daily backups:

```
  dbbackups:
    image: 'kartoza/pg-backup:15-3.3'
    volumes:
      - './db-backups:/backups'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=mmuser
      - POSTGRES_PASS=mmuser_password
      - REMOVE_BEFORE=7
      - DUMPPREFIX=mattermost
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
```

I then backup these service-specific folders with the dumps there e.g. via duplicity:

```
duplicity backup \
    --include '/data' \
    --full-if-older-than 1W \
    / \
    rclone://gdrive:/Backups/duplicity-backups
```
