### DISCUSSION TITLE
Coolify not following local volumes

### DISCUSSION THREAD

**Discussion by dan-is-not-the-man** [coollabsio/coolify#3268] [Q&A]
Hi, i have  a project setup with a Dockerfile hosted in github. Whenever i re-deploy the Dockerfile it seems to create the original folder locations `/data/coolify/` instead of following the docker compose file locations `/root/coolify/data/coolify`. How do i change this?

```
    working_dir: /var/www/html
    volumes:
      - type: bind
        source: /root/coolify/.env
        target: /var/www/html/.env
        read_only: true
      - /root/coolify/data/coolify/ssh:/var/www/html/storage/app/ssh
      - /root/coolify/data/coolify/applications:/var/www/html/storage/app/applications
      - /root/coolify/data/coolify/databases:/var/www/html/storage/app/databases
      - /root/coolify/data/coolify/services:/var/www/html/storage/app/services
      - /root/coolify/data/coolify/backups:/var/www/html/storage/app/backups
      - /root/coolify/data/coolify/webhooks-during-maintenance:/var/www/html/storage/app/webhooks-during-maintenance

 ```
