### DISCUSSION TITLE
Volumes mount with absolute paths to location of the current application

### DISCUSSION THREAD

**Discussion by Nexulo** [coollabsio/coolify#3294] [Q&A]
I have a docker-compose.yaml and a docker-compose.prod.yaml file. 

Therefore the following user-defined start command:
`docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d`

docker-compose.prod.yaml:
```
services:
  example:
    image: debian:bullseye-slim
    environment:
      - SOME_PATH=${SOME_PATH}
    command: sh -c "echo ${SOME_PATH}; <some custom command> "
    volumes:
      - ${PWD}/app/www:${SOME_PATH}
      - /mnt/customfolder:/mnt/customfolder
    depends_on:
      - apache-httpd
    networks:
      - custom-stack
    restart: "no"
```

Unfortunately, mounting volumes like '${PWD}/app/www:${SOME_PATH}' are not mounted as i want. I thought ${PWD} should point to the location of the active application of coolify (e.g.: /data/coolify/applications/currentApplicationId).

Is there already a way to solve this? Unfortunately, with these definitions I end up with the following volume mount in the container:
`/artifacts/<currentApplicationId>/app/www -> /www `

${SOME_PATH} =  /www

--

And for information: This does not work and results in the same incorrectly mounted paths.
```
volumes:
      - ./app/www:${SOME_PATH}
```
