### DISCUSSION TITLE
Postiz

### DISCUSSION THREAD

**Discussion by andrasbacsai** [coollabsio/coolify#3341] [Service Template Requests]
https://github.com/gitroomhq/postiz-app?tab=readme-ov-file

**Comment by parthamjangir2020** [comment]
Postiz: The All-in-One Social Media Management Tool

https://postiz.com :  OpenSource 

Postiz offers everything you need to manage your social media posts, build an audience, capture leads, and grow your business.

**Comment by tnhoang** [comment]
Hey, guys! Probably it's already released on this version
https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.368

**Comment by mredodos** [comment]
can you add the version with multiple container? 

Controlling container services
When the environment variable POSTIZ_APPS is not set, or is set to an empty string, all services will be started in a single container. This is normally fine for small, personal deployments.

However, you can only start specific services within the docker container by changing this environement variable.

If you need to scale, you can experiement with having multiple containers defined like;

Frontend only: POSTIZ_APPS="frontend"
Backend only: POSTIZ_APPS="backend"
Worker and Cron only: POSTIZ_APPS="worker cron"

**Reply by mredodos** [reply]
@andrasbacsai

**Comment by BjoernRave** [comment]
the service is currently not working, at least not out of the box. When trying to register I get: `Your browser got a 404 when trying to contact the API, the most likely reasons for this are the NEXT_PUBLIC_BACKEND_URL is set incorrectly, or the backend is not running.` I am on an https route and NEXT_PUBLIC_BACKEND_URL seems to be setup correctly

**Reply by Alexmry** [reply]
Hi BjoernRave, did you find any solutions? Many thanks

**Reply by Cristy94** [reply]
Probably he didn't, I also tried setting it up a few weeks ago, with no success :(

**Reply by Xsmael** [reply]
same here. any one getting success ?

**Comment by BjoernRave** [comment]
I got it working via the docker-compose deployment with the following file: 
```yaml
services:
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: always
    environment:
      # You must change these. Replace `postiz.your-server.com` with your DNS name - this needs to be exactly the URL you're accessing Postiz on.
      MAIN_URL: "https://postiz.example.com"
      FRONTEND_URL: "https://postiz.example.com"
      NEXT_PUBLIC_BACKEND_URL: "https://postiz.example.com/api"
      JWT_SECRET: "123"
 
      # These defaults are probably fine, but if you change your user/password, update it in the
      # postiz-postgres or postiz-redis services below.
      DATABASE_URL: "postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db-local"
      REDIS_URL: "redis://postiz-redis:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: true # Required for self-hosting.
      DISABLE_REGISTRATION: false # Only allow single registration, then disable signup
      # The container images are pre-configured to use /uploads for file storage.
      # You probably should not change this unless you have a really good reason!
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    ports:
      - 5000:5000
    networks:
      - postiz-network
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.postiz-https.rule=Host(`postiz.example.com`) && PathPrefix(`/`)
      - traefik.http.routers.postiz-https.entryPoints=https
      - traefik.http.routers.postiz-https.middlewares=gzip
      - traefik.http.routers.postiz-https.service=postiz-service
      - traefik.http.routers.postiz-https.tls=true
      - traefik.http.services.postiz-service.loadbalancer.server.port=5000
      - traefik.http.routers.postiz-https.tls.certresolver=letsencrypt
      - traefik.http.routers.postiz-http.rule=Host(`postiz.example.com`) && PathPrefix(`/`)
      - traefik.http.routers.postiz-http.entryPoints=http
      - traefik.http.routers.postiz-http.middlewares=redirect-to-https
 
  postiz-postgres:
    image: postgres:17-alpine
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postiz-password
      POSTGRES_USER: postiz-user
      POSTGRES_DB: postiz-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postiz-network
    healthcheck:
      test: pg_isready -U postiz-user -d postiz-db-local
      interval: 10s
      timeout: 3s
      retries: 3
  postiz-redis:
    image: redis:7.2
    container_name: postiz-redis
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz-redis-data:/data
    networks:
      - postiz-network
 
 
volumes:
  postgres-volume:
    external: false
 
  postiz-redis-data:
    external: false
 
  postiz-config:
    external: false
 
  postiz-uploads:
    external: false
 
networks:
  postiz-network:
    external: false
```
