### DISCUSSION TITLE
open-webui

### DISCUSSION THREAD

**Discussion by saeedesmaili** [coollabsio/coolify#3344] [Service Template Requests]
User-friendly WebUI for chatting with various LLMs.
https://github.com/open-webui/open-webui

**Comment by matsyui** [comment]
is it possible to set this up manually with coolify?

**Comment by hashmil** [comment]
i can see openwebui has been added to coolify. However has anyone been able to get pipelines working with it? 

i managed to update the docker file with this:
```
  pipelines:
    image: 'ghcr.io/open-webui/pipelines:main'
    ports:
      - '9099:9099'
    volumes:
      - 'pipelines:/app/pipelines'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
```

then refreshed the coolify configuration page. which showed the pipeline service in the stack. assigned a domain `pipelines.mydomain.com` 

then did this:
-  In Open WebUI: Navigate to the Admin Panel > Settings > Connections > OpenAI API section.
-  Set the API URL to `pipelines.mydomain.com` and the API key to `0p3n-w3bu!`. pipelines should now be active and i can go to the Piplines section in the admin panel and import pipelines.

While i can see my imported pipelines i'm getting error 401. Anyone managed to figure this out?
