### DISCUSSION TITLE
Docker compose - array to string conversion error

### DISCUSSION THREAD

**Discussion by vojtech-cerveny** [coollabsio/coolify#3346] [Q&A]
I am getting same error as #1506 but on 

```log
[OUTPUT]
Switched to branch 'pr-2-coolify'

[2024-Sep-06 13:50:33.516913]

[COMMAND] docker exec r0c0kg0 bash -c 'cd /artifacts/r0c0kg0 && git log -1 9da017335237a50ddf3317e0ce19c1871cd2f93d --pretty=%B'
[OUTPUT]
chore: coolify env

[2024-Sep-06 13:50:35.086564] Oops something is not okay, are you okay? 😢

[2024-Sep-06 13:50:35.088835] Array to string conversion
```

```yml

version: "3.8"

services:
  haraka:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "25:25"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d email-haraka"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    command: npm run start-api

volumes:
  postgres_data:

```

I have this settings and this works properly for "main" application from `master` but it doesn't work on Preview applications. What I should change?
