### DISCUSSION TITLE
Mosquitto Mqtt

### DISCUSSION THREAD

**Discussion by jawwaonline** [coollabsio/coolify#3365] [Service Template Requests]
## 🧠 Feature Request: Mosquitto as MQTT Broker in Coolify

I'd love to see Mosquitto integrated as an MQTT Broker within Coolify! 

### Here's my experience so far:

I managed to set up Mosquitto via Docker Compose in Coolify, but I encountered a few issues:
- MQTTS (secure MQTT) doesn’t seem to work ☹️
- Since I couldn't find an option to set the subdomain directly within Coolify, and I'm using Cloudflare as DNS, I had to manually set up a subdomain in Cloudflare with an A record pointing to the IP of my Coolify server ( **without proxy enabled** )

### Here's my current Docker Compose setup:

```yaml
# Documentation: https://mosquitto.org/documentation/
# Slogan: Mosquitto is lightweight and suitable for use on all devices, from low-power single-board computers to full servers.
# Tags: mosquitto, mqtt, ws, open-source
# Logo: svgs/mosquitto.svg
# Port: 1883

version: '3.8'
services:
  mosquitto:
    image: 'eclipse-mosquitto:2.0'
    ports:
      - '1883:1883'
      # - '8883:8883'  # MQTTS (secure MQTT)
      # - '9001:9001'  # WebSocket (optional)
    environment:
      # - SERVICE_FQDN_MQTT
      - MQTT_USERNAME=${MQTT_USERNAME:-defaultuser}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-defaultpassword}
    volumes:
      - './mosquitto/config:/mosquitto/config'
      - './mosquitto/data:/mosquitto/data'
      - './mosquitto/log:/mosquitto/log'
    entrypoint: |
      sh -c "
        echo 'listener 1883' > /mosquitto/config/mosquitto.conf &&
        echo 'allow_anonymous false' >> /mosquitto/config/mosquitto.conf &&
        echo 'password_file /mosquitto/config/passwords' >> /mosquitto/config/mosquitto.conf &&
        echo 'listener 8883' >> /mosquitto/config/mosquitto.conf &&
        echo 'require_certificate false' >> /mosquitto/config/mosquitto.conf &&
        echo 'listener 9001' >> /mosquitto/config/mosquitto.conf &&
        echo 'protocol websockets' >> /mosquitto/config/mosquitto.conf &&
        touch /mosquitto/config/passwords &&
        mosquitto_passwd -b -c /mosquitto/config/passwords $MQTT_USERNAME $MQTT_PASSWORD &&
        chmod 0600 /mosquitto/config/passwords &&
        chown mosquitto:mosquitto /mosquitto/config/passwords &&
        exec mosquitto -c /mosquitto/config/mosquitto.conf
      "
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mqtt.entrypoints=mqtt
      # - 'traefik.tcp.routers.mqtts.rule=HostSNI(`${SERVICE_FQDN_MQTT}`)'
      - traefik.tcp.routers.mqtts.entrypoints=mqtts
      - traefik.tcp.routers.mqtts.tls=true
      - traefik.tcp.routers.mqtts.tls.certresolver=myresolver
    restart: always

```

### Current issues:
- MQTTS (port 8883): Not working as expected.
- DNS/Subdomain configuration: Manual setup was required in Cloudflare due to the lack of options in Coolify.

**Comment by nishantssoni** [comment]
**Try this it worked for me use docker compose deployment **
```yaml

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-anyrandom
    restart: unless-stopped
    environment:
      MQTT_USERNAME: '${SERVICE_USER_MOSQUITTO}'
      MQTT_PASSWORD: '${SERVICE_PASSWORD_MOSQUITTO}'
      REQUIRE_CERTIFICATE: '${REQUIRE_CERTIFICATE:-false}'
      ALLOW_ANONYMOUS: '${ALLOW_ANONYMOUS:-true}'
      SERVICE_USER_MOSQUITTO: '${SERVICE_USER_MOSQUITTO}'
      SERVICE_PASSWORD_MOSQUITTO: '${SERVICE_PASSWORD_MOSQUITTO}'
      COOLIFY_RESOURCE_UUID: anyrandom
      COOLIFY_CONTAINER_NAME: mosquitto-anyrandom
      COOLIFY_URL: 'https://mosquitto-anyrandom.demo-domain.com'
      COOLIFY_FQDN: mosquitto-anyrandom.demo-domain.com
    volumes:
      - 'anyrandom_mosquitto-config:/mosquitto/config'
      - 'anyrandom_mosquitto-certs:/certs'
    expose:
      - "9001"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint: >
      sh -c "
        echo 'listener 9001' > /mosquitto/config/mosquitto.conf;
        echo 'protocol websockets' >> /mosquitto/config/mosquitto.conf;
        echo 'require_certificate '$REQUIRE_CERTIFICATE >> /mosquitto/config/mosquitto.conf;
        echo 'allow_anonymous '$ALLOW_ANONYMOUS >> /mosquitto/config/mosquitto.conf;
        if [ -n \"$SERVICE_USER_MOSQUITTO\" ] && [ -n \"$SERVICE_PASSWORD_MOSQUITTO\" ]; then
          echo 'password_file /mosquitto/config/passwords' >> /mosquitto/config/mosquitto.conf;
          touch /mosquitto/config/passwords;
          chmod 0700 /mosquitto/config/passwords;
          chown root:root /mosquitto/config/passwords;
          mosquitto_passwd -b -c /mosquitto/config/passwords \"$SERVICE_USER_MOSQUITTO\" \"$SERVICE_PASSWORD_MOSQUITTO\";
          chown mosquitto:mosquitto /mosquitto/config/passwords;
        fi;
        exec mosquitto -c /mosquitto/config/mosquitto.conf
      "
    labels:
      - traefik.enable=true
      - "traefik.http.routers.mqtt-ws.rule=Host(`mosquitto-anyrandom.demo-domain.com`)"
      - "traefik.http.routers.mqtt-ws.entrypoints=websecure"
      - "traefik.http.routers.mqtt-ws.tls.certresolver=letsencrypt"
      - "traefik.http.services.mqtt-ws.loadbalancer.server.port=9001"
      # Coolify/Caddy labels below; can be retained if needed
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.serviceId=6
      - coolify.type=service
      - coolify.name=mosquitto-anyrandom
      - coolify.resourceName=mosquitto-anyrandom
      - coolify.projectName=demo-project
      - coolify.serviceName=mosquitto
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - coolify.service.subId=6
      - coolify.service.subType=application
      - coolify.service.subName=mosquitto
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 1883}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://mosquitto-anyrandom.demo-domain.com'
      - caddy_ingress_network=coolify

    networks:
      - coolify

volumes:
  anyrandom_mosquitto-config:
    name: anyrandom_mosquitto-config
  anyrandom_mosquitto-certs:
    name: anyrandom_mosquitto-certs

networks:
  coolify:
    external: true

````
