### DISCUSSION TITLE
Meshcentral

### DISCUSSION THREAD

**Discussion by diogo24m** [coollabsio/coolify#3371] [Service Template Requests]
https://github.com/Ylianst/MeshCentral

**Comment by riemers** [comment]
I created a docker compose, it is working.. but sometimes it looses connection i have no clue why yet though.

```
version: '3'
services:
  mongodb:
    restart: always
    container_name: mongodb
    image: 'mongo:latest'
    volumes:
      - './meshcentral/mongodb_data:/data/db'
    healthcheck:
      test:
        - CMD
        - sh
        - '-c'
        - "timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/27017'"
      interval: 30s
      timeout: 10s
      retries: 3
  meshcentral:
    restart: always
    container_name: meshcentral
    image: 'ghcr.io/ylianst/meshcentral:latest'
    depends_on:
      - mongodb
    ports:
      - '8086:443'
    volumes:
      - './meshcentral/data:/opt/meshcentral/meshcentral-data'
      - './meshcentral/user_files:/opt/meshcentral/meshcentral-files'
      - './meshcentral/backup:/opt/meshcentral/meshcentral-backups'
      - './meshcentral/web:/opt/meshcentral/meshcentral-web'
    healthcheck:
      test:
        - CMD
        - nc
        - '-z'
        - localhost
        - '80'
      interval: 30s
      timeout: 10s
      retries: 3
```

suppose networks is not required too, but perhaps it helps the next person to polish it up more.

see https://github.com/coollabsio/coolify/issues/3432 discussions here for first trials
