### DISCUSSION TITLE
nixpacks NPM_TOKEN for private npm package

### DISCUSSION THREAD

**Discussion by benjaminpreiss** [coollabsio/coolify#3476] [Q&A]
Hey y'all,

It seems that I can't install private npm packages on nixpack, even though I have set NPM_TOKEN as an env variable.
Does anyone here have a workaround for that?

Glad for help!

**Comment by alexanderfink** [comment]
Have you found a solution for this? I have the issue that when I request private repositories they always timeout?

EDIT: See my solution below.

**Reply by benjaminpreiss** [reply]
Hey, yes.

I ended up doing it with docker-compose.
The below approach is also a little bit more complex, because I use infisical to load the env variables.

Here is my Dockerfile:
```Dockerfile
FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Install curl and add Infisical CLI
RUN apt-get update && apt-get install -y curl
RUN curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | bash
RUN apt-get update && apt-get install -y infisical

COPY . /app
WORKDIR /app

# Define ARGs that will be used across stages
ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV:-production}

RUN --mount=type=secret,id=infisical_client_id \
    --mount=type=secret,id=infisical_client_secret \
    --mount=type=secret,id=infisical_project_id \
    --mount=type=cache,id=pnpm,target=/pnpm/store \
    infisical run \
        --token=$(infisical login --method=universal-auth \
            --client-id="$(cat /run/secrets/infisical_client_id)" \
            --client-secret="$(cat /run/secrets/infisical_client_secret)" \
            --silent --plain) \
        --projectId="$(cat /run/secrets/infisical_project_id)" \
        --env="prod" \
        -- bash -c 'pnpm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}" && \
            pnpm install --prod=false --frozen-lockfile --ignore-scripts && \
            pnpm config delete "//registry.npmjs.org/:_authToken"'

FROM base AS build
# Read ARGs and set as ENV
ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV:-production}

RUN --mount=type=secret,id=infisical_client_id \
    --mount=type=secret,id=infisical_client_secret \
    --mount=type=secret,id=infisical_project_id \
    export INFISICAL_TOKEN=$(infisical login --method=universal-auth \
        --client-id="$(cat /run/secrets/infisical_client_id)" \
        --client-secret="$(cat /run/secrets/infisical_client_secret)" \
        --silent --plain) && \
    export INFISICAL_PROJECT_ID="$(cat /run/secrets/infisical_project_id)" && \
    pnpm --filter frontend... build

FROM base
# Read ARGs and set as ENV in final stage too
ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV:-production}
ENV INFISICAL_CLIENT_ID=""
ENV INFISICAL_CLIENT_SECRET=""
ENV INFISICAL_PROJECT_ID=""

COPY --from=build /app /app
EXPOSE 3000
CMD export INFISICAL_TOKEN=$(infisical login \
    --method=universal-auth \
    --client-id="${INFISICAL_CLIENT_ID}" \
    --client-secret="${INFISICAL_CLIENT_SECRET}" \
    --silent --plain) && \
    pnpm start
```

Then the docker-compose:

```yml
version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - NODE_ENV=${NODE_ENV:-production}
            secrets:
                - infisical_client_id
                - infisical_client_secret
                - infisical_project_id
        environment:
            - INFISICAL_CLIENT_ID=${INFISICAL_CLIENT_ID}
            - INFISICAL_CLIENT_SECRET=${INFISICAL_CLIENT_SECRET}
            - INFISICAL_PROJECT_ID=${INFISICAL_PROJECT_ID}
        ports:
            - "3000:3000"

secrets:
    infisical_client_id:
        environment: INFISICAL_CLIENT_ID
    infisical_client_secret:
        environment: INFISICAL_CLIENT_SECRET
    infisical_project_id:
        environment: INFISICAL_PROJECT_ID
```
