### DISCUSSION TITLE
template for drupal 7 to 10 with mysql

### DISCUSSION THREAD

**Discussion by agelospanagiotakis** [coollabsio/coolify#3538] [Feature Requests]
drupal 7 to 10 with mysql 
example from wodby 
```
version: "3.4"

services:
  db:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_db"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db:/var/lib/mysql # Docker volume sync

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: db
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_ROOT_PASSWORD: admin123
      DB_NAME: drupal
      DB_DRIVER: mysql
      COLUMNS: 80 # Set 80 columns for docker exec -it.
      DOCROOT_SUBDIR: docroot/web
      WODBY_APP_SUBSITE: default
      HTTP_ROOT: /var/www/html/docroot/web
      APP_ROOT: /var/www/html
      CONF_DIR: /var/www/conf
      DRUPAL_VERSION: "7"
      DRUSH_OPTIONS_URI: ${PROJECT_BASE_URL}
      DRUPAL_SITE: "default"
      DRUPAL_SITE_DIR: "/var/www/html/docroot/web/sites/default"
      DRUPAL_HASH_SALT: "bad-hash-salt-must-be-32-characters_long"
      DRUPAL_FILES_SYNC_SALT: "files-sync-bad-salt"
      PHP_FPM_USER: "wodby"
      PHP_FPM_GROUP: "wodby"
      WODBY_HOSTS: '["${PROJECT_BASE_URL}"]'
      WODBY_PRIMARY_HOST: "$PROJECT_BASE_URL"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "redis"
    networks:
      - default
      - traefik
    volumes:
      - codebase-sync:/var/www/html/docroot # Docker-sync
      - files:/mnt/files/ # Docker volume sync

  nginx:
    container_name: "${PROJECT_NAME}_nginx"
    image: wodby/nginx:$NGINX_TAG
    networks:
      - default
      - traefik
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: 'off'
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/docroot/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
      NGINX_DRUPAL_FILE_PROXY_URL: https://$PROJECT_STAGE_URL
    volumes:
      - codebase-sync:/var/www/html/docroot # Docker-sync
      - files:/mnt/files/ # Docker volume sync
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${PROJECT_NAME}_nginx.entrypoints=https'
      - 'traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)'
      ## if varnish is enabled disable above label and enable the following
      # - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`nginx-${PROJECT_BASE_URL}`)"
      - 'traefik.http.routers.${PROJECT_NAME}_nginx.tls=true'
      - 'traefik.http.services.${PROJECT_NAME}_nginx.loadbalancer.server.port=80'
      - 'traefik.http.routers.${PROJECT_NAME}_nginx.service=${PROJECT_NAME}_nginx@docker'
      - 'traefik.docker.network=traefik_proxy'


  # varnish:
  #   image: wodby/varnish:$VARNISH_TAG
  #   networks:
  #     - default
  #     - traefik
  #   container_name: "${PROJECT_NAME}_varnish"
  #   depends_on:
  #     - nginx
  #   environment:
  #     VARNISH_SECRET: secret
  #     VARNISH_BACKEND_HOST: nginx
  #     VARNISH_BACKEND_PORT: 80
  #     VARNISH_CONFIG_PRESET: drupal
  #     VARNISH_PURGE_EXTERNAL_REQUEST_HEADER: X-Real-IP
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.${PROJECT_NAME}_varnish.entrypoints=https"
  #     - "traefik.http.routers.${PROJECT_NAME}_varnish.rule=Host(`${PROJECT_BASE_URL}`)"
  #     - "traefik.http.routers.${PROJECT_NAME}_varnish.tls=true"
  #     - "traefik.http.services.${PROJECT_NAME}_varnish.loadbalancer.server.port=6081"
  #     - "traefik.http.routers.${PROJECT_NAME}_varnish.service=${PROJECT_NAME}_varnish@docker"
  #     - "traefik.docker.network=traefik_proxy"

  mailhog:
    image: mailhog/mailhog
    networks:
      - default
      - traefik
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`${PROJECT_BASE_URL}`) && PathPrefix(`/mailhog`)"
      - "traefik.http.middlewares.${PROJECT_NAME}_mailhog.stripprefix.prefixes=/mailhog"
      #### use these middlewares (rules like our-auth,our-retry,our-ratelimit are defined within traefik's labels)
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.middlewares=our-slash@docker"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.tls=true"
      - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.service=${PROJECT_NAME}_mailhog@docker"
      - "traefik.docker.network=traefik_proxy"

  redis:
    container_name: "${PROJECT_NAME}_redis"
    image: wodby/redis:$REDIS_TAG
    environment:
      REDIS_PASSWORD: redis

  pma:
    image: phpmyadmin/phpmyadmin
    networks:
      - default
      - traefik
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: admin123
      PHP_UPLOAD_MAX_FILESIZE: 100G
      PHP_MAX_INPUT_VARS: 100G
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_pma.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`${PROJECT_BASE_URL}`) && PathPrefix(`/pma`)"
      - "traefik.http.middlewares.${PROJECT_NAME}_pma.stripprefix.prefixes=/pma"
      #### use these middlewares (rules like our-auth,our-retry,our-ratelimit are defined within traefik's labels)
      - "traefik.http.routers.${PROJECT_NAME}_pma.middlewares=our-slash@docker"
      - "traefik.http.routers.${PROJECT_NAME}_pma.tls=true"
      - "traefik.http.services.${PROJECT_NAME}_pma.loadbalancer.server.port=80"
      - "traefik.http.routers.${PROJECT_NAME}_pma.service=${PROJECT_NAME}_pma@docker"
      - "traefik.docker.network=traefik_proxy"

  # elasticsearch:
  #   image: wodby/elasticsearch:$ELASTICSEARCH_TAG
  #   container_name: "${PROJECT_NAME}_elastic"
  #   networks:
  #     - default
  #     - traefik
  #   environment:
  #     ES_JAVA_OPTS: "-Xms500m -Xmx500m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - 9200:9200

  # kibana:
  #   image: wodby/kibana:$KIBANA_TAG
  #   container_name: "${PROJECT_NAME}_kibana"
  #   volumes:
  #     - ./kibana-config/kibana.yml:/usr/share/kibana/config/kibana.yml
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     SERVER_NAME: '${PROJECT_BASE_URL}/kibana'
  #     KIBANA_DEFAULTAPPID: 'home'
  #     KIBANA_SERVER_NAME: kibana
  #     KIBANA_SERVER_HOST: 0
  #     # KIBANA_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  #     ELASTICSEARCH_URL: 'http://elasticsearch:9200'
  #     XPACK_MONITORING_ENABLED: 'false'
  #     STATUS_ALLOW_ANONYMOUS: 'true'
  #     XPACK_REPORTING_ENABLED: 'false'
  #     XPACK_SECURITY_ENABLED: 'false'
  #     ELASTICSEARCH_USERNAME: 'elastic'
  #     ELASTICSEARCH_PASSWORD: 'changeme'
  #     XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "false"
  #     #XPACK_GRAPH_ENABLED: 'false'
  #   ports:
  #     - 5601:5601
  #   networks:
      # - default
  #     - traefik
  #   labels:
  #     - "traefik.http.routers.${PROJECT_NAME}_kibana.entrypoints=https"
  #     - "traefik.http.routers.${PROJECT_NAME}_kibana.rule=Host(`${PROJECT_BASE_URL}`) && PathPrefix(`/app/kibana`)"
  #     - "traefik.http.middlewares.${PROJECT_NAME}_kibana.stripprefix.prefixes=/app/kibana"
  #     #### use these middlewares (rules like our-auth,our-retry,our-ratelimit are defined within traefik's labels)
  #     - "traefik.http.routers.${PROJECT_NAME}_kibana.middlewares=our-slash@docker"
  #     - "traefik.http.routers.${PROJECT_NAME}_kibana.tls=true"
  #     - "traefik.http.services.${PROJECT_NAME}_kibana.loadbalancer.server.port=5601"
  #     - "traefik.http.routers.${PROJECT_NAME}_kibana.service=${PROJECT_NAME}_kibana@docker"
  #     - "traefik.docker.network=traefik_proxy"

  rsyslog:
    container_name: "${PROJECT_NAME}_rsyslog"
    image: wodby/rsyslog:$RSYSLOG_TAG

  # node:
  #   image: wodby/node:$NODE_TAG
  #   container_name: "${PROJECT_NAME}_node"
  #   working_dir: /var/www/html/docroot
  #   expose:
  #     - "3000"
  #   volumes:
  #     - codebase-sync:/var/www/html/docroot # Docker-sync
  #   command: sh -c 'tail -f /dev/null'
  # portainer:
  #   image: portainer/portainer
  #   container_name: "${PROJECT_NAME}_portainer"
  #   command: --no-auth -H unix:///var/run/docker.sock
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   labels:
  #     - 'traefik.backend=${PROJECT_NAME}_portainer'
  #     - 'traefik.port=9000'
  #     - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL}'
  #   networks:
  #     - default
  #     - traefik

  # traefik:
  #   image: traefik
  #   container_name: "${PROJECT_NAME}_traefik"
  #   command: -c /dev/null --web --docker --logLevel=INFO
  #   ports:
  #     - '8000:80'
  #     - '8080:8080' # Dashboard
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - default
  #     - traefik


volumes:
## Docker-sync
  codebase-sync:
    external: true
    name: ${PROJECT_NAME}-codebase
  files:
    external: true
    name: ${PROJECT_NAME}-files
  db:
    name: ${PROJECT_NAME}-db

networks:
  traefik:
    external:
      name: traefik_proxy

```
example .env file 
```
### Documentation available at https://wodby.com/docs/stacks/drupal/local
### Changelog can be found at https://github.com/wodby/docker4drupal/releases
### Images tags format explained at https://github.com/wodby/docker4drupal#images-tags

### PROJECT SETTINGS

PROJECT_NAME=lala
PROJECT_BASE_URL=lala.docker.localhost
PROJECT_STAGE_URL=www.lala.com
# PROJECT_STAGE_URL=""
PROJECT_PRODUCTION_URL=""
PROJECT_VERSION=5.4.35

### --- DB ----
MARIADB_TAG=10.5-3.13.2

### --- PHP ----

# Linux (uid 1000 gid 1000)

PHP_TAG=7.4-4.27.1
# PHP_TAG=8.1-4.51.2

### --- NGINX ----

# NGINX_TAG=1.20-5.14.1
NGINX_TAG=1.20-5.17.3
# NGINX_TAG=1.19-5.14.1
# NGINX_TAG=1.18-5.14.1

NGINX_VHOST_PRESET=drupal7

### --- ELASTICSEARCH ---

# ELASTICSEARCH_TAG=5-4.1.2
ELASTICSEARCH_TAG=5.6-2.2.0
# ELASTICSEARCH_TAG=7-5.8.1
# ELASTICSEARCH_TAG=7.10
#ELASTICSEARCH_TAG=6-5.8.1
KIBANA_TAG=5-4.1.2

### --- REDIS ---

#REDIS_TAG=4-3.2.4
REDIS_TAG=5-3.9.1

### --- NODE ---

NODE_TAG=12-0.17.0

### --- VARNISH ---

#VARNISH_TAG=6.0-4.7.2
VARNISH_TAG=4.1-4.7.2

### OTHERS

RSYSLOG_TAG=latest
```
