### DISCUSSION TITLE
Add Prestashop

### DISCUSSION THREAD

**Discussion by mredodos** [coollabsio/coolify#3558] [Service Template Requests]
please add prestashop https://github.com/PrestaShop/PrestaShop

here a docker compose example updated and an example for add phpmyadmin https://devdocs.prestashop-project.org/8/basics/installation/environments/docker/

here we have other official compose but i think the version in documentations is partially better and updated 

https://github.com/PrestaShop/PrestaShop/blob/develop/docker-compose.yml

here an example with mariadb https://github.com/PrestaShop/PrestaShop/blob/develop/docker-compose.mariadb.yml

i have try to make a compose updated with mariadb(I have not yet tested the file)

```version: '3.8'

volumes:
  db-data:
    name: prestashop_db_data
  prestashop-data:
    name: prestashop_data
  prestashop-themes:
    name: prestashop_themes
  prestashop-modules:
    name: prestashop_modules

services:
  mariadb:
    image: mariadb:11.4
    container_name: prestashop-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - prestashop-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DB_SERVER: mariadb
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWORD}
      PS_DOMAIN: ${PS_DOMAIN}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      PS_LANGUAGE: ${PS_LANGUAGE:-it}
      PS_COUNTRY: ${PS_COUNTRY:-IT}
      PS_INSTALL_AUTO: 0
      PS_ERASE_DB: 0
      PS_DEV_MODE: 0
      PS_ENABLE_SSL: 1
      ADMIN_MAIL: ${ADMIN_MAIL}
      ADMIN_PASSWD: ${ADMIN_PASSWD}
    volumes:
      - prestashop-data:/var/www/html
      - prestashop-themes:/var/www/html/themes
      - prestashop-modules:/var/www/html/modules
    networks:
      - prestashop-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prestashop.rule=Host(`${PS_DOMAIN}`)"
      - "traefik.http.routers.prestashop.entrypoints=websecure"
      - "traefik.http.routers.prestashop.tls=true"
      - "traefik.http.services.prestashop.loadbalancer.server.port=80"

networks:
  prestashop-network:
    name: prestashop_network

**Comment by aindot** [comment]
Prestashop is actually a weird script, I managed to deploy it to coolify with the following composer:

```yaml
services:
  prestashop:
    image: 'prestashop/prestashop:latest'
    volumes:
      - 'prestashop-data:/var/www/html'
    environment:
      - DB_SERVER=mariadb
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - DB_USER=$SERVICE_USER_PRESTASHOP
      - DB_PASSWD=$SERVICE_PASSWORD_PRESTASHOP
      - DB_NAME=prestashop
      - DB_PREFIX=ps_
      - PS_INSTALL_AUTO=1
      - PS_LANGUAGE=en
      - PS_COUNTRY=kw
      - PS_ENABLE_SSL=0
      - SERVICE_URL_PRESTASHOP
      - 'ADMIN_EMAIL=${ADMIN_EMAIL:-admin@locahost}'
      - ADMIN_PASSWORD=$SERVICE_PASSWORD_ADMIN
    depends_on:
      - mariadb
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10
  mariadb:
    image: 'mariadb:11'
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=$SERVICE_USER_PRESTASHOP
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_PRESTASHOP
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 5s
      timeout: 20s
      retries: 10
```

But for some reason it insist to resolve the domain locally and redirect to 127.0.0.1.

**Comment by aindot** [comment]
This is a working version:
```yaml
# documentation: https://devdocs.prestashop-project.org/9/basics/installation/environments/docker/
# slogan: PrestaShop is a free and Open Source e-commerce web platform
# category: ecommerce
# port: 80

services:
  prestashop:
    image: prestashop/prestashop:latest
    volumes:
      - prestashop-data:/var/www/html
    environment:
      - SERVICE_URL_PRESTASHOP
#      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - DB_SERVER=mariadb
      - DB_USER=$SERVICE_USER_PRESTASHOP
      - DB_PASSWD=$SERVICE_PASSWORD_PRESTASHOP
      - DB_NAME=prestashop
      - DB_PREFIX=ps_
      - PS_INSTALL_AUTO=1
      - PS_LANGUAGE=${PS_LANGUAGE:-en}
      - PS_COUNTRY=${PS_COUNTRY:-kw}
      - PS_ENABLE_SSL=1
      - PS_TRUSTED_PROXIES=REMOTE_ADDR
      - PS_DOMAIN=$SERVICE_FQDN_PRESTASHOP
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=$SERVICE_PASSWORD_ADMIN
#      - PS_FOLDER_ADMIN=$SERVICE_USER_ADMINFOLDER
#      - PS_FOLDER_INSTALL=$SERVICE_PASSWORD_INSTALLFOLDER
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 2s
      timeout: 10s
      retries: 10
  mariadb:
    image: mariadb:11
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=$SERVICE_USER_PRESTASHOP
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_PRESTASHOP
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 20s
      retries: 10
```

The issue with this deployment script:
1- you can not access the admin panel, since PS_ENABLE_SSL=1, (if set to false, you won't be able to access the front office).
2- the admin folder can not be renamed, otherwise the auto install will fail.
3- To access the admin panel you must login to the terminal to identify the correct admin folder name.

For me the deployment is succeed if I could manage to forward the headers.
