### DISCUSSION TITLE
Surrealdb V2 as Database

### DISCUSSION THREAD

**Discussion by Nebula-Spark** [coollabsio/coolify#3587] [Database Requests]
Right now, we can deploy it as a service using a Docker file, but we are unable to connect to the database.

It would be really great if we had an official SurrealDB template in the database!

**Comment by basicalex** [comment]
I've not been able to deploy using Coolify at all, the surrealdb added in the templates would be a life-saver.. At the moment we deployed directly on the server with a direct docker file command:

docker run --rm --pull always -p 8000:8000 --user 0  -v /mnt/surrealdb-data:/mydata surrealdb/surrealdb:latest start --user root --pass root rocksdb:/mydata/mydatabase.db

I had to set up the persistent volume on my server in advance with correct formatting, the surrealdb can now actually save data on the rocksdb and interpret it.

**Comment by ctwhome** [comment]
i got it working with this configuration for docker-compose

```
services:
  surrealdb:
    image: 'surrealdb/surrealdb:v2'
    command: start
    user: root
    environment:
      - SERVICE_FQDN_SURREALDB_8000
      - 'SURREAL_PATH=${SURREAL_PATH:-rocksdb://data/database.db}'
      - 'SURREAL_USER=${SERVICE_USER_ROOT}'
      - 'SURREAL_PASS=${SERVICE_PASSWORD_ROOT}'
      - 'SURREAL_EXPERIMENTAL_GRAPHQL=${ENABLE_GRAPHQL:-true}'
      - 'SURREAL_LOG=${SURREAL_LOG:-info}'
      - 'SURREAL_STRICT=${SURREAL_STRICT:-false}'
      - 'SURREAL_CLIENT_IP=${SURREAL_CLIENT_IP:-X-Forwarded-For}'
      - 'SURREAL_CAPS_ALLOW_GUESTS=${SURREAL_CAPS_ALLOW_GUESTS:-false}'
      - 'SURREAL_CAPS_ALLOW_SCRIPT=${SURREAL_CAPS_ALLOW_SCRIPT:-true}'
      - 'SURREAL_CAPS_ALLOW_NET=${SURREAL_CAPS_ALLOW_NET:-false}'
      - 'SURREAL_CAPS_DENY_FUNC=${SURREAL_CAPS_DENY_FUNC:-false}'
    volumes:
      -
        type: volume
        source: surrealdb
        target: /data
    healthcheck:
      test:
        - CMD
        - /surreal
        - isready
      interval: 2s
      timeout: 10s
      retries: 10
```
