### DISCUSSION TITLE
Multiple wildcard domains

### DISCUSSION THREAD

**Discussion by myugan** [coollabsio/coolify#3626] [Feature Requests]
The idea is to have a setting that allows the use of multiple wildcard domains. For example, when deploying Coolify, I want some services to be generated as **xxx.domain.com** for public testing, while other services are generated as **yyy.domain.org** for internal testing.

**Comment by joezimjs** [comment]
Yes please!

**Comment by mredodos** [comment]
+1

**Comment by Shadowfita** [comment]
+1 !

**Reply by Shadowfita** [reply]
This is achievable already when manually entering a domain that is wildcarded appropriately, but having proper UI / setting management for multiple domains would be great.

**Reply by hnykda** [reply]
Hey @Shadowfita  ! Can you say more about how did you achieve that? I can't figure out what you meant

**Reply by FiliePepijn** [reply]
Did you manage to do this, if yes how?

**Comment by 2F-112** [comment]
+1

**Comment by XEJK** [comment]
This would be an awesome addition to have

**Comment by hnykda** [comment]
I am somewhat surprised this is not possible. I tried various hacks with dynamic configuration, but didn't succeeded, sadly.

**Reply by myugan** [reply]
In Traefik, it’s possible to define the domain for each container by adding a label, and adding a wildcard with a different domain should also be doable

**Reply by hnykda** [reply]
Maybe it's doable, but I didn't succeeded. I also have a static website where I couldn't override dockercompose.

**Reply by djsisson** [reply]
show what you tried, and give an example of what you want to happen

**Reply by hnykda** [reply]
Tried putting it here, can't, got validation error:
<img width="5598" height="1284" alt="image" src="https://github.com/user-attachments/assets/bfebacfb-6c92-4ea0-ae6f-9a51fa558bc0" />

Tried putting it in the deployment domains, there I get SSL errors as the cert is not generated via letsencrypt:
<img width="3356" height="2286" alt="image" src="https://github.com/user-attachments/assets/f3a0417a-5fe3-40a6-8b1d-44848a420b7c" />

I also just tried some other domain the the server main domain, didn't work, got SSL error again (i.e. the wildcard domain being https://somedomain.cz and then putting https://otherdomain.cz in the deployment endpoint)

Tried dynamic conf:
```
http:
  routers:
    # ACME challenge routers with very high priority
    acme-mydomain:
      rule: Host(`mydomain.cz`) && PathPrefix(`/.well-known/acme-challenge/`)
      service: noop@internal
      entryPoints:
        - http
      priority: 10000

    # General HTTP routers for domains
    mydomain-http:
      rule: Host(`mydomain.cz`)
      service: noop@internal
      entryPoints:
        - http
      priority: 100
    

    # Certificate generation routers
    cert-mydomain-https:
      rule: Host(`mydomain.cz`)
      service: noop@internal
      entryPoints:
        - https
      tls:
        certResolver: letsencrypt
```

got just 

```
2025-09-09T11:43:07.411534780Z time="2025-09-09T11:43:07Z" level=error msg="Unable to obtain ACME certificate for domains \"mydomain.cz\": unable to generate a certificate for the domains [mydomain.cz]: error: one or more domains had a problem:\n[mydomain.cz] invalid authorization: acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 2a02:2b88:1:4::16: Invalid response from http://mydomain.cz/.well-known/acme-challenge/6buNNwA9XNwsNmTLIAbpolMvzM7c29psuViAXkqvbjk: 404\n" ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=cert-kokdvur-https@file rule="Host(`mydomain.cz`)" providerName=letsencrypt.acme

```


What I expect to happen is that putting a whatever domain that target my server will get HTTPS working.
