### DISCUSSION TITLE
Add InvoiceShelf (formerly Crater) as a service

### DISCUSSION THREAD

**Discussion by rihards-simanovics** [coollabsio/coolify#3634] [Service Template Requests]
Docker version of the app available here: https://github.com/InvoiceShelf/docker

**Comment by rihards-simanovics** [comment]
confirmed working SQLite version of the application

`docker-compose.yml`
```yml
services:
  invoiceshelf:
    image: 'invoiceshelf/invoiceshelf:latest'
    container_name: invoiceshelf
    volumes:
      - './invoiceshelf_sqlite/data:/data'
      - './invoiceshelf_sqlite/conf:/conf'
    networks:
      - invoiceshelf
    environment:
      - SERVICE_FQDN_FRONTEND
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - 'APP_URL=http://localhost:80'
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/InvoiceShelf/database/database.sqlite
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=localhost
      - 'SANCTUM_STATEFUL_DOMAINS=localhost:90'
      - STARTUP_DELAY=
      - 'MAIL_DRIVER=${MAIL_DRIVER:-smtp}'
      - MAIL_HOST=$MAIL_HOST
      - 'MAIL_PORT=${MAIL_PORT:-587}'
      - MAIL_USERNAME=$MAIL_USERNAME
      - MAIL_PASSWORD=$MAIL_PASSWORD
      - 'MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-tls}'
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 2s
      timeout: 10s
      retries: 15
networks:
  invoiceshelf: null
  ```

**Comment by rihards-simanovics** [comment]
here is another MySQL version

- Database HostName: `mariadb`
- Database Name: `invoiceshelf`
- Database Username: `check generated env`
- Database Password: `check generated env`

`docker-compose.yml`
```yml
services:
  invoiceshelf:
    image: 'invoiceshelf/invoiceshelf:latest'
    volumes:
      - 'invoiceshelf-files:/data'
    environment:
      - SERVICE_FQDN_INVOICESHELF
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=$SERVICE_FQDN_INVOICESHELF
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=invoiceshelf
      - DB_USERNAME=$SERVICE_USER_INVOICESHELF
      - DB_PASSWORD=$SERVICE_PASSWORD_INVOICESHELF
      - DB_PASSWORD_FILE=
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=localhost
      - 'SANCTUM_STATEFUL_DOMAINS=localhost:90'
      - STARTUP_DELAY=
    depends_on:
      - mariadb
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10
  mariadb:
    image: 'mariadb:11.5'
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=invoiceshelf
      - MYSQL_USER=$SERVICE_USER_INVOICESHELF
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_INVOICESHELF
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 5s
      timeout: 20s
      retries: 10

```

**Comment by rihards-simanovics** [comment]
here is another MySQL version

- Database Host: `postgres`
- Database Port: `5432`
- Database Name: `invoiceshelf`
- Database Username: `invoiceshelf`
- Database Password: `invoiceshelf`

`docker-compose.yml`
```yml
services:
  postgres:
    image: postgres:15
    volumes:
      - postgres-files:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=invoiceshelf
      - POSTGRES_USER=invoiceshelf
      - POSTGRES_DB=invoiceshelf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 10
  invoiceshelf:
    image: 'invoiceshelf/invoiceshelf:latest'
    volumes:
      - 'invoiceshelf-files:/data'
    environment:
      - SERVICE_FQDN_FRONTEND
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:90
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=invoiceshelf
      - DB_USERNAME=invoiceshelf
      - DB_PASSWORD=invoiceshelf
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:90
      - STARTUP_DELAY=
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
    depends_on:
      - postgres
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10
```

**Comment by peaklabs-dev** [comment]
@rihards-simanovics Please create a PR for this service make sure to use the Coolify magic https://coolify.io/docs/knowledge-base/docker/compose#coolifys-magic-environment-variables

**Reply by rihards-simanovics** [reply]
Will do thanks for pointing out the docs for env vars, haven't seen it before.

**Reply by rihards-simanovics** [reply]
Hi @peaklabs-dev, had some time today to look at the env vars, and already made some changes to the MySQL one.

Also just to clarify, and not sure if this would be a problem, but Invoice Shelf has been designed to be hosted like a traditional LEMP/LAMP Web App, which does means it still wants the user to fill the information about DB and mailing through the Setup Wizard.

We do need to change the project initialisation to ensure that env vars are used during the setup and make sure some setup steps are bypassed, however for the time being the user will unfortunately, still need to enter the details twice.

**Reply by peaklabs-dev** [reply]
A setup wizard is perfectly fine and should work, Nextcloud does that as well for example. If the user has to enter the details manually, that is also normal and there is not much we can do about it as some services are built that way.

**Reply by mrakus-sofomo** [reply]
How its going? If you do not have time then I can take it :D

**Reply by rihards-simanovics** [reply]
> How its going? If you do not have time then I can take it :D

Hey @mrakus-sofomo, yeah if you have time you can absolutely have a look into it. I've done the MySQL version already, you only need to copy the env to the PostgreSQL and SQLite. here is the MySQL config: https://github.com/coollabsio/coolify/discussions/3634#discussioncomment-10929432

One thing to note is that we've found an issue in the container where if it gets restarted almost all .env values get reset and not populated - see https://github.com/InvoiceShelf/InvoiceShelf/issues/218 known issues under CSRF issue. I will be working on a fix some time between now and early January, just have some uni assessments to take care of first.

**Comment by MichaelHaushofer** [comment]
Here's a configuration that works with Coolify in 2025:

```
services:
  invoiceshelf:
    image: 'invoiceshelf/invoiceshelf:2.1.1-legacy'
    volumes:
      - 'invoiceshelf-files:/data'
    environment:
      - SERVICE_FQDN_INVOICESHELF
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - APP_NAME=InvoiceShelf
      - APP_ENV=production
      - APP_DEBUG=false
      - 'APP_URL=${SERVICE_FQDN_INVOICESHELF}'
      - 'APP_KEY=base64:${SERVICE_REALBASE64_INVOICESHELF}'
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=invoiceshelf
      - 'DB_USERNAME=${SERVICE_USER_MARIADB}'
      - 'DB_PASSWORD=${SERVICE_PASSWORD_MARIADB}'
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=localhost
      - 'SANCTUM_STATEFUL_DOMAINS=localhost:90'
      - 'TRUSTED_PROXIES=*'
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10
  mariadb:
    image: 'mariadb:11.5'
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_MARIADBROOT}'
      - MYSQL_DATABASE=invoiceshelf
      - 'MYSQL_USER=${SERVICE_USER_MARIADB}'
      - 'MYSQL_PASSWORD=${SERVICE_PASSWORD_MARIADB}'
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 5s
      timeout: 20s
      retries: 10
volumes:
  invoiceshelf-files: null
  mariadb-data: null
```

**Reply by rihards-simanovics** [reply]
Please hold on, this one uses a legacy version. We have changed how the volumes are mapped, and it will create confusion for people. Once we release version 2.2.0, I'll be happy to submit the updated Coolify template for InvoiceShelf.

**Reply by rihards-simanovics** [reply]
We may even add one called docker-compose.coolify.yaml so it's easy to update by the coolify maintainers.

**Reply by MichaelHaushofer** [reply]
Thanks for the info! Just a heads up there's currently no 'latest' tag on Docker Hub, 
only 'latest-legacy', '2.1.1-legacy', 'nightly' and alpha versions. 

The compose examples above using 'invoiceshelf/invoiceshelf:latest' won't work 
without a valid tag.

Looking forward to the 2.2.0 release and the docker-compose.coolify.yaml

**Reply by ooaklee** [reply]
Hey, wanted to get this running on my Coolify instance and managed to get it working, so I created this PR - https://github.com/InvoiceShelf/docker/pull/74

Which creates the `docker-compose.coolify. yaml`. From my tests, it works with a simple copy-and-paste. I tested it with a completely clean instance. 

> Thanks for sharing what you did @MichaelHaushofer, I used it as a base for getting the nightly image running

**Comment by ooaklee** [comment]
Here's a configuration that works with the latest Coolify nightly image in 2025:

> [more context
](https://github.com/coollabsio/coolify/discussions/3634#discussioncomment-15042148)


```
services:
  invoiceshelf:
    image: 'invoiceshelf/invoiceshelf:nightly'
    container_name: invoiceshelf-variant-pgsql
    environment:
      - SERVICE_FQDN_INVOICESHELF
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - APP_NAME=InvoiceShelf
      - APP_ENV=production
      - APP_DEBUG=false
      - 'APP_URL=https://${SERVICE_FQDN_INVOICESHELF_8080}'
      - 'APP_KEY=base64:${SERVICE_BASE64_INVOICESHELF}'
      - 'SESSION_DOMAIN=${SERVICE_FQDN_INVOICESHELF_8080}'
      - 'SANCTUM_STATEFUL_DOMAINS=${SERVICE_FQDN_INVOICESHELF_8080}'
      - 'TRUSTED_PROXIES=*'
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - DB_CONNECTION=pgsql
      - 'DB_HOST=${POSTGRESQL_HOST:?database}'
      - 'DB_PORT=${POSTGRESQL_PORT:?5432}'
      - 'DB_DATABASE=${POSTGRESQL_DATABASE:?invoiceshelf}'
      - 'DB_USERNAME=${SERVICE_USER_POSTGRESQL:?}'
      - 'DB_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL:?}'
      - DB_PASSWORD_FILE=
    volumes:
      - 'invoiceshelf_storage:/var/www/html/storage/'
      - 'invoiceshelf_modules:/var/www/html/Modules/'
    networks:
      - invoiceshelf
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: invoiceshelf-pgsql
    image: 'postgres:15-alpine'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRESQL:?}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL:?}'
      - 'POSTGRES_DB=${POSTGRESQL_DATABASE:?invoiceshelf}'
    volumes:
      - 'invoiceshelf_postgres:/var/lib/postgresql/data'
    networks:
      - invoiceshelf
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${SERVICE_USER_POSTGRESQL} -d ${POSTGRESQL_DATABASE}'
      interval: 5s
      timeout: 20s
      retries: 10
    restart: unless-stopped

networks:
  invoiceshelf: null
volumes:
  invoiceshelf_postgres: null
  invoiceshelf_storage: null
  invoiceshelf_modules: null

```
