### DISCUSSION TITLE
Espo CRM

### DISCUSSION THREAD

**Discussion by dreadyx** [coollabsio/coolify#3657] [Service Template Requests]
is it possible to add espo crm to the services?

**Comment by mateusz-zadorozny** [comment]
Oh yeah. That would be great!

**Reply by cloudpotions** [reply]
@dreadyx @mateusz-zadorozny I just submitted a pull request on GitHub to add EspoCRM support to Coolify! 

The pull request includes a Docker Compose template that I believe works great, but it’s still under review by the Coolify maintainers. If you’d like to test it yourself, here’s how you can set it up and please let me know if you come across any issues. 
Go to Coolify and click "Add New Service/Resource".
Select "Docker Compose".
Paste the Docker Compose File

Custom Domains (Optional):

Let the Docker Compose file run first to set everything up with auto-generated domains.
Once everything is running, go to the Coolify GUI and update the domains:

Set the Web App domain to https://yourdomain.com.
Set the WebSocket domain to https://ws.yourdomain.com.


Make sure to create A records for both domains and then point BOTH to your server's IP address. It uses a Web App and Web Socket so it needs both. 

I believe everything is working well, but let me know if you find any glitches 

```
services:
  espocrm-db:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MARIADB_DATABASE=espocrm
      - MARIADB_USER=espocrm
      - MARIADB_PASSWORD=$SERVICE_PASSWORD_DB
    volumes:
      - espocrm-db:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  espocrm:
    image: espocrm/espocrm:apache
    environment:
      - ESPOCRM_DATABASE_PLATFORM=Mysql
      - ESPOCRM_DATABASE_HOST=espocrm-db
      - ESPOCRM_DATABASE_USER=espocrm
      - ESPOCRM_DATABASE_PASSWORD=$SERVICE_PASSWORD_DB
      - ESPOCRM_ADMIN_USERNAME=admin
      - ESPOCRM_ADMIN_PASSWORD=$SERVICE_PASSWORD_ADMIN
      - ESPOCRM_SITE_URL=https://$SERVICE_FQDN_ESPOCRM
      - SERVICE_FQDN_ESPOCRM
    volumes:
      - espocrm:/var/www/html
    restart: always
    depends_on:
      espocrm-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.espocrm.rule=Host(`$SERVICE_FQDN_ESPOCRM`)
      - traefik.http.routers.espocrm.entryPoints=http
      - traefik.http.services.espocrm.loadbalancer.server.port=80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  espocrm-daemon:
    image: espocrm/espocrm:apache
    volumes:
      - espocrm:/var/www/html
    restart: always
    entrypoint: docker-daemon.sh
    depends_on:
      - espocrm

  espocrm-websocket:
    image: espocrm/espocrm:apache
    environment:
      - ESPOCRM_CONFIG_USE_WEB_SOCKET=true
      - ESPOCRM_CONFIG_WEB_SOCKET_URL=wss://$SERVICE_FQDN_SOCKET
      - ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN=tcp://*:7777
      - ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN=tcp://espocrm-websocket:7777
      - SERVICE_FQDN_SOCKET
    volumes:
      - espocrm:/var/www/html
    restart: always
    entrypoint: docker-websocket.sh
    labels:
      - traefik.enable=true
      - traefik.http.routers.espocrm-websocket.rule=Host(`$SERVICE_FQDN_SOCKET`)
      - traefik.http.routers.espocrm-websocket.entryPoints=http
      - traefik.http.services.espocrm-websocket.loadbalancer.server.port=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  espocrm-db:
  espocrm:
```
