### DISCUSSION TITLE
How to run Coolify on docker compose?

### DISCUSSION THREAD

**Discussion by alvarofpp** [coollabsio/coolify#3712] [Q&A]
Hello, I hope you're well.

I'm trying to run Coolify locally using Docker Compose, but I'm not succeeding. My goal is to test a possible integration between Coolify, an existing Traefik and Authentik to allow access to Coolify. I'm using the Docker Compose files in the repository as a base, but they don't work (or maybe they need some not-so-intuitive sequence of commands).

My docker-compose file:

```
---
services:
  coolify:
    container_name: coolify
    image: ghcr.io/coollabsio/coolify:4.0.0-beta.349
    environment:
      - APP_NAME=${COOLIFY_APP_NAME:-Coolify}
      - APP_ENV=production
      - DB_DATABASE=${COOLIFY_DB_NAME:-coolify}
      - DB_USERNAME=${COOLIFY_DB_USERNAME:-coolify}
      - DB_PASSWORD=${COOLIFY_DB_PASSWORD:?Database password required}
      - DB_HOST=postgres
      - DB_CONNECTION=pgsql
      - DB_PORT=5432
      - REDIS_HOST=coolify-redis
      - SSL_MODE=off
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    networks:
      - paas
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - coolify-data:/data
      - ./coolify/keys/:/var/www/html/storage/app/ssh/keys/
    depends_on:
      - postgres
      - coolify-redis

  postgres:
    container_name: postgres
    image: docker.io/library/postgres:16.4
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
    networks:
      - paas
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/

  coolify-redis:
    container_name: coolify-redis
    image: docker.io/library/redis:7.4.0
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks:
      - paas
    volumes:
      - coolify-redis-data:/data

networks:
  paas:
    driver: bridge

volumes:
  coolify-data:
    driver: local
  database-data:
    driver: local
  coolify-redis-data:
    driver: local
...
```

I'm currently getting this error:

```
...
🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...
🔓 SSL_MODE has been DISABLED, setting the web server to work in HTTP only...

   INFO  The [public/storage] link has been connected to [storage/app/public].serversideup.nethttps://serversideup.net/sponsor

   INFO  Nothing to migrate.
[03-Oct-2024 02:43:46] NOTICE: fpm is running, pid 99
[03-Oct-2024 02:43:46] NOTICE: ready to handle connections
[03-Oct-2024 02:43:46] NOTICE: systemd monitor interval set to 10000ms

   INFO  Seeding database.

Running in self-hosted mode.

In EncryptionServiceProvider.php line 83:

  No application encryption key has been specified.


s6-rc: warning: unable to start service init-seeder: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
[03-Oct-2024 02:43:48] NOTICE: Terminating ...
[03-Oct-2024 02:43:48] NOTICE: exiting, bye-bye!
```

Does anyone have any `docker-compose.yml` to share that makes it possible to use Coolify?

**Comment by Omid-Zahed** [comment]
It seems like the issue is related to missing the application encryption key, which is crucial for Laravel-based applications like Coolify. The error in the logs indicates that Coolify is not able to find the encryption key.

### Suggested Solution:

1. **Generate a Laravel Encryption Key**: This key can be generated using the `php artisan key:generate` command inside the Coolify container.

   - **Manual Approach**:
     After running `docker-compose up`, attach to the Coolify container:
     ```bash
     docker exec -it coolify bash
     ```
     Then run:
     ```bash
     php artisan key:generate
     ```
     This will generate the key and add it to your `.env` file, which Laravel uses for encryption.

2. **Update the Docker Compose**:
   Add the following environment variable to your Coolify service in the `docker-compose.yml` file:
   ```yaml
   - APP_KEY=base64:your_generated_key

**Comment by peaklabs-dev** [comment]
@alvarofpp Coolify has different compose files for different environments. This is why we use docker compose overrides: https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/ So we have a base compose file `docker-compose.yml` that is used by all environments and then your specific compose file that is used for your specific environment, e.g. production, development...

You can use the base compose file `docker-compose.yml` and `docker-compose.prod.yml` file and then run the following command with the adjusted paths to start Coolify (and of course you need an `.env` file). 

```bash
docker compose --env-file /data/coolify/source/.env -f /data/coolify/source/docker-compose.yml -f /data/coolify/source/docker-compose.prod.yml up -d --pull always --remove-orphans --force-recreate
```

-> **Please make sure you are hosting on Linux** as we do not really support MacOS or Windows for hosting Coolify yet. If you want to develop on Coolify (to submit PRs), I do not recommend this manual approach described above (that one is for hosting Coolify). If you are developing for Coolify, please follow this [contribution guide](https://github.com/coollabsio/coolify/blob/main/CONTRIBUTING.md) in detail, as it also works on Windows and Mac OS without problems. 

I hope I could help, if you have any further questions, just let me know.

**Comment by mustafa-ramax** [comment]
If anyone still looking for a way to run Coolify inside docker, for testing/self-host — full working steps (Coolify v4.x):

use this if you want to run Coolify as a container (for testing / playground / not production)
it works — but Coolify will still expect SSH access to the host, even if host is local > this is normal so you will need to run it on Linux or windows not mac.

**1- docker-compose.yml example:**

```
services:
  coolify:
    image: ghcr.io/coollabsio/coolify:latest
    container_name: coolify
    ports:
      - "8080:8080"
    volumes:
      - coolify-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://coolify:coolify@coolify-db:5432/coolify
      REDIS_HOST: coolify-redis
      APP_KEY: "get it by: php artisan key:generate"
    networks:
      - coolify

  postgres:
    image: postgres:15-alpine
    container_name: coolify-db
    restart: always
    environment:
      POSTGRES_USER: coolify
      POSTGRES_PASSWORD: coolify
      POSTGRES_DB: coolify
    volumes:
      - coolify-postgres:/var/lib/postgresql/data
    networks:
      - coolify

  redis:
    image: redis:7-alpine
    container_name: coolify-redis
    restart: always
    networks:
      - coolify

networks:
  coolify:
    driver: bridge

volumes:
  coolify-data:
  coolify-postgres:
```

**2- generate SSH key (needed even for local)**
`ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519_coolify -N ""`
add id_ed25519_coolify.pub to ~/.ssh/authorized_keys on host:
`cat ~/.ssh/id_ed25519_coolify.pub >> ~/.ssh/authorized_keys`

in Coolify Web UI > Settings > Private Keys > add the private key id_ed25519_coolify 

Now Coolify will be able to manage local Docker server via this SSH key → and local server validation should work.

Notes:
	• Do not use this setup for production — it is for testing inside docker only, mostly can use it to understand the UI or test it.
	• Production > better to install Coolify directly on the host

Useful troubleshooting commands:

To enter the container:
`docker exec -it coolify sh
`
You can run this inside the container if you get “table does not exist” errors — but only during testing!
`php artisan migrate:fresh --seed
`
