### DISCUSSION TITLE
Zero-Downtime deployment

### DISCUSSION THREAD

**Discussion by AndyMik90** [coollabsio/coolify#3767] [Feature Requests]
For more production ready / production apps, zero-downtime deployments is a very nice feature to have (in my eyes a must).

Should not be to much of work to implement something with the current Traefik / Docker compose setup that Coolify has; found this nice guide on structuring it as a blue-green deployment strategy:
https://www.maxcountryman.com/articles/zero-downtime-deployments-with-docker-compose

**Comment by KaelWD** [comment]
Looks like it should be doable with `--scale` too: https://github.com/wowu/docker-rollout

**Reply by franciscobmacedo** [reply]
docker-rollout requires that the container can't have `container_name` which coolify automatically assigns, so I don't think it's a possibility?

**Comment by AndyMik90** [comment]
Maybe if this is not something that will be in Coolify natively, there could be some documentation how users can set it up for themselves with the proxy in Coolify? @andrasbacsai @peaklabs-dev

**Reply by ghost** [reply]
It's definitely possible because you can do it with normal docker, and since coolify uses docker then they should be able to added it, not sure why it's not in by default but it will be nice once its added.

**Reply by imankeeth** [reply]
+1

**Reply by mattaiod** [reply]
+1, you are amazing, please do that for the world ASAP. Thank you very much

**Comment by AndyMik90** [comment]
Any comments or feedback regarding this one @peaklabs-dev @andrasbacsai ?

**Reply by franciscobmacedo** [reply]
Did you made it work in a somewhat straightforward way? Wondering if you have any tips on how to set this up

**Reply by AndyMik90** [reply]
@franciscobmacedo myself have not had the time to set it up.

**Comment by roshanjonah** [comment]
+1

**Comment by AndyMik90** [comment]
@peaklabs-dev @andrasbacsai This could be a done quite easily as long as persistent storage is left out of the equation.

**Reply by djsisson** [reply]
you can switch to swarm mode, then this is handled automatically by docker

**Reply by luco** [reply]
@djsisson Any tips on how doing it?

**Reply by KaelWD** [reply]
@djsisson #3798

**Reply by djsisson** [reply]
@KaelWD you need to pre set it up

**Comment by luco** [comment]
@andrasbacsai @peaklabs-dev Thoughts?

**Comment by yes-oo** [comment]
any updates ? any ideas , this is what holding me back to launch my website with coolify

**Comment by SindelarPetr** [comment]
I would say this is the feature which would stop a lot of production projects from launching using Coolify. In my job, it was normal for Java or Python services to take take up to 30s to start. 

On Kubernetes it was no big deal, because it supports zero downtime deployments out of the box.

I still think Coolify is still better alternative than Kubernetes for most of the non-enterprise projects. But this feature would allow software architects to explain the value of it to the necessary stakeholders.

**Reply by luco** [reply]
> I would say this is the feature which would stop a lot of production projects from launching using Coolify. In my job, it was normal for Java or Python services to take take up to 30s to start.
> 
> On Kubernetes it was no big deal, because it supports zero downtime deployments out of the box.
> 
> I still think Coolify is still better alternative than Kubernetes for most of the non-enterprise projects. But this feature would allow software architects to explain the value of it to the necessary stakeholders.

Maybe setting it optional.

**Reply by djsisson** [reply]
coolify has zero-downtime as long as you aren't setting ports, fixed container names etc

and it also works fine in docker swarm

**Reply by farisgoogerit** [reply]
@djsisson 

>  as long as you aren't setting ports

means?

**Reply by djsisson** [reply]
if a container is currently using a fixed port on the host, you cant start another container that uses the same port unless you stop the first one, generally you should never be mapping direct to the host, as you have no control over what traffic is hitting those ports from outside.

this isn't an issue in swarm mode, since fixing ports aren't mapped to the host, (although you can still do this)

**Reply by McAndze** [reply]
@djsisson how is the current deployment method zero downtime? Am I missing something? When I deploy with Docker Compose, I can clearly see in the log that old containers are removed first, and then the new ones are started up, which in my case equates to around 90s of downtime because of Ktor starting up.

I feel like I've missed something, because I was almost certain that Coolify did zero downtime deployments until I realized myself that we had some small periods of downtime around deployment. 

Maybe it's only when deploying a Docker image directly that Coolify supports zero downtime and not with Docker Compose?

**Reply by djsisson** [reply]
@McAndze yes sorry, in docker compose projects, they run stop containers during deployment, so a compose project doesn't get rolling updates

to get around this you split your compose, so static services stay in the compose, and you have your build seperate but within same docker network as your compose, so you get rolling updates on your builds.

Or you use swarm , where docker stack automatically has rolling updates if specified in the deploy section where order: start_first is set in the compose

**Reply by Patrick3131** [reply]
@djsisson 
I now have docker swarm running and I reduced my downtime compared to before. However, it still has a 1-2s downtime when getting deployed.
This is my deploy:
```
    networks:
      - coolify-overlay
    deploy:
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 20s
```

I am working with one node I am using the manager as a worker and I only have 1 replica. Is there something I could improve further?

**Reply by djsisson** [reply]
if this is swarm within coolify, then it will still stop the containers first in a compose project, it only runs docker stack in none compose projects currently

https://github.com/coollabsio/coolify/blob/f28eefe603fab5becabd8821746304fa622b5802/app/Jobs/ApplicationDeploymentJob.php#L522

so if you want swarm it can't be with coolify (it's simple enough to run the build / push to registry / docker stack command from within ci/cd tho if you still wanted to do it that way). For coolify you just can't run your app builds using a compose project currently if you need zero downtime.

####

i will add i assume part of the reason for not supporting compose in swarm within coolify, is due to swarm not interpolating env directly as well as not supporting some other compose 

one way to get around this is you can run:

```docker stack deploy -c <(docker compose -f docker-compose.yaml config | grep -v ^'name') mystack```

also although you can set custom build/start commands, coolify will still stop all containers in a compose project before running the custom start command, so setting the above would still not work within coolify

**Reply by Patrick3131** [reply]
Thanks a lot for your input. So coolify is not production ready yet if we want to use docker compose.

**Reply by oribenez** [reply]
I think that also using dockerfile to start the container you dont have zero downtime deployment.
In my apps we have ~10 sec of downtime

**Reply by djsisson** [reply]
@oribenez as long as you don't have fixed ports, container name or ip, then the old container isn't stopped till after the new ones are up running and are healthy
so there should be no downtime

**Reply by oribenez** [reply]
> @oribenez as long as you don't have fixed ports, container name or ip, then the old container isn't stopped till after the new ones are up running and are healthy
> 
> so there should be no downtime

Tnx for your quick reply.
That is strange cause i have ports on expose.
Maybe it is because i switched to caddy proxy?

**Reply by luco** [reply]
@djsisson How can we do it without exposing ports?

**Reply by oribenez** [reply]
> @djsisson How can we do it without exposing ports?

Instead of port expose you can use the ports mapping solution.

**Comment by acoard** [comment]
![image](https://github.com/user-attachments/assets/007323c0-b2d6-40b8-9d85-216bb5a17bcf)

So what's the status of zero downtime deployment and rolling updates? I see the documentation only refers to losing rolling updates if you _do_ use port mappings. But the comments in this thread by @djsisson and @oribenez  (thanks for helping out on this btw!) seem to imply you lose it if you _don't_ use port mappings.

Additionally, the port expose seems like a  required value. If I try to do what @oribenez proposes, not using port expose, the form validation blocks me. Am I doing something wrong? I'm using the nix build here, but happy to switch to docker if it helps.
 
![image](https://github.com/user-attachments/assets/c8657ddd-0db1-46f9-a439-7fa39f1f8ae9)

Loving Coolify so far, but zero-downtime deployments are a must, and I would hate to have to migrate off of coolify.

**Reply by djsisson** [reply]
@acoard I only mentioned you lose rolling updates when setting port mappings, fixed container names and fixed ip

Not the other way around, maybe that was poor wording on my part.

Port exposes is just documenting which ports inside the container you want to access from outside, though not required by docker, maybe coolify now requires it.

Regarding zero downtime, this is only an issue when using a compose file. As docker stack is also not used when in swarm mode.

**Reply by yes-oo** [reply]
I think we must mention some strong core team members. I don't think it's hard to achieve zero downtime if the core team makes it a top priority.

**Reply by tomocrafter** [reply]
maybe this documentation is talking about Rolling Updates of **Coolify itself**: https://coolify.io/docs/knowledge-base/rolling-updates.

**Reply by garraflavatra** [reply]
No, that doc is about rolling updating your application. Make sure you have a healthcheck configured in order for rolling updates to work.

**Reply by grdevd** [reply]
@garraflavatra The problem exists when using **Docker Compose**. Even having healthchecks in the docker compose file and NOT using container name, during a deployment when the Docker file gets downloaded, the application shows 

```no available server```

and this can take up to 1-2 minutes where the application is down.

On other platforms (like Digital Ocean), the container is replaced after starting and we have no downtime.

We have this problem with missing rolling updates with the following docker compose file:

```yaml
version: "4"
services:
  client:
      image: "<docker image>"
      pull_policy: always
      environment:
          ...
      restart: unless-stopped
      expose:
        - "3000"
      healthcheck:
        test:
            - CMD-SHELL
            - 'curl -s -X GET -f http://localhost:3000/ > /dev/null || wget -q -O- http://localhost:3000/ > /dev/null || exit 1'
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
  server:
      image: "<docker image>"
      pull_policy: always
      environment:
          ...
      restart: unless-stopped
      expose:
        - "1337"
      healthcheck:
        test:
            - CMD-SHELL
            - 'curl -s -X GET -f http://localhost:1337/ > /dev/null || wget -q -O- http://localhost:1337/ > /dev/null || exit 1'
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 30s
```
