### DISCUSSION TITLE
Default Redirect 404 File (Dynamic)

### DISCUSSION THREAD

**Discussion by hybes** [coollabsio/coolify#3774] [Feature Requests]
Hi, I would like to add support for a redirect file or such, that could be dynamic, I don't directly want to redirect to another site, I would like to to display something better than a blank 404 error not found.

For example, if I deployed example.com and it was down, I would want a nice styled page that says 'example.com' is not available, please try again later. If you believe this is in error, bla bla bla.

Ideally we just route to a HTML file, or we could add an argument to the redirect URL, so I could redirect to myapp.com/redirect_catch?site={{example.com}} and could make that all happen on there.

**Comment by KaelWD** [comment]
The default response should be 503 too not 404. I've tried the configurations from https://community.traefik.io/t/catchall-router-that-returns-503-service-unavailable-response-code/10651 but it still returns 404 for sites that don't exist.

```
http:
  routers:
    catchall:
      entryPoints:
        - http
      rule: PathPrefix(`/`)
      service: unavailable
      priority: 1
  services:
    unavailable:
      loadBalancer:
        servers: {  }
```

```
- traefik.http.routers.unavailable.entrypoints=http
- traefik.http.routers.unavailable.rule=PathPrefix(`/`)
- traefik.http.routers.unavailable.priority=1
- traefik.http.services.unavailable.loadbalancer.server.port=0
```

**Reply by KaelWD** [reply]
Switching to caddy works, just have to delete `/data/coolify/proxy/caddy/dynamic/default_redirect_404.caddy` which isn't possible in the ui for some reason.

```
:80, :443 {
  respond 503
}
```

you can make a custom error page too, 503.html is placed in `/data/coolify/proxy/caddy/data`

```
:80, :443 {
  rewrite * /data/503.html
  file_server {
    status 503
  }
}
```

**Reply by KaelWD** [reply]
:angry: default_redirect_404 comes back if you restart the proxy

**Reply by hybes** [reply]
Agreed 503 should be the default! The fact we can swap away and then it gets reset at least means it's possible.

**Reply by KaelWD** [reply]
Ok I think I got it working. You have to create a docker compose service with the caddy config:

```yml
networks:
  coolify:
    external: true
services:
  caddy:
    container_name: coolify-proxy
    image: 'lucaslorentz/caddy-docker-proxy:2.8-alpine'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - CADDY_DOCKER_POLLING_INTERVAL=5s
      - CADDY_DOCKER_CADDYFILE_PATH=/dynamic/Caddyfile
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy/caddy/dynamic:/dynamic'
      - '/data/coolify/proxy/caddy/config:/config'
      - '/data/coolify/proxy/caddy/data:/data'
```

Then stop the proxy and set it to `Custom (None)` and start the custom service. Now you can place your own `.caddy` files in `/data/coolify/proxy/caddy/dynamic/` without coolify messing with them.
