### DISCUSSION TITLE
Issue with docker compose deployments.

### DISCUSSION THREAD

**Discussion by Nneji123** [coollabsio/coolify#3779] [Q&A]
I've been able to configure and deploy a Django backend that works with some services (redis, rabbitmq etc) using docker compose. Everything deploys successfully and I can access the API.

The deployment uses a private GitHub repo which I've also successfully linked to our self-hosted coolify instance.

When I make a push to the branch linked to the deployment only one of the services' files are updated. The worker and scheduler services which use the same docker file as the web service do not get updated.

I've tried redeploying the services with the without cache option and it still uses the old project files instead of pulling the latest changes from the branch that triggered the redeployment.

I've also turned on the "Preserve Repository During Deployment"

Note only the web service is updated. The worker and scheduler services are not updated during redeployment.

 Here's my compose file:

```
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: trendibble-api
    command: scripts/start_server.sh
    ports:
      - ${WEB_PORT:-8000}:8000
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      RABBITMQ_USER: ${RABBITMQ_USER:-user}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-password}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      SERVICE_TYPE: "web"
    env_file: .env
    restart: on-failure
    volumes:
      - ./:/app
      - ./logs:/app/logs

  redis:
    image: redis:7.2.4-alpine3.19
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-password}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  scheduler:
    container_name: trendibble-api-scheduler
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: scripts/start_celery_beat.sh
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      RABBITMQ_USER: ${RABBITMQ_USER:-user}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-password}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      SERVICE_TYPE: "scheduler"
    restart: on-failure

  worker:
    container_name: trendibble-api-worker
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: scripts/start_celery_worker.sh
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - mjml-server
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      RABBITMQ_USER: ${RABBITMQ_USER:-user}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-password}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      SERVICE_TYPE: "worker"
    env_file: .env
    restart: on-failure

  mjml-server:
    image: danihodovic/mjml-server:4.15.3
    ports:
      - "${MJML_SERVER_PORT:-15500}:15500"
    restart: unless-stopped

volumes:
  data:
```
