### DISCUSSION TITLE
OSTicket

### DISCUSSION THREAD

**Discussion by kanhaic** [coollabsio/coolify#3850] [Service Template Requests]
Hi,

I would like to request that osticket be added.

I have done some work, but i'm not sure if this docker compose is correct

```yml
version: '3'
services:
  osticket:
    image: tiredofit/osticket
    restart: always
    environment:
      - SERVICE_FQDN_OSTICKET_8080
      - 'APP_URL=${SERVICE_FQDN_OSTICKET}'
      - CRON_INTERVAL=10
      - DB_HOST=mariadb
      - 'DB_NAME=${OSTICKET_DATABASE}'
      - 'DB_USER=${SERVICE_USER_MARIADB}'
      - 'DB_PASS=${SERVICE_PASSWORD_MARIADB}'
      - 'INSTALL_SECRET=${SERVICE_PASSWORD_OSTICKETSECRET}'
      - 'ADMIN_FIRSTNAME=${OSTICKET_FIRSTNAME:-Admin}'
      - 'ADMIN_LASTNAME=${OSTICKET_LASTNAME:-istrator}'
      - 'ADMIN_EMAIL=${OSTICKET_ADMIN_EMAIL:-admin@example.com}'
      - 'ADMIN_USER=${OSTICKET_ADMIN_USER:-admin}'
      - 'ADMIN_PASS=${SERVICE_PASSWORD_OSTICKETADMINPASS}'
    healthcheck:
      test: 
        - CMD-SHELL
        - 'curl --fail http://localhost/ || exit 1'
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - mariadb
    links:
      - mariadb
    volumes:
      - 'osticket_data:/www/osticket'
  mariadb:
    image: 'mariadb:11'
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '${SERVICE_PASSWORD_MARIADBROOT}'
      MARIADB_DATABASE: '${OSTICKET_DATABASE:-osticket}'
      MARIADB_USER: '${SERVICE_USER_MARIADB}'
      MARIADB_PASSWORD: '${SERVICE_PASSWORD_MARIADB}'
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - 'db_data:/var/lib/mysql'
volumes:
  db_data: {  }
  osticket_data: {}
```

it is working on my instance, however, I am not sure if anything more needs to be added.
