### DISCUSSION TITLE
Postal Server - An Opensource Mail Delivery Platform

### DISCUSSION THREAD

**Discussion by therajoka** [coollabsio/coolify#3925] [Service Template Requests]
It will be great to have Opensource mail server Postal with one click install. https://docs.postalserver.io/

**Comment by intentionull** [comment]
This. Unsend and Plunk are wrappers for AWS SES from my understanding and to be honest, not optimal for most solutions that want to stay away from depending on AWS.

**Comment by Nekidev** [comment]
+1 for this, all the existing service templates either depend on AWS or are testing-intended, having an SMTP server/relay would be a great addition.

**Comment by cmdaltctr** [comment]
Much needed. I'm finding a PaaS alternative to Cloudron for a mail server.

**Comment by rh-id** [comment]
+1 for this having mail server with webhook and REST API capabilities are very nice to have.

**Comment by sdoering** [comment]
+1 for this. Might look into it.

**Comment by itsjavi** [comment]
+1 . I agree. I tried Unsend but it requires AWS SES (good luck getting an approval for this service). This is the only missing piece to fully self-host. here is an example docker config (not tested, and not coolify-ed yet). I might open a PR soon.

```yaml
services:
  mariadb:
    image: 'mariadb:11'
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: postal
      MARIADB_ROOT_PASSWORD: '${SERVICE_PASSWORD_MARIADB}'
    volumes:
      - 'postal_db_data:/var/lib/mysql'
  web:
    platform: linux/amd64
    image: 'ghcr.io/postalserver/postal:stable'
    restart: unless-stopped
    command: 'postal web-server'
    environment:
      - BIND_ADDRESS=0.0.0.0
      - PORT=5000
    depends_on:
      - mariadb
    volumes:
      - '/opt/postal/config:/config'
    labels:
      - traefik.enable=true
      - traefik.http.routers.postal.rule=Host(`postal.EXAMPLE.com`)
      - traefik.http.routers.postal.entrypoints=websecure
      - traefik.http.routers.postal.tls=true
      - traefik.http.services.postal.loadbalancer.server.port=5000
  smtp:
    platform: linux/amd64
    image: 'ghcr.io/postalserver/postal:stable'
    restart: unless-stopped
    command: 'postal smtp-server'
    cap_add:
      - NET_BIND_SERVICE
    depends_on:
      - mariadb
    volumes:
      - '/opt/postal/config:/config'
  worker:
    platform: linux/amd64
    image: 'ghcr.io/postalserver/postal:stable'
    restart: unless-stopped
    command: 'postal worker'
    depends_on:
      - mariadb
    volumes:
      - '/opt/postal/config:/config'

```
