### DISCUSSION TITLE
Add Home Assistant Service

### DISCUSSION THREAD

**Discussion by aybasaran** [coollabsio/coolify#3933] [Service Template Requests]
https://www.home-assistant.io/

**Comment by MPParsley** [comment]
Adding a link to the documentation: https://www.home-assistant.io/installation/alternative#docker-compose

```
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
```

Optional for Zigbee devices:
```
services:
  homeassistant:
    ...
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```

![image](https://github.com/user-attachments/assets/b54f76c4-f641-4a4b-bf27-51ab58db63e5)
