### DISCUSSION TITLE
Mailpit enable TLS

### DISCUSSION THREAD

**Discussion by affanshahid** [coollabsio/coolify#3935] [Q&A]
How do I go about enabling TLS for the mailpit deployed through coolify? I was previously doing this when using compose directly:

```yml
services:
  smtp4dev:
    container_name: mailpit
    image: axllent/mailpit
    restart: always
    ports:
      - "5025:8025"
      - "2525:1025"
    volumes:
      - /var/lib/docker/volumes/caddy_data/_data/caddy/certificates/acme.zerossl.com-v2-dv90/mydomain.com/:/certs
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_TLS_CERT: /certs/mydomain.com.crt
      MP_SMTP_TLS_KEY: /certs/mydomain.com.key
      MP_SMTP_REQUIRE_TLS: true

```
