### DISCUSSION TITLE
How to deploy different ports from the same repo using the compose buildpack?

### DISCUSSION THREAD

**Discussion by affanshahid** [coollabsio/coolify#3963] [Q&A]
I have a Github repo that I want to deploy into multiple environments with a different port for the postgres container but I am not sure how.

So, say I have a repo `RepoFoo` which has a `docker-compose.yml` with the following part:
```yml
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESPASSWORD}
      - POSTGRES_DB=timmy
    volumes:
      - db-data:/var/lib/postgresql/data
```

I have a coolify project `Foo` with two environments `staging` and `production`. I want to deploy this repo to both with different configurations, specifically I want a different postgres port for each environment. However I am not sure how to go about this.
