### DISCUSSION TITLE
Automatically include WP-CLI with WordPress

### DISCUSSION THREAD

**Discussion by theDanielJLewis** [coollabsio/coolify#3990] [Feature Requests]
Would you please configure including and configuring for `wordpress:cli` in all WordPress resources?

I've been trying to manually add it, but it's a struggle because Coolify keeps rebooting the wp-cli container.

Here's how I added the `wordpress-cli` to Coolify's Docker Compose:

```yaml
services:
# These wordpress and mariadb sections are untouched from Coolify's default
  wordpress:
    image: 'wordpress:latest'
    volumes:
      - 'wordpress-files:/var/www/html'
    environment:
      - SERVICE_FQDN_WORDPRESS
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=$SERVICE_USER_WORDPRESS
      - WORDPRESS_DB_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mariadb
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10
  mariadb:
    image: 'mariadb:11'
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=$SERVICE_USER_WORDPRESS
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 5s
      timeout: 20s
      retries: 10

# The following are my only changes
  wordpress-cli:
    image: 'wordpress:cli'
    user: '33'
    volumes:
      - 'wordpress-files:/var/www/html'
    depends_on:
      mariadb:
        condition: service_started
      wordpress:
        condition: service_started
    environment:
      - SERVICE_FQDN_WORDPRESS
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=$SERVICE_USER_WORDPRESS
      - WORDPRESS_DB_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
      - WORDPRESS_DB_NAME=wordpress
    healthcheck:
      test:
        - CMD
        - wp
        - '--version'
      interval: 5s
      timeout: 10s
      retries: 10
```

This _almost_ works. Actually, I can launch the wordpress-cli terminal and successfully run any `wp` command, but Coolify keeps restarting the service, so I'm not sure what I'm doing wrong with the above config.

I'm guessing that once we figure this out, I can do a PR to make these changes for Coolify's default WordPress setups.

**Comment by theDanielJLewis** [comment]
Even if I set the test to `true`, Coolify/Docker still thinks it's unhealthy and it keeps restarting it.

I've experimented with adding `wp` commands to the compose file and they successfully run with data from the site. So I _know_ the connection between the images is configured correctly, but the Docker health check thinks otherwise, so it keeps restarting that container.

I also tried:

```yaml
healthcheck:
  disable: true
```

But that doesn't fix it, either.

**Reply by bogdanrn** [reply]
according to the docs you would have to do it like this, have you tried that?

```
services:
  some-service:
    exclude_from_hc: true
    ...
```

https://coolify.io/docs/knowledge-base/docker/compose#exclude-from-healthchecks

**Comment by bogdanrn** [comment]
is there any official way of adding it?

**Comment by wdmtech** [comment]
Adding the health check and `command: tail -f /dev/null` seemed to do the trick

```yaml
services:
  wordpress:
    image: 'wordpress:latest'
    volumes:
      - 'wordpress-files:/var/www/html'
    environment:
      - SERVICE_URL_WORDPRESS
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=$SERVICE_USER_WORDPRESS
      - WORDPRESS_DB_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mysql
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1" ]
      interval: 2s
      timeout: 10s
      retries: 10

  mysql:
    image: 'mysql:8'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=$SERVICE_USER_WORDPRESS
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 5s
      timeout: 20s
      retries: 10

  wpcli:
    image: wordpress:cli
    command: tail -f /dev/null
    working_dir: /var/www/html
    volumes:
      - 'wordpress-files:/var/www/html'
    depends_on:
      - wordpress
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: $SERVICE_USER_WORDPRESS
      WORDPRESS_DB_PASSWORD: $SERVICE_PASSWORD_WORDPRESS
      WORDPRESS_DB_NAME: wordpress
    healthcheck:
      test: [ "CMD", "wp", "cli", "version" ]
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  wordpress-files: null
  mysql-data: null

```
