### DISCUSSION TITLE
Limit coolify access to the machine or network

### DISCUSSION THREAD

**Discussion by hensansi** [coollabsio/coolify#4031] [General]
This [issue](https://github.com/coollabsio/coolify/issues/2427) was closed but I found a cleaner solution on how to deal with this:

The solution is to add the following to `/data/coolify/source/.env`:
`APP_PORT=127.0.0.1:8000`

This will bind the docker service to the localhost not exposing it to the internet.

In my case I'm actually using tailscale and I want to still keep it exposed to that network so I can simply grab the ip with `tailscale ip` and use that instead of 127.0.0.1

The final solution to add the entry to the file looks something like this:

```
LOCAL_IP=$(tailscale ip 2>/dev/null | head -n1 || echo "127.0.0.1") && \
echo "APP_PORT=${LOCAL_IP}:8000" >> /data/coolify/source/.env
```

Afterwards if you run the `/data/coolify/source/upgrade.sh` script the services should be restarted with the new variable.

If there is someone from the collaborators or the team that could add/link the solution to that issue, maybe it will help other people out there.

**FYI:**
There is a weird artifact 0/tcp shouldn't be there but it should be of no consequence:

Ports before:
`443/tcp, 8000/tcp, 9000/tcp, 0.0.0.0:8000->80/tcp`

Ports after:
` 0/tcp, 443/tcp, 9000/tcp, 127.0.0.1:8000->80/tcp`

**FYI 2:**
Oh, and keep in mind that the coolify-realtime is still exposed. I'm new to coolify so I will just avoid exposing till I know what is for.
`0.0.0.0:6001-6002->6001-6002/tcp`

```
LOCAL_IP=$(tailscale ip 2>/dev/null | head -n1 || echo "127.0.0.1") && \
echo "SOKETI_PORT=${LOCAL_IP}:6001" >> /data/coolify/source/.env
```

**Comment by hensansi** [comment]
@peaklabs-dev can you add this extra info to https://github.com/coollabsio/coolify/issues/2427?

**Comment by djsisson** [comment]
you can use a custom.yml file to override the defaults also
just save it in this location:
/data/coolify/source/docker-compose.custom.yml

i use this since i dont need any ports mapped to host

```yaml
services:
    coolify:
        ports: !reset []
    soketi:
        ports: !reset []
```

but you can also use !override
```yaml
services:
    coolify:
        ports: !override
          - 127.0.0.1:8000:80
    soketi:
        ports: !override
          - 127.0.0.1:6001:6001
          - 127.0.0.1:6002:6002
```
