### DISCUSSION TITLE
Support `include` section for docker compose

### DISCUSSION THREAD

**Discussion by meslzy** [coollabsio/coolify#4049] [Improvement Requests]
### Description

I have created a docker compose that uses `include` which includes sub docker files

but when using `Coolify` it only parse the top level file.

- this is the top level docker compose file

```yml
include:
  - ./backend/docker-compose.yml
  - ./frontend/docker-compose.yml

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "6000:80"
    volumes:
      - ./infra/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # backend apps
      - api
      # frontend apps
      - website
    networks:
      - bridge

networks:
  bridge:
    driver: "bridge"
```

this will result 

- this is the result of coolify, which misses the frontend and backend files.

```yml
services:
  nginx:
    image: 'nginx:alpine'
    container_name: nginx-do80cos-163917957249
    ports:
      - '6000:80'
    volumes:
      - '/data/coolify/applications/do80cos/infra/nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - api
      - website
    networks:
      bridge: null
      do80cos: null
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-sos8040.entryPoints=http
      - traefik.http.routers.http-0-sos8040.middlewares=gzip
      - 'traefik.http.routers.http-0-sos8040.rule=Host(`rww8gw4.193.122.68.5.sslip.io`) && PathPrefix(`/`)'
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=http://rww8gw4.193.122.68.5.sslip.io'
      - caddy_ingress_network=do80cos
      - coolify.managed=true
      - coolify.version=4.0.0-beta.315
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=nginx-do80cos-163917957249
      - coolify.pullRequestId=0
    restart: unless-stopped
volumes: {  }
networks:
  bridge: null
  do80cos:
    name: do80cos
    external: true
configs: {  }
secrets: {  }
```

Docker version 26.0.2, build 3c863ff
Docker Compose version v2.28.1
Coolify v4.0.0-beta.315

### Minimal Reproduction (if possible, example repository)

just create a a simple docker compose but use include 

### Exception or Error

```txt
[2024-Jul-17 16:42:22.161326] Oops something is not okay, are you okay? 😢

[2024-Jul-17 16:42:22.163381] service "nginx" depends on undefined service "api": invalid compose project
```

### Version

v4.0.0-beta.315
