### DISCUSSION TITLE
Joomla 1-click install

### DISCUSSION THREAD

**Discussion by QarthO** [coollabsio/coolify#4054] [Service Template Requests]
Would love to have a Joomla 1-click install! Joomla is an opensource CMS very similar to wordpress. The setup will be nearly identical to the existing wordpress service.
Website: https://www.joomla.org/
Source: https://github.com/joomla
Official Docker Image: https://hub.docker.com/_/joomla

**Comment by QarthO** [comment]
This is the compose script i'm using currently on coolify
```yml
services:
  joomla:
    image: 'joomla:latest'
    volumes:
      - 'joomla-files:/var/www/html'
    environment:
      - SERVICE_FQDN_JOOMLA
      - JOOMLA_DB_HOST=mariadb
      - JOOMLA_DB_USER=$SERVICE_USER_JOOMLA
      - JOOMLA_DB_PASSWORD=$SERVICE_PASSWORD_JOOMLA
      - JOOMLA_DB_NAME=joomla
    depends_on:
      - mariadb
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10
  mariadb:
    image: 'mariadb:11'
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=joomla
      - MYSQL_USER=$SERVICE_USER_JOOMLA
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_JOOMLA
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 5s
      timeout: 20s
      retries: 10
```

I still had to input the database host/credentials in the Joomla installer after deploying. I'm not sure as to why because I believe I'm using the same environment variables listed on the joomla image page. If those can be ironed out then should be good to go
