### DISCUSSION TITLE
how to use Coolify's reverse proxy for a baremetal application?

### DISCUSSION THREAD

**Discussion by itsyigid** [coollabsio/coolify#4059] [Q&A]
Hello everyone,

I apologize if this question has been asked before. I've searched through previous discussions and the web but haven't found a helpful solution. 

I recently installed Syncthing on bare metal to address some performance issues. I bound it to localhost:3003. I also tried configuring "Dynamic Configurations" under "Server > Proxy" but this only resulted in losing access to the proxy altogether. 

Below are the specific configurations I attempted:

### 1

```yaml
http:
  routers:
    syncthing:
      rule: "Host(`sync.example.org`)"
      service: syncthing
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - secHeaders@file

  services:
    syncthing:
      loadBalancer:
        servers:
          - url: "http://localhost:3003"
```

### 2

```yaml
http:
  routers:
    syncthing:
      rule: "Host(`sync.example.org`)"
      service: syncthing
      entryPoints:
        - websecure
      tls:
        certResolver: coolify

  services:
    syncthing:
      loadBalancer:
        servers:
          - url: "http://localhost:3003"
```

### 3

```yaml
http:
  routers:
    syncthing:
      rule: "Host(`sync.example.org`)"
      service: syncthing
      tls: {}

  services:
    syncthing:
      loadBalancer:
        servers:
          - url: "http://localhost:3003"
```

Thanks in advance.

**Comment by djsisson** [comment]
```yaml
http:
  middlewares:
    redirect-to-https:
      redirectscheme:
        scheme: https
    gzip:
      compress: true
  routers:
    syncthing-http:
      middlewares:
        - redirect-to-https
      entryPoints:
        - http
      service: syncthing
      rule: Host(`sync.example.org`)
    syncthing-https:
      entryPoints:
        - https
      service: syncthing
      rule: Host(`sync.example.org`)
      tls:
        certresolver: letsencrypt
  services:
    syncthing:
      loadBalancer:
        servers:
          -
            url: 'http://host.docker.internal:3003'
```

this assumes you have certs installed or are not behind a dns proxy
if you are you would have to remove the https entries
