### DISCUSSION TITLE
Ability to customize different Preview URL Template for each services in docker compose

### DISCUSSION THREAD

**Discussion by tonkaew131** [coollabsio/coolify#4199] [Feature Requests]
In case of multiple services in single docker compose like this one. Having ability to customize different Preview URL Template would be nice, but work around right now it's manually change domain in each preview deployment

```yaml
services:
    api:
        build:
            dockerfile: ./api/DockerFile
            args:
                - DATABASE_URL=${DATABASE_URL}
        restart: always
    client:
        build:
            dockerfile: ./client/DockerFile
            args:
                - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        restart: always
```

- Customize each domain for each services in normal deploymen ![image](https://github.com/user-attachments/assets/3d6836d7-a6d0-4cd8-b2e4-4cc4f06ef2cf)

- Added ability to customize Preview URL Template in each services ![image](https://github.com/user-attachments/assets/9a606666-4da4-4b67-852d-9bcc12dd4baf)
