### DISCUSSION TITLE
How to give docker container access to my local files?

### DISCUSSION THREAD

**Discussion by Tripolt** [coollabsio/coolify#4297] [Q&A] [answered]
Hi, I am new to hosting stuff on Coolify. I installed the locally hosted instance on my Raspberry Pi and configured the access via Cloudflare tunnels. That works great for applications when I just need to clone a GitHub repo with all the necessary data included. I unfortunately need to deploy a Python script that needs a lot of pictures to work. Of course, I can't push the images to GitHub. How can I define in my Dockerfile.server a specific path on my Raspberry Pi that the container has access to? Should I use volumes? The problem is that I do not know how to correctly configure the local path to the img folder.

This is my Dockerfile.server currently:

```
FROM python:3.10

WORKDIR /app

COPY ./Backend/requirements.txt .

RUN apt-get update && apt-get install -y libgl1-mesa-glx && \
    pip install -r requirements.txt

COPY ./Backend .

EXPOSE 8000

CMD ["python", "server.py"]
```

And my docker-compose.yml:
```
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Backend/Dockerfile.api
    ports:
      - "8001:8000" 
    environment:
      - PORT=8000

  server:
    build:
      context: .
      dockerfile: Backend/Dockerfile.server
    ports:
      - "8002:8000"
    environment:
      - PORT=8000
  nextjs:
    build:
      context: .
      dockerfile: Frontend/Dockerfile.nextjs
    ports:
      - "3000:3000" 
    environment:
      - PORT=3000
```
Only the Dockerfile.server needs the extra folder with images.

I get the error in my logs that it can't find my images. That’s true because they are not pushed on GitHub. Hopefully someone has a bit of experience with this because all tutorials on YouTube show examples where all the data is in the GitHub Repo. Thanks Matteo.
