### DISCUSSION TITLE
Inngest

### DISCUSSION THREAD

**Discussion by dre-on** [coollabsio/coolify#4473] [Service Template Requests]
A new-ish kid on the block, trigger.dev alternative:

https://www.inngest.com/
https://www.inngest.com/docs/self-hosting#how-to-self-host-inngest

**Comment by imaxisXD** [comment]
Bumping up

**Comment by andrewbellucci** [comment]
I wrote up a small docker-compose file to get some basic functionality working:
```
services:
  inngest:
    image: inngest/inngest
    command: 'inngest start'
    ports:
      - '8288:8288'
    environment:
      - 'INNGEST_SQLITE_DIR=/app/data'
      - 'INNGEST_EVENT_KEY=${INNGEST_EVENT_KEY}'
      - 'INNGEST_DEV=0'
    volumes:
      - 'inngest-data:/app/data'
```
<img width="886" alt="Screenshot 2025-01-15 at 5 04 06 PM" src="https://github.com/user-attachments/assets/60b63862-49da-49c4-839d-d7399dfbec32" />

That gives us a basic development server to work with, but I'm pretty sure this is still experimental, considering it isn't behind some sort of password protection and the page reads Inngest Development Server. You could probably hook it up to Cloudflare and setup some basic password or IP protection, but I'd still be iffy about using it for any production use cases until further notice.

**Comment by dre-on** [comment]
@andrewbellucci, @imaxisXD 
I actually made it work way back when, just totally forgot about this ticket.

Here's my version traefik basic auth. Realistically though, the thing looks very raw and it's probably better to just stick with ActivePieces or n8n, or even trigger.dev (but it requires docker registry for prod)
```
services:
  inngest:
    image: inngest/inngest
    environment:
      - SERVICE_FQDN_INNGEST_8288
      - INNGEST_DEV=false
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
    restart: always
    labels:
      - 'traefik.http.middlewares.inngest.basicauth.users=${BASIC_AUTH_USER}:${BASIC_AUTH_PASSWORD}'
    command: 'inngest start'
    volumes:
      - 'inngest_data:/data'
  ```

Closing. I don't think this is worth a PR.
