### DISCUSSION TITLE
Deploying Laravel 11 + InertiaJS(React)

### DISCUSSION THREAD

**Discussion by KwaminaWhyte** [coollabsio/coolify#4533] [General]
I want to deploy Laravel 11 + InertiaJS(React) 
It works fine when I deploy it locally with docker. Deploying it with Coolify, I can access the page for phpmyadmin but the main app shows `404 page not found`.

Please any help?

![image](https://github.com/user-attachments/assets/a38798fe-425b-4d23-ae53-e4dad2086267)

Build Pack: Docker Compose 

This is my docker-compose.yml
```
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp_app
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      BROADCAST_DRIVER: reverb
      BROADCAST_CONNECTION: reverb
      REVERB_APP_ID: ${REVERB_APP_ID}
      REVERB_APP_KEY: ${REVERB_APP_KEY}
      REVERB_APP_SECRET: ${REVERB_APP_SECRET}
      REVERB_HOST: reverb
      REVERB_PORT: ${REVERB_PORT}
      REVERB_SCHEME: ${REVERB_SCHEME}
    volumes:
      - ./:/var/www
      - app_storage:/var/www/storage
    networks:
      - myapp
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp_queue
    restart: unless-stopped
    command: php artisan queue:work
    working_dir: /var/www/
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      BROADCAST_DRIVER: reverb
      BROADCAST_CONNECTION: reverb
      REVERB_APP_ID: ${REVERB_APP_ID}
      REVERB_APP_KEY: ${REVERB_APP_KEY}
      REVERB_APP_SECRET: ${REVERB_APP_SECRET}
      REVERB_HOST: reverb
      REVERB_PORT: ${REVERB_PORT}
      REVERB_SCHEME: ${REVERB_SCHEME}
    volumes:
      - ./:/var/www
      - app_storage:/var/www/storage
    networks:
      - myapp
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp_reverb
    restart: unless-stopped
    command: php artisan reverb:start --port=${REVERB_PORT} --host=0.0.0.0
    working_dir: /var/www/
    ports:
      - "${REVERB_PORT}:${REVERB_PORT}"
    environment:
      BROADCAST_DRIVER: reverb
      BROADCAST_CONNECTION: reverb
      REVERB_APP_ID: ${REVERB_APP_ID}
      REVERB_APP_KEY: ${REVERB_APP_KEY}
      REVERB_APP_SECRET: ${REVERB_APP_SECRET}
      REVERB_HOST: reverb
      REVERB_PORT: ${REVERB_PORT}
      REVERB_SCHEME: ${REVERB_SCHEME}
      VITE_REVERB_APP_ID: ${VITE_REVERB_APP_ID}
      VITE_REVERB_APP_KEY: ${VITE_REVERB_APP_KEY}
      VITE_REVERB_APP_SECRET: ${VITE_REVERB_APP_SECRET}
      VITE_REVERB_HOST: localhost
      VITE_REVERB_PORT: ${VITE_REVERB_PORT}
      VITE_REVERB_SCHEME: ${VITE_REVERB_SCHEME}
    volumes:
      - ./:/var/www
      - app_storage:/var/www/storage
    networks:
      - myapp

  nginx:
    image: nginx:alpine
    container_name: myapp_nginx
    restart: unless-stopped
    ports:
      - "8088:8088"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./docker/ssl:/etc/nginx/ssl/
      - app_storage:/var/www/storage
    networks:
      - myapp

  db:
    image: mysql:8.0
    container_name: myapp_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - myapp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myapp_phpmyadmin
    restart: unless-stopped
    ports:
      - "8089:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - myapp

  redis:
    image: redis:alpine
    container_name: myapp_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data
    networks:
      - myapp

networks:
  myapp:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
  app_storage:
    driver: local
```

My Dockerfile
```
FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Install Node.js and npm
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm@latest

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

# Copy composer files first to leverage Docker cache
COPY composer.json composer.lock ./
RUN composer install --no-scripts --no-autoloader

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy existing application directory contents
COPY . .

# Generate optimized autoload files
RUN composer dump-autoload --optimize

# Build frontend assets
RUN npm run build

# Set permissions for Laravel storage and cache
RUN chmod -R 775 /var/www/storage /var/www/bootstrap/cache && \
    chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]
```
