### DISCUSSION TITLE
How to Route All Subdomains to a Single App in Coolify?

### DISCUSSION THREAD

**Discussion by fischer-c187** [coollabsio/coolify#4644] [Q&A]
Hello,

I have two apps that work together:

app-main: A platform where users can create accounts and personalized dashboards.
app-dashboard: Allows users to access their personalized dashboards, available at dashboard-name.example.com.

Expected behavior:

https://example.com → app-main (port 3000)
https://*.example.com → app-dashboard (port 3001)

Problem:

I can access the dashboard via http://test.example.com:3001, but I would like to access it without specifying the port (e.g., https://test.example.com). When I remove the port from the address, it does not work.

Here are my docker-compose configurations:
**app-main:**
```yaml
services:
  app:
    build:
      context: .
    environment:
      - NODE_ENV=development
      - DB_HOST=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_NAME=main_db
      - LOCAL_DOMAIN=example.com
    networks:
      - shared_network

  postgresql:
    image: postgres:14
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=main_db
    ports:
      - "5432:5432"
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
```
![coolify-app-main](https://github.com/user-attachments/assets/48fbe087-8c22-42b3-be48-59c4129ded6c)

**app-dashboard:**
```yaml
services:
  app:
    build:
      context: .
    environment:
      - NODE_ENV=development
      - DB_HOST=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_NAME=main_db
      - LOCAL_DOMAIN=example.com
    networks:
      - shared_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.dashboard-http.entrypoints=web"
      - "traefik.http.routers.dashboard-http.rule=HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.example.com`)"
      - "traefik.http.routers.dashboard-http.middlewares=redirect-to-https"
      - "traefik.http.routers.dashboard-https.entrypoints=websecure"
      - "traefik.http.routers.dashboard-https.rule=HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.example.com`)"
      - "traefik.http.routers.dashboard-https.tls=true"
      - "traefik.http.routers.dashboard-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.dashboard.loadbalancer.server.port=3001"

networks:
  shared_network:
    driver: bridge

```
![coolify-dashboard](https://github.com/user-attachments/assets/1e8fe9c8-1459-4eae-b1f6-51ae36aba52d)

In the 'domain for app' field, I tried adding 'https://*.example.com' and 'https://example.com/', but neither worked.

Both apps are on the same Docker network and use the same PostgreSQL instance.
How can I configure Traefik and Coolify to properly route all subdomains to app-dashboard in HTTPS?
