### DISCUSSION TITLE
how to use proxy?

### DISCUSSION THREAD

**Discussion by dungsil** [coollabsio/coolify#468] [Q&A]
Hi, can I know how to configure a proxy using traefik?
I wrote it as below referring to the code in this repository, but there is an error in traefik.

` time="2022-06-20T13:05:52Z" level=error msg="Provider connection error cannot fetch configuration data: Get \"http://host.docker.internal:3000/traefik.json\": dial tcp 172.17.0.1:3000: connect: connection refused, retrying in 682.296822ms" providerName=http`

And when I access the failed URL, I see a 404 error.
![image](https://user-images.githubusercontent.com/39783731/174608743-9796b703-0295-41f8-a373-62da354471e1.png)

my docker script:
https://github.com/dungsil/IaC/blob/main/docker-compose.yml
<details>

```yaml
version: '3.8'
networks:
  coolify:
    driver: bridge
services:
  coolify:
    container_name: coolify
    image: coollabsio/coolify
    restart: unless-stopped
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    networks:
      - coolify
    volumes:
      - ".docker-volumes/coolify/db:/app/db"
      - ".docker-volumes/coolify/ssl:/app/ssl"
      - "~/.cert:/etc/letsencrypt"
      - "${DOCKER_HOST_PATH}:/var/run/docker.sock"
    env_file: [.env]
    environment:
      - COOLIFY_IS_ON=docker
      - COOLIFY_WHITE_LABELED=false
      - COOLIFY_AUTO_UPDATE=false
      - COOLIFY_DATABASE_URL=file:/app/db/dev.db
  coolify-redis:
    container_name: coolify-redis
    image: bitnami/redis:6.2
    restart: unless-stopped
    networks:
      - coolify
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    sysctls:
      - "vm.overcommit_memory=1" # Redis 권장 설정
  proxy:
    image: traefik:v2.6
    command:
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=false
      - --providers.docker.exposedbydefault=false
      - --providers.http.endpoint=http://host.docker.internal:3000/traefik.json
      - --providers.http.pollTimeout=5s
      - --log.level=error
    ports:
      - '8080:80'
      - '8443:443'
      - '18080:8080'
    volumes:
      - "${DOCKER_HOST_PATH}:/var/run/docker.sock"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
```

</details>
