### DISCUSSION TITLE
Preview deployments with docker compose: how to connect between containers?

### DISCUSSION THREAD

**Discussion by hydrandt** [coollabsio/coolify#4708] [Q&A]
I have an app that consists of three containers: django backend, mysql database, react frontend. I could deploy it using this docker compose file:

```
services:

  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      ...
    volumes:
      - .:/code
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      target: ...
    volumes:
      - .:/node_app/code
    depends_on:
      - django

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.coolify.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - django
```

This works fine for the "normal deployment". However, I am mostly interested to use the "Preview deployment" functionality. When I manually deploy a pull request now, the docker compose file that is generated changes the container names (`db-pr-295`, `frontend-pr-295` etc.). This breaks the connection to the database, and nginx config, as it relies on the original container names.

What would be the recommended way to go forward here?  What I could think of:

## 1. Use a separately deployed mysql; get rid of the nginx container

- deploy a database instance inside the project
- then use the `Pre Deployment Commands` function to create a new database, using the environment variable that coolify can generate for docker compose projects (`SERVICE_USER_DB` and `SERVICE_PASSWORD_DB` should work?)
- instead of having the nginx reverse proxy, use the "Domains" config space and configure something like this: `https://{{pr_id}}.coolify.project.com:9000/api, https://{{pr_id}}.coolify.project.com:9000/admin, https://{{pr_id}}.coolify.project.com:9000/api, https://{{pr_id}}.coolify.project.com:9000/admin`. ...)
  - Problem: I tried this, but the `/api`, `/admin` etc. get stripped from the path, so the route is wrong; I suppose it should be possible to configure this behavior?

## 2. Use the `COOLIFY_BRANCH` env var to construct other containers name

In django configuration code, and after starting the nginx container using `envsubst`, detect that we are not on the "main" branch, and in that case, construct the hostnames of other containers from the `COOLIFY_BRANCH` env var.

That's quite hacky.

## 3. Some other way?

Is there another preferred way to do this?

For the sake of completeness, this is the nginx config:

```
http {
  upstream django {
    server django:9000; 
  }
  upstream frontend {
    server frontend:80;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://frontend;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ ^/(api|qadmin|validate_token|confirm|static) {
      proxy_pass http://django;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
```
