### DISCUSSION TITLE
Add pre-defined default label to all containers

### DISCUSSION THREAD

**Discussion by devdilson** [coollabsio/coolify#4747] [Feature Requests]
I would like to have a tighter integration with identity providers such as Authentik, which relies on docker compose labels to implement routing and forward auth to containers. 
Coolify would offer the possibility to include user defined labels to all containers by default.
For example, in order to implement traefik forward auth I have to add the following label to all protected containers, otherwise they are publicly available by default:

My dynamic middleware:
```yaml
http:
  middlewares:
    authentik-auth:
      forwardAuth:
        address: 'http://authentik-server-ncoc0ooog0ckwc0gwgoocgs8:9000/outpost.goauthentik.io/auth/traefik'
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-entitlements
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
```
The custom label I would like to apply by all containers by default.
```yaml
    labels:
      - traefik.http.middlewares.authentik-auth@file
```
Forgoting to include this label could create a security problem, as the container would be publicly exposed without the forward auth. 

I couldn't find other way to implement this feature, so I apologize if it already exists.
