### DISCUSSION TITLE
Add support for inngest

### DISCUSSION THREAD

**Discussion by imaxisXD** [coollabsio/coolify#4792] [Feature Requests]
Can coolify add support for inngest,
https://www.inngest.com/docs/self-hosting?ref=github-inngest-readme

**Comment by imaxisXD** [comment]
Bumping, if any developer can pick this up I am ready to co-code with him (I am a frontend guy)

**Comment by ek-kpr** [comment]
One more bump. V1 seems fleshed out. I tried to do it with the docker compose example. But ended up having routing errors and container crashes.

**Comment by OllieJennings** [comment]
This docker compose file should be fine for you, its currently what l run:

```yaml
services:
  inngest:
    image: inngest/inngest
    command: 'inngest start'
    ports:
      - '8288:8288'
      - '8289:8289'
    environment:
      - 'INNGEST_EVENT_KEY=${INNGEST_EVENT_KEY:?}'
      - 'INNGEST_SIGNING_KEY=${INNGEST_SIGNING_KEY:?}'
      - 'INNGEST_POSTGRES_URI=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5555/inngest'
      - 'INNGEST_REDIS_URI=redis://redis:6379'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8288/health'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  postgres:
    image: 'postgres:17'
    command:
      - postgres
      - '-p'
      - '5555'
    environment:
      - POSTGRES_DB=inngest
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
    ports:
      - '5555:5555'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5555'
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: 'redis:7-alpine'
    command: '--save 60 1 --loglevel warning'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  postgres_data: null
  redis_data: null
```
