### DISCUSSION TITLE
I am confused about docker-compose, how can I deploy 3 services with different subdomains and the same build and environment variables?

### DISCUSSION THREAD

**Discussion by isaacfink** [coollabsio/coolify#4829] [Q&A]
Here is a sample `docker-compose.yaml`

```yaml
x-common-variables: &common-env
  GOOGLE_API_KEY: { { environment.GOOGLE_API_KEY } }

services:
  main-site:
    image: ubuntu:20.04
    build:
      context: .
      dockerfile: Dockerfile
      args:
        project: client
    container_name: main-site
    environment:
      <<: *common-env
      SERVICE_FQDN_SITE: https://{{ environment.BASE_URL }}
    ports:
      - "3001:3000"
  admin:
    image: ubuntu:20.04
    build:
      context: .
      dockerfile: Dockerfile
      args:
        project: client
    container_name: admin
    environment:
      <<: *common-env
      SERVICE_FQDN_SITE: https://admin.{{ environment.BASE_URL }}
    ports:
      - "3001:3000"
   ```
   
   Is this enough to build my site? in vscode I am getting errors in the first declaration because it's not a string or boolean, all my variables (couple dozen) are defined in the environment shared variables

my actual `Dockerfile` takes a while to complete so ideally I would like a setup that also reuses the same `Dockerfile` for all deployments in a specific commit
