### DISCUSSION TITLE
New Magic Env Var: Predefined Network Suffix

### DISCUSSION THREAD

**Discussion by bioshazard** [coollabsio/coolify#4960] [Feature Requests]
Coolify has many magic variables to simplify docker compose wiring. I was unable to find any docs on it, but would like to see a variable to auto-handle the "but this will make the internal Docker DNS not work as expected" thing as noted in the docs:

https://coolify.io/docs/knowledge-base/docker/compose#connect-to-predefined-networks

I am thinking something like `${SERVICE_PREDEFINED}` that would default to an empty string and when you enabled predefined networks, it would become `-$PROJECTID` following the guidance linked above. That way coolify-aware compose files could add it inline with the intra-compose services and everything would "just work". eg, I deployed a gitlab runner yesterday:

```
services:
  dind:
    image: 'docker:20-dind'
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ''
    command:
      - '--storage-driver=overlay2'
  runner:
    restart: always
    image: 'registry.gitlab.com/gitlab-org/gitlab-runner:alpine'
    depends_on:
      - dind
    environment:
      - 'DOCKER_HOST=tcp://dind${SERVICE_PREDEFINED}:2375'
    volumes:
      - 'gitlab-runner-config:/etc/gitlab-runner:z'
```

Is this already feasible? Anyone interested if I attempt to contribute such a feature?
