### DISCUSSION TITLE
Valkey

### DISCUSSION THREAD

**Discussion by Huluti** [coollabsio/coolify#5086] [Database Requests]
Hello!
Do you think that it would be possible to have Valkey integration in addition of Redis.
Valkey is the Linux Foundation's Redis fork 
👉 https://valkey.io

Thanks in advance!

**Comment by Velorian666** [comment]
This should happen now that redis changed their license especially.

**Comment by michalzarddev** [comment]
Any update on this ?

**Comment by ardasugur** [comment]
``` 
documentation: https://hub.docker.com/r/valkey/valkey
slogan: A high-performance data structure server for key/value workloads.
tags: [cache, database, key-value]
logo: svgs/valkey.svg
port: 6379

version: '3.8'

services:
  valkey:
    image: valkey/valkey:latest
    volumes:
      - './data:/data'
    command: ["valkey-server", "--requirepass", "${SERVICE_PASSWORD_VALKEY}"]
    environment:
      - VALKEY_PASSWORD=${SERVICE_PASSWORD_VALKEY}
    expose:
      - "6379" 
```
I've drafted a service template for Valkey to be submitted as a pull request. I used the official `valkey/valkey` image, but I'm a bit uncertain about the environment variables, specifically the user/password configuration.

While the `command` uses `--requirepass`, I couldn't find an official `VALKEY_PASSWORD` environment variable in the documentation to set it. 
I also considered using a `valkey.conf` file, but for a simple service template, I wanted to prioritize using environment variables if possible.
My goal was to make this template useful for anyone familiar with managing Valkey, so I'm sharing it here for feedback.

Any insights on the correct way to handle the user/password side would be greatly appreciated!

**Reply by michalzarddev** [reply]
@ardasugur  I believe you should include `SERVICE_FQDN_VALKEY_6379` env variable & i believe its required to include healthcheck aswell for example : 

```yaml
healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6379' || exit 1"]
      interval: 5s
      timeout: 20s
      retries: 3 
```
i'd say you should make the volumes be like : './valkey-data:/data' rather than generic data just in case
