### DISCUSSION TITLE
SERVICE_FQDN and docker-compose build

### DISCUSSION THREAD

**Discussion by Kworz** [coollabsio/coolify#5193] [Q&A] [answered]
Hey everyone,

I'm trying to deploy a docker-compose app, but my react-app built by vite must have the backend FQDN at build-time.
For now i'm passing the SERVICE_FQDN_API via a build-arg like this:

docker-compose.yaml
```yaml
name: alc-coolify

services:
  front:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile.coolify
      args:
        - PACKAGE_TOKEN=${GITLAB_TOKEN}
        - VITE_APP_API_URL=${SERVICE_FQDN_API}
      
  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile.coolify
      args:
        - PACKAGE_TOKEN=${GITLAB_TOKEN}
    environment: 
      - NODE_ENV=coolify
```

Dockerfile.coolify (front)
```dockerfile
# Base image used by both production and builder
FROM node:22-alpine AS builder

ARG PACKAGE_TOKEN

ARG VITE_APP_API_URL
ENV VITE_APP_API_URL=${VITE_APP_API_URL}

RUN corepack enable
RUN corepack prepare pnpm@9.13.0 --activate

WORKDIR /app

COPY . .

RUN pnpm config set inject-workspace-packages true
RUN pnpm config set link-workspace-packages false

RUN pnpm i
RUN pnpm build:libs
RUN pnpm --filter "./packages/frontend" build

# Production final image

FROM nginx:1.23.3-alpine

COPY ./packages/frontend/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/packages/frontend/build /usr/share/nginx/html
```

For now the VITE_APP_API_URL is always empty, but the PACKAGE_TOKEN is not empty.

The documentation is not clear, and when looking trough the source code i wasn't able to find wether the SERVICE_FQDN_* variables are available at build time or after when the docker-compose images have been built.

The environnement variables always come with the SERVICE_FQDN grayed out and blank i suppose its meant to work this way tho.

<img width="1504" alt="Capture d’écran 2025-02-20 à 23 14 26" src="https://github.com/user-attachments/assets/ccf16e1b-eee0-410d-8ec2-4610f18ba118" />

If anyone has the answer it would be hugely appreciated 😜

many thanks
