### DISCUSSION TITLE
Cant access InfluxDB via domain (and/or public ip/port)

### DISCUSSION THREAD

**Discussion by gltched-usr** [coollabsio/coolify#5321] [Q&A]
I'm trying to deploy influxdb on coolify using this docker compose file:
```yml
services:
  influxdb:
    image: 'influxdb:2'
    volumes:
      - 'influxdb_data:/var/lib/influxdb2'
      - 'influxdb_config:/etc/influxdb2'
```

On influxdb I set the influxdb port (8086) under public port and checked "Make it public availible".  When I access <my ip>:8086 it says server not found. Also when I checked if port 8060 is open on my server it says port is closed.

<img width="761" alt="Screenshot 2025-03-11 at 15 26 35" src="https://github.com/user-attachments/assets/f87694ab-d1ef-434b-b96e-c78c3d1b88bc" />

On other services I get the option to set a domain which I somehow dont get here.
