### DISCUSSION TITLE
Service Question: LibreTranslate – Enable API Key Only

### DISCUSSION THREAD

**Discussion by cannap** [coollabsio/coolify#5345] [General]
Hey, today I tried to use the service: LibreTranslate ,but I can't figure out how to enable API key-only mode.
And also is there a way to disable the Frontend so i have api only use?

```
services:
  libretranslate:
    image: 'libretranslate/libretranslate:latest'
    environment:
      - SERVICE_FQDN_LIBRETRANSLATE_5000
      - 'LT_SSL=${LT_SSL:-true}'
      - 'LT_UPDATE_MODELS=${LT_UPDATE_MODELS:-true}'
      - 'LT_LOAD_ONLY=${LT_LOAD_ONLY:-en,es,fr,de,ja}'
      - 'LT_API_KEYS=${LT_API_KEYS:-true}'
      - 'LT_LOAD_ONLY=${LT_LOAD_ONLY:-true}'
    volumes:
      - 'libretranslate-api-keys:/app/db'
      - 'libretranslate-models:/home/libretranslate/.local'
    healthcheck:
      test:
        - CMD-SHELL
        - './venv/bin/python scripts/healthcheck.py'
```
![image](https://github.com/user-attachments/assets/ba505ca1-20ba-461c-a84b-6f31a42084ad)

thanks coolify is awesome!

**Comment by djsisson** [comment]
@cannap 

LT_REQUIRE_API_KEY_ORIGIN , this sets any requests from the given domain in this env to not require an api key

to force api keys i think you need to set the following env

LT_REQ_LIMIT=0 this means an api key will be required which has its own request limit

LT_DISABLE_WEB_UI=true this is to disable web ui

please note these need to be set in the compose, not in the env tab

this is for settings...
https://github.com/LibreTranslate/LibreTranslate?tab=readme-ov-file#settings--flags

this is for creating api keys
https://github.com/LibreTranslate/LibreTranslate?tab=readme-ov-file#manage-api-keys

**Reply by cannap** [reply]
hey thanks like this ??


```
services:
  libretranslate:
    image: 'libretranslate/libretranslate:latest'
    environment:
      - SERVICE_FQDN_LIBRETRANSLATE_5000
      - 'LT_SSL=${LT_SSL:-true}'
      - 'LT_UPDATE_MODELS=${LT_UPDATE_MODELS:-true}'
      - 'LT_LOAD_ONLY=${LT_LOAD_ONLY:-en,es,fr,de,ja}'
      - 'LT_REQ_LIMIT=${LT_REQ_LIMIT:0}'
      - 'LT_DISABLE_WEB_UI=${LT_DISABLE_WEB_UI:true}'
    volumes:
      - 'libretranslate-api-keys:/app/db'
      - 'libretranslate-models:/home/libretranslate/.local'
    healthcheck:
      test:
        - CMD-SHELL
        - './venv/bin/python scripts/healthcheck.py'
```

update:

```
services:
  libretranslate:
    image: 'libretranslate/libretranslate:latest'
    environment:
      - SERVICE_FQDN_LIBRETRANSLATE_5000
      - 'LT_SSL=${LT_SSL:-true}'
      - 'LT_UPDATE_MODELS=${LT_UPDATE_MODELS:-true}'
      - 'LT_LOAD_ONLY=${LT_LOAD_ONLY:-en,es,fr,de,ja}'
      - 'LT_REQ_LIMIT=0'
      - 'LT_DISABLE_WEB_UI=true'
    volumes:
      - 'libretranslate-api-keys:/app/db'
      - 'libretranslate-models:/home/libretranslate/.local'
    healthcheck:
      test:
        - CMD-SHELL
        - './venv/bin/python scripts/healthcheck.py'

```
