### DISCUSSION TITLE
Why domain name for each service is checked via isDatabaseImage() method

### DISCUSSION THREAD

**Discussion by shashank-sharma** [coollabsio/coolify#5370] [Q&A] [answered]
I have a use case, where I want to specify a domain with ports so that it gets forward correctly to the container. Now I observed that for some of my custom resources, I can set this domain perfectly fine, but for minio, it doesn't show the input.

After digging up a bit, I found that it first checks whether the image exists in database or not
https://github.com/coollabsio/coolify/blob/main/resources/views/livewire/project/application/general.blade.php#L49

And there are lists of images where this thing is disabled
https://github.com/coollabsio/coolify/blob/main/bootstrap/helpers/constants.php#L20

I am curious to know why this decision was made? Is there a workaround, where I can achieve the same result of specifying the domain with port?

My use case: I am trying to forward the requests from one trafik proxy to another traefik proxy which later resolves it to the container running, reason being I have one static ip for multiple machines running, which I initialized using Coolify, hence multiple traefik proxy.

**Comment by djsisson** [comment, marked as answer]
@shashank-sharma those images listed do not have an internal http server running, so that's why it hides adding a domain, as there would be nothing to point to.

regarding your forwarding, you can just add a dynamic file to your first proxy to forward to the second proxy. specifying the ip:port of the second proxy, for minio you should see the url's on the right hand side where it shows the password etc.

**Reply by shashank-sharma** [reply]
@djsisson That makes sense, I think I confused myself assuming minio was present under `DATABASE_DOCKER_IMAGES` constant, I mean for some reason domain input was hiding so i assumed that might be the case

I tried doing forwarding the request like:

```
http:
  middlewares:
    redirect-to-https:
      redirectscheme:
        scheme: https
    gzip:
      compress: true
    set-forwarded-proto:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
        sslRedirect: false
        sslTemporaryRedirect: false
        sslProxyHeaders:
          X-Forwarded-Proto: https
  routers:
    minio-https:
      rule: Host(`minio.abc.xyz`)
      service: rp1-https
      middlewares:
        - set-forwarded-proto
        - gzip
      tls:
        certResolver: letsencrypt
    minio-api-https:
      rule: Host(`minio-api.abc.xyz`)
      service: rp1-https
      middlewares:
        - set-forwarded-proto
        - gzip
      tls:
        certResolver: letsencrypt
  services:
    rp1-https:
      loadBalancer:
        servers:
          -
            url: 'http://192.168.1.20:80'
```

But for some reason, it goes into recursive redirect when i try to access via https. I tried doing same thing for other services where I have defined domain like `sub.abc.com:8000` and these are working fine. 

`set-forwarded-proto` was my wild attempt to try debugging and see if it solves the issue
