### DISCUSSION TITLE
Allow fastcgi backends for caddy

### DISCUSSION THREAD

**Discussion by dpacmittal** [coollabsio/coolify#5438] [Feature Requests]
I have a wordpress website with following compose file:
``` yaml
  services:
  wordpress:
    image: 'chialab/php:8.4-fpm'
    volumes:
      - '/home/dpac/websites/xyz.com:/var/www/html'
    environment:
      - SERVICE_FQDN_WORDPRESS
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_NAME
      - WP_HOME
```

The service listens on port 9000 using the fastcgi protocol. Right now this doesn't work as caddy is trying to use the http protocol to talk to php-fpm. Can we make this work so there's no need for apache/nginx in the middle?
