### DISCUSSION TITLE
Easy deployment of coolify with docker compose

### DISCUSSION THREAD

**Discussion by akarray** [coollabsio/coolify#5543] [Improvement Requests]
I'm looking for an easy deployment of coolify with docker compose with one command. I coolify container 
I see this problem in log : Unable To Create Directory.php line 18: Unable to create a directory at /var/www/html/storage/app/ssh/keys. Could not setup dynamic configuration: Call to a member function setupDynamicProxyConfiguration() on null  To avoid all problem 

Please note that I'm launching the yml with a root user and I configured traefik in another docker compose file. 
Any one have tried to run coolify like me ?  
This is my current project : 
```
networks:
  traefik:
    external: true
  coolify:
        name: coolify
        driver: bridge
        external: false

# description: An open-source & self-hostable Heroku / Netlify / Vercel alternative.
# https://coolify.io/

services:
  coolify:
    image: ${COOLIFY_REGISTRY_URL:-ghcr.io}/coollabsio/coolify:${COOLIFY_DOCKER_TAG:-latest}
    container_name: ${COOLIFY_CONTAINER_NAME:-coolify}
    restart: ${COOLIFY_RESTART:-unless-stopped}
    working_dir: /var/www/html
    extra_hosts:
        - host.docker.internal:host-gateway
    networks:
      - traefik
      - coolify
    volumes:
      - ./etc/coolify/data/ssh:/var/www/html/storage/app/ssh
      - ./etc/coolify/data/applications:/var/www/html/storage/app/applications
      - ./etc/coolify/data/databases:/var/www/html/storage/app/databases
      - ./etc/coolify/data/services:/var/www/html/storage/app/services
      - ./etc/coolify/data/backups:/var/www/html/storage/app/backups
      - ./etc/coolify/data/webhooks-during-maintenance:/var/www/html/storage/app/webhooks-during-maintenance
      - /etc/localtime:/etc/localtime:ro
    environment:
      - APP_ENV=${COOLIFY_APP_ENV:-production}
      - PHP_MEMORY_LIMIT=${COOLIFY_PHP_MEMORY_LIMIT:-256M}
      - PHP_FPM_PM_CONTROL=${COOLIFY_PHP_FPM_PM_CONTROL:-dynamic}
      - PHP_FPM_PM_START_SERVERS=${COOLIFY_PHP_FPM_PM_START_SERVERS:-1}
      - PHP_FPM_PM_MIN_SPARE_SERVERS=${COOLIFY_PHP_FPM_PM_MIN_SPARE_SERVERS:-1}
      - PHP_FPM_PM_MAX_SPARE_SERVERS=${COOLIFY_PHP_FPM_PM_MAX_SPARE_SERVERS:-10}
      - DB_HOST=postgres
      - DB_USERNAME=${COOLIFY_DB_USERNAME}
      - DB_PASSWORD=${COOLIFY_DB_PASSWORD}
      - DB_DATABASE=${COOLIFY_DB_DATABASE:-coolify}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${COOLIFY_REDIS_PASSWORD}
      - TZ=${TZ}
    #ports:
    #  - "${APP_PORT:-8088}:8080"
    #expose:
    #  - "${APP_PORT:-8088}"

    healthcheck:
      test: curl --fail http://127.0.0.1:8080/api/health || exit 1
      interval: 5s
      retries: 10
      timeout: 2s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      soketi:
        condition: service_healthy
    labels:
      - traefik.enable=${COOLIFY_TRAEFIK_ENABLED:-true}
      - traefik.http.routers.coolify.entrypoints=websecure
      - traefik.http.routers.coolify.rule=Host(`${COOLIFY_HOST_NAME:-coolify}.${HOST_DOMAIN}`)
      #- traefik.http.services.coolify.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.coolify.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=${COOLIFY_WATCHTOWER_ENABLED:-true}
      - autoheal=${COOLIFY_AUTOHEAL_ENABLED:-true}

  postgres:
    image: postgres:15-alpine
    container_name: coolify-db
    volumes:
      - ./etc/coolify/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${COOLIFY_DB_USERNAME}"
      POSTGRES_PASSWORD: "${COOLIFY_DB_PASSWORD}"
      POSTGRES_DB: "${COOLIFY_DB_DATABASE:-coolify}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${COOLIFY_DB_USERNAME}", "-d", "${COOLIFY_DB_DATABASE:-coolify}" ]
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - coolify

  redis:
    image: redis:7-alpine
    container_name: coolify-redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${COOLIFY_REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: "${COOLIFY_REDIS_PASSWORD}"
    volumes:
      - ./etc/coolify/redis/data:/data
    healthcheck:
      test: redis-cli ping
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - coolify

  soketi:
    image: '${REGISTRY_URL:-ghcr.io}/coollabsio/coolify-realtime:1.0.6'
    container_name: coolify-realtime
    extra_hosts:
            - host.docker.internal:host-gateway
    ports:
      - "${COOLIFY_SOKETI_PORT:-6001}:6001"
      - "6002:6002"
    volumes:
      - ./etc/coolify/data/ssh:/var/www/html/storage/app/ssh
    environment:
      APP_NAME: "${COOLIFY_APP_NAME:-Coolify}"
      SOKETI_DEBUG: "${COOLIFY_SOKETI_DEBUG:-false}"
      SOKETI_DEFAULT_APP_ID: "${COOLIFY_PUSHER_APP_ID}"
      SOKETI_DEFAULT_APP_KEY: "${COOLIFY_PUSHER_APP_KEY}"
      SOKETI_DEFAULT_APP_SECRET: "${COOLIFY_PUSHER_APP_SECRET}"
      REDIS_HOST: redis
      REDIS_PASSWORD: ${COOLIFY_REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:6001/ready && wget -qO- http://127.0.0.1:6002/ready || exit 1" ]
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - coolify
```
