### DISCUSSION TITLE
Is there an equivalent of the Vercel "Include files outside the root directory in the build step" ?

### DISCUSSION THREAD

**Discussion by Toukassay** [coollabsio/coolify#5656] [Q&A] [answered]
I have a monorepo app (frontend/backend) which looks like this:
```
/client
/server
/shared
```
On Vercel I can deploy it by setting "client" as base dir + toggle this switch
![image](https://github.com/user-attachments/assets/25a707b9-01a5-4754-8988-c4bcdd2e593b)

Does Coolify have the same concept? Because currently I have some issue telling that @shared is not recognize whereas it is when builing localy.

**Comment by Toukassay** [comment, marked as answer]
I've answered myself, by using Docker compose (thanks ChatGPT...)

`client/docker-compose.yaml`
```
services:
  client:
    build:
      context: ../
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
```
`client/Dockerfile`
```
FROM node:23-slim AS builder

WORKDIR /app

COPY shared ./shared
COPY client ./client

WORKDIR /app/client

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/client/dist /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
```
`On coolify`
![image](https://github.com/user-attachments/assets/1ae0d492-eb97-4403-b62a-053917568f2a)
![image](https://github.com/user-attachments/assets/825105a8-33c6-4318-bb0f-ede476a945c4)
