### DISCUSSION TITLE
Plausible upgrade

### DISCUSSION THREAD

**Discussion by saeedesmaili** [coollabsio/coolify#5677] [Q&A]
I have previously deployed plausible community edition v2.1.1 on my coolify instance. I see that the [template is updated to latest v.3.0.1](https://github.com/coollabsio/coolify/commit/151b4b69d21491fec21a4c6388ab8a70a08c2593), but there are many additions and removals in the docker compose file in the commit. Can someone kindly guide what's the best way to upgrade an existing plausible instance? Should I just repeat the changes in the commit verbatim? 

My current docker compose is:
```yaml
services:
  plausible:
    image: 'ghcr.io/plausible/community-edition:v2.1.1'
    command: 'sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"'
    environment:
      - 'DATABASE_URL=postgres://postgres:$SERVICE_PASSWORD_POSTGRES@plausible_db/plausible'
      - BASE_URL=$SERVICE_FQDN_PLAUSIBLE
      - SECRET_KEY_BASE=$SERVICE_BASE64_64_PLAUSIBLE
      - TOTP_VAULT_KEY=$SERVICE_REALBASE64_TOTP
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - DISABLE_REGISTRATION=$DISABLE_REGISTRATION
      - MAILER_ADAPTER=$MAILER_ADAPTER
      - MAILER_NAME=$MAILER_NAME
      - MAILER_EMAIL=$MAILER_EMAIL
      - SMTP_HOST_ADDR=$SMTP_HOST_ADDR
      - SMTP_HOST_PORT=$SMTP_HOST_PORT
      - SMTP_USER_NAME=$SMTP_USER_NAME
      - SMTP_USER_PWD=$SMTP_USER_PWD
      - SMTP_HOST_SSL_ENABLED=$SMTP_HOST_SSL_ENABLED
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
  mail:
    image: bytemark/smtp
  plausible_db:
    image: 'postgres:14-alpine'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=plausible
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
  plausible_events_db:
    image: 'clickhouse/clickhouse-server:24.3.3.102-alpine'
    volumes:
      -
        type: volume
        source: event-data
        target: /var/lib/clickhouse
      -
        type: bind
        source: ./clickhouse/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/logging.xml
        read_only: true
      -
        type: bind
        source: ./clickhouse/clickhouse-user-config.xml
        target: /etc/clickhouse-server/users.d/logging.xml
        read_only: true
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
```
