### DISCUSSION TITLE
Add Service: Akaunting

### DISCUSSION THREAD

**Discussion by simplerethink** [coollabsio/coolify#5736] [Service Template Requests]
Please add Akaunting as a service.

[Official Website](https://akaunting.com/)
[Installation Docs](https://akaunting.com/hc/docs/on-premise/installation/)
[Github Docker](https://github.com/akaunting/docker)
[Docker Image](https://hub.docker.com/r/akaunting/akaunting)

**Comment by yipfram** [comment]
I did this for now, but i don't have the time to finish it right now..

Feel free :

```
# documentation: https://github.com/akaunting/docker
# slogan: Akaunting is a free, open-source, self-hosted accounting software that helps you manage your finances.
# tags: lowcode, nocode, ai, llm, openai, anthropic, machine-learning, rag, agents, chatbot, api, team, bot
# logo: svgs/akaunting.svg
# port: 8080

services:

  akaunting:
    container_name: akaunting
    image: docker.io/akaunting/akaunting:latest
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      - akaunting-data:/var/www/html
    restart: unless-stopped
    environment:
      - AKAUNTING_SETUP
      - SERVICE_FQDN_AKAUNTING_8080
      - APP_URL=${SERVICE_FQDN_AKAUNTING}
      - DB_HOST=${DB_HOST:-akaunting-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-akaunting}
      - DB_USERNAME=${DB_USERNAME:-admin}
      - DB_PASSWORD=${SERVICE_PASSWORD_DBAKAUNTING}
      - DB_PREFIX=${DB_PREFIX:-asd_}
      - COMPANY_NAME=${COMPANY_NAME:-My Company}
      - COMPANY_EMAIL=${COMPANY_EMAIL:-my@company.com}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-me@company.com}
      - ADMIN_PASSWORD=${SERVICE_PASSWORD_AKAUNTING}
      - LOCALE=${LOCALE:-en-US}

    depends_on:
      - akaunting-db

  akaunting-db:
    container_name: akaunting-db
    image: mariadb
    volumes:
      - akaunting-db:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_NAME:-akaunting}
      - MYSQL_USER=${DB_USERNAME:-admin}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_DBAKAUNTING}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD:-yes}
volumes:
  akaunting-data:
  akaunting-db:
```


Tried to deploy it but got:

```
 akaunting Pulled 
Creating Docker network.
ec307146aa57a79110b16125f3685fd9053357e76d743c98fdc137bf1a68d63e
Starting service.
#0 building with "default" instance using docker driver

#1 [akaunting internal] load build definition from Dockerfile
#1 transferring dockerfile: 2B done
#1 DONE 0.0s
failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
```
