### DISCUSSION TITLE
Use distinguishable (human-readable) bridge interface name instead of br-7da...

### DISCUSSION THREAD

**Discussion by Talkless** [coollabsio/coolify#5893] [Feature Requests]
Hi,

Currently in my installation (Debian 12 host) Docker has created bridge interface with name `br-7da043d4db4d`.

Zone-based firewall managers like `firewalld`, `Shorewall`, `foomuuri`, etc., needs to specify interface names to map it into the zone, and having `br-7da043d4db4d` specified there is kinda not really self-explanatory, nor "stable". I guess reinstalling Coolify or doing other changes might change that generated name?

Apparently, docker supports setting custom interface name, so `docker-componse.yaml` could looke something like this (NOT actually tested):
```
networks:
    coolify:
        name: coolify
        driver: bridge
        external: false
        networks:
        driver_opts:
            com.docker.network.bridge.name: br-coolify
```

See: https://docs.docker.com/engine/network/drivers/bridge/#options
See: https://docs.docker.com/reference/compose-file/networks/#driver_opts

**Comment by djsisson** [comment]
i think this is one of those things which is so niche, to specific users it probably won't get altered, however there is an option to set this 

create this file
```/data/coolify/source/docker-compose.custom.yml```
contents:
```yaml
networks:
    coolify:
        driver_opts:
            com.docker.network.bridge.name: br-coolify
```

this would get merged with the compose when installing/upgrading, meaning you are free to choose what you want here

**Comment by Talkless** [comment]
Cool, didn't new there was `custom.yml`!

But it has no effect after install.sh ("upgrade"), maybe it would have effect only during first install..?

```
root@vcoolify:/data/coolify/source# head -n1 upgrade-2025-05-27-14-59-27.log 
docker-compose.custom.yml detected.
```

```
root@vcoolify:/data/coolify/source# cat docker-compose.custom.yml 
networks:
  coolify:
    driver_opts:
      com.docker.network.bridge.name: br-coolify
```

```
root@vcoolify:/data/coolify/source# ip link | fgrep -e ": br-coolify" -e ": br-"
4: br-7da043d4db4d: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
```
```
