### DISCUSSION TITLE
Adding Coolify to existing VPS with Nginx and Docker Compose

### DISCUSSION THREAD

**Discussion by SadmanYasar** [coollabsio/coolify#5918] [Q&A]
I have a VPS with Nginx and SSL certificates setup as well as docker containers running with docker compose. Currently I set up a CICD pipeline that uses some shell scripts to pull image and start containers. But everything is in terminal and I was wondering if Coolify can be added in this VPS while all the configs of Nginx and the docker containers are kept. I have a PostGIS database, Redis, Directus, and a Nextjs application, all as docker containers. TIA.

The docker compose in Directus:
```yml
version: "3"
services:
  database:
    image: postgis/postgis:13-master
    restart: unless-stopped
    ports:
      - 2345:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
    env_file:
      - __env__/database.env

  cache:
    image: redis:6
    restart: unless-stopped

  directus:
    build: .
    restart: unless-stopped
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    env_file:
      - __env__/directus.env
```

Directus Dockerfile:
```DOCKERFILE
FROM directus/directus:11.5.1
USER root
RUN corepack enable \
  && corepack prepare pnpm@8.15 --activate \
  # Currently required, we'll probably address this in the base image in future release
  && chown node:node /directus

USER node
RUN pnpm install directus-extension-vgrid-interface directus-extension-sync directus-extension-image-annotator@latest directus-extension-field-actions directus-extension-brand-sku directus-extension-quantity-table @directus-labs/resend-operation
```

Dockerfile for Nextjs app is same as the [Official Example](https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/next-app/prod.Dockerfile)
