### DISCUSSION TITLE
[Bug]: Issue Deploying dify.yaml on Coolify v4.0.0-beta.389

### DISCUSSION THREAD

**Discussion by jorgeortizfuentes** [coollabsio/coolify#6036] [Q&A]
### Error Message and Logs

When deploying dify.yaml by copying and pasting the file in New Project > Docker Compose Empty on Coolify v4.0.0-beta.389, the Dify website only partially loads.

Upon inspecting the browser console, the following errors are observed:

```
Failed to load resource: the server responded with a status of 404 ()
hook.js:608 Response
overrideMethod @ hook.js:608
apps:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
console/api/setup:1 

Failed to load resource: the server responded with a status of 404 ()
install:1 Uncaught (in promise) Response
install:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

I am leaving all the default variables without modifying anything.

### Steps to Reproduce

	1.	Navigate to New Project > Docker Compose Empty in Coolify.
	2.	Copy and paste the contents of dify.yaml.
	3.	Deploy the project.
	4.	Open the Dify website in the browser and inspect the console for errors.

### Coolify Version

v4.0.0-beta.389

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

### Additional Information

Expected Behavior:
The Dify website should load fully without any console errors.

Actual Behavior:
The website partially loads, and several 404 errors and JSON parsing issues appear in the console.

**Comment by ebertti** [comment]
I found a fix that worked for me!

In the  web service section, change it to:

```yaml
  web:
    image: 'langgenius/dify-web:latest'
    environment:
      - SERVICE_FQDN_WEB_3000
      - 'CONSOLE_API_URL=${CONSOLE_API_URL}'
      - 'APP_API_URL=${SERVICE_API_URL}'
      - 'SENTRY_DSN=${WEB_SENTRY_DSN:-}'
      - 'NEXT_TELEMETRY_DISABLED=${NEXT_TELEMETRY_DISABLED:-0}'
```

Hope this helps!
