### DISCUSSION TITLE
Docker compose setting environment variables

### DISCUSSION THREAD

**Discussion by ghost** [coollabsio/coolify#877] [General]
The variables I set like so in the compose file I provide:

```
services:

  pg:
    container_name:postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    ports:
      - 5432
    volumes:
      - ./scripts/db-seed.sql:/docker-entrypoint-initdb.d/db-seed.sql
      - db_data:/var/lib/postgresql/data
```

They are undefined when the app is deployed so errors are thrown. Is there a way to set them from the compose file or an .env file?

**Comment by Lukas-Sachse** [comment]
I tried different ways for some hours and this is my understanding and workaround.

In my case, with `Coolify v3.12.28` and a build-step inside one of 3 services:
Coolify don't use anything defined inside  `environment:`, instead it only uses variables defined inside the `Coolify-Secrets`.


### Workaround for Coolify:

1. I removed the `environment:` part completely

```yaml
services:

  pg:
    container_name:postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432
    volumes:
      - ./scripts/db-seed.sql:/docker-entrypoint-initdb.d/db-seed.sql
      - db_data:/var/lib/postgresql/data
```

2. I defined all my variables inside a `.env` file
```text
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=postgres
POSTGRES_PORT=5432
```
3. I copied the whole text and use the `Add Secrets in Batch`-option inside Coolify-Secrets

:arrow_right:  Now it's working inside Coolify




### Workaround for Development:
4. I created a separate `docker-compose-dev.yaml`
5. I am using `env_file: .env` instead of `environment:`

```yaml
services:

  pg:
    container_name:postgres
    image: postgres:15-alpine
    restart: always
    env_file: .env
    ports:
      - 5432
    volumes:
      - ./scripts/db-seed.sql:/docker-entrypoint-initdb.d/db-seed.sql
      - db_data:/var/lib/postgresql/data
```
:arrow_right:  Now it's working in my local development with "standard-docker"
