### ISSUE TITLE
[Feature]: Please allow us to add this env in bitnami/mongodb for Replica set

### ISSUE THREAD

**Issue by masterbater** [coollabsio/coolify#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I have this docker compose, but was thinking if you could add support to add this enviroment variables in Configuration Database

    MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
    MONGODB_REPLICA_SET_MODE=primary
    MONGODB_REPLICA_SET_KEY=replicasetkey123

This env are useful for one replica set sufficient enough to use with prisma

```
version: '3.6'
services:
  database:
    image: 'bitnami/mongodb:latest'
    restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=anyuser
      - MONGODB_ROOT_PASSWORD=anypassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - '27017:27017'
volumes:
  # postgres-db:
  mongo-db:
```
  

### Why should this be worked on?

Prisma is getting popular and mongodb always recommend to use Replica Set for ACID Transaction for production
