### ISSUE TITLE
[Bug]: Services: Docker Networks not created correctly

### ISSUE THREAD

**Issue by zewas-digital** [coollabsio/coolify#1386]
### Description

I am trying to create a Service with a network with a custom subnet. Therefore I define the subnet like this:
```
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```
But somehow the configuration doesn't apply to the created network. If I execute `docker network inspect` I get the subnet 172.28.0.0/16.

Another problem is that it isn't possible to assign static IP addresses to containers with docker compose. If I configure my network in my service like that:
```
networks:
  default:
    ipv4_address: 192.168.203.254
```
and then deploy I get the error message `parsing /data/coolify/services/xxxxxx/docker-compose.yml: Non-string key in services.xxxxxx.networks: 0`

### Minimal Reproduction (if possible, example repository)

Just create a Service with the following configuration:
```
services:
  test:
    image: hello-world:latest
    networks:
      default:
        ipv4_address: 192.168.203.254

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```

### Exception or Error

parsing /data/coolify/services/xxxxxx/docker-compose.yml: Non-string key in services.xxxxxx.networks: 0

### Version

v4.0.0-beta.108
