### ISSUE TITLE
[Bug]: Wildcard domain SSL certificate generation feels broken

### ISSUE THREAD

**Issue by samgozman** [coollabsio/coolify#1590]
### Description

First of all - thank you for this project! I have been looking for something like this for years and finally found it thanks to you.

What I'm trying to do is to use wildcard domains for my apps with one SSL certificate for all. I have been following instructions in your docs https://coolify.io/docs/wildcard-certificates

So far, domains work but SSL certificate/s are not generated for the apps. Only for the Coolify admin panel URL SSL is generated.

Coolify address is https://host.example.com, my app domains are (expected) to be https://*.host.example.com.

Maybe I am missing something or is there a way to force the SSL regeneration job?

🎄  P.S. Happy holidays! 

### Minimal Reproduction (if possible, example repository)

1. Install Coolify and apps on the Hetzner server
2. Add A records in Namecheap for Coolify address and wildcard <img width="1144" alt="Screenshot 2023-12-30 at 18 01 51" src="https://github.com/coollabsio/coolify/assets/3392560/98eba411-db88-4f30-b7db-5ab029da047d">
3. Set Traefik config: 
  ```yaml
  version: '3.8'
  networks:
    coolify:
      external: true
  services:
    traefik:
      container_name: coolify-proxy
      image: 'traefik:v2.10'
      restart: unless-stopped
      environment:
        - HETZNER_API_KEY=<MY_HETZNER_API_KEY>
      extra_hosts:
        - 'host.docker.internal:host-gateway'
      networks:
        - coolify
      ports:
        - '80:80'
        - '443:443'
        - '8080:8080'
      healthcheck:
        test: 'wget -qO- http://localhost:80/ping || exit 1'
        interval: 4s
        timeout: 2s
        retries: 5
      volumes:
        - '/var/run/docker.sock:/var/run/docker.sock:ro'
        - '/data/coolify/proxy:/traefik'
      command:
        - '--ping=true'
        - '--ping.entrypoint=http'
        - '--api.dashboard=true'
        - '--api.insecure=false'
        - '--entrypoints.http.address=:80'
        - '--entrypoints.https.address=:443'
        - '--entrypoints.http.http.encodequerysemicolons=true'
        - '--entrypoints.https.http.encodequerysemicolons=true'
        - '--providers.docker.exposedbydefault=false'
        - '--providers.file.directory=/traefik/dynamic/'
        - '--providers.file.watch=true'
        - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
        - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
        - '--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=hetzner'
        - '--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0'
        - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
        - '--providers.docker=true'
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.entrypoints=http
        - traefik.http.routers.traefik.middlewares=traefik-basic-auth@file
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.tls.certresolver=letsencrypt
        - traefik.http.routers.traefik.tls.domains[0].main=host.example.com
        - traefik.http.routers.traefik.tls.domains[0].sans=*.host.example.com
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        - traefik.http.middlewares.gzip.compress=true
  ```
 4. Generate domain for the app and redeploy <img width="1211" alt="Screenshot 2023-12-30 at 18 38 03" src="https://github.com/coollabsio/coolify/assets/3392560/a1502696-25e1-46ab-bd96-d9005df9ea41">
 5. Try to send request to this domain over HTTPS and get error: `Error: write EPROTO 4682231096:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER` or if in browser `ERR_SSL_PROTOCOL_ERROR`. Ordinary http works fine..

### Exception or Error

Server logs from the Coolify, but logs may be unrelated to the problem:
```bash
2023-12-30T15:20:02.893647953Z time="2023-12-30T15:20:02Z" level=info msg="Configuration loaded from flags."
2023-12-30T15:20:03.202160977Z time="2023-12-30T15:20:03Z" level=error msg="middleware \"redirect-to-https@docker\" does not exist" entryPointName=http routerName=coolify-http@file
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value
```

### Version

v4.0.0-beta.175
