### ISSUE TITLE
[Bug]: Environment variable not set 

### ISSUE THREAD

**Issue by alwyn974** [coollabsio/coolify#1600]
### Description

Environment variable are not available on the docker container, and also with custom docker compose command.

![image_2024-01-04_012942888](https://github.com/coollabsio/coolify/assets/47529956/8dff26cd-696f-4d93-8da8-8b58fb9d3b99)

### Minimal Reproduction (if possible, example repository)

Simple docker-compose.yml, using private github repository as source

```yml
services:
  uptimekuma:
    image: 'louislam/uptime-kuma:1'
    volumes:
      - 'uptime-kuma:/app/data'
    healthcheck:
      test:
        - CMD-SHELL
        - extra/healthcheck
      interval: 2s
      timeout: 10s
      retries: 15
```

### Exception or Error

Using env as custom start command
![image_2024-01-04_012826590](https://github.com/coollabsio/coolify/assets/47529956/51815266-dfca-4ea1-9803-d9c80a800d2c)

Running env command in the docker
![image_2024-01-04_012746313](https://github.com/coollabsio/coolify/assets/47529956/bd6652da-6b25-4bea-976d-5377f063a67c)

### Version

beta.180
