### ISSUE TITLE
[Bug]: Error response from daemon: network f0s0408 not found

### ISSUE THREAD

**Issue by Yurgeman** [coollabsio/coolify#1674]
### Description

Unable to install the service using Docker-compose - error:
`Error response from daemon: network f0s0408 not found`

## Origin compose
```
services:
  piwigo:
    image: 'lscr.io/linuxserver/piwigo:latest'
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - '/path/to/appdata/config:/config'
      - '/path/to/appdata/gallery:/gallery'
    ports:
      - '80:8090'
    restart: unless-stopped
```
## Deployed compose
```
version: '3.8'
services:
  piwigo:
    image: 'lscr.io/linuxserver/piwigo:latest'
    container_name: piwigo-f0s0408
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - '/path/to/appdata/config:/config'
      - '/path/to/appdata/gallery:/gallery'
    ports:
      - '80:8090'
    restart: unless-stopped
    networks:
      f0s0408: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.199
      - coolify.serviceId=26
      - coolify.type=service
      - coolify.name=piwigo-f0s0408
      - coolify.pullRequestId=0
      - coolify.service.subId=45
      - coolify.service.subType=application
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-d04wcc8.entryPoints=http
      - traefik.http.routers.http-0-d04wcc8.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-d04wcc8.rule=Host(`piwigo.docsme.ru`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-d04wcc8.entryPoints=https
      - traefik.http.routers.https-0-d04wcc8.middlewares=gzip
      - 'traefik.http.routers.https-0-d04wcc8.rule=Host(`piwigo.docsme.ru`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-d04wcc8.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-d04wcc8.tls=true
volumes: {  }
networks:
  f0s0408:
    name: f0s0408
    external: true

```

### Exception or Error

```
Saved configuration files to /data/coolify/services/f0s0408.
Creating Docker network.
Starting service piwigo docker on localhost.
Pulling images.
 piwigo Pulling 
 piwigo Pulled 
Starting containers.
Error response from daemon: network f0s0408 not found
```

### Version

v4.0.0-beta.199
