### ISSUE TITLE
[Bug]: port expose discrepancy between docker image based deploys and docker compose based deploys

### ISSUE THREAD

**Issue by RayBB** [coollabsio/coolify#1685]
### Description

There is an issue with exposing ports via docker compose.

Note: I expose the port manually because the dockerfile doesn't expose the port I want (5800). It exposes [another instead](https://github.com/jlesage/docker-jdownloader-2/blob/51c60e71d66959221cf976641892566bc30c7f9d/Dockerfile#L82).

Thanks for taking the time to read this and make coolify. It is really awesome and has inspired me to selfhost more.
For some context: on this issue, I would like to submit jdownloader as a coolify service template but I'm struggling to get it working using docker compose when the docker image works fine. 

### Minimal Reproduction (if possible, example repository)

If I make a new resource based on an existing docker image with the image set to `jlesage/jdownloader-2` and the "Ports Exposes" set to `5800` then jdownloader works fine when I hit open application. I get a url like `https://is8wksg.mydomain.com/` and only that url.

However, if I create a docker compose based resource like so:
``` yaml
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - '5800'
    environment:
      - SERVICE_FQDN_JD
```

Then the app has two urls `https://mydomain.com:5800/` and `https://jd-jckco08.mydomain.com/`
However, the :5800 url says `Unable to connect` and the other url says `Bad Gateway`.

Ideally, the 5800 one shouldn't be exposed in the first place but also I have no idea why neither url works.

Two question/problems:
- Why is  `https://mydomain.com:5800/` exposed with the docker compose deploy but not the docker image deploy?
- Why does the docker compose deploy have a bad gateway when the docker image deploy doesn't?

### Version

v4.0.0-beta.200

**Comment by mejiasd3v** [comment]
hey, did you figure this? having a similar issue

**Comment by RayBB** [comment]
Nope. It's the only thing stopping me from adding a new template.
Maybe @andrasbacsai knows a work around?

**Comment by saullo** [comment]
+1

**Comment by peaklabs-dev** [comment]
This is not a bug in coolify, but rather a configuration issue. In the image deploy step you are setting the `expose` to `5800` and in the compose you are doing something incomplete (it is not valid like that). 
Either do the following:
```yaml
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    Ports:
      - 5800:5800
    Environment:
      - SERVICE_FQDN_JD_5800
```
-> This is not fully functional yet as the FQDN needs to be set to an APP_URL or some other environment to work (specific for you service) and then you do not need to expose any port and can remove the `ports` section entirely as the reverse proxy will handle that.

If you just want to do `expose` in compose it would look like this:
```YAML
Services:
  jdownloader-2:
    Image: jlesage/jdownloader-2
    expose:
      - 5800
    Environment:
      - SERVICE_FQDN_JD_5800
```
-> The provided composer is not valid, which is why it does not work.

**Comment by RayBB** [comment]
@peaklabs-dev I think this is still an issue.

I've tried the ways you mentioned and a few others since it has been a long time since I opened this.
```
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    expose:
      - 5800
    environment:
      - SERVICE_FQDN_JD2_5800
```
and
```
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    expose:
      - 5800
    environment:
      - SERVICE_FQDN_JD2
```

At the end of the day, I think there is still an issue where if the base image exposes the wrong port then a docker compose deploy just doesn't work in coolify even with the expose set in the compose.

However, a docker image based deploy works flawlessly with only the following settings.
<img width="990" alt="image" src="https://github.com/user-attachments/assets/d5a967cc-f40d-45c9-95d7-abd374e1e257">

So I think there must be a bug in coolify or at least an unsupported feature.
