### ISSUE TITLE
[Bug]: Custom Labels do not work in Docker compose

### ISSUE THREAD

**Issue by AndreasFaust** [coollabsio/coolify#1737]
### Description

I tried to apply these traefic middlewares (www-redirect, basic authentication) via custom labels to a service:
https://coolify.io/docs/traefik/redirects
https://coolify.io/docs/traefik/basic-auth

I wrote the labels into the docker compose file and, as the "deployable compose" preview shows, they are applied (to the beginning of the labels section. But they do not have an effect. Am I doing something wrong?

### Minimal Reproduction (if possible, example repository)

<img width="1155" alt="Bildschirmfoto 2024-02-12 um 10 26 02" src="https://github.com/coollabsio/coolify/assets/15075587/7473511f-dbaa-4911-b502-859afc433d54">
The example shows only authentication. I tried to copy the router name used at other labels, but this changes after every re-deploy.

### Version

beta.213

**Comment by djoohl** [comment]
I'm having the same problem, pushing this.

**Comment by andrasbacsai** [comment]
I will add a fix in the next version (today).

**Comment by pksorensen** [comment]
I am working on the same thing and the two docs that are in the pr just goes to intro side. 

I have tried everything , also copy pasting all labels my self

```
version: '3.8'
services:
  traefik-forward-auth:
    image: 'thomseddon/traefik-forward-auth:2'
    environment:
      - DEFAULT_PROVIDER=oidc
      - 'PROVIDERS_OIDC_ISSUER_URL=${AUTZ_OPENID_ISSUER}'
      - 'PROVIDERS_OIDC_CLIENT_ID=${AUTZ_OPENID_CLIENT_ID}'
      - 'PROVIDERS_OIDC_CLIENT_SECRET=${AUTZ_OPENID_CLIENT_SECRET}'
      - 'SECRET=${AUTZ_OPENID_CLIENT_SECRET}'
      - LOG_LEVEL=debug
    labels:
      - 'traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181'
      - traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User
      - traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181
  opendevin-app:
    image: 'ghcr.io/opendevin/opendevin:0.8'
    environment:
      - 'SANDBOX_USER_ID=${SANDBOX_USER_ID}'
      - WORKSPACE_MOUNT_PATH=/data/opendevin
    volumes:
      - '/data/opendevin:/opt/workspace_base'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '3000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    labels:
      - traefik.http.routers.https-0-x84so8c-opendevin-app.middlewares=traefik-forward-auth
      - coolify.managed=true
      - coolify.serviceId=7
      - coolify.type=service
      - coolify.name=opendevin-app-x84so8c
      - coolify.service.subId=17
      - coolify.service.subType=application
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-x84so8c-opendevin-app.entryPoints=http
      - traefik.http.routers.http-0-x84so8c-opendevin-app.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-x84so8c-opendevin-app.rule=Host(`opendevin.kjeldager.io`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-x84so8c-opendevin-app.service=http-0-x84so8c-opendevin-app
      - traefik.http.routers.https-0-x84so8c-opendevin-app.entryPoints=https
      - traefik.http.routers.https-0-x84so8c-opendevin-app.middlewares=gzip
      - 'traefik.http.routers.https-0-x84so8c-opendevin-app.rule=Host(`opendevin.kjeldager.io`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-x84so8c-opendevin-app.service=https-0-x84so8c-opendevin-app
      - traefik.http.routers.https-0-x84so8c-opendevin-app.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-x84so8c-opendevin-app.tls=true
      - traefik.http.services.http-0-x84so8c-opendevin-app.loadbalancer.server.port=3000
      - traefik.http.services.https-0-x84so8c-opendevin-app.loadbalancer.server.port=3000
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://opendevin.kjeldager.io'
      - caddy_ingress_network=x84so8c
```


I basically need to add one label ` - traefik.http.routers.https-0-x84so8c-opendevin-app.middlewares=traefik-forward-auth` and it do not seem to have an effect and also saw it changed the routername back to container name which i first tried as some point. Unsure how to proceed. did you get it working @djoohl @AndreasFaust
