### ISSUE TITLE
[Bug]: Docker compose from git repository does not recognize database services

### ISSUE THREAD

**Issue by GringoDotDev** [coollabsio/coolify#1738]
### Description

If you deploy a docker-compose.yaml as part of a git repository deployment, it doesn't seem to recognize things like mysql or databases as the database subtype. This means that you can't access things like database backups, etc.

This is a difference in behavior between pasting in the same docker-compose as part of the non-git workflow.

Let's take a simple example, let's say your docker compose looks like this:

```
version: '3.8'

services:
    mysql:
        image: mysql:8.3
        environment:
          MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-rootpassword}"
          MYSQL_DATABASE: "${DB_DATABASE:-laravel_db}"
          MYSQL_USER: "${DB_USER:-laravel_user}"
          MYSQL_PASSWORD: "${DB_PASSWORD:-laravel_pass}"
        volumes:
          - mysql_data:/var/lib/mysql
        healthcheck:
          test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER:-laravel_user}", "--password=${DB_PASSWORD:-laravel_pass}" ]
          interval: 5s
          retries: 10
          timeout: 2s
volumes:
  mysql_data:
```

If you paste that into the git-less deploy flow, the docker-compose will come out like this for the mysql container (excluding networks, volumes, etc. for brevity):

```
  mysql:
    image: 'mysql:8.3'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-rootpassword}'
      MYSQL_DATABASE: '${DB_DATABASE:-laravel_db}'
      MYSQL_USER: '${DB_USER:-laravel_user}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-laravel_pass}'
    volumes:
      - 'g0o0c8o_mysql-data:/var/lib/mysql'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
        - '-u'
        - '${DB_USER:-laravel_user}'
        - '--password=${DB_PASSWORD:-laravel_pass}'
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      g0o0c8o: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.213
      - coolify.serviceId=8
      - coolify.type=service
      - coolify.name=mysql-g0o0c8o
      - coolify.pullRequestId=0
      - coolify.service.subId=7
      - coolify.service.subType=database
    restart: unless-stopped
    container_name: mysql-g0o0c8o
```

But if you set up an app using a git repo, the same compose will come out like this:

```
  mysql:
    image: 'mysql:8.3'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-rootpassword}'
      MYSQL_DATABASE: '${DB_DATABASE:-laravel_db}'
      MYSQL_USER: '${DB_USER:-laravel_user}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-laravel_pass}'
    volumes:
      - 'mysql_data:/var/lib/mysql'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
        - '-u'
        - '${DB_USER:-laravel_user}'
        - '--password=${DB_PASSWORD:-laravel_pass}'
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      rg0s0k0: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.213
      - coolify.applicationId=22
      - coolify.type=application
      - coolify.name=mysql-rg0s0k0-195343739031
      - coolify.pullRequestId=0
    restart: unless-stopped
    container_name: mysql-rg0s0k0-195343739031
```

Not sure if it's the root cause, but notice the difference in the labels applied to the containers.

Net-net, instead of having a dashboard that looks like this:

<img width="1463" alt="image" src="https://github.com/coollabsio/coolify/assets/506437/c0ffebb5-dfc0-4dbd-948c-8eed01cd6948">

With the ability to manage your db services like this:

<img width="1483" alt="image" src="https://github.com/coollabsio/coolify/assets/506437/335a4eab-e7f0-4a0d-8b08-16d3d8cdb1ae">

You instead end up with this:

<img width="1503" alt="image" src="https://github.com/coollabsio/coolify/assets/506437/83a60f53-8aad-454c-8776-061d5b3b4772">

I'm motivated to get this fixed since it would unblock some cool deployment workflows for us (that I would also like to publicize on Youtube). I'm a pretty good Laravel dev but don't know this codebase particularly well. If you point me in the right direction I'm happy to make an attempt at a PR.

Thank you!

### Minimal Reproduction (if possible, example repository)

* Use the compose file above in a git deploy flow
* Use it with the docker compose git-less flow
* Notice that the git-less flow recognizes the services correctly but not the git deploy flow

### Version

v4.0.0-beta.213
