### ISSUE TITLE
[Bug]: Error when creating a resource from docker compose with volume already on disk

### ISSUE THREAD

**Issue by Zzombiee2361** [coollabsio/coolify#1754]
### Description

When creating a resource with volumes that bind to a directory that already exists, coolify will throw an error like this
![image](https://github.com/coollabsio/coolify/assets/37852137/da2a3af7-f723-401b-b258-0f0a3f38a7f4)

This seems to only happen when creating a new resource. Creating a resource that bind to a directory that doesn't exists but then updating the compose file to a directory that does exists seems fine.

### Minimal Reproduction (if possible, example repository)

1. Create a directory `/opt/test-bug/config`
2. Create a new resource
3. Select Applications > Based on a Docker Compose
4. Select Server and Destination
5. Use this docker compose
    ```
    version: '3.8'
    services:
      hello-world:
        image: alpine
        command: 'echo "Hello World"'
        volumes:
          - '/opt/test-bug/config:/config'
    ```
6. Coolify will throw an error like in screenshot

### Exception or Error

After some digging it seems that the cause is in here
https://github.com/coollabsio/coolify/blob/6ddff8fae1bf7d6a7f295b34773271fd848e8eda/bootstrap/helpers/shared.php#L773-L825

`$isDirectory` is set to false by default and will never be updated to true if you're using simple volume binding like on my example, because there's **no check to the filesystem**. This in turn will make `LocalFileVolume.is_directory` to false.

Then sometime later `LocalFileVolume.saveStorageOnServer` is called and actually does **check to the filesystem** whether it's a directory or not

https://github.com/coollabsio/coolify/blob/6ddff8fae1bf7d6a7f295b34773271fd848e8eda/app/Models/LocalFileVolume.php#L49-L55

### Version

v4.0.0-beta.219
