### ISSUE TITLE
[Bug]: multiple domains and middlwares

### ISSUE THREAD

**Issue by rkcreation** [coollabsio/coolify#1772]
### Description

If you try to add a middleware (basic auth) in only one domain, on a service with multiple domains, middleware is applied to all domains.

### Minimal Reproduction (if possible, example repository)

* Add Uptime Kuma from Services templates
* Add multiple domains (uptime kuma supports a custom domain for a status page), https://uptime.example.com,https://status.example.com
* Add custom labels (basic auth test / test) : 
```yml
      - 'traefik.http.middlewares.https-1-qcwsssw-auth.basicauth.users=test:$2y$05$ypuP3YnQoHM4avWGrkkinuk.zu//J6qs6xMQVuJ4wRGj4bUc6yRDa'
      - traefik.http.routers.https-1-qcwsssw.middlewares=https-1-qcwsssw-auth
```
* This results in deployable compose file : 
```yml
      - 'traefik.http.routers.https-0-qcwsssw.middlewares=gzip,https-1-qcwsssw-auth'
      - 'traefik.http.routers.https-1-qcwsssw.middlewares=gzip,https-1-qcwsssw-auth'
```
I've tried multiple middleware name, but it's applied to `https-0-...` and  `https-1-...`

### Version

v4.0.0-beta.221

**Comment by andrasbacsai** [comment]
I've made some changes, so you just have to include the `basicauth` section: https://coolify.io/docs/traefik/basic-auth#docker-compose-based-applications-one-click-services

note: keep in mind, that some of the services cannot handle multiple domains, Uptime Kuma can.

**Comment by rkcreation** [comment]
Thanks @andrasbacsai but it doesn't work.

Here is the source compose file, edited in Coolify UI:
```yaml
services:
  uptime-kuma:
    image: 'louislam/uptime-kuma:1'
    environment:
      - SERVICE_FQDN
    volumes:
      - '/data/apps/internal/uptime:/app/data'
    healthcheck:
      test:
        - CMD-SHELL
        - extra/healthcheck
      interval: 2s
      timeout: 10s
      retries: 15
    labels:
      - 'traefik.http.middlewares.https-1-qcwsssw-uptime-kuma-auth.basicauth.users=test:$2y$05$ypuP3YnQoHM4avWGrkkinuk.zu//J6qs6xMQVuJ4wRGj4bUc6yRDa'
      - traefik.http.routers.https-1-qcwsssw-uptime-kuma.middlewares=https-1-qcwsssw-uptime-kuma-auth
```

And here is the deployed compose file:
```yaml
version: '3.8'
services:
  uptime-kuma:
    image: 'louislam/uptime-kuma:1'
    environment:
      - SERVICE_FQDN
    volumes:
      - '/data/apps/internal/uptime:/app/data'
    healthcheck:
      test:
        - CMD-SHELL
        - extra/healthcheck
      interval: 2s
      timeout: 10s
      retries: 15
    labels:
      - 'traefik.http.middlewares.https-1-qcwsssw-uptime-kuma-auth.basicauth.users=test:$2y$05$ypuP3YnQoHM4avWGrkkinuk.zu//J6qs6xMQVuJ4wRGj4bUc6yRDa'
      - traefik.http.routers.https-1-qcwsssw-uptime-kuma.middlewares=https-1-qcwsssw-uptime-kuma-auth
      - coolify.managed=true
      - coolify.version=4.0.0-beta.227
      - coolify.serviceId=2
      - coolify.type=service
      - coolify.name=uptime-kuma-qcwsssw
      - coolify.pullRequestId=0
      - coolify.service.subId=2
      - coolify.service.subType=application
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-qcwsssw-uptime-kuma.entryPoints=http
      - traefik.http.routers.http-0-qcwsssw-uptime-kuma.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-qcwsssw-uptime-kuma.rule=Host(`uptime.example.com`) && PathPrefix(`/`)'
      - traefik.http.routers.http-1-qcwsssw-uptime-kuma.entryPoints=http
      - traefik.http.routers.http-1-qcwsssw-uptime-kuma.middlewares=redirect-to-https
      - 'traefik.http.routers.http-1-qcwsssw-uptime-kuma.rule=Host(`status.example.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-qcwsssw-uptime-kuma.entryPoints=https
      - 'traefik.http.routers.https-0-qcwsssw-uptime-kuma.middlewares=gzip,https-1-qcwsssw-uptime-kuma-auth'
      - 'traefik.http.routers.https-0-qcwsssw-uptime-kuma.rule=Host(`uptime.example.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-qcwsssw-uptime-kuma.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-qcwsssw-uptime-kuma.tls=true
      - traefik.http.routers.https-1-qcwsssw-uptime-kuma.entryPoints=https
      - 'traefik.http.routers.https-1-qcwsssw-uptime-kuma.middlewares=gzip,https-1-qcwsssw-uptime-kuma-auth'
      - 'traefik.http.routers.https-1-qcwsssw-uptime-kuma.rule=Host(`status.example.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-1-qcwsssw-uptime-kuma.tls.certresolver=letsencrypt
      - traefik.http.routers.https-1-qcwsssw-uptime-kuma.tls=true
    networks:
      qcwsssw: null
    restart: unless-stopped
    container_name: uptime-kuma-qcwsssw
volumes: {  }
networks:
  qcwsssw:
    name: qcwsssw
    external: true
```

You see that both routers use middleware:

```yaml
      # ...
      - 'traefik.http.routers.https-0-qcwsssw-uptime-kuma.middlewares=gzip,https-1-qcwsssw-uptime-kuma-auth'
      # ...
      - 'traefik.http.routers.https-1-qcwsssw-uptime-kuma.middlewares=gzip,https-1-qcwsssw-uptime-kuma-auth'
      # ...
```

And I would like to have:

```yaml
      # ...
      - 'traefik.http.routers.https-0-qcwsssw-uptime-kuma.middlewares=gzip'
      # ...
      - 'traefik.http.routers.https-1-qcwsssw-uptime-kuma.middlewares=gzip,https-1-qcwsssw-uptime-kuma-auth'
      # ...
```

Maybe you could match middlewares with name starting with router name specifically?
