### ISSUE TITLE
[Bug]: Cloning only clones top level files and docker-compose

### ISSUE THREAD

**Issue by mjwsteenbergen** [coollabsio/coolify#1805]
### Description

When using `docker compose` with some small configuration files, Coolify does not import the entire repository.
This leads to inconsistencies where locally a `docker compose` will succeed but in coolify it won't.
It led me to spend 3 hours and diving into the internals to figure out that this was not possible.
[I am not](https://discord.com/channels/459365938081431553/1199722090090213437/1199722090090213437) [the first](https://discord.com/channels/459365938081431553/1210053086769586236/1210053086769586236) to have this problem

### Minimal Reproduction (if possible, example repository)

1. Create new resource 
2. Choose Public Repository
3. Repository URL: https://github.com/authelia/authelia/tree/merge-v4.38
4. Use the following in general config:
     a. Build Pack: Docker compose
     b. Raw Compose Deployment: True
     c. Base Directory: /examples/compose/local/
     d. Docker Compose Location: /docker-compose.yml
5. Go to the install location on disk: `/data/coolify/applications/{YOUR_FOLDER}`
6. See that only README and `docker-compose.yml` exists, not any other configuration needed.

### Version

v4.0.0-beta.230

**Comment by andrasbacsai** [comment]
I added a few fixes in the upcoming version, that will:

1. Create all directories based on the compose file.
2. Mount the right directory into the server (it was mounting a temporary dir from the build container).

**Comment by mjwsteenbergen** [comment]
Running beta.234 today and the problem still persists.

To explain it a different way:

1. Create a docker-compose.yml file like so:
```
name:  myProject
services:
    traefik:
        ports:
            - 8080:8080
            - 80:80
        volumes:
            - ./config/traefik.toml:/etc/traefik/traefik.toml
            - /var/run/docker.sock:/var/run/docker.sock
        image: traefik:v1.7
```
and create a traefik config file in `./config/traefik.toml`
2. Push this to a repository
3. When you import this project into coolify, it will only put the `docker-compose.yml` file in the `/data/coolify/applications` folder, but skip the `traefik.toml` file. Leading to the application spinning up with a missing config file
