### ISSUE TITLE
[Bug]: Docker compose no longer editable. Errors about env variables and volumes being undefined.

### ISSUE THREAD

**Issue by amerkestijn** [coollabsio/coolify#1840]
### Description

When creating a new resource service or editing an existing service, editing the docker compose file is not possible if environment variables or volumes are required.

Deploying without editing the docker compose works fine.

![image](https://github.com/coollabsio/coolify/assets/11274322/813511ec-787d-4900-82b6-84592e5c642f)

### Minimal Reproduction (if possible, example repository)

- Add a new resource
- pick a service
- go through the steps until you get to "configuration"
- click "Edit compose file"
- click save (if any environment variables and/or volumes are required)

### Exception or Error

Invalid docker-compose file.
time="2024-03-14T15:06:00Z" level=warning msg="The \"SERVICE_REALBASE64_64_PENPOT\" variable is not set. Defaulting to a blank string."
time="2024-03-14T15:06:00Z" level=warning msg="The \"SERVICE_FQDN_FRONTEND\" variable is not set. Defaulting to a blank string."
time="2024-03-14T15:06:00Z" level=warning msg="The \"SERVICE_USER_POSTGRES\" variable is not set. Defaulting to a blank string."
time="2024-03-14T15:06:00Z" level=warning msg="The \"SERVICE_PASSWORD_POSTGRES\" variable is not set. Defaulting to a blank string."
time="2024-03-14T15:06:00Z" level=warning msg="The \"SERVICE_FQDN_FRONTEND\" variable is not set. Defaulting to a blank string."
time="2024-03-14T15:06:00Z" level=warning msg="The \"SERVICE_USER_POSTGRES\" variable is not set. Defaulting to a blank string."
time="2024-03-14T15:06:00Z" level=warning msg="The \"SERVICE_PASSWORD_POSTGRES\" variable is not set. Defaulting to a blank string."
service "penpot-backend" refers to undefined volume penpot-assets: invalid compose project

### Version

v4.0.0-beta.237

**Comment by iamEvanYT** [comment]
@andrasbacsai
it doesn't let me save my docker-compose file for uptime kuma service so the labels cannot be saved.

source compose:
```yaml
services:
  uptime-kuma:
    image: 'louislam/uptime-kuma:1'
    environment:
      - SERVICE_FQDN_3001
    volumes:
      - 'uptime-kuma:/app/data'
    healthcheck:
      test:
        - CMD-SHELL
        - extra/healthcheck
      interval: 2s
      timeout: 10s
      retries: 15
```

in deployable compose, the volume has transformed to this:
```yaml
volumes: {  }
```

that may be the issue.
