### ISSUE TITLE
[Bug]: Umami Analytics is shown as unhealthy

### ISSUE THREAD

**Issue by Wulfheart** [coollabsio/coolify#1848]
### Description

The umami service is shown as unhealthy.

### Minimal Reproduction (if possible, example repository)

https://github.com/coollabsio/coolify/blob/467c826c04df3fe4b93f5465a8f1238c23cf603a/templates/compose/umami.yaml#L7-L30

This is the standard tempalte I deployed. The umami service is missing a healthcheck. I added it like this in the compose file:
```yaml
   healthcheck:
      test:
        - CMD-SHELL
        - 'curl https://umami.wulf-industries.com/api/heartbeat'
```

I would have contributed a fix for this as a PR but I don't know how it works with the URL (where is it defined etc.).

### Version

v4.0.0-beta.239
