### ISSUE TITLE
[Bug]: Traefik dynamic setup not working

### ISSUE THREAD

**Issue by nicanordlc** [coollabsio/coolify#1870]
### Description

I just followed docs [here](https://coolify.io/docs/traefik/dashboard#secure-mode-with-dynamic-configuration) and it ask me for the basic auth credentials but when I enter those it throws a 404 page. I think it is not quite getting to the service `api@internal` or something.

### Minimal Reproduction (if possible, example repository)

Enter the following `*.yml` file into the `Dynamic Configurations` for the proxy of your server. Assuming the IP of your server is `10.0.0.37`. Password is the same as the docs `test test`

```
http:
  routers:
    dashboard:
      rule: Host(`10.0.0.37.sslip.io`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      service: api@internal
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - "test:$apr1$154ethlp$Re.R1QjCkyOyKKmgYHHYP1"
```

Bonus: (Not a blocker)

When entering the contents of the `*.yml` file the first time it throws an error about base64 encode and it enters the file as empty which then you can proceed to hit the `Edit` button and enter the contents of that file right there.

### Version

v4.0.0-beta.239

**Comment by LockeAG** [comment]
Yeah happening to me in container load balancing. 

After further investigation, it appears the root of my "Bad Gateway" issues is that Traefik's dynamic proxy functionality isn't working as expected. Despite configuring Traefik to dynamically route traffic based on hostnames and paths, requests aren't correctly forwarded to the intended backend services.

It seems that the challenges with Traefik's dynamic proxy not functioning correctly are linked to the recent update to version v4.0.0-beta 237 (released on March 14th).

**Comment by brendoncarvalho** [comment]
I'm having the same difficulty, I couldn't define the "Dynamic Configurations". 

When accessing the defined host, the 404 page is displayed.

![image](https://github.com/coollabsio/coolify/assets/1341565/28cac4d0-b44f-441b-8bfe-232a97d88b5e)

**Comment by ArchangelGCA** [comment]
This still seems to be an ongoing issue even on: v4.0.0-beta.293.
Same configuration, still error `404 page not found`.

**Comment by thomasmol** [comment]
i think i am experiencing a bug related to this issue where my config is not recognized in my container. I get this error: `2024-06-04T14:12:19.408664499Z time="2024-06-04T14:12:19Z" level=error msg="the service \"forward-compute@docker\" does not exist" routerName=compute-forward-router@docker entryPointName=https`

**Comment by SpuriousGer** [comment]
I'm wondering if my issues have the same origin. I can't access coolify which I've hosted on my on premise server from another VLAN in the same network. 
It is accessible from externally.

Now, I've tried to restart the proxy and it doesn't want to start up again.

**Comment by ArchangelGCA** [comment]
> I'm wondering if my issues have the same origin. I can't access coolify which I've hosted on my on premise server from another VLAN in the same network. It is accessible from externally.
> 
> Now, I've tried to restart the proxy and it doesn't want to start up again.

I can agree on this, I had to reinstall everything a few days ago. After the proxy crashed (for unknwon reasons) it was unable to restart. I mean, it could restart but it didn't work at all and had config issues. Resetting didn't help at first, but manually deleting everything and reinstalling worked (the uninstall script wasn't enough).

**Comment by TeenageMutantCoder** [comment]
I initially had the same issue of getting a 404 page when trying to access the dashboard, but I eventually got it working after doing a few things.

Firstly, my domain for the dashboard is set up in Cloudflare with strict TLS, and going to the URL showed an error page related to an invalid SSL cert. To fix it, I added the following line to the dynamic config file.
```
tls:
        certresolver: letsencrypt
```

Secondly, and this is the most important part, I ADDED A TRAILING SLASH TO MY URL. For whatever reason, it is MANDATORY. Instead of going to `https://example.com/dashboard`, you have to go to `https://example.com/dashboard/`

https://doc.traefik.io/traefik/operations/dashboard/#the-dashboard
> The trailing slash / in /dashboard/ is mandatory

My dynamic configuration file is named `dashboard.yaml` and looks like this (edited to take out sensitive details):
```
http:
  routers:
    dashboard:
      rule: 'Host(`<DOMAIN>`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))'
      service: api@internal
      tls:
        certresolver: letsencrypt
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - '<USERNAME>:<GENERATED PASSWORD HASH>'
```
