### ISSUE TITLE
[Bug]: Deployments based on Docker Compose cannot join the coolify network and cannot connect to preset services, such as MySQL.

### ISSUE THREAD

**Issue by Huangwh826** [coollabsio/coolify#1874]
### Description

Deployments based on Docker Compose can only communicate within their own network, even though I declared networks in the yml.

```
# container networks
root@racknerd-d8d60a:/data/coolify/# docker ps -q | xargs docker inspect -f '{{ .Name }} {{ .NetworkSettings.Networks }}'
/halo-asosswg map[asosswg:0xc00016e460]  # halo
/a4gs0k0 map[coolify:0xc00016e540]  # mysql
/coolify-proxy map[asosswg:0xc0004e4000 coolify:0xc0004e40e0 dss44sc:0xc0004e41c0 n4wokcs:0xc0004e42a0]
/coolify map[coolify:0xc00016e000]
/coolify-redis map[coolify:0xc0004e4380]
/coolify-realtime map[coolify:0xc00016e0e0]
/coolify-db map[coolify:0xc00016e460]
```

![image](https://github.com/coollabsio/coolify/assets/79346828/5a6ffc9b-f9a1-4410-b4c5-6abffbe3adfe)

### Minimal Reproduction (if possible, example repository)

version: [v4.0.0-beta.239](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.239)

docker-compose
```
version: '3'
services:
  halo:
    image: 'halohub/halo:2.13'
    container_name: halo
    restart: 'on-failure:3'
    volumes:
      - './halo2:/root/.halo2'
    ports:
      - '9001:8090'
    command:
      - '--spring.r2dbc.url=r2dbc:pool:mysql://a4gs0k0:3306/halo'
      - '--spring.r2dbc.username=****'
      - '--spring.r2dbc.password=*****'
      - '--spring.sql.init.platform=mysql'
      - '--halo.external-url=**********'
      - '--server.port=8090'
    networks:
      - coolify
networks:
  coolify:
    external: true
```

### Version

v4.0.0-beta.239
