### ISSUE TITLE
[Bug]: Cannot save docker compose service configuration

### ISSUE THREAD

**Issue by hmps** [coollabsio/coolify#1877]
### Description

**First things first: Thank you for your great work on this** 🙌

I'm trying to migrate services from v3 to v4. 

I deploy via the Github app, using the docker compose build pack. I have successfully migrated other packages, which uses the docker build pack.

All the docker compose packs ends fails with the same error. When I add the path to the docker-compose file and try to save it, it spins for a few seconds, shows an error message, and then kicks back to the previous value.

![CleanShot 2024-03-21 at 10 02 35](https://github.com/coollabsio/coolify/assets/1231909/59ea27e0-199d-421c-956e-62a4ee32febd)

### Minimal Reproduction (if possible, example repository)

Here's the docker compose file

```
version: '3'
services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordlynx
    cap_add:
      - NET_ADMIN
    ports:
      - 3002:3002
    environment:
		 - PRIVATE_KEY=***
		 - QUERY=***
    sysctls:
		- value_1=1
		- value_2=2
    restart: unless-stopped
  automation:
    build:
      context: .
      dockerfile: packages/automation/Dockerfile
      args:
	    - SERVICE_ACCOUNT=***
    network_mode: service:nordlynx
    volumes:
     - data:/data 
    depends_on:
      - nordlynx
volumes:
  data:
    external: true
```

### Exception or Error

> generateEnvValue(): Argument #1 ($command) must be of type string, null given, called in /var/www/html/bootstrap/helpers/shared.php on line 1484

This is the LOC it points to: https://github.com/coollabsio/coolify/blob/07c9db9b54ea746ce65aa0b57f03eb7634ba44af/bootstrap/helpers/shared.php#L1484

### Version

v4.0.0-beta.239

**Comment by andrasbacsai** [comment]
If I'm right the `# REDACTED` parts are not there, as it makes the yaml file invalid.

Can you please add the envs (ofc with different values) and all the `REDACTED` values (ofc with different values) to the example? 

I've added a fix to the next version, but I would like to make sure.

If I'm right, one of them are starting with `SERVICE`.

**Comment by hmps** [comment]
> If I'm right, one of them are starting with `SERVICE`.

You are totally correct 👏

```
  automation:
    build:
      context: .
      dockerfile: packages/automation/Dockerfile
      args:
	    - SERVICE_ACCOUNT=***
    network_mode: service:nordlynx
```
