### ISSUE TITLE
[Bug]: Https isn't enforced

### ISSUE THREAD

**Issue by Ujstor** [coollabsio/coolify#1880]
### Description

Traffic from HTTP isn't automatically redirected to HTTPS. The option in the configuration under Advanced (Force HTTPS) is checked, and yet I can still access my app through HTTP. Is there something I might be misconfiguring? The domain in the general settings starts with https://.

I am also using V3, and I didn't have this issue

### Minimal Reproduction (if possible, example repository)

I am providing an example Docker Compose with network configuration:

version: '3'
services:
  probitapi:
    image: 'ujstor/probitapi:1.0.4'
    ports:
      - '5005:5005'
    environment:
      - 'KEY=${KEY}'
      - 'ID=${ID}'
      - 'SECRET=${SECRET}'
    networks:
      t880g0g: null
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-p4c4k80.entryPoints=http
      - 'traefik.http.routers.http-0-p4c4k80.rule=Host(`probit.astipan.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-p4c4k80.entryPoints=https
      - traefik.http.routers.https-0-p4c4k80.middlewares=gzip
      - 'traefik.http.routers.https-0-p4c4k80.rule=Host(`probit.astipan.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-p4c4k80.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-p4c4k80.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://probit.astipan.com'
      - caddy_ingress_network=p4c4k80
      - coolify.managed=true
      - coolify.version=4.0.0-beta.239
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=probitapi-t880g0g-222457280347
      - coolify.pullRequestId=0
    restart: unless-stopped
    container_name: probitapi-t880g0g-222457280347
volumes: {  }
networks:
  t880g0g:
    name: t880g0g
    external: true

### Exception or Error

This is not the case with just one app. I deployed four different code examples, and in every case, I experienced the same issue. Was this previously known behavior?

Thanks for the help....project is amazing

### Version

 v4.0.0-beta.239

**Comment by andrasbacsai** [comment]
Can you please click on the `Reset Coolify Generated Labels` button on the general configuration page?

The assignment of the middleware called `redirect-to-https` is missing from the labels list.

If it is still missing, please let me know more details about your deployment type (git based or not, which buildpack do you use, etc, basically a screenshot from the general tab wouldbe sufficient)

**Comment by andrasbacsai** [comment]
(I've sent you an email, please check that first.)

The assignment of the middleware called `redirect-to-https` is missing from the labels list.

Can you please click on the `Reset Coolify Generated Labels` button on the general configuration page?

If it is still missing, please let me know more details about your deployment type (git based or not, which buildpack do you use, etc, basically a screenshot from the general tab wouldbe sufficient)

**Comment by Ujstor** [comment]
@andrasbacsai In prod, I am still using CL v3, but I did a test to see if the issue still persists and I have interesting results. 

I deployed my portfolio website from a public Git source using a simple Docker Compose with an image from DockerHub

The first test was on a domain that I used in other projects, so it had a generated certificate with Let's Encrypt. For the first five minutes, there was a problem with the certificate, but it was resolved automatically afterward.

But still, if I try to access the domain with http://, it won't redirect automatically to https

```bash
services:
  web:
    image: 'ujstor/portfolio-web-go:1.2.0'
    ports:
      - '${PORT}:${PORT}'
    environment:
      - 'PORT=${PORT}'
    networks:
      kosg0og: null
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-vg4s800.entryPoints=http
      - 'traefik.http.routers.http-0-vg4s800.rule=Host(`test.ujstor.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-vg4s800.entryPoints=https
      - traefik.http.routers.https-0-vg4s800.middlewares=gzip
      - 'traefik.http.routers.https-0-vg4s800.rule=Host(`test.ujstor.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-vg4s800.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-vg4s800.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://test.ujstor.com'
      - caddy_ingress_network=kosg0og
      - coolify.managed=true
      - coolify.version=4.0.0-beta.294
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=web-kosg0og-212210758740
      - coolify.pullRequestId=0
    restart: unless-stopped
    container_name: web-kosg0og-212210758740
volumes: {  }
networks:
  kosg0og:
    name: kosg0og
    external: true
```
![image](https://github.com/coollabsio/coolify/assets/116409846/5f0e467b-4d00-44dc-a3c5-cb30f8f3bb09)

I ran one more test on a different worker and domain inside the same Cooldy cluster. Now cert works fine on the first attempt. In this case, HTTPS is enforced and automatically redirects from http:// on Brave, not a case in Firefox

```bash
services:
  web:
    image: 'ujstor/portfolio-web-go:1.2.0'
    ports:
      - '${PORT}:${PORT}'
    environment:
      - 'PORT=${PORT}'
    networks:
      yoccw44: null
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-s8w4w0s.entryPoints=http
      - 'traefik.http.routers.http-0-s8w4w0s.rule=Host(`test2.ujstor.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-s8w4w0s.entryPoints=https
      - traefik.http.routers.https-0-s8w4w0s.middlewares=gzip
      - 'traefik.http.routers.https-0-s8w4w0s.rule=Host(`test2.ujstor.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-s8w4w0s.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-s8w4w0s.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://test2.ujstor.com'
      - caddy_ingress_network=yoccw44
      - coolify.managed=true
      - coolify.version=4.0.0-beta.294
      - coolify.applicationId=2
      - coolify.type=application
      - coolify.name=web-yoccw44-205954710543
      - coolify.pullRequestId=0
    restart: unless-stopped
    container_name: web-yoccw44-205954710543
volumes: {  }
networks:
  yoccw44:
    name: yoccw44
    external: true
```
![image](https://github.com/coollabsio/coolify/assets/116409846/838b14e9-d624-41f0-9c3d-b8da828b19c2)


Last time, I ran CL version v4.0.0-beta.239, and now I am testing on v4.0.0-beta.294.

Config that i gave you are default generated, I see that traefik Assigned Middleware to HTTP Router label redirect-to-https is missing

The strange thing is, when I tested different browsers  (latest versions) on https://www.browserling.com/, only Brave and Firefox did not redirect to HTTPS, other browsers did

I provision and configure the infrastructure with Terraform and Ansible on Hetzner.
https://github.com/Ujstor/self-hosting-infrastructure-cluster

I thought that maybe the way I am provisioning and configuring infrastructure could be a problem, and I spotted an issue in my Ansible logs connected with the SSH hardening configuration. Made tests after fixing it and got the same result.

The HTTPS redirect issue only occurs when I deploy from Docker Compose. Deployment from a Dockerfile works, and it has attached traefik.http.routers.http-0-o844s0c.middlewares=redirect-to-https

I tried Docker Compose prod (with an image on DockerHub) and built image from the code repository, same result. The question is why 'redirect-to-https' isn't attached to the Compose labels?

Hope this helps.

Congrats on the latest Fireship shoutout. You deserve it for your amazing work!

**Comment by mooxl** [comment]
I'm encountering the same. Despite having the "Force HTTPS" option enabled in the Advanced settings, HTTP traffic is not being redirected to HTTPS. This is affecting our ability to ensure secure connections.
We briefly discussed this via email, but since I haven't received a follow-up, I'm commenting here.
The repository being deployed is: https://github.com/mediaatrium/gerber. 
The generated Docker Compose file:
```yaml
services:
  cache:
    image: 'varnish:alpine'
    restart: unless-stopped
    volumes:
      - '/data/coolify/applications/lcwsggo/default.vcl:/etc/varnish/default.vcl'
    tmpfs:
      - '/app:exec'
    environment:
      - VARNISH_SIZE=512M
    networks:
      lcwsggo: null
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-ys40ooo.entryPoints=http
      - 'traefik.http.routers.http-0-ys40ooo.rule=Host(`gerber-fachhandel.de`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ys40ooo.entryPoints=https
      - traefik.http.routers.https-0-ys40ooo.middlewares=gzip
      - 'traefik.http.routers.https-0-ys40ooo.rule=Host(`gerber-fachhandel.de`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ys40ooo.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-ys40ooo.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://gerber-fachhandel.de'
      - caddy_ingress_network=lcwsggo
      - coolify.managed=true
      - coolify.version=4.0.0-beta.301
      - coolify.applicationId=1362
      - coolify.type=application
      - coolify.name=cache-lcwsggo-180959312430
      - coolify.pullRequestId=0
    container_name: cache-lcwsggo-180959312430
  site:
    build: .
    restart: unless-stopped
    depends_on:
      - cache
    networks:
      lcwsggo: null
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-fckccsw.entryPoints=http
      - traefik.http.routers.http-0-fckccsw.middlewares=gzip
      - 'traefik.http.routers.http-0-fckccsw.rule=Host(`r0k44cs.49.13.197.248.sslip.io`) && PathPrefix(`/`)'
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=http://r0k44cs.49.13.197.248.sslip.io'
      - caddy_ingress_network=lcwsggo
      - coolify.managed=true
      - coolify.version=4.0.0-beta.301
      - coolify.applicationId=1362
      - coolify.type=application
      - coolify.name=site-lcwsggo-180959313075
      - coolify.pullRequestId=0
    container_name: site-lcwsggo-180959313075
volumes: {  }
networks:
  lcwsggo:
    name: lcwsggo
    external: true

```
Your insights or updates on resolving this issue would be greatly appreciated. Thank you!
