### ISSUE TITLE
[Bug]: SERVICE_FQDN with port numbers binds incorrectly on importing docker compose

### ISSUE THREAD

**Issue by hades200082** [coollabsio/coolify#1904]
### Description

With the following in my docker compose...

```yaml
    environment:
      - SERVICE_FQDN_MYAPPAPI_3001
      - SERVICE_FQDN_MYAPPADMIN_3002
```

when first importing the docker compose, it creates environment variables like this...

```env
SERVICE_FQDN_MYAPPADMIN=https://myapp_admin-lo4000o.mydomain.com
SERVICE_FQDN_MYAPPADMIN_3002=https://myapp_api-lo4000o.mydomain.com:3001,https://myapp_admin-lo4000o.mydomain.com:3002
SERVICE_FQDN_MYAPPAPI=https://myapp_api-lo4000o.mydomain.com
SERVICE_FQDN_MYAPPAPI_3001=https://myapp_api-lo4000o.mydomain.com:3001
```

The `SERVICE_FQDN_MYAPPADMIN_3002` variable seems to include the value from `SERVICE_FQDN_MYAPPAPI_3001` as well as the one it should have.

This seems incorrect and breaks the vhost bindings for apps where a single docker compose service exposes multiple endpoints.

### Minimal Reproduction (if possible, example repository)

Run the following docker-compose in coolify

```yaml
# To use this docker-compose 
version: "3.9"
services:
  logto:
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto:${TAG-latest}
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - SERVICE_FQDN_LOGTOAPI_3001
      - SERVICE_FQDN_LOGTOADMIN_3002
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://${SERVICE_USER_LOGTOPG}:${SERVICE_PASSWORD_LOGTOPG}@postgres:5432/${POSTGRES_DB-logto}
      # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
      # Or, you can leverage it for local testing.
      - ENDPOINT=$SERVICE_FQDN_LOGTOAPI
      - ADMIN_ENDPOINT=$SERVICE_FQDN_LOGTOADMIN
  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: ${SERVICE_USER_LOGTOPG}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_LOGTOPG}
      POSTGRES_DB: ${POSTGRES_DB-logto}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - logto-postgresql-data:/var/lib/postgresql/data
```

### Version

v4.0.0-beta.245
