### ISSUE TITLE
[Bug]: Setting instance's domain doesn't update FQDN environment variables

### ISSUE THREAD

**Issue by hades200082** [coollabsio/coolify#1906]
### Description

When creating a stack using docker compose, if I have `SERVICE_FQDN_*` variables in the compose file, and any of them are for port mapped versions (e.g. `SERVICE_FQDN_MYAPP_3000`) then when I change the domains in the services of the stack it doesn't update the associated environment variables.

### Minimal Reproduction (if possible, example repository)

1. Run the following docker compose in coolify

```yaml
# After importing this docker compose file into Coolify, go to the environment variables for the stack
# and in developer mode, edit the SERVICE_FQDN_LOGTO_3002 variable to only include the domain with port 3002.
# Ensure your custom domains in the logto server match the domains in the environment variables or vice-versa.
#
# Once started, wait about 5 mins, then hit the URL from $SERVICE_FQDN_LOGTO to access the admin console.
version: "3.9"
services:
  logto:
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto:${TAG-latest}
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - SERVICE_FQDN_AUTH_3001
      - SERVICE_FQDN_LOGTO_3002
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB-logto}
      # Mandatory for GitPod to map host env to the container, thus GitPod can dynamically configure the public URL of Logto;
      # Or, you can leverage it for local testing.
      - ENDPOINT=$SERVICE_FQDN_AUTH
      - ADMIN_ENDPOINT=$SERVICE_FQDN_LOGTO
    healthcheck:
      test: curl --fail -s http://localhost:3002 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: ${SERVICE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRES}
      POSTGRES_DB: ${POSTGRES_DB-logto}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - logto-postgres-data:/var/lib/postgresql/data
```

2. Under "Service Stack" select "Settings" on the "Logto" service
3. Change the "domains" field
4. Go "Back" and check the environment variables in developer mode

Notice that the FQDN env vars are still the originally generated domains rather than the ones you changed them to.

### Version

v4.0.0-beta.245
