### ISSUE TITLE
[Bug]: New resource based on docker compose cannot recognize volumes  ( bug in versions v240 and above )

### ISSUE THREAD

**Issue by Huangwh826** [coollabsio/coolify#1924]
### Description

New resource based on docker compose cannot recognize volumes  ( bug in versions v240 and above )

### Minimal Reproduction (if possible, example repository)

for example:

```
version: '3'
services:
  halo:
    image: 'halohub/halo:2.13'
    container_name: halo
    restart: 'on-failure:3'
    volumes:
      - './halo2:/root/.halo2'
    ports:
      - '9001:8090'
    command:
      - '--spring.r2dbc.url=r2dbc:pool:mysql://mysql-host:3306/halo'
      - '--spring.r2dbc.username=root'
      - '--spring.r2dbc.password=pwd'
      - '--spring.sql.init.platform=mysql'
      - '--halo.external-url=https://www.xxxxx.com/'
      - '--server.port=8090'
```

![image](https://github.com/coollabsio/coolify/assets/79346828/502cb53a-ee59-4ef9-8de4-66cf80ef3d20)

```
version: '3.7'
services:
  douyin_tiktok_download_api:
    image: evil0ctal/douyin_tiktok_download_api
    container_name: douyin_tiktok_download_api
    restart: always
    ports:
      - '9002:9002'
      - '9003:9003'
    volumes:
      - './config.yml:/app/config.yml'
    deploy:
      resources:
        limits:
          cpus: '1.0'
```
![image](https://github.com/coollabsio/coolify/assets/79346828/5f41c995-c00b-44a1-81e7-d8a67fcdd65f)

### Exception or Error

cannot recognize volumes

### Version

v4.0.0-beta.248
