### ISSUE TITLE
[Bug]: GitLab MR Preview with docker-compose fails (depends on unknown service)

### ISSUE THREAD

**Issue by A-D-E-A** [coollabsio/coolify#2005]
### Description

When I create a merge request to get a preview app, it fails and tells me that my service is unknown.

I think the issue is that coolify renames the services in its custom docker-compose.yaml and does not rename the fields in "depends_on" or "links". I was not able to reproduce this error when copying the commands shown in the debug logs.

### Minimal Reproduction (if possible, example repository)

Use the following docker-compose file:

```yaml
services:
  myapp:  # My web app
    # ...
    depends_on: # Works with "links" too
      - cache
  cache:  # My redis service
    image: redis:latest
```

And, after configuring the preview apps in coolify and the needed webhook in GitLab, create a merge request.

### Exception or Error

```txt
[2024-Apr-16 13:49:55.170892] Oops something is not okay, are you okay? 😢

[2024-Apr-16 13:49:55.183408] time="2024-04-16T13:49:55Z" level=warning msg="/artifacts/jc404ck/compose.yaml: `version` is obsolete"
service "myapp-pr-4" depends on unknown service "cache"
```

### Version

v4.0.0-beta.258

**Comment by rdamborsky** [comment]
I run into the same issue when running preview deployments. On the main deployment flow the process works fine.

> service "backend-pr-117" depends on undefined service "database": invalid compose project

(reduced) docker-compose content from coolify UI:

```
services:
  backend:
    build: .
    depends_on:
      - database
    labels:
      - coolify.version=4.0.0-beta.278
      - coolify.type=application
      - coolify.name=backend-f2sg4o0-172530544062
      - coolify.pullRequestId=0
    container_name: backend-f2sg4o0-172530544062
  database:
    image: 'mariadb:11.3'
    labels:
      - coolify.version=4.0.0-beta.278
      - coolify.type=application
      - coolify.name=database-f2sg4o0-172530544894
      - coolify.pullRequestId=0
    restart: unless-stopped
    container_name: database-f2sg4o0-172530544894
```
