### ISSUE TITLE
[Bug]: Env variables set in coolify are overriden by default variables in .env file

### ISSUE THREAD

**Issue by noximo** [coollabsio/coolify#2017]
### Description

In the last day or two, my builds started failing due to already used ports. 

But I have ports defined in the compose.yml using the env variable. 

I've noticed that plenty of envs I've set up display this message: **This variable is not found in the compose file, so it won't be used.**

That's problematic for several reasons: 

1) Some of the variables actually are present in the compose.yml. From what I gathered, only variables used in the environment: section of the configuration of the service are detected:

```yaml
services:
    php:
        image: ${IMAGES_PREFIX:-}app-php
        restart: unless-stopped
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}, php:80 # <-- FOUND
        ports:
            # HTTP
            -   target: 80
                published: ${HTTP_PORT:-80} # <-- NOT FOUND
                protocol: tcp
```

2) I have several compose files and it looks like only the main one gets analyzed. 

I'm starting the containers with this command: 
`docker compose -f compose.yml -f compose.prod.yml up -d `

and compose.prod.yml looks (simplified) like: 

```yaml
services:
    php:
        build:
            context: .
            target: frankenphp_prod
        environment:
            APP_SECRET: ${APP_SECRET} # <-- NOT FOUND
```

3) Not all variables are relevant to the compose.yml. 

I have variables set up that aren't and won't be part of the compose.yml. I need them present during build step because one of the build steps of Dockerfile is calling symfony command that dumps all env variables into php file. That worked well so far. ,

### Minimal Reproduction (if possible, example repository)

Probably any env variable that's not present in the main compose.yml under environment key. I will investigate further.  

### Version

v4.0.0-beta.262
