### ISSUE TITLE
[Bug]: Custom caddy labels in compose based deployment are not escaped

### ISSUE THREAD

**Issue by w3cj** [coollabsio/coolify#2069]
### Description

Similar to issue #2013 but for a docker compose based deployment with the labels specified in the compose file.

When I add a custom caddy label in the docker compose like so:

```yml
services:
  app:
    image: 'node'
    labels:
      - caddy_0.basicauth.0_cj=$2a$14$PQEq3Ql.QWIgXcMfXwm.5.4FGc6iKJjXAHez7RQdWeBhmU2CzgUA.
```

The label passed to the container is truncated to:
`$2a$14.QWIgXcMfXwm.5.4FGc6iKJjXAHez7RQdWeBhmU2CzgUA.`

### Minimal Reproduction (if possible, example repository)

1. Create a compose based deployment

```yml
services:
  app:
    image: 'node'
    labels:
      - caddy_0.basicauth.0_cj=$2a$14$PQEq3Ql.QWIgXcMfXwm.5.4FGc6iKJjXAHez7RQdWeBhmU2CzgUA.
```

2. Inspect the labels passed to the container to see the truncated value

### Version

v4.0.0-beta.266
