### ISSUE TITLE
[Bug]: Minio Service unable to login

### ISSUE THREAD

**Issue by Flowko** [coollabsio/coolify#2263]
### Description

after adding the minio service and setting up the configuration, it loads fine, but cant seem to be able to login

### Minimal Reproduction (if possible, example repository)

- Add Minio service to your project
- Update domain and start the service

### Error
![image](https://github.com/coollabsio/coolify/assets/35883748/954acbf9-b350-4c09-b0f9-29bf0de7522c)

no errors throwing on the logs, which is weird

Good to mention that i have it set up with cloudflare, not sure if thats what causing it to break

### Version

v4.0.0-beta.285

**Comment by Flowko** [comment]
@andrasbacsai would love some help if you have some time, thank you

**Comment by jozefbonnar** [comment]
I'm unable to produce your error? 
![brave_Y039sWe68y](https://github.com/coollabsio/coolify/assets/42479938/2c65954b-6aa2-430b-ab13-498d9250d238)

**Comment by nicnocquee** [comment]
Hey @Flowko I found the problem with set up here https://github.com/coollabsio/coolify/issues/2124#issuecomment-2161848837

**Comment by StianHaugland1** [comment]
I encountered an issue where I had set up my environment on a local network using a private DNS server that manages records for services like Minio and Coolify. The problem arose because I forgot to configure the Coolify host to use this DNS server (not through Coolify's UI but on the Ubuntu server itself). As a result, the Minio container couldn't resolve the internal URL, which led to an 'invalid login' error. Once I corrected the DNS server configuration on the host and rebooted, I was able to log in successfully🥳

**Comment by Flowko** [comment]
Thanks guys, i just had to reconfig my vps instance and cloudflare, reseted some stuff, now working as expected!

**Comment by jimmysafe** [comment]
@Flowko  how did you ended up configuring Cloudflare with Coolify to enable Minio login? 
im going insane and i cant figure out a way to serve Minio with https when using Cloudflare tunnels..

**Comment by Flowko** [comment]
@jimmysafe i honestly dont recall the steps, but before i was using Traefik, and it was configured with cloudflare throught their token and some config i added to work with subdomains, it was messy, but i moved to Caddy and it just works out of the box with it, all i had to do is keep the DNS records for the ip address, also my DNS validation is ON now and DNS server is set to: `1.1.1.1`

here is my minio compose, i didnt change i think, but just for reference:
```
services:
  minio:
    image: 'quay.io/minio/minio:latest'
    command: 'server /data --console-address ":9001"'
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_BROWSER_REDIRECT_URL=$MINIO_BROWSER_REDIRECT_URL
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
    volumes:
      - 'minio-data:/data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:9000/minio/health/live'
      interval: 5s
      timeout: 20s
      retries: 10
```

**Comment by jimmysafe** [comment]
Ok i managed to fix the issue.

With CF tunnels don’t use the Minio one click deploy, instead spin up a new service with docker compose and paste this as docker-compose file:

```
services:
  minio:
    image: minio/minio
    environment:
      - 'MINIO_ROOT_USER=${SERVICE_USER_MINIO}'
      - 'MINIO_ROOT_PASSWORD=${SERVICE_PASSWORD_MINIO}'
    command: 'server --console-address ":9001" /data'
    healthcheck:
      test: 'sleep 5 && exit 0'
      interval: 2s
      timeout: 10s
      retries: 5
    volumes:
      - './volumes/storage:/data'
```

**Also dont forget to append the port 9001 to the domain.**

![image](https://github.com/user-attachments/assets/dc502c8a-6666-4297-9872-a19f8de5d3b6)

![image](https://github.com/user-attachments/assets/8958e13e-eb20-48fc-beaf-c5663cb7c55a)
