### ISSUE TITLE
[Feature]: Jitsi Meet Template

### ISSUE THREAD

**Issue by RayBB** [coollabsio/coolify#2304]
### Description

I would like a template for Jitsi Meet merged into this Coolify repo.

Generally, feature requests don't go in issue they go in discussion (like I posted with details in https://github.com/coollabsio/coolify/discussions/2197) but I want to set a bounty on this so I'm making it an issue.

If you can get a Jitsi meet template working and merged I consider then the bounty is complete.

PS: I tried to get this working myself but ran into issues with exposing the ports. I suspect this shouldn't be too hard to resolve for someone who has setup Jitsi before.

### Minimal Reproduction (if possible, example repository)

n/a

### Version

n/a

**Comment by DeVoresyah** [comment]
how to increase bounty? I also wanna add the amount

**Comment by LEstradioto** [comment]
/attempt #2304

I will PR shortly

This is a tricky template. Some notes here:
- Jitsi uses WebRTC, so it only works with HTTPS, trying to run on localhost, LAN, probably needs more config
- Jitsi uses JVB Videobridge to enable screens sharing with a room >2 people (eq two = p2p), and JVB requires opening a UDP port, which requires changing proxy configuration to open this port and in any other firewall
- I did the minimal template with some env vars, but Jitsi has many many others options to enable if needed, check [here](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker)

that said, using Traefik, on Server > Proxy > Configuration, we must edit PORTS and ADD Traefik entryPoints, eg.:

```yaml
version: '3.8'
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v2.10'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
         # This line maps UDP port 10000 on the host to the container
      - '10000:10000/udp'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=50'
      # This line configures Traefik entrypoints to work with Jitsi template and listen on UDP port 10000
      - '--entryPoints.video.address=:10000/udp'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--providers.docker=true'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - coolify.managed=true
```

In my case, I also needed to open port 10000 in AWS Firewall.

I don't think it's possible to configure these Traefik settings on the fly using only template or Dynamic Configuration. I couldn't do it but it would simplify Jitsi setup. Perhaps with Caddy, however, it wouldn't be explicit about what's happening to the user.
