### ISSUE TITLE
[Feature]: Rocket.Chat Template

### ISSUE THREAD

**Issue by DeVoresyah** [coollabsio/coolify#2318]
### Description

I want a template for Rocket.Chat merged into this Coolify repo.
Suppose you can get a Rocket.Chat template is working and merged I consider that the bounty is complete.

### Minimal Reproduction (if possible, example repository)

n/a

### Version

n/a

**Comment by LEstradioto** [comment]
Hi, I want to try. I did and tested on my end, it worked.

The only thing is that Im having difficult to be sure about the healthcheck of Rocketchat app, but it should work. Mongodb is all good though.

Here is the template code:

```yaml
# documentation: https://github.com/RocketChat/Rocket.Chat
# slogan: Self-hosted, secure and highly customizable open-source communication platform for organizations with sophisticated security and privacy concerns.
# tags: rocketchat,chat,communication,privacy,mongodb,open,source
# logo: svgs/rocketchat.svg
# port: 3000

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    environment:
      - SERVICE_FQDN_ROCKETCHAT_3000
      - MONGO_URL=mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/${MONGODB_DATABASE:-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}
      - MONGO_OPLOG_URL=mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}
      - ROOT_URL=$SERVICE_FQDN_ROCKETCHAT
      - DEPLOY_METHOD=docker
      - REG_TOKEN=$REG_TOKEN
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/api/info"]
      interval: 2s
      timeout: 10s
      retries: 15

  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME:-rs0}
      - MONGODB_PORT_NUMBER=${MONGODB_PORT_NUMBER:-27017}
      - MONGODB_INITIAL_PRIMARY_HOST=${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      - MONGODB_ENABLE_JOURNAL=${MONGODB_ENABLE_JOURNAL:-true}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 2s
      timeout: 10s
      retries: 15
```

I didnt attempt yet because Im from Brazil and am reaching Algora, I think its not easy to register there because of it.
