### ISSUE TITLE
[Bug]: Docker Compose deployment, .env file not found

### ISSUE THREAD

**Issue by Stradi** [coollabsio/coolify#2338]
### Description

I got the following error while deploying using Docker Compose deployment. Previously, there were no issues but I think something has changed since.

### Minimal Reproduction (if possible, example repository)

Since the repository is private, I can't give the URL, but here is my Docker Compose file.

```yaml
name: my-app

services:
  backend:
    build:
      context: ../apps/backend
    depends_on:
      timeseries-db:
        condition: service_healthy
    environment:
      - CRON_KEY=secret
      - QUESTDB_DATABASE=questdb
      - QUESTDB_HOST=timeseries-db
      - QUESTDB_PORT=8812
      - QUESTDB_USER=admin
      - QUESTDB_PASSWORD=quest
      - LIBSQL_DB_AUTH_TOKEN=basic:YWRtaW46YWRtaW4=
      - LIBSQL_DB_URL=https://db.example.com
  timeseries-db:
    image: questdb/questdb:latest
    volumes:
      - questdb-data:/var/lib/questdb
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9003' || exit 1
      interval: 5s
      timeout: 15s
      retries: 5

volumes:
  questdb-data:

networks:
  web:
```

Custom build command:
```bash
docker compose -f ./docker/docker-compose.production.yml build
```

Custom start command:
```bash
docker compose -f ./docker/docker-compose.production.yml up -d
```

### Exception or Error

```
... Container building logs

[2024-Jun-01 17:35:21.477288] Removing old containers.
[2024-Jun-01 17:35:21.920331]

[COMMAND] docker network connect i8ocww4 coolify-proxy || true
[OUTPUT]
Error response from daemon: endpoint with name coolify-proxy already exists in network i8ocww4

[2024-Jun-01 17:35:22.184837]

[COMMAND] docker exec kowgwg4 bash -c 'cd /artifacts/kowgwg4 && docker compose -f ./docker/docker-compose.production.yml up -d'
[OUTPUT]
env file /artifacts/kowgwg4/docker/.env not found: stat /artifacts/kowgwg4/docker/.env: no such file or directory

[2024-Jun-01 17:35:22.271622] Oops something is not okay, are you okay? 😢

[2024-Jun-01 17:35:22.275654] env file /artifacts/kowgwg4/docker/.env not found: stat /artifacts/kowgwg4/docker/.env: no such file or directory
```

### Version

v4.0.0-beta.293
