### ISSUE TITLE
[Bug]: On each redeploy new volume is created

### ISSUE THREAD

**Issue by VCasecnikovs** [coollabsio/coolify#2376]
### Description

For each redeploy of an app - new volume is created.
I use docker compose app with mentioned volume
```
volumes:
  store:
    driver: local
```

It creates a new volume for each redeploy:
![Screenshot 2024-06-07 at 14 53 28](https://github.com/coollabsio/coolify/assets/29467201/a6bfe1d2-9ee9-4c8d-83e2-3a34c2f77ab1)

It does not see storage in storages:
![Screenshot 2024-06-07 at 14 54 37](https://github.com/coollabsio/coolify/assets/29467201/cea20047-1805-410e-b4e5-0ccb5d0e0dd7)

### Minimal Reproduction (if possible, example repository)

Create docker compose service with storage -> redeploy it

### Version

v4.0.0-beta.294 Latest

**Comment by VCasecnikovs** [comment]
This is how store is added
volumes:
      - 'store:/store'

**Comment by andrasbacsai** [comment]
I found the issue (and it will be fixed in the upcoming version).

If you define the top-level volumes like you did:
```
volumes:
  store:
    driver: local
```
Coolify does not modify this value (as it thinks that as you defined this part, so you know what you are doing). This is a "bug" as then Docker defines the volume name based on the current dir, which is different for each deployment. That is why you have different volumes.

In the next version, Coolify will check if you defined the `name` property, and if not, it will define it, so it won't be randomly generated.

The storage view should be empty as everything is hardcoded.


I have a plan to improve this part, to be similar as the services view.

**Comment by VCasecnikovs** [comment]
Thank you, so, to fix it right now I should set `name` value to the store?

**Comment by andrasbacsai** [comment]
Yes.

**Comment by itsUndefined** [comment]
What if we deploy two docker compose projects with the same volume name? That shouldn't be an issue but it is.

**Comment by devjume** [comment]
I noticed similar bug that kinda relates to this, so I won't open new issue yet.

**Issue / bug:**
Coolify is not adding dynamic name for the volumes.
This creates problems when deploying multiple services with identical Docker Compose files on a single server, as they both attempt to use the same volume.

In documentation it says that each volume should get dynamic name. But that is not the case. (At least when deploying with docker compose)
_"To prevent storage overlapping between resources, Coolify automatically adds the resource’s UUID to the volume name."_
[Persistent Storage - Coolify Docs](https://coolify.io/docs/knowledge-base/persistent-storage)

Example fo `docker-compose.yaml` where this happens. 
When deploying this twice, both `pocketbase` containers tries to use same volume `pb_data`
```
services:
  sveltekit:
    build:
      context: ./sveltekit
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - pocketbase

  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    environment:
      GO_ENV: production
    volumes:
      - pb_data:/home/nonroot/app/pb_data
```
When creating new resource using previous docker-compose file, coolify just adds this to it. No dynamic tag.
```
volumes:
  pb_data:
    name: pb_data
```

**Comment by OmkoBass** [comment]
I still can't fix this. The volumes are being lost on each redeploy.

My `docker-compose.yaml` volumes are:
```yaml
volumes:
  project_db_data:
    name: project_db_data
```

**Comment by OmkoBass** [comment]
This is a huge problem docker compose builds cannot be used at all. I hope we find a solution soon. If I find anything I'll update here.

**Comment by andrasbacsai** [comment]
Can you please check again with the latest version? I have added a few fixes.<br><br>You need to create your application again to test it.

**Comment by OmkoBass** [comment]
Hey Andras,

- I deleted the entire application and recreated it.
- Added some data to the database
- Went back to Coolify and pressed redeploy
- The data is missing now

This is my database inside the docker-compose file
```yaml
  db:
    image: bitnami/postgresql:latest
    platform: linux/amd64
    restart: always
    volumes:
      - db_data:/bitnami/postgresql
    ports:
      - ${POSTGRESQL_PORT}:5432
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    logging: *default-logging

volumes:
  db_data:
    name: 'db_data'
    driver: local
```

The problem still persists for me. Can someone else check just so we're sure it's not on my side.
