### ISSUE TITLE
[Bug]: Couldn't find env file

### ISSUE THREAD

**Issue by mjwsteenbergen** [coollabsio/coolify#2436]
### Description

Regression Error: Trying to deploy gives an error error, even though with a previous version it was working

I updated to 296, saw it failed. Then bisected down until it failed. Consider the version below as the first version I found that failed.

### Minimal Reproduction (if possible, example repository)

I am using Coolify as barebones as possible, with `Raw Compose Deployment` enabled.

### Exception or Error

```
[OUTPUT]
Couldn't find env file: /artifacts/lscwwcc/SUB_FOLDER/.env

[2024-Jun-10 19:44:31.539704] Oops something is not okay, are you okay? 😢

[2024-Jun-10 19:44:31.546279] Couldn't find env file: /artifacts/lscwwcc/SUB_FOLDER/.env
```

### Version

4.0.0-beta.291

**Comment by Thijmen** [comment]
Do you have some steps to reproduce here, e.g. example application to enter?

**Comment by alwyn974** [comment]
I have the same issue on version **306**, only with raw docker compose

Here an example docker
```yml
services:
  uptimekuma:
    image: louislam/uptime-kuma:1.23.13@sha256:96510915e6be539b76bcba2e6873591c67aca8a6075ff09f5b4723ae47f333fc
    volumes:
      - uptime-kuma:/app/data
    labels:
      - caddy=status.example.com
      - caddy.reverse_proxy="* {{upstreams 3001}}"
    networks:
      - coolify
    healthcheck:
      test:
        - CMD-SHELL
        - extra/healthcheck
      interval: 2s
      timeout: 10s
      retries: 15

volumes:
  uptime-kuma:
    name: uptime-kuma

networks:
  coolify:
    external: true
```
