### ISSUE TITLE
[Bug]: Docker compose deployment has empty COOLIFY_FQDN and COOLIFY_URL

### ISSUE THREAD

**Issue by scflode** [coollabsio/coolify#2470]
### Description

The Coolify pre defined variables `COOLIFY_FQDN` and `COOLIFY_URL` are empty when using a `Docker Compose` Git based resource. It's empty on all services.

### Minimal Reproduction (if possible, example repository)

* Create a `Docker Compose` app (done via GitHub app)
* Configure app (URL)
* Deploy
* Run `env` inside any of the containers

### Version

v4.0.0-beta.297

**Comment by herkulano** [comment]
I'm having the same issue with `nixpacks`

**Comment by herkulano** [comment]
Maybe related: https://github.com/coollabsio/coolify/issues/2316

**Comment by colinmollenhour** [comment]
I just ran into this as well, was expecting to be able to do this (using bitnami/magento):

```
- MAGENTO_HOST=${COOLIFY_URL}
```

But the environment variable is set but empty.

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by ruohki** [comment]
`APP_URL=${COOLIFY_URL}`

will still yield an empty `APP_URL` on `[v4.0.0-beta.330](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.330)`

**Comment by easis** [comment]
Still empty on [v4.0.0-beta.358](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.358)

**Comment by eaton** [comment]
Just ran into this on [v4.0.0-beta.360](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.360) — copying the contents of docker-compose.yaml file (rather than using a git repository) works fine.

**Comment by sallar** [comment]
Also having this empty issue with docker compose.
Here's my compose file:

```
version: "3"

services:
  api:
    container_name: api
    environment:
      - SERVICE_FQDN_TURBOAPI_3001
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
  web:
    container_name: web
    environment:
      - SERVICE_FQDN_TURBOWEB_3000
      - 'NEXT_PUBLIC_API_HOST=${SERVICE_FQDN_TURBOAPI}'
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always

```
