### ISSUE TITLE
[Bug]: When adding a redis container to the WordPress service/ compose install (for caching), the container does not appear in the UI.

### ISSUE THREAD

**Issue by ayntk-ai** [coollabsio/coolify#2505]
### Description

I want to use redis object cache for my WordPress site and when I add the flowing lines to my WordPress docker compose file:
```yml
redis:
  image: 'redis:alpine'
  container_name: redis
  ports:
    - '6379:6379'
  expose:
    - '6379'
  restart: always
```
-> and then I deploy the stack -> all 3 containers are deployed, redis and WordPress (and proxy), but the redis container does not appear in the UI.

### Minimal Reproduction (if possible, example repository)

Use the WordPress MariaDB compose file and add a redis container. The container will not appear in the UI --> when using the compose file as compose type (not a service) the container also does not appear in the UI:
UI: 
![image](https://github.com/coollabsio/coolify/assets/122374094/ff41da24-8358-4121-b4e2-7f9d44fc5e9f)
Full compose file:
```yml
services:
  wordpress:
    image: 'wordpress:latest'
    volumes:
      - 'wordpress-files:/var/www/html'
    environment:
      - SERVICE_FQDN_WORDPRESS
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=$SERVICE_USER_WORDPRESS
      - WORDPRESS_DB_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mariadb
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10
  mariadb:
    image: 'mariadb:11'
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=$SERVICE_USER_WORDPRESS
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 5s
      timeout: 20s
      retries: 10
redis:
  image: 'redis:alpine'
  container_name: redis
  ports:
    - '6379:6379'
  expose:
    - '6379'
  restart: always


```

### Version

v4.0.0-beta.294
