### ISSUE TITLE
[Bug]: unable to generate a certificate for the domains

### ISSUE THREAD

**Issue by ArtDoctor** [coollabsio/coolify#2531]
### Description

# Description
I can't get https domains working. I set up domain as described in documentation:
![image](https://github.com/coollabsio/coolify/assets/46786959/bcc81bbe-fd77-4ccb-a0ab-488693319eba)
(I have a docker-compose exposing 9324 port)
No errors are shows when I click save, but when I deploy it, SSL doesn't work:
![image](https://github.com/coollabsio/coolify/assets/46786959/ca86ff00-b11f-41b9-80a4-16c75c634ee1)
However, if I go to http://domain.xyz:9324, everything seems to be working.

### Minimal Reproduction (if possible, example repository)

I used default coolify installation, not sure what I did wrong or how to reproduce it.

### Exception or Error

If I curl my url using ubuntu, I get this error:
curl: (6) Could not resolve host: curl
curl: (35) error:0A000458:SSL routines::tlsv1 unrecognized name

### Version

v4.0.0-beta.297

**Comment by Thijmen** [comment]
If you run a docker-compose exposing 9324, then that service should take care of their own SSL certs. Is there a reason why you don't use Traefik for SSL management?

**Comment by ArtDoctor** [comment]
I'm sorry, I was unclear in original post - I don't use docker-compose directly, I connect my Github repo, and there I have a docker-compose. The docker-compose was automatically edited by Coolify, so I assumed it handled SSL management by itself:

```
services:
  stuff:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - '9324:9324'
    restart: always
    networks:
      qksskcc: null
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-a084k80.entryPoints=http
      - 'traefik.http.routers.http-0-a084k80.rule=Host(`mydomain`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-a084k80.service=http-0-a084k80
      - traefik.http.routers.https-0-a084k80.entryPoints=https
      - traefik.http.routers.https-0-a084k80.middlewares=gzip
      - 'traefik.http.routers.https-0-a084k80.rule=Host(`mydomain`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-a084k80.service=https-0-a084k80
      - traefik.http.routers.https-0-a084k80.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-a084k80.tls=true
      - traefik.http.services.http-0-a084k80.loadbalancer.server.port=9324
      - traefik.http.services.https-0-a084k80.loadbalancer.server.port=9324
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 9324}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://mydomain'
      - caddy_ingress_network=qksskcc
      - coolify.managed=true
      - coolify.version=4.0.0-beta.297
      - coolify.applicationId=8
      - coolify.type=application
      - coolify.name=stuff-blah-blah
      - coolify.pullRequestId=0
    container_name: stuff-blah-blah
volumes: {  }
networks:
  qksskcc:
    name: qksskcc
    external: true
```
