### ISSUE TITLE
[Bug]: TOLGEE_AUTHENTICATION_INITIAL_USERNAME en var added inncorectly

### ISSUE THREAD

**Issue by el-garro** [coollabsio/coolify#2540]
### Description

For the docker compose deployments, when the field 'image' is not set for some reason, the TOLGEE_AUTHENTICATION_INITIAL_USERNAME is added automatically to the env vars. 

Now, why would the image field be unset? There's the use case of building with context, example:
```
services:
  libretranslate:
    container_name: libretranslate
    build:
      context: https://github.com/LibreTranslate/LibreTranslate.git
      dockerfile: docker/Dockerfile
```

Although I'm aware as of now, this use case is not supported by coolify

### Minimal Reproduction (if possible, example repository)

Create a new resource based on docker compose with this payload

```
services:
  serviceexample:
```

### Version

v4.0.0-beta.297
