### ISSUE TITLE
[Bug]: High cpu usage /app/sentinel 

### ISSUE THREAD

**Issue by mutonby** [coollabsio/coolify#2771]
### Description

Spikes of 99% cpu in all cores (actually 8 cores) with the process /app/sentinel

### Minimal Reproduction (if possible, example repository)

We have 4 statics fronts, 1 mongodb and 1 backend docker compose

### Exception or Error

error logs seeing in sentinel:

[GIN] 2024/07/08 - 11:34:00 | 200 |       59.17µs |       127.0.0.1 | GET      "/api/health"
Failed to get usage for partition /boot: no such file or directory
Error getting container metrics: json: unsupported value: NaN
Error getting container metrics: json: unsupported value: NaN
[GIN] 2024/07/08 - 11:34:10 | 200 |      46.316µs |       127.0.0.1 | GET      "/api/health"
Error getting container metrics: json: unsupported value: NaN
Error getting container metrics: json: unsupported value: NaN

### Version

v4.0.0-beta.306

**Comment by mutonby** [comment]
Any idea what it might be or if I can do something to reduce the spikes?

**Comment by mutonby** [comment]
![image](https://github.com/coollabsio/coolify/assets/30499505/b9dea1e8-5181-4832-bb65-71a9e32cb42f)

**Comment by victorcavero14** [comment]
Same bug here

**Comment by ksaitor** [comment]
Same here! This is really bad. CPU went to max. Instance became unresponsive.

<img width="301" alt="Screenshot 2024-07-09 at 10 16 10" src="https://github.com/coollabsio/coolify/assets/936436/45d19ddc-401a-4b1f-a0f5-205078ad6586">

**Comment by ksaitor** [comment]
@andrasbacsai just suggest people to use Netdata for their server monitoring and get them to sponsor Coolify. Imho adding these additional dependencies sabotages stability of Coolify

**Comment by maietta** [comment]
You by chance using Ubuntu server?

I notice this any time there are updates pending. Logging into the server via SSH will usually show a banner showing a restart is pending.

**Comment by Rhiz3K** [comment]
Same happened today after update to 307:
![image](https://github.com/coollabsio/coolify/assets/33246262/a3d47987-7a4a-4304-b1f8-97ae759936d9)

Discord helped me to disable metrics(Sentinel restart didn't helped) and it went to normal:
![image](https://github.com/coollabsio/coolify/assets/33246262/5270ede0-bb96-4287-8466-2a4ff3ad5409)

**Comment by PovarovDenis** [comment]
<img width="857" alt="image" src="https://github.com/coollabsio/coolify/assets/13823784/35cde6db-94dd-462c-974d-8dda42548480">
same here, it's hetzner ARM server

**Comment by nickneustroev** [comment]
Same. Had to disable it. 
![image](https://github.com/coollabsio/coolify/assets/7358816/099ec1b1-51a5-45f2-8b01-05ec3a02b6bc)

**Comment by maietta** [comment]
I found my servers unresponsive this morning.

One of them was caused by Sentinel doung something strange with disk io and ramping up on CPU.

The others were because of a crippled network caused by a hurricane.

**Comment by ViX3L** [comment]
Both, ram and cpu spikes were intolerable. Had to restart the sentinel container, and operation were smooth again.

**Comment by devdjdjdj** [comment]
Use netdata meanwhile

```
version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - 'netdataconfig:/etc/netdata'
      - 'netdatalib:/var/lib/netdata'
      - 'netdatacache:/var/cache/netdata'
      - '/:/host/root:ro,rslave'
      - '/etc/passwd:/host/etc/passwd:ro'
      - '/etc/group:/host/etc/group:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/etc/os-release:/host/etc/os-release:ro'
      - '/var/log:/host/var/log:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    labels: 'traefik.http.middlewares.http-0-o0w4g8k-netdata.basicauth.users=test:$2y$12$ci.4U63YX83CwkyUrjqxAucnmi2xXOIlEF6T/KdP9824f1Rf1iyNG'
volumes:
  netdataconfig: null
  netdatalib: null
  netdatacache: null
```

Refer to this for basic auth - https://coolify.io/docs/knowledge-base/traefik/basic-auth
