### ISSUE TITLE
[Bug]: How to solve this problem?

### ISSUE THREAD

**Issue by Dexterity104** [coollabsio/coolify#2782]
### Description

I'm trying to install an app on Coolify, but the following error occurs. (lack of possible addresses)
How can I solve this?
![photo_5220199059850125575_x](https://github.com/coollabsio/coolify/assets/173429049/6f4c7ed1-1b34-48fd-9a74-296f33436196)

### Minimal Reproduction (if possible, example repository)

I'm trying to install farfalle on Coolify using docker compose file.

services:
  backend:
    depends_on:
      - db
      - searxng
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SEARCH_PROVIDER=${SEARCH_PROVIDER:-searxng}
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL:-http://searxng:8080}

      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - BING_API_KEY=${BING_API_KEY}

      - OLLAMA_API_BASE=${OLLAMA_API_BASE:-http://host.docker.internal:11434}

      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}

      - AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_BASE=${AZURE_API_BASE}
      - AZURE_API_VERSION=${AZURE_API_VERSION}

      - OPENAI_MODE=${OPENAI_MODE}

      - CUSTOM_MODEL=${CUSTOM_MODEL}

      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg2://postgres:password@db:5432/postgres}
      - DB_ENABLED=${DB_ENABLED:-True}

      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-False}
      - REDIS_URL=${REDIS_URL}

      - ENABLE_LOCAL_MODELS=${ENABLE_LOCAL_MODELS:-True}

    entrypoint: >
      /bin/sh -c "
        cd /workspace/src/backend &&
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
    develop:
      watch:
        - action: sync
          path: ./src/backend
          target: /workspace/src/backend
    networks:
      - farfalle-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        - NEXT_PUBLIC_LOCAL_MODE_ENABLED=${NEXT_PUBLIC_LOCAL_MODE_ENABLED:-true}
        - NEXT_PUBLIC_PRO_MODE_ENABLED=${NEXT_PUBLIC_PRO_MODE_ENABLED:-true}
    restart: always
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./src/frontend
          target: /app
          ignore:
            - node_modules/
    networks:
      - farfalle-network

  searxng:
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    networks:
      - farfalle-network

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - farfalle-network

networks:
  farfalle-network:
    name: farfalle-network

volumes:
  db_volume:

### Version

v4.0.0-beta.306

**Comment by TeenageMutantCoder** [comment]
One thing that I think I see is that you are using port 8000:8000 for the backend service. Try changing the port to something else like 8001:8000.

Coolify uses port 8000 for its dashboard. Not sure if your other ports also have issues,  but you can run `sudo docker ps` on the server to see which external ports are being used. If I understand it correctly, the external ports look something like `0.0.0.0::<port>` or `:::<port>`

**Comment by peaklabs-dev** [comment]
@Dexterity104 Please change Port  8000:8000 and 3000=3000 to something like 8002=8000 and 3002=3000 as these could cause conflicts and try again (like TeenageMutantCorder said). Also there are some issue with the compose above for example the args should be in the build section so try this compose file:
```yml
services:
  backend:
    depends_on:
      - db
      - searxng
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SEARCH_PROVIDER=${SEARCH_PROVIDER:-searxng}
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL:-http://searxng:8080}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - BING_API_KEY=${BING_API_KEY}
      - OLLAMA_API_BASE=${OLLAMA_API_BASE:-http://host.docker.internal:11434}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_BASE=${AZURE_API_BASE}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      - OPENAI_MODE=${OPENAI_MODE}
      - CUSTOM_MODEL=${CUSTOM_MODEL}
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg2://postgres:password@db:5432/postgres}
      - DB_ENABLED=${DB_ENABLED:-True}
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-False}
      - REDIS_URL=${REDIS_URL}
      - ENABLE_LOCAL_MODELS=${ENABLE_LOCAL_MODELS:-True}
    entrypoint: >
      /bin/sh -c "
        cd /workspace/src/backend &&
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
    develop:
      watch:
        - action: sync
          path: ./src/backend
          target: /workspace/src/backend
    networks:
      - farfalle-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        NEXT_PUBLIC_LOCAL_MODE_ENABLED: ${NEXT_PUBLIC_LOCAL_MODE_ENABLED:-true}
        NEXT_PUBLIC_PRO_MODE_ENABLED: ${NEXT_PUBLIC_PRO_MODE_ENABLED:-true}
    restart: always
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./src/frontend
          target: /app
      ignore:
        - node_modules/
    networks:
      - farfalle-network

  searxng:
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    networks:
      - farfalle-network

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - farfalle-network

networks:
  farfalle-network:
    name: farfalle-network

volumes:
  db_volume:
```
