### ISSUE TITLE
Docker deployment is done but containers couldn't find project files

### ISSUE THREAD

**Issue by abdulrahmanhenedy** [coollabsio/coolify#2786]
### Description

I'm running through a silly error here so I have a dockerized nuxt app with django backend and just finished deploying it with coolify. The thing is the frontend/backend/domain urls are not working and it gives "404 page not found" in a coolify theme i guess.

So after debugging the logs, it seems that both the front/back couldn't initialize the project since the package.json is missing as well as the manage.py file. 

### Minimal Reproduction (if possible, example repository)

Project structure: 
![Screen Shot 2024-07-10 at 2 16 15 PM](https://github.com/coollabsio/coolify/assets/114556029/b615e5b6-1789-4ebf-844a-bf535de3843f)

front.dockerfile:
```dockerfile
# Use Node.js 20 as specified in your package.json
FROM node:20-alpine AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json from the front directory
COPY ./front/package.json ./front/package-lock.json* ./

# Install dependencies
RUN npm ci

# Copy the rest of the frontend code from the front directory
COPY ./front .

# Increase Node.js memory allocation and build the Nuxt application
RUN NODE_OPTIONS="--max_old_space_size=8192" npm run build

# Use a smaller base image for the final stage
FROM node:20-alpine AS production

# Set the working directory in the container
WORKDIR /app

# Copy built files and node_modules from the build stage
COPY --from=build /app .

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the app
CMD ["npm", "run", "start"]
```

back.dockerfile:
```dockerfile
# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file from the back directory
COPY ./back/requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend code from the back directory
COPY ./back .

# Expose the port the app runs on
EXPOSE 8000

# Define the command to run the app
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
```
docker-compose.yml:
``` yml
version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: front.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./front:/app
      - /app/node_modules
    networks:
      default: null
    environment:
      MONGODB_URI: ${MONGODB_URI}
      NODE_ENV: ${production}
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      STORGE_BUCKET: ${STORGE_BUCKET}
      SENDER_ID: ${SENDER_ID}
      NUXT_API_BASE: ${NUXT_API_BASE}
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G

  backend:
    build:
      context: .
      dockerfile: back.Dockerfile
    ports:
      - "9090:8000"
    volumes:
      - ./back:/app
    networks:
      default: null
    environment:
      TOGETHER_API_KEY: ${TOGETHER_API_KEY}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      production_debug: ${production_debug}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

networks:
  default:
    name: ${COOLIFY_NETWORK:-coolify_network}
    external: true
```

### Exception or Error

Frontend logs:

```log
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-07-10T11_17_24_244Z-debug-0.log
npm error code ENOENT
npm error syscall open
npm error path /app/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/app/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent

npm error A complete log of this run can be found in: /root/.npm/_logs/2024-07-10T11_18_24_943Z-debug-0.log
```

backend logs

```log
python: can't open file '/app/manage.py': [Errno 2] No such file or directory
python: can't open file '/app/manage.py': [Errno 2] No such file or directory
python: can't open file '/app/manage.py': [Errno 2] No such file or directory
python: can't open file '/app/manage.py': [Errno 2] No such file or directory
python: can't open file '/app/manage.py': [Errno 2] No such file or directory
python: can't open file '/app/manage.py': [Errno 2] No such file or directory
python: can't open file '/app/manage.py': [Errno 2] No such file or directory
python: can't open file '/app/manage.py': [Errno 2] No such file or directory
python: can't open file '/app/manage.py': [Errno 2] No such file or directory
```

### Version

v4.0.0-beta.306
