### ISSUE TITLE
[Bug]: traefik's reverse proxy not working while caddy works fine

### ISSUE THREAD

**Issue by AlcoholicCoder** [coollabsio/coolify#2800]
### Description

I've deployed simple server written in `dart` with `docker-compose`. It exposes port `8000`. 

My `docker-compose.yaml`:
```
services:

  dartserver:
    build: ./dartserver
    container_name: dart-server
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://0.0.0.0:8000/uptime"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
```

I've added a generated domain using coolify's in-built domain and re-deployed.
Now when i try to reach `http://XXX.sslip.io` it shows 404 error.
But when i add port after domain `http://XXX.sslip.io:8000` it starts working.

In my app config i've tried to add domain with port as coolify docs: `http://XXX.sslip.io:8000` and it's not working.

How can i solve this issue?

`docker ps` shows:
`0.0.0.0:8000->8000/tcp, :::8000->8000/tcp`

Telnet check using ssh:
```
root@localhost:~# telnet 0.0.0.0 8000
Trying 0.0.0.0...
Connected to 0.0.0.0.
Escape character is '^]'.
```

### Minimal Reproduction (if possible, example repository)

N/A

### Exception or Error

N/A

### Version

v4.0.0-beta.309

**Comment by AlcoholicCoder** [comment]
The `healthcheck` doesn't seem to work either. :/

**Comment by AlcoholicCoder** [comment]
Generated docker-compose file:
```
services:
  dartserver:
    build: ./dartserver
    container_name: dartserver-wookg4c-185238256611
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - '8000:8000'
    networks:
      wookg4c: null
    healthcheck:
      test:
        - CMD
        - wget
        - '--spider'
        - 'http://localhost:8000/uptime_robot'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-eg4k4co.entryPoints=http
      - traefik.http.routers.http-0-eg4k4co.middlewares=gzip
      - 'traefik.http.routers.http-0-eg4k4co.rule=Host(`XXX.sslip.io`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-eg4k4co.service=http-0-eg4k4co
      - traefik.http.services.http-0-eg4k4co.loadbalancer.server.port=8000
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 8000}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=http://XXX.sslip.io'
      - caddy_ingress_network=wookg4c
      - coolify.managed=true
      - coolify.version=4.0.0-beta.309
      - coolify.applicationId=11
      - coolify.type=application
      - coolify.name=dartserver-wookg4c-185238256611
      - coolify.pullRequestId=0
networks:
  wookg4c:
    name: wookg4c
    external: true
```
