### ISSUE TITLE
[Bug]: Permission denied on mongod.conf when using MongoDB service

### ISSUE THREAD

**Issue by ReCREWt-Philipp** [coollabsio/coolify#2862]
### Description

When I provide a mongod.conf definition via the "Custom MongoDB Configuration" field for the MongoDB service the service is not able to start due to a permission denied error (see "Exception or Error" below)

### Minimal Reproduction (if possible, example repository)

I created a completely new MongoDB service.

I added following configuration in the "Custom MongoDB Configuration" field:
```
net:
   tls:
      mode: requireTLS
      certificateKeyFile: /data/mongo/mongodb.pem
      CAFile: /data/mongo/mongodb-cert.crt
```

Maybe also important: 
On the localhost coolify is configured in root mode. The MongoDB service is installed on a remote server, where coolify is acting in non-root mode

### Exception or Error

```grep: /etc/mongo/mongod.conf: Permission denied
Error: EACCES: permission denied, open '/etc/mongo/mongod.conf'
error: unexpected "js-yaml.js" output while parsing config:
grep: /etc/mongo/mongod.conf: Permission denied
```

### Version

v4.0.0-beta.315
