### ISSUE TITLE
[Bug]: Plane - new install - sign up page

### ISSUE THREAD

**Issue by jocubeit** [coollabsio/coolify#2870]
### Description

On brand new one-click install of Plane, using the sslip.io url provided one cannot sign up or login:
Error message:
Instance not configured. Please contact your administrator.

What configuration is required beyond one-click install? I notice the URLs are empty in ENV VARS.

### Minimal Reproduction (if possible, example repository)

Add a service.
Choose Plane.
Deploy.
Go to sslip.io url.
Click on Sign up.
Provide email address.
Click Continue button.

### Exception or Error

Instance not configured. Please contact your administrator.

<img width="490" alt="Screenshot 2024-07-18 at 7 53 32 PM" src="https://github.com/user-attachments/assets/da4cfabc-40dc-4215-b7d4-0190683e6c4e">

### Version

v4.0.0-beta.315

**Comment by andrasbacsai** [comment]
I think you need to access it on `/god-mode` to get started.

**Comment by jocubeit** [comment]
Ok great thank you.

Now what do we need to do to configure a domain and SSL. For every other app I have simply created a traefik dynamic proxy config like so:

```yaml
http:
  routers:
    dashboard:
      rule: Host(`sub.domain.com`)
      service: projects
      entryPoints:
        - https
      tls:
        certresolver: letsencrypt
```
And then add the appropriate sub.domain A record pointing at the server IP in DNS settings.

This does not seem to work with the Plane one-click. The SSL cert is generated, but every URL results in a 404 Not Found HTTP error.

I really think the Coolify docs need to be updated for each service, so we can just follow the docs. Currently the docs seems to end at the Minio service.
