### ISSUE TITLE
[Bug]: Volume is created as Folder instead of file

### ISSUE THREAD

**Issue by ingokpp** [coollabsio/coolify#2888]
### Description

I've tried setting up a Wordpress instance using docker-compose with 2 Volumes.

Coolify shows the storage for uploads.ini as File Mount but I noticed (By looking through ssh) that it actually created a folder uploads.ini/. Also editing the content won't work.

### Minimal Reproduction (if possible, example repository)

Compose File:

```
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - wordpress-files:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - SERVICE_FQDN_WORDPRESS
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=$SERVICE_USER_WORDPRESS
      - WORDPRESS_DB_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 2s
      timeout: 10s
      retries: 10
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=$SERVICE_USER_WORDPRESS
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 20s
      retries: 10

```

uploads.ini (Put beside the compose file):

```
file_uploads = On
memory_limit = 500M
upload_max_filesize = 500M
post_max_size = 500M
max_execution_time = 600
```

### Version

v4.0.0-beta.317

### Cloud?

- [ ] Yes
- [X] No
