### ISSUE TITLE
[Bug]: Badly formatted env variables on docker compose file corrupt the whole resource beyond repair/access.

### ISSUE THREAD

**Issue by mvartuc** [coollabsio/coolify#2918]
### Description

I've encountered this bug while figuring out how to pass env variables to asp.net core containers.
My coolify resource, immediately upon fetching the compose file from the repo, gives out this error `Error: Array to String Conversion` and fails. Trying to navigate to the resource brings up this error page:
<img width="1261" alt="image" src="https://github.com/user-attachments/assets/105e9a40-539e-4747-ac7a-0799038fde4a">

The bug is pretty harmful considering it blocks access to the whole resource and prevents you from deleting or troubleshooting it.

### Minimal Reproduction (if possible, example repository)

1.a) Use the simple proof of concept repo that I've made:
https://github.com/mvartuc/coolify-env-bug-poc

1.b) or, create a directory with the following structure (no need to populate the Dockerfile since the bug is purely on the compose file level):
```
.
├── App
│  └── Dockerfile
└── docker-compose.yml
```
where the `docker-compose.yml` is as follows:
```
services:
  api:
    build:
      context: ./App
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - "CloudinarySettings__CloudName": ${Cloudinary__CloudName}
      - "CloudinarySettings__ApiKey": ${Cloudinary__ApiKey}
      - "CloudinarySettings__ApiSecret": ${Cloudinary__ApiSecret}
```

2) create a new docker compose based resource on your coolify dashboard and correct the default `docker-compose.yaml` to `docker-compose.yml`

3) observe the error

### Version

v4.0.0-beta.317

### Cloud?

- [ ] Yes
- [X] No
