### ISSUE TITLE
[Bug]: Bad Gateway on Deployed Docker Containers

### ISSUE THREAD

**Issue by yashkolambekar** [coollabsio/coolify#3009]
### Description

I receive `Bad Gateway` on every page which is deployed using a docker container using docker-compose. Even the plain nginx server without any modifications is not running. Tried php:8.3-apache and ubuntu/apache as well
This only happens with docker and not with node apps from github or the premade services like glances

And, it is accesible on the localhost though, if I get into terminal and do `curl localhost:8888` it works 

### Minimal Reproduction (if possible, example repository)

docker compose file
```
version: '3.8'
services:
  server:
    image: 'nginx:latest'
    container_name: nginxserver
    ports:
      - '8888:80'
```

Domain:
https://nginx.example.com:8888

### Exception or Error

Bad Gateway
![image](https://github.com/user-attachments/assets/b39a7f37-8077-45e7-a787-3a68d283d7d1)

### Version

v4.0.0-beta.319

### Cloud?

- [ ] Yes
- [X] No
