### ISSUE TITLE
[Bug]: Coolify ignores the selected network and uses the `coolify` network

### ISSUE THREAD

**Issue by Telokis** [coollabsio/coolify#3041]
### Description

It's already happened 4 times that, when creating my resource, I select my own network but when checking "Connect To Predefined Network", the network the container is attached to is `coolify`.  
The first time I thought I simply selected the wrong network without paying attention but since then it's happened multiple times more.

### Minimal Reproduction (if possible, example repository)

- Go to `Projects`
- Create a new project
- Go into `Production`
- Go to `Add new resource`
- Select `Docker Compose`
- Select your network that is NOT `coolify`. (`web`, in my case)
- Paste the following test `docker-compose.yml`:

```yml
services:
  glances:
    image: 'nicolargo/glances:latest'
    restart: unless-stopped
    environment:
      - GLANCES_OPT=-w
      - SERVICE_FQDN_GLANCES_61208
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    pid: host
    privileged: true
```

- Check `Connect To Predefined Network` <-- Very important, we want to connect to the `web` network
- Click `Deploy` to create your container
- Use `ssh` to connect to the server on which you deployed the service
- Use `docker ps -a `grep glances` to find the container we just created
- Use `docker inspect glances-<uid>` to check the details of the container
- At the bottom, in the `"Networks"` section, notice that the container is connected to the `coolify` network and not to `web` as configured.

![image](https://github.com/user-attachments/assets/53c46932-e609-4594-b077-7ef553f35a58)

### Version

v4.0.0-beta.319

### Cloud?

- [X] Yes
- [ ] No
