### ISSUE TITLE
[Bug]: Can't update redis password

### ISSUE THREAD

**Issue by Vahor** [coollabsio/coolify#3104]
### Description

The default password is great, but I'd like to change it to use a team variable. But changing the password does not seem possible.

The end goal here is to update the password to a team variable. (or export the redis password to a team variable to reuse it on other services)

### Minimal Reproduction (if possible, example repository)

Create a redis instance
There's no option to update the password. 

What I tried:

1. Add `requirepass` in `redis.conf` :x:

I tried to update the redis config by setting  [requirepass](https://redis.io/docs/latest/operate/oss_and_stack/management/security/#authentication)`requrirepass [password]` in the `Custom Redis Configuration` field. But with this change I have an error
```
1:C 16 Aug 2024 12:57:59.220 # Fatal error, can't open config file '/usr/local/etc/redis/redis.conf': Permission denied
```
To fix that I applied `chmod 644 redis.conf` (in /data/coolify/databases/vgcgosoc4c4g08scockcc04c/redis.conf)

But it does not work

Note: Even if it worked, as you'll see in 2., `requirepass` is passed in arguments, I suppose it would override the config set in redis.conf (same issue as https://github.com/coollabsio/coolify/issues/2637)

2. Add env var `REDIS_PASSWORD` :x:

From what I see in the docker-compose file
```
command: 'redis-server /usr/local/etc/redis/redis.conf --requirepass YO909xY0iISWtiK3IWlHRmQEQkep0TEJWheyTilMztjfho0Q5gr058UxQ57t2L1M --appendonly yes'
        container_name: vgcgosoc4c4g08scockcc04c
        environment:
            - REDIS_PASSWORD=YO909xY0iISWtiK3IWlHRmQEQkep0TEJWheyTilMztjfho0Q5gr058UxQ57t2L1M
```

the password is defined in an env var but also in the command. So I first tried to update the env var using coolify ui. 
But by doing so, the variable is always set to ''. I tried using team variable and hardcoded ones, same issue.

3. Change the command directly :x:

As seen in 2., the command has requirepass hardcoded, so why no edit it there ?
The issue here is that the dockerfile is generated on each restart so our changes are not persisted.

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No
