### ISSUE TITLE
[Bug]: "Preserve Repository During Deployment" option has trouble with directories

### ISSUE THREAD

**Issue by hugodu69** [coollabsio/coolify#3114]
### Description

the new option "Preserve Repository During Deployment", recently implemented as a solution to the problem explained here : https://github.com/coollabsio/coolify/issues/1996, is really helpful, thanks !

but I encountered two problems with it : 

1. the first is this message : "`cannot overwrite directory "/data/coolify/applications/bccw40sk84oks0ogc8k0oogo/BACK/db/migration.sql" with non-directory "/data/coolify/applications/bccw40sk84oks0ogc8k0oogo"`"   
   
   -> if i check the coolify repo on the server at the first step of creation of a new app, the folder "./db/migration.sql" is already created, as a folder, not a file. Then, when i hit "deploy" it must try to replace this repo with the file from github, and it fails

2. the second is when i updated my github repo by renaming a folder, the change propagate in the coolify repo, but not as expected : instead of renaming the folder, it created a new one with the new name, while keeping the old one

### precision :

The first error is based on a non-conventional configuration of my docker-compose.yml file : i use a bind mounting file, which is not explicitly allowed nor disallowed in the doc, i believe : 

```
services:
  myservice:
    image: myimage
    volumes:
      - ./path/to/file1.txt:/path/in/container/file2.txt
```
from this, coolify will create a directory ./path/to/file.txt/ instead of a file, but i don't know if this i an error. So here, the issue that i'm reporting, is not about having created a folder instead of a file, it's about not being able to overwrite it with the right file when copying files from github

### first error, cannot overwrite a directory with a file : 

1. having a docker-compose.yml file with a bind mount file :   
   ```
   services:
     bdd:
       image: "postgres:14-alpine"
       volumes:
         - ./BACK/db/migration.sql:/docker-entrypoint-initdb.d/create_tables.sql
   ```
2. creating a new application from a public github repo with this docker-compose file
3. wait for loading docker files to complete
4. check the "Preserve Repository During Deployment" setting
5. hit the "deploy" button
6. see the error "`cannot overwrite directory "/data/coolify/applications/m04g4w0cww8cwwwk0scs08sw/BACK/db/migration.sql" with non-directory "/data/coolify/applications/m04g4w0cww8cwwwk0scs08sw"`"

### second error, cannot rename a directory, create a new one instead : 

7. (resolve previous error by deleting migration.sql/ on server then deploy again, maybe multiple time before it works)
8. rename a directory in local and push to github
9. redeploy
10. error : the directory is not renamed, a new one is created

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No
