### ISSUE TITLE
[Bug]: Cannot share a volume between services in docker-compose

### ISSUE THREAD

**Issue by Signum** [coollabsio/coolify#3126]
### Description

I would like to have a persistent volume that can be accessed by 2 services in a docker-compose/stack.

The idea is to add an SFTP service to the stack so that a web developer can access the DocumentRoot of another web service to put files there.

Unfortunately Coolify rejects that change: "Duplicate entry found. Please use a different name."

### Minimal Reproduction (if possible, example repository)

```yaml
services:
  backend:
    image: example/database
    volumes:
      - db-data:/etc/data

  backup:
    image: backup-service
    volumes:
      - db-data:/var/lib/backup/data

volumes:
  db-data:
```

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by peaklabs-dev** [comment]
@Signum This should be working, as I can not reproduce the error with this compose file:
```
services:
  backend:
    image: 'redis:alpine'
    volumes:
      - 'db-data:/etc/data'
  backup:
    image: 'redis:alpine'
    volumes:
      - 'db-data:/var/lib/backup/data'
volumes:
  db-data: null
  ```

**Comment by Signum** [comment]
It took me a bit to reproduce it. But now I managed to. Try this:

Create a new stack from the app store for "Wordpress with MariaDB". That will properly deploy and lead to this stack:

```yaml
services:
  wordpress:
    image: 'wordpress:latest'
    volumes:
      - 'wordpress-files:/var/www/html'
    environment:
      - SERVICE_FQDN_WORDPRESS
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=$SERVICE_USER_WORDPRESS
      - WORDPRESS_DB_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mariadb
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10
  mariadb:
    image: 'mariadb:11'
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=$SERVICE_USER_WORDPRESS
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 5s
      timeout: 20s
      retries: 10
```

Everything works.

Now I am clicking "Edit Compose File" and am adding an sftp-server to that stack and am deploying…

```yaml
  sftp-server:
      image: emberstack/sftp
      environment:
        - USERS=demo:demo:1001:1001
      expose:
        - "2200"
      volumes:
        - wordpress-files:/home/demo/sftp
      ports:
        - "2200:2200"
```

That also works.

Then I realize that I want to mount the "wordpress-files" volume not at /home/demo/sftp but rather at /home/demo/web. So I'm changing the "sftp-server" service (actually only the "volumes:" definition) to:


```yaml
  sftp-server:
      image: emberstack/sftp
      environment:
        - USERS=demo:demo:1001:1001
      expose:
        - "2200"
      volumes:
        - wordpress-files:/home/demo/web
      ports:
        - "2200:2200"
```

I click on "Save" and am reliably getting the "Duplicate entry found. Please use a different name." error message. However when I change the path back to "/home/demo/sftp", I can save.

So basically sharing a volume works the first time. But if you decide to change the path where it gets mounted into a further service, you get this error.

Could you please try this?
