### ISSUE TITLE
[Bug]:  environment variable is undefined when in production

### ISSUE THREAD

**Issue by Salman9000** [coollabsio/coolify#3262]
### Description

environment variable is undefined when in production

```
  const APP_ID = process.env.NEXT_PUBLIC_APP_ID;
    const [loading, setLoading] = useState(true);
  
    useEffect(() => {
      window.fbAsyncInit = function () {
        window.FB.init({
          appId: APP_ID,
          cookie: true,
          xfbml: true,
          version: 'v19.0',
        });

      window.FB.AppEvents.logPageView();
      window.FB.getLoginStatus(function (response: any) {
        setLoading(false);
        console.log(APP_ID);
        console.log('log status change');
        console.log(JSON.stringify(response));
      });
    };

    (function (d, s, id) {
      var js: HTMLScriptElement,
        fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {
        return;
      }
      js = d.createElement(s) as HTMLScriptElement;
      js.id = id;
      js.src = 'https://connect.facebook.net/en_US/sdk.js';
      if (fjs && fjs.parentNode) {
        fjs.parentNode.insertBefore(js, fjs);
      }
    })(document, 'script', 'facebook-jssdk');
  }, [process.env.NEXT_PUBLIC_APP_ID]);
```

### Minimal Reproduction (if possible, example repository)

Create .env file in local. Add your environment variable value.
Create NEXT_PUBLIC_APP_ID env in coolify
![image](https://github.com/user-attachments/assets/44997123-163a-432c-8bea-e72e5a9d3b36)

### Exception or Error

```
window.FB.getLoginStatus(function (response: any) {
        setLoading(false);
        console.log(APP_ID);
        console.log('log status change');
        console.log(JSON.stringify(response));
      });
```
      
      APP_ID is undefined in production 

My docker compose file
![image](https://github.com/user-attachments/assets/d9f606f3-4d8d-45f7-9f10-bf5af96265c5)

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [ ] No

**Comment by djsisson** [comment]
can you confirm that in your docker compose you only have the var listed with no value set?
if thats the case then thats why it isnt working, youre inject blank values into your environment
have you tried setting them like this - 'NEXT_PUBLIC_APP_ID=${NEXT_PUBLIC_APP_ID}'

**Comment by Salman9000** [comment]
This is my docker file
```
services:
  # web:
  #   build:
  #       context: .
  #   ports:
  #     - 8081:8081
  #   volumes:
  #     # - ./pb_migrations:/pb/pb_migrations
  #     # - ./pb_hooks:/pb/pb_hooks
  #     - ./pb_data:/pb/pb_data
  #   healthcheck:
  #     test: curl --fail http://localhost:8001/api || exit 1
  #     interval: 40s
  #     timeout: 40s
  #     retries: 3
  #     start_period: 60s
  next:
    build:
        context: ./nextjs-docker
    ports:
      - ${HOST_PORT}:3001
    environment:
      - OPENAI_API_KEY
      - INNGEST_SIGNING_KEY
      - INNGEST_EVENT_KEY
      - INNGEST_SERVE_PATH
      - NODE_ENV=production
      - WA_PHONE_NUMBER_ID
      - CLOUD_API_ACCESS_TOKEN
      - CLOUD_API_VERSION
      - USER_ACCESS_TOKEN
      - NEXT_PUBLIC_AXIOM_TOKEN
      - NEXT_PUBLIC_AXIOM_DATASET
      - NEXT_PUBLIC_APP_ID
      - APP_SECRET
      - BUSINESS_ID
      - NEXT_PUBLIC_PB_URL
      - APP_URL
      - NEXT_PUBLIC_APP_URL
      - RESEND_API_KEY
```
