### ISSUE TITLE
[Bug]: COOLIFY_CONTAINER_NAME does not match any of container names

### ISSUE THREAD

**Issue by fipnooone** [coollabsio/coolify#3280]
### Description

Created containers:
<img width="986" alt="coolify-containers" src="https://github.com/user-attachments/assets/7e3f1db6-45d1-435c-8129-ba64bd7dfa82">

Docker inspect for node service show this env:
```
"Env": [
               // other
                "COOLIFY_CONTAINER_NAME=lck0o48-061119181951",
                // other
            ],
```

Docker inspect for mysql service:
```
"Env": [
               // other
                "COOLIFY_CONTAINER_NAME=lck0o48-061119181951",
                // other
            ],
```

Shouldn’t all containers have the same identifier? That is, 061119181951 in this case.

### Minimal Reproduction (if possible, example repository)

docker-compose file:
```
services:
  staging-project-nginx:
    image: nginx:alpine
    container_name: staging-project-nginx
    depends_on:
      - staging-project-node
    ports:
      - '8001:80'
    volumes:
      - './:/var/app'
      - './deploy/nginx/staging:/etc/nginx/conf.d/'
    networks:
      - staging-project-network
  staging-project-node:
    container_name: staging-project-node
    depends_on:
      - staging-project-mysql
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - '${DEPLOYMENT_PROXY_PORT:-3201}:3000'
    working_dir: /app
    networks:
      - staging-project-network
    command: pnpm run prisma:migrate:deploy
  staging-project-mysql:
    image: mysql:8.4
    container_name: staging-project-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '3306:3306'
    volumes:
      - 'staging-project-mysql:/var/lib/mysql'
    networks:
      - staging-project-network

networks:
  staging-project-network:
    name: staging-project-network
    internal: true
    driver: bridge
volumes:
  staging-project-mysql:
    driver: local
```

Part of my env file:
```
DB_DATABASE=databasename
DB_USERNAME=user
DB_PASSWORD=password
MYSQL_ROOT_PASSWORD=password
DB_HOST=staging-project-mysql-${COOLIFY_CONTAINER_NAME}
DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@${DB_HOST}:3306/${DB_DATABASE}
```

### Exception or Error

<img width="1047" alt="Screenshot 2024-09-01 at 13 54 51" src="https://github.com/user-attachments/assets/74626558-cfca-4beb-a510-ae9c4b47eb5f">

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No
