### ISSUE TITLE
Add watchtower service

### ISSUE THREAD

**Issue by Soneji** [coollabsio/coolify#329]
Watchtower can update container images automatically

Info: https://github.com/containrrr/watchtower
Configuration options: https://containrrr.dev/watchtower

My personal watchtower `docker-compose.yml` config

```yml
version: "3"
services:
 watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -s "0 4 * * 6" --cleanup
```

Maybe useful to keep images up to date?

Or could be used as a one-shot option in coolify, to update all the images as a setting in the dashboard. 

This could be useful for updating for example the database versions
