### ISSUE TITLE
[Bug]: Preview deployments on Docker Compose based apps end with Array to string conversion

### ISSUE THREAD

**Issue by gabrielalmeida** [coollabsio/coolify#3292]
### Description

Preview Deployments with Docker Compose fails with `Array to string conversion` during build. 

Non Preview Deployments builds without issues.

Related #2471 #2918 #2336

### Minimal Reproduction (if possible, example repository)

Create a Docker Compose app (done via GitHub app)
Configure app (URLs, env vars)
Create a preview deployment manually

### Exception or Error

```
Switched to branch 'pr-889-coolify'

[2024-Sep-03 01:29:07.884748]

[COMMAND] docker exec jckc0g8kwo488484wg8gkw8o bash -c 'cd /artifacts/jckc0g8kwo488484wg8gkw8o && git log -1 5b31d19bdb07338db55b6f8a17b141fd22243f7f --pretty=%B'
[OUTPUT]
[coolify] Preview environments

[2024-Sep-03 01:29:08.351252]

[COMMAND] docker exec jckc0g8kwo488484wg8gkw8o bash -c 'stat -c '%F' /artifacts/jckc0g8kwo488484wg8gkw8o/packages/hasura'
[OUTPUT]
directory

[2024-Sep-03 01:29:13.510930] Oops something is not okay, are you okay? 😢

[2024-Sep-03 01:29:13.513132] Array to string conversion
```

Besides `v4.0.0-beta.325`, I've rollbacked to `v4.0.0-beta.324` and `v4.0.0-beta.323` and got the same error. I wasn't getting this error on those versions earlier this month, I wasn't able to pinpoint the root cause but I suspect it was introduced by changes to my `docker-compose.yaml` that coolify is now failing to parse or to the usage of multiple FQDNs.

### Version

v4.0.0-beta.325

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
Can you please give me an example compose file?

**Comment by gabrielalmeida** [comment]
Unfortunately I don't have a minimal reproducible example, here is the docker-compose as is:

<details>
  <summary>docker-compose.preview.yaml</summary>

```yaml
services:
  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile.dashboard
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - GITHUB_SHA=${GITHUB_SHA}
        - NEXT_PUBLIC_HASURA_ENDPOINT=${NEXT_PUBLIC_HASURA_ENDPOINT}
        - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
    environment:
      - HASURA_ENDPOINT=http://hasura:8080/v1/graphql
      - S3_ENDPOINT=http://minio:9000
      - TEMPORAL_ADDRESS: temporal:7233
    user: 0:0
    env_file:
      - .env
      - .env.development      
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - hasura_console
  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile.worker
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file: .env.development
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      DATABASE_URL: postgres://postgres:XXXXX@postgres:5432/postgres
    depends_on:
      - temporal
    restart: unless-stopped
  postgres:
    build:
      context: .
      dockerfile: pg-Dockerfile
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', 'postgres', '-U', 'postgres']
    environment:
      POSTGRES_PASSWORD: XXXXX
  hasura:
    image: hasura/graphql-engine:v2.8.1
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      options:
        max-size: 100m
        max-file: 10
    healthcheck:
      test: timeout 1s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256", "key": "XXXXXXXXXX" }'
      HASURA_GRAPHQL_CORS_DOMAIN: '*'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      # Disable server console, because only hasura-cli console can handle migrations
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: XXXX
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:XXXXXX@postgres:5432/postgres

      ACTION_BASE_URL: http://host.docker.internal:3000/dashboard/api
      XXXX_WS_DOCKER: http://host.docker.internal:8088

    extra_hosts:
      - host.docker.internal:host-gateway
  hasura_console:
    image: hasura/graphql-engine:latest.cli-migrations-v3
    working_dir: /root/hasura
    healthcheck:
      test: timeout 1s bash -c ':> /dev/tcp/127.0.0.1/9695' || exit 1
    entrypoint: sh -c "hasura-cli migrate apply --skip-update-check --all-databases && hasura-cli metadata apply --skip-update-check && hasura-cli seeds apply --skip-update-check --all-databases && hasura-cli console --address 0.0.0.0 --api-host https://hasura-api.preview.XXXX.com --api-port 443 --console-hge-endpoint https://hasura.preview.XXXX.com --skip-update-check --no-browser"
    ports:
      - 9695:9695
      - 9693:9693
    environment:
      - HASURA_GRAPHQL_ENDPOINT=http://hasura:8080
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_SECRET}
    env_file:
      - .env
      - .env.development
    volumes:
      - ./packages/hasura:/root/hasura
    restart: unless-stopped
    depends_on:
      hasura:
        condition: service_healthy
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped
  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
      - minio_config:/config
    environment:
      MINIO_ROOT_USER: XXXX
      MINIO_ROOT_PASSWORD: XXXX
    command: server --console-address ":9001" /data

  minio-client:
    image: minio/mc
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add XXXX http://host.docker.internal:9000 XXXX XXXX) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb XXXX/XXXX-media;
      sleep infinity;
      "
  temporal:
    # https://hub.docker.com/r/temporalio/server/tags
    image: temporalio/server:latest
    restart: unless-stopped
    user: 0:0 # running as root to avoid permission issues with writing to /tmp/sqlite/db
    entrypoint: sh -c "temporal server start-dev --namespace=default --db-filename=/tmp/sqlite/db --ip=0.0.0.0 & until (/root/temporal/search-attributes.sh) do echo '...waiting' && sleep 1; done; wait"
    volumes:
      - ./apps/temporal/search-attributes.sh:/root/temporal/search-attributes.sh
    tmpfs:
      - /tmp/sqlite
    ports:
      - 7233:7233
      - 8888:8233

volumes:
  db_data:
  es_data:
  minio_data:
  minio_config:
```
</details>

**Comment by kmbuthia** [comment]
Hi @gabrielalmeida something you could try is declare the `environment` variables in a uniform way.
The syntax that works for me (on multiple docker files across different resources/projects on Coolify) is:

```
environment:
  - 'VAR_NAME=VAR_VALUE'
```

Mixing styles/syntax could cause things to break e.g. the dashboard service above has

```
environment:
      - HASURA_ENDPOINT=http://hasura:8080/v1/graphql
      - S3_ENDPOINT=http://minio:9000
      - TEMPORAL_ADDRESS: temporal:7233
```

Here, `TEMPORAL_ADDRESS` is declared/written differently from the other options above it and that could cause the issue.

The other syntax of `VAR_NAME: VAR_VALUE` should also work but mixing them both under one `environment` I think confuses Coolify.

**Comment by gabrielalmeida** [comment]
@kmbuthia Hi! I've updated to [v4.0.0-beta.341](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.341) and tried a bunch of different permutations after your suggestions, all of them still resulted in the `Array to string conversion` message.

* `KEY: VALUE`
* `- KEY=VALUE`
* `- 'KEY=VALUE'`
* `- 'KEY="VALUE"'`

Note that all of those generated a valid YAML file based on `yamllint`. Each of them were used consistently throughout the compose file and re-deployed individually.

**Comment by kmbuthia** [comment]
@gabrielalmeida I just noticed this is in reference to preview deployments and not "regular" docker-compose deployments. I haven't started using preview deployments yet but chances are there is a bug with this feature.

**Comment by Ymirke** [comment]
I had this issue, and had a hard time understanding what was going on. 

Turns out symphony / some php dependency can't parse the docker-compose.yaml file fully.

I think a more long term fix from coolify's side is to swap out the library used to parse docker-compose.yaml files. 

Here are changes suggested by chatgpt to fix it, I got it working after implementing them:

## 1 Extended depends_on Objects
Example that triggers the notice
```yaml
depends_on:
  db:
    condition: service_started
    required: true
```

Why it is a problem
Coolify’s PHP parser stores depends_on as a string list. When it receives a mapping (db: {condition:…}) it tries to concatenate that mapping as if it were a string, leading to the warning. In practice Coolify also ignores the condition: logic, so the extra detail buys nothing.

Safer alternative
```yaml
depends_on:
  - db
```

## 2 Long-Form ports, volumes, or networks

Notice-producing form

```yaml
ports:
  - mode: ingress
    target: 80
    published: "8080"
    protocol: tcp
```

Why it is a problem
The PHP helper expects each item to be a scalar (e.g. "8080:80"). Passing a mapping causes the conversion notice and may drop the port from the final container spec.

Safer alternative
```yaml
ports:
  - "8080:80"
```
Apply the same idea to volumes: and service-level networks:.

## 3 Array-Form command or healthcheck.test
Notice-producing form
```yaml
command:
  - sh
  - -c
  - ./entrypoint.sh
```

Why it is a problem
Symfony YAML turns that list into a PHP array. The downstream DTO calls string helpers (trim, explode) on it and emits the notice. In some cases the command is truncated, so the container exits immediately.

Safer alternative
```yaml
command: >-
  sh -c ./entrypoint.sh
The folded scalar (>-) remains readable while satisfying the scalar requirement.
```

## 4 Empty Mapping Stubs {} Notice-producing form
```yaml
volume: {}
```

Why it is a problem
{} is an empty map, which becomes a PHP array. If the value flows into a string context (for example, label templating) Coolify logs the notice. The stub is usually added by formatters but serves no purpose.

Safer alternative
Remove the key entirely.
```yaml
# nothing here; Compose will use defaults
```

The same applies to unused top-level sections such as configs: {} or secrets: {}.

## 5 Implicit Networks and Non-spec restart Values

Notice-producing form

```yaml
restart: never      # non-spec string
networks:
  - coolify-proxy   # declared nowhere; assumed internal
```

Why it is a problem
restart—anything other than "no", "on-failure", "always", or "unless-stopped" is stored as a raw string. The parser later attempts to treat it as a constant and warns.

Networks—if an external network is referenced but not marked external: true, Coolify may create a new internal network instead of joining the proxy, breaking routing.

Safer alternative
```yaml
restart: "no"

networks:
  coolify-proxy:
    external: true
```
