### ISSUE TITLE
[Bug]: can't mount volumes with external drivers in compose files

### ISSUE THREAD

**Issue by RayBB** [coollabsio/coolify#3303]
### Description

When I try to mount a volume from an external driver (rclone in this case) it doesn't work. It just shows an empty folder.

more info at https://rclone.org/docker/

### Minimal Reproduction (if possible, example repository)

```
sudo mkdir -p /var/lib/docker-plugins/rclone/config
sudo mkdir -p /var/lib/docker-plugins/rclone/cache

ln -s ~/.config/rclone/rclone.conf /var/lib/docker-plugins/rclone/config

## Choose the right tag here for your machine
docker plugin install rclone/docker-volume-rclone:arm64 \
  --alias rclone \
  --grant-all-permissions \
  args="-v --allow-other"
docker plugin enable rclone

docker volume create rclone-http -d rclone -o type=http -o http-url=https://beta.rclone.org/test/

# See it working by opening that folder in filebrowser locally without coolify
docker run --rm \
  -v rclone-http:/srv/httptesting \
  -p 8888:80 \
  -e FB_NOAUTH=noauth \
  --name filebrowser filebrowser/filebrowser:latest
```

However, it doesn't work when we use a compose file in coolify
```
services:
  filebrowser:
    image: 'filebrowser/filebrowser:latest'
    environment:
      - SERVICE_FQDN_FILEBROWSER2
      - PUID=1000
      - PGID=1000
      - FB_NOAUTH=noauth
    volumes:
      - 'rclone-http:/srv/httptesting'
volumes:
  rclone-http:
    external: true
```

I just get an empty folder.

I think this is a bug.

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by RayBB** [comment]
Actually, I think it's just that external volumes aren't supported in general.

If I try to inline the external part like so:
```
services:
  filebrowser:
    image: 'filebrowser/filebrowser:latest'
    environment:
      - SERVICE_FQDN_FILEBROWSER2
      - PUID=1000
      - PGID=1000
      - FB_NOAUTH=noauth
    volumes:
      - type: volume
        source: rclone-http
        target: /srv/httptesting
        external: true
```

I get this error:

`validating /data/coolify/services/c88wks0cgc0kgwcooo8sscgg/docker-compose.yml: services.app.volumes.2 Additional property external is not allowed `
