### ISSUE TITLE
[Bug]: network_mode: host is not supported anymore.

### ISSUE THREAD

**Issue by lohrbini** [coollabsio/coolify#3336]
### Description

Stacks which has been created before updating to v329 are able to run docker compose files with the `network_mode: host` option. After updating to version 329 due to a bug with changing volumes the creation of new compose stacks with host_mode is not possible anymore

### Minimal Reproduction (if possible, example repository)

1. Create a new compose file

```
services:
  cloudflare-ddns:
    image: 'harbor.skl.works/library/cloudflare-ddns6:v1.0.0'
    network_mode: host
    restart: always
    environment:
      - 'CLOUDFLARE_API_TOKEN=${CF_API_KEY}'
      - RECORD_NAME=fml6.skl.works
      - UPDATE_INTERVAL=10
```
2. Add the needed environment key
3. Deploy the application

```
Saved configuration files to /data/coolify/services/ps88wkcwo4g408g0ggw8gkgk.
Creating Docker network.
Starting service.
Pulling images.
service cloudflare-ddns declares mutually exclusive `network_mode` and `networks`: invalid compose project
```

### Exception or Error

```
Saved configuration files to /data/coolify/services/ps88wkcwo4g408g0ggw8gkgk.
Creating Docker network.
Starting service.
Pulling images.
service cloudflare-ddns declares mutually exclusive `network_mode` and `networks`: invalid compose project
```

### Version

v4.0.0-beta.329

### Cloud?

- [ ] Yes
- [X] No
