### ISSUE TITLE
[Bug]: Plunk API does not work, so Plunk sing-up is broken (parser issue)

### ISSUE THREAD

**Issue by peaklabs-dev** [coollabsio/coolify#3351]
### Minimal Reproduction (if possible, example repository)

1. Install the new Plunk service via one click install (use the `next` branch, as I already fixed another issue for plunk)
2. Look at the `API_URI=` it is empty instead of being filled like this:  `API_URI=${SERVICE_FQDN_PLUNK}/api`

-> I think this is a parser issue. 

Edit: As reported below and by Darren on discord it should be URL here not FQDN, so  `API_URI=${SERVICE_URL_PLUNK}/api` , I think something with the switch up between the tow is still not properly switched. Also all service temlate use FQDN we should switch them to URL and add a condition to the UI to display it correctly, so URL form now on (in the link on the top left...) and FQDN for older ones.

### Version

v4.0.0-beta.330

### Cloud?

- [ ] Yes
- [X] No

**Comment by djsisson** [comment]
@peaklabs-dev 
i did not find any issue wit h this, please make sure you are on the current version:

however there is a different issue

1) the dbname is not set right neither is the healthcheck on the db

2) if youre using a dns proxy you get cors errors due to the FQDN being http but youre on https... so below is an ammended compose

please note after initial run some env get baked in, so you have to delete and restart

```yaml
version: '3'
services:
  plunk:
    image: driaug/plunk
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SERVICE_FQDN_PLUNK
      - 'REDIS_URL=redis://redis:6379'
      - 'DATABASE_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgresql/${POSTGRES_DB}?schema=public'
      - 'JWT_SECRET=${SERVICE_PASSWORD_JWT_SECRET}'
      - 'AWS_REGION=${AWS_REGION}'
      - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'
      - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
      - 'AWS_SES_CONFIGURATION_SET=${AWS_SES_CONFIGURATION_SET}'
      - 'NEXT_PUBLIC_API_URI=https://${SERVICE_URL}/api'
      - 'APP_URI=https://${SERVICE_URL}'
      - 'API_URI=https://${SERVICE_URL}/api'
      - DISABLE_SIGNUPS=False
    entrypoint:
      - /app/entry.sh
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '--spider'
        - 'http://127.0.0.1:3000'
      interval: 2s
      timeout: 10s
      retries: 15
  postgresql:
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - 'POSTGRES_DB=${POSTGRES_DB:-plunk}'
    volumes:
      - 'postgresql-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${SERVICE_USER_POSTGRES} -d ${POSTGRES_DB}'
      interval: 5s
      timeout: 10s
      retries: 20
  redis:
    image: 'redis:7.4-alpine'
    volumes:
      - 'redis-data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - PING
      interval: 5s
      timeout: 10s
      retries: 20
```

i cant fully check as i dont have aws key which is where it gets stuck, no cors errors and env are all valid
