### ISSUE TITLE
[Bug]: Docker-compose volume file source mounting as directory

### ISSUE THREAD

**Issue by nickhid** [coollabsio/coolify#3375]
### Description

When attempting to mount a file with docker-compose, Coolify mounts as a directory instead.

### Minimal Reproduction (if possible, example repository)

Example docker-compose.yml

```
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - type: bind
        source: ./config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        is_directory: false

```

Issue occurs when following [Coolify documentation](https://coolify.io/docs/knowledge-base/docker/compose), including with `is_directory:false`, and with the less verbose 
` 
volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
`

Workaround:

Project -> Configuration -> Storages -> Find Directory Mount & `Convert to File` -> Copy and paste file -> Save & redeploy

### Exception or Error

Result:

![image](https://github.com/user-attachments/assets/c6f1f2c0-2ecc-4b7d-9771-78ab57bc08ae)

Error:

> Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/data/coolify/applications/jw8088gk80s0o44c8ogsoc4w/config/prometheus.yml" to rootfs at "/etc/prometheus/prometheus.yml": mount /data/coolify/applications/jw8088gk80s0o44c8ogsoc4w/config/prometheus.yml:/etc/prometheus/prometheus.yml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

### Version

v4.0.0-beta.331

### Cloud?

- [ ] Yes
- [X] No
