### ISSUE TITLE
[Bug]: MongoDB Initialization Script not executed in Coolify Deployment

### ISSUE THREAD

**Issue by volodymyr-sch** [coollabsio/coolify#3392]
### Description

I'm encountering an issue with MongoDB initialization in my Coolify deployment via Docker compose. The mongo-init.js script is not executing during startup, apparently because it's being interpreted as a directory rather than a file.

### Minimal Reproduction (if possible, example repository)

Here is my docker-compose file:
```
version: '3.8'
services:
  mongodb-dev:
    image: mongo:latest
    container_name: mongodb-dev
    restart: always
    # env_file: ${ENV_FILE:-.env}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro //This should be executed by Mongo during startup
    networks:
      - my-network

  my-nest-backend:
    build: .
    container_name: my-nest-backend
    ports:
      - '${PORT}:${PORT}'
      - '9229:9229'
    depends_on:
      - mongodb-dev
    networks:
      - my-network
    # env_file: ${ENV_FILE:-.env}
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      MONGODB_HOST: ${MONGODB_HOST}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      MONGO_URI: mongodb://${DATABASE_USER}:${DATABASE_PASS}@${MONGODB_HOST}:27017/${DATABASE_NAME}?authSource=admin&directConnection=true
    command: npm run start:debug

volumes:
  mongodbdata:

networks:
  my-network:
    driver: bridge
```

### Exception or Error

<img width="796" alt="image" src="https://github.com/user-attachments/assets/5792ac44-404e-4a92-943a-db9ff65894d4">

By checking the file in the path:
```
/data/coolify/applications/gg4o4w4ko4okc00cwwso4kg8# cat mongo-init.js
cat: mongo-init.js: Is a directory
```

### Version

v4.0.0-beta.325

### Cloud?

- [ ] Yes
- [X] No

**Comment by djsisson** [comment]
try change to

```yaml
volumes:
    type: bind
    source: ./mongo-init.js
    target: /docker-entrypoint-initdb.d/mongo-init.js:ro
```
