### ISSUE TITLE
[Bug]: Using both image: and build: in a Docker Compose service breaks rolling updates

### ISSUE THREAD

**Issue by vanWittlaer** [coollabsio/coolify#3408]
### Description

If an image: "image" is specified in a docker compose service together with a build: instruction (meaning "build the container from a dockerfile and store it as "image""), rollback images are not created

Background: We use a docker compose setup, where services reuse images built in previous steps. Thus we do need to use build: and image: tags in one and the same service to be able to refer to the image in a later service.

Note: This might (!) be related to https://github.com/coollabsio/coolify/discussions/2824, but my point here is we are using/setting image (!) names, and not container names. IMHO the conclusion in the mentioned discussion might be erroneous.

### Minimal Reproduction (if possible, example repository)

Create a resource of type Private Repository with the Docker Compose build pack.

This docker-compose.yml generates a rollback image correctly:
```yaml
services:
    shell:
        build:
            context: .
            dockerfile: docker/Dockerfile
```

This docker-compose.yml does **not** generate a rollback image:
```yaml
services:
    shell:
        image: local/shell:latest
        build:
            context: .
            dockerfile: docker/Dockerfile
```

### Exception or Error

There is no rollback image stored.

### Version

v4.0.0-beta.332

### Cloud?

- [ ] Yes
- [X] No
