### ISSUE TITLE
[Bug]: Traefik basic auth credentials are not set

### ISSUE THREAD

**Issue by bafonins** [coollabsio/coolify#3414]
### Description

Similar to https://github.com/coollabsio/coolify/issues/2069

When using `traefik.http.middlewares.<changeme>.basicauth.users` traefik label credentials are set properly.

### Minimal Reproduction (if possible, example repository)

1. Deploy custom `docker compose` resource via Coolify
2. Set `traefik.http.middlewares.custom-auth3.basicauth.users=test:$2y$05$OpnNJgwdtK/PLkP.JL7Rzeikv2PB2skTZC1B3x15Zka.Vevo5ux6m` label for one of the services (Note: credentials taken from https://github.com/coollabsio/coolify-examples/blob/main/docker-compose-test/docker-compose.yaml, [issue comment](https://github.com/coollabsio/coolify/issues/2069#issuecomment-2080165198))
3. Deploy the resource
4. Observe warning in the logs: `level=warning msg="The \"OpnNJgwdtK\" variable is not set. Defaulting to a blank string."`
5. Run `docker inspect` on the service and observe `"traefik.http.middlewares.custom-auth3.basicauth.users": "test:$2y$05/PLkP.JL7Rzeikv2PB2skTZC1B3x15Zka.Vevo5ux6m"`

Note: single quotes or double quotes with escapes for special characters do not solve the issue (https://github.com/coollabsio/coolify/issues/2032#issuecomment-2093833185), i.e.
```
    labels:
      - traefik.http.middlewares.custom-auth3.basicauth.users=test:$2y$05$OpnNJgwdtK/PLkP.JL7Rzeikv2PB2skTZC1B3x15Zka.Vevo5ux6m
    labels:
      - 'traefik.http.middlewares.custom-auth3.basicauth.users=test:$2y$05$OpnNJgwdtK/PLkP.JL7Rzeikv2PB2skTZC1B3x15Zka.Vevo5ux6m'
    labels:
      - traefik.http.middlewares.custom-auth3.basicauth.users=test:\\$2y\\$05\\$OpnNJgwdtK/PLkP.JL7Rzeikv2PB2skTZC1B3x15Zka.Vevo5ux6m
    labels:
      - "traefik.http.middlewares.custom-auth3.basicauth.users=test:\\$2y\\$05\\$OpnNJgwdtK/PLkP.JL7Rzeikv2PB2skTZC1B3x15Zka.Vevo5ux6m"
```

However, there are cases when credentials are set as expected without any errors, for example:
```
htpasswd -nbB test changeme
test:$2y$05$.wdIGOOQBRnO9YzB2pphCeSfKmjWaNvVWuohuEEULoowzdiq7pdJ.
```
Produces no errors and basic auth works properly

### Version

v4.0.0-beta.335

### Cloud?

- [ ] Yes
- [X] No
