### ISSUE TITLE
[Bug]: Permissions issues when using `Preserve Repository During Deployment` with non-root user

### ISSUE THREAD

**Issue by Vahor** [coollabsio/coolify#3440]
### Description

My docker compose is something like this:

```yaml
version: '3.8'
services:
  redis:
    image: 'redis:7.4.0-alpine'
    container_name: redis
    network_mode: host
    volumes:
      - './redis-data:/data:rw'
      - ./redis.conf:/etc/redis/redis.conf:ro
```

the config file is stored on github, but the rdb is kept in a volume on the machine. 
As the config is on github, I've checked `Preserve Repository During Deployment`

meaning that on the server I expect to have a folder called `some-data` and be able to write to it from the docker container using `/data` path.

The issue is that on my server, coolify creates the folder with the main user and the image is using a different one. 

![image](https://github.com/user-attachments/assets/e6350be2-7387-4d45-bd89-98c1692258fc)
left is a server with coolify installed with a root user
right is a server with a non-root user (but sudoer)

As we can see on the left `redis-data` as the uid 999 as owner, so the app can use it. On the left it's `ubuntu` so the app can't use it.

### Minimal Reproduction (if possible, example repository)

1. Using a server with non-root user
2. Add a public repository app with https://github.com/Vahor/test-coolify-docker-compose-volume then pick docker-compose
3. Check `Preserve Repository During Deployment`
4. Start the app

to trigger a permission error you can try to force save the rdb file  using `redis-cli save`.
if there's an error it will return `ERR` and if it works it will return `OK`

Not sure if we have to use a docker compose / git / preserve. That's what I have in my setup, and it fails using this reproduction.

### Version

v4.0.0-beta.335

### Cloud?

- [ ] Yes
- [X] No
