### ISSUE TITLE
[Bug]: Unable to edit Odoo 17 website. Mixed Content Error

### ISSUE THREAD

**Issue by BayBreezy** [coollabsio/coolify#3441]
### Description

I created an Odoo 17 website with the 1-click service.
I was able to add the Recruitment module.
When I tried editing the Website, the editor would not open, I kept getting this error in the web console

```
Mixed Content: The page at 'https://odoo.coolify.behonbaker.com/web#action=247&cids=1&menu_id=176' was loaded over HTTPS, but requested an insecure frame 'http://odoo.coolify.behonbaker.com/'. This request has been blocked; the content must be served over HTTPS.
```

After some amount of digging, i stumbled on this post: [Mixed Content Error](https://www.odoo.com/forum/help-1/mixed-content-request-from-an-insecure-resource-140344) where someone stated that adding a few headers to the Nginx config would fix the problem. 

I am not sure of how to do this in the UI of Coolify. This is what I see for this service:
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/26317207-d2f6-4e6a-86fb-c35a2c2d6fcb">

Can you help me or point me to the docs that say how we can add the different heders to the proxy file?

### Minimal Reproduction (if possible, example repository)

- Create an Odoo 17 app with the 1-click service from the UI
- Start the website and visit the live URL given by coolify.
- Go to the website editor in Odoo

### Exception or Error

Mixed Content: The page at 'https://odoo.coolify.behonbaker.com/web#action=247&cids=1&menu_id=176' was loaded over HTTPS, but requested an insecure frame 'http://odoo.coolify.behonbaker.com/'. This request has been blocked; the content must be served over HTTPS.

### Version

4.0.0-beta.335

### Cloud?

- [ ] Yes
- [X] No

**Comment by djsisson** [comment]
im not sure which part is broken for you

![image](https://github.com/user-attachments/assets/c751d82a-9818-4a06-ada0-6339cc275a82)

![image](https://github.com/user-attachments/assets/52bf7082-d4ae-4881-940f-f75cc1c25c36)

**Comment by BayBreezy** [comment]
The website editor. Try editing the website. I did get the recruitment module to work no problem

**Comment by djsisson** [comment]
@BayBreezy this took way to long to fix, none of the suggestions worked

![image](https://github.com/user-attachments/assets/7f37cdac-a1ee-4a40-8c73-77f009017de2)

add a transform rule in cloudflare

modify  response headers

match your odoo domain
then add dynamic Location and set value to
concat("https://", substring(http.response.headers["location"][0], 7))

please note i also have amended some traefik labels, but im not sure they are even necessary at this point

**Comment by djsisson** [comment]
@BayBreezy 

```yaml
- traefik.http.routers.odoo.entryPoints=http
- traefik.http.middlewares.csp-header.headers.customResponseHeaders.Content-Security-Policy=upgrade-insecure-requests
- traefik.http.routers.odoo.middlewares=gzip,csp-header
- 'traefik.http.routers.odoo.rule=Host(`odoo.domain.com`) && PathPrefix(`/`)'
- traefik.http.routers.odoo.priority=100
```

this is for http, you would need to modify for https

also i added this volume mount

```yaml
-
        type: bind
        source: ./odoo.conf
        target: /etc/odoo/odoo.conf
        contents: |
          [options]
            addons_path = /mnt/extra-addons
            data_dir = /var/lib/odoo
            proxy_mode = True
```
i also modified the web.base.url and web.base.url.freeze in Settings -> Technical -> System Parameters in dev mode

**Comment by djsisson** [comment]
note the volume mount will remove the admin password if u have one set up

**Comment by BayBreezy** [comment]
Ok. Thank you. I will give this a shot when I am around the computer again. I will let you know if it helped

**Comment by BayBreezy** [comment]
@djsisson well that didn't work :(

**Comment by djsisson** [comment]
@BayBreezy the other option is to install a plugin for traefik that modifies headers, and the nyou can jsut modify the Location header using a regexp, similar to what i did in cloudflare

**Comment by BayBreezy** [comment]
@djsisson , I will have to do that... after learning how ytaefik works lolol.
I only know about traefik through coolify. Been using nginx all my life.
But If i get it to work, I will share my findings. Thanks for the help. I appreciate it

**Comment by djsisson** [comment]
Well maybe you could add nginx to the compose and route all traffic through that

**Comment by stefsava** [comment]
I'm not an expert on reverse proxies unfortunately.

I think the problem complained about is due to the lack of management of port 8072 towards which the /longpolling traffic (up to version 15.0) or /websocket (from version 16.0 onwards) must be directed.

Please see:

- https://stackoverflow.com/questions/66151900/odoo-using-traefik-proxy-instead-of-nginx
- https://www.odoo.com/documentation/15.0/administration/on_premise/deploy.html#id7
- https://www.odoo.com/documentation/18.0/administration/on_premise/deploy.html#id8

**Comment by CGeorges** [comment]
Odoo doesn't know he runs over HTTPS because it's setup behind traefik, for odoo to know that and use https even if it's running on HTTP inside `/etc/odoo-server.conf`
`proxy_mode=True` should be added.

It's not just website editor broken, multiple things that require to send a callback url for example, like SSO.

I'm not sure how to do the change permanently yet.

**Comment by CGeorges** [comment]
Updating the compose file to:
```
configs:
  odoo_conf:
    content: |
      [options]
      admin_passwd = admin
      addons_path = /mnt/extra-addons
      data_dir = /var/lib/odoo
      proxy_mode = True
services:
  odoo:
    image: 'odoo:17'
    configs:
      - source: odoo_conf
        target: /etc/odoo/odoo.conf
    environment:
      - SERVICE_FQDN_ODOO_8069
      - HOST=postgresql
      - USER=$SERVICE_USER_POSTGRES
      - PASSWORD=$SERVICE_PASSWORD_POSTGRES
    volumes:
      - 'odoo-web-data:/var/lib/odoo'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8069'
      interval: 2s
      timeout: 10s
      retries: 30
  postgresql:
    image: 'postgres:16-alpine'
    volumes:
      - 'postgresql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - POSTGRES_DB=postgres
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d postgres'
      interval: 5s
      timeout: 20s
      retries: 10
```

made everything work
