### ISSUE TITLE
[Bug]: Cannot define domain for service when deploying with docker-compose

### ISSUE THREAD

**Issue by oussamadouhou** [coollabsio/coolify#3466]
### Error Message and Logs

When deploying an app from a public repository with a docker-compose in the root directory all configurations are loaded but the option for the domain is missing and not available.
![image](https://github.com/user-attachments/assets/6d064b82-30c5-4547-a327-5e97f9d47062)

### Steps to Reproduce

1. Go to projects
2. Choose desired project
3. Click on new resource
4. Choose Git based -> Public Repository
5. Select desire server (mine is V4.0.0-beta.338
6. Add desired repository (mine https://github.com/hashicorp-forge/hermes.git)
7. Click check repository
8. Change Build Pack to docker-compose
9. Set base directory to /
10. change Docker compose location to /docker-compose.yml and click Continue
11. In the General tab Domains option is empty

![image](https://github.com/user-attachments/assets/7187b868-8cc1-410d-8b62-810c4891c73d)

### Example Repository URL

https://github.com/hashicorp-forge/hermes

### Coolify Version

V4.0.0-beta.338

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by djsisson** [comment]
confirmed, domain field is now missing

**Comment by eduhdev12** [comment]
> @oussamadouhou its missing due to this service not having any accessible https endpoint.
> 
> its postgres you cant directly assign it a domain

No, he is right. Something happened try this from official docs https://raw.githubusercontent.com/coollabsio/coolify/main/templates/compose/plausible.yaml to see the issue

**Comment by djsisson** [comment]
@eduhdev12 

this is a multi service compose, you enter the domain from settings or yellow icon for each service that needs one

see image ( the compose is missing one line so there is no domain auto generated)
this line is missing at top of environment 
```yaml
- SERVICE_FQDN_PLAUSIBLE
```


![image](https://github.com/user-attachments/assets/8d2588b6-c061-43de-ad3b-08736ce7728b)

**Comment by stevenhuyn** [comment]
tyty, docs should be updated for this

**Comment by mrcloudbook** [comment]
Iam using latest version 
Here iam getting same 

<img width="2052" alt="image" src="https://github.com/user-attachments/assets/45f2487f-9cb9-47ac-adba-d307e7023a59">

**Comment by djsisson** [comment]
@mrcloudbook theres no links if you dont define a domain, without seeing your compose i can't say why this is happening

**Comment by mrcloudbook** [comment]
Here is Compose test 
```
version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "5g"
    tag: "{{.Name}}"

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: registry.digitalocean.com/pdevsecops/documenso/postgres
    container_name: postgres
    restart: always
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

    logging: *default-logging

  documenso:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: registry.digitalocean.com/pdevsecops/documenso/documenso
    container_name: documenso
    restart: always
    depends_on:
      - postgres
    environment:
      - SERVICE_FQDN_DOCUMENSO
      - BASE_URL=$SERVICE_FQDN_DOCUMENSO
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PRIVATE_DATABASE_URL=${NEXT_PRIVATE_DATABASE_URL}
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=${NEXT_PRIVATE_DIRECT_DATABASE_URL}
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=${NEXT_PRIVATE_SMTP_FROM_ADDRESS}
      - NEXT_PRIVATE_SMTP_FROM_NAME=${NEXT_PRIVATE_SMTP_FROM_NAME}
      - NEXT_PRIVATE_SMTP_HOST=${NEXT_PRIVATE_SMTP_HOST}
      - NEXT_PRIVATE_SMTP_PASSWORD=${NEXT_PRIVATE_SMTP_PASSWORD}
      - NEXT_PRIVATE_SMTP_PORT=${NEXT_PRIVATE_SMTP_PORT}
      - NEXT_PRIVATE_SMTP_USERNAME=${NEXT_PRIVATE_SMTP_USERNAME}
      - NEXT_PUBLIC_ALLOW_SIGNUP=${NEXT_PUBLIC_ALLOW_SIGNUP}
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
      - NEXT_PRIVATE_ENCRYPTION_KEY=${NEXT_PRIVATE_ENCRYPTION_KEY}
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=${NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY}
    logging: *default-logging

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAMEN=${AWS_STORAGE_BUCKET_NAME}
    volumes:
      - production_postgres_data_backups:/backups:z
    logging: *default-logging
    ```
