### ISSUE TITLE
[Bug]: Nginx not find services in preview deployment

### ISSUE THREAD

**Issue by picheidt** [coollabsio/coolify#3511]
### Error Message and Logs

I have a PHP application using nginx as a reverse proxy. I deploy it with Coolify and Docker Compose, and the main deployment works as expected. However, the preview deployment results in the following error:

```
error: nginx: [emerg] host not found in upstream "php_mm2" in /etc/nginx/conf.d/default.conf:16
```

**Below are my current files**

- DockerFile.nginx
```
FROM nginx:stable-alpine

WORKDIR /var/www/html/

COPY ./webroot /var/www/html
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80/tcp
```
- nginx.conf
```
server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/html;

    location / {
    	try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ˆ(.+\.php)(/.+)$;
        fastcgi_pass php_mm2:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```

- docker-compose
```
services:
  nginx_mm2:
    build:
      context: .
      dockerfile: Dockerfile.nginx.staging
    container_name: nginx_mm2
    ports:
      - "80"
    depends_on:
      - php_mm2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/app/healthCheck" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
  
  php_mm2:
    build:
      context: .
      dockerfile: Dockerfile.staging
    container_name: php_mm2
    command: sh ./run_dependencies_staging.sh
    ports:
      - "9000"
```

### Steps to Reproduce

1. Active preview deployment
2. Use docker-compose with an application and nginx containers
3. Open a PR to trigger the preview Deployment

### Coolify Version

v4.0.0-beta.338

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04.4 LTS  

### Additional Information

The application and nginx containers are on the same network. I couldn’t debug nginx because it keeps restarting in a loop due to the error.

**Comment by tm1000** [comment]
- https://github.com/coollabsio/coolify/discussions/4708

**Comment by tm1000** [comment]
The solution to this problem will need to be the following in /data/coolify/applications/*/docker-compose-pr-*.yaml:

```
    nginx-pr-615:
        networks:
          p0g0ck8c44o4oo4w808so8w4-615: null
```

to 


```
    nginx-pr-615:
        networks:
          p0g0ck8c44o4oo4w808so8w4-615:
            aliases:
              - nginx
```

Since this file is automatically generated a fix similar to https://github.com/coollabsio/coolify/pull/2204 will need to be done

**Comment by tm1000** [comment]
Temporary fix for this (but it's not ideal) is for each service defined in your docker-compose.yaml file add the following:

```
        networks:
            default:
                aliases:
                    - <real service name>
 ```

Example:

```
nginx-pr-615:
        networks:
            default:
                aliases:
                    - nginx
```

**Comment by tm1000** [comment]
Thinking more about this the solution I provided won't conflict because the proxy addresses the container names as the full name and each deployment has a self contained network. But this has to be addressed in the code itself where it makes `network: null`. I know where this is at in the code but will need to setup a coolify dev instance to run it through checks

**Comment by tm1000** [comment]
Quick patch that I'm going to test this next week (that seems to work correctly)

```
diff --git a/bootstrap/helpers/shared.php b/bootstrap/helpers/shared.php
old mode 100644
new mode 100755
index 7aa411cd1..c7a4b9fb4
--- a/bootstrap/helpers/shared.php
+++ b/bootstrap/helpers/shared.php
@@ -3438,7 +3438,11 @@ function newParser(Application|Service $resource, int $pull_request_id = 0, ?int
                 }
             }
             foreach ($baseNetwork as $key => $network) {
-                $networks_temp->put($network, null);
+                if ($isApplication && $isPullRequest) {
+                    $networks_temp->put($network, ['aliases' => [$serviceName]]);
+                } else {
+                    $networks_temp->put($network, null);
+                }
             }
 
             if ($isApplication) {
```

Another way to do this is create another base network that just binds all containers together but doesn't have the coolify proxy attached. I'll wait a bit before submitting a PR to see what the best way forward is on that

**Comment by hydrandt** [comment]
@tm1000 did you have success with the suggested solution?

**Comment by rfournier1** [comment]
While this issue is still open, I share here my workaround : 

I had the same problem : although refering to another container using the service name worked in a "regular" deployment, it failed in preview deployments. 

In my case with the following entry in my docker-compose.yml : 
```
services:
  db:
    image: postgres:14-alpine
    expose:
      - 5432
```
Refering the host `db` was properly resolved in my deployment (connecting to `postgresql://db:5432` for example), but not in a preview deployment 

I found a workaround using the "hostname" field in my docker-compose.yml : https://docs.docker.com/reference/compose-file/services/#hostname to force the container hostname on the network created by coolify, that work in both cases as it is not overwritten during the docker-compose generation. 

```
services:
  db:
    image: postgres:14-alpine
    expose:
      - 5432
    hostname: db
```
