### ISSUE TITLE
[Bug]: bash: line 7: syntax error near unexpected token `then' - Traefik Installation

### ISSUE THREAD

**Issue by derpoho** [coollabsio/coolify#3645]
### Error Message and Logs

While installing a fresh server, the error occures while starting the traefik proxy.

 bash: line 7: syntax error near unexpected token `then' 

### Steps to Reproduce

1. Fresh Server (Ubuntu 24.04 + GNU bash, version 5.2.21, Docker version 27.3.1)
2. Create Sudo User
3. Connect to Server
4. Activate Proxy
5. Error

### Coolify Version

v4.0.0-beta.347

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04 LTS

### Additional Information

Log Output:
```
Creating required Docker Compose file.
Pulling docker image.
 traefik Pulling 
 traefik Pulled 
bash: line 7: syntax error near unexpected token `then'
```

Compose File (generated, unmodified)
```
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v3.1'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=50'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--providers.docker=true'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - coolify.managed=true
      - coolify.proxy=true
```
