### ISSUE TITLE
[Bug]: Docker Compose environment variable value with equal sign breaks parsing

### ISSUE THREAD

**Issue by nightvisi0n** [coollabsio/coolify#3674]
### Error Message and Logs

Environment variables with an equal sign "=" somewhere inside the value are incorrectly parsed (see the example in the reproduction steps).

### Steps to Reproduce

Use the docker compose buildpack with a compose file like this:  
```yaml
services:
    frontend:
      build: apps/frontend
      environment:
        EXAMPLE: "This is an example=with an equal sign"
```
Which results in the following parsed compose file content:  
```yaml
services:
    frontend:
      build: apps/frontend
      environment:
        'This is an example': 'with an equal sign'
```

### Coolify Version

v4.0.0-beta.349

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

AlmaLinux 9.4 (Seafoam Ocelot)
