### ISSUE TITLE
[Bug]: Appwrite function domain is incorrect

### ISSUE THREAD

**Issue by mikelgmh** [coollabsio/coolify#3718]
### Error Message and Logs

The function domain generated using the GitHub integration is not correct. As you can see, it adds the function id before the Appwrite domain.

![image](https://github.com/user-attachments/assets/4788109b-9c6a-4e22-9e1c-1288f9413f18)

### Steps to Reproduce

1. Create a function in Appwrite using the GitHub integration
2. Build the function

### Coolify Version

4.0.0-beta.355

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.4

### Additional Information

Keep in mind that my appwrite instance is running on a subdomain.

**Comment by kuzerno1** [comment]
This because the SERVICE_URL_ and SERVICE_FQDN_ are mixed up like that was with COOLIFY_URL AND COOLIFY_FQDN. But the COOLIFY one got fixed, see #2443.

But when this gets fixed the url wont be reachable because you need to add the url to the domains list in the coolify appwrite service. There is a way to not have to do this but that involves to setup a wildcard ssl certificate for your domain.

**Comment by mikelgmh** [comment]
@kuzerno1 So I'm a little bit confused. I don't mind adding the urls to the domains list in the appwrite service, but which would be the solution to this problem? Do I need to update SERVICE_URL_  or SERVICE_FQDN_  in any specific way? Thank you in advance!

**Comment by kuzerno1** [comment]
@mikelgmh you cant change these variables because they come from coolify. But you can change service_fqdn_appwrite to service_url_appwrite in the compose file.

This will work but soon as you add the function url I think it will break stuff in appwrite.

Because _APP_DOMAIN and a few other variables want only one domain if Im correctly. You will need to change these variables with your main domain.

**Comment by UncleVesimir** [comment]
Apologies if this is this the wrong place to post this, but I keep getting 404's on function domains.

Coolifyv4-beta.370
appwrite 1.6.0

Unchecked "Strip Prefixes" in both Appwrite Console and Realtime Services

Also have wildcard set up for appwrite.codeprojects in squarespace

Any ideas?

**Comment by voglster** [comment]
Exact same setup as uncle vesimir, the path is correct but the functions give 404s and hit what looks like trraefic instead of getting passed in.

I'm willing to help debug but basically latest coolify and appwrite from a blank install.

**Comment by kuzerno1** [comment]
Can you guys check if you're running version 2 or 3 of Treafik? You can check this by Servers, choose your server and then Proxy.

The reason I ask this is because I got everything working but a few days back I saw a issue that someone could not get wildcard certificate to work. He was also getting 404 pages. But I saw in his issue that he was using Traefik version 3 and I'm using version 2.

And after some digging I found out that since version v4.0.0-beta.324 this has been changed to version 3 and I installed Coolify before that so that was de reason why I was running version 2 instead of version 3. Luckily there is a button reset default config and now I'm running version 3. But now I'm also getting 404 pages.

So I check the docs again about the wildcard certificates but that is still for Traefik version 2. And for Traefik 3, according to the [docs](https://doc.traefik.io/traefik/v3.0/routing/routers/#host-and-hostregexp) of Traefik I needed to change ``HostRegexp(`{subdomain:[a-zA-Z0-9]+}.domain.com`)`` to ``HostRegexp(`^.+\.domain\.com$`)`` in my applications compose file and now everything is working again.

**Comment by voglster** [comment]
HostRegexp(`{subdomain:[a-zA-Z0-9]+}.domain.com`) to HostRegexp(`^.+\.domain\.com$`) is what fixed it...

so steps for anyone else:
setup wildcard domain
add a dynamic proxy config to redirect wildcard traffic to the main appwrite instance

**Comment by crimue** [comment]
Hey, I also stumbled across this issue. 

My function domain urls are created correctly (https://functionname.appwrite.example.com) but I only receive a "404 page not found". If I add temporarly "https://functionname.appwrite.example.com" separated by a comma to the "appwrite"-service (domains section) in coolify the SSL works and the function is accessible. So I think my wildcard domain is working.

<img width="1072" alt="Image" src="https://github.com/user-attachments/assets/314ffc84-942d-41e0-9c87-77f99e21560a" />

@voglster talked about a regex but I am not able to get it to work. I tried the following in the coolify Proxy dynamic configuration of the server:
```
http:
  routers:
    appwrite-wildcard:
      rule: HostRegexp(`^.+\.appwrite\.example\.com$`)
      entryPoints:
        - https
      service: appwrite-service
      tls:
        certResolver: letsencrypt
  services:
    appwrite-service:
      loadBalancer:
        servers:
          -
            url: 'http://appwrite:80'
 ```

What am I doing wrong here? Thank you very much!

My traefik (default) config:

```
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v3.1'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
      - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http3'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--api.insecure=false'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - coolify.managed=true
      - coolify.proxy=true

```

**Comment by AndreaDev237** [comment]
Bump for this

**Comment by Zersya** [comment]
The domain name is correct on my end; however, Coolify is unable to detect the generated domain. After that I must manually add the generated domain into the service domain and then restart the resource/project.


Updated:
It seems to be working for me now. I've added a new configuration to the Servers Dynamic Configurations. Here's the config in case anyone needs it.

`appwrite-wildcard.yaml`
```yaml
http:
  routers:
    appwrite-wildcard-https:
      entryPoints:
        - https
      service: appwrite-wildcard-service
      rule: 'HostRegexp(`^.+\.fn\.appwrite\.example\.com`) || HostRegexp(`^.+\.site\.appwrite\.example\.com`)'
      tls:
        certresolver: letsencrypt
  services:
    appwrite-wildcard-service:
      loadBalancer:
        servers:
          -
            url: 'http://appwrite:80' # This should be match with service name in the projects/resources
```
