### ISSUE TITLE
Change the default coolify 3000 port

### ISSUE THREAD

**Issue by mkilinskidev** [coollabsio/coolify#382]
Hi. I need to change the default 3000 port that coolify uses for the panel. How can I do that?

**Comment by mkilinskidev** [comment]
I've tried to make my own docker-compose and I've changed the install.sh file, but the script doesn't use a custom docker-compose file.

**Comment by gregfr** [comment]
It's a must-have, many projects use port 3000.

**Comment by 416d72** [comment]
This is a much needed feature since I want to use it behind cloudflare, which doesn't support port 3000

**Comment by louis-eyond** [comment]
> This is a much needed feature since I want to use it behind cloudflare, which doesn't support port 3000

Use Cloudflare Tunnel with the cloudflared process, which connects any port to Cloudflare for proxy.  Two nice things about are that you don't even have to open your firewall to it, and the new UI for setting up makes it super easy.

Of course, this does not solve the original post about having 2 services on the same port, where neither will allow a default port change.

**Comment by 416d72** [comment]
> Use Cloudflare Tunnel with the cloudflared process, which connects any port to Cloudflare for proxy. Two nice things are that you don't even have to open your firewall to it, and the new UI for setting up makes it super easy.

This is clever, I'm going to try it

**Comment by kirill-dev-pro** [comment]
@mkilinskidev don't use the script, create your own docker-compose file.
Here is mine, a slightly modified version from the image with scripts

```yml
version: '3.8'

services:
  coolify:
    image: coollabsio/coolify:latest
    restart: always
    # container_name: coolify
    ports:
      - target: 3000
        published: 3010
        protocol: tcp
        mode: host
    volumes:
      - 'coolify-db:/app/db'
      - 'coolify-logs:/app/logs'
      - 'coolify-ssl-certs:/app/ssl'
      - 'coolify-traefik-letsencrypt:/etc/traefik/acme'
      - 'coolify-letsencrypt:/etc/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock'
    env_file:
      - '.env'
    networks:
      - coolify-infra
  fluent-bit:
    image: coollabsio/coolify-fluent-bit:1.0.0
    # container_name: coolify-fluentbit
    volumes:
      - 'coolify-logs:/app/logs'
    networks:
      - coolify-infra
networks:
  coolify-infra:
    attachable: true
    name: coolify-infra

volumes:
  coolify-logs:
    name: coolify-logs
  coolify-db:
    name: coolify-db
  coolify-pgdb:
    name: coolify-pgdb
  coolify-ssl-certs:
    name: coolify-ssl-certs
  coolify-letsencrypt:
    name: coolify-letsencrypt
  coolify-traefik-letsencrypt:
    name: coolify-traefik-letsencrypt
```
