### ISSUE TITLE
[Bug]: Error while creating a MongoDB Service with a Custom Mongo Configuration

### ISSUE THREAD

**Issue by n3m** [coollabsio/coolify#3970]
### Error Message and Logs

I just created a new MongoDB Service in Coolify, and added this "Custom MongoDB Configuration"
```
replication:
  replSetName: "rs0"
```
in Coolify's service settings.

However the database is not starting and the only thing getting logged is the following.
```
Error: EACCES: permission denied, open '/etc/mongo/mongod.conf'
error: unexpected "js-yaml.js" output while parsing config:
```

I'm only interacting through Coolify's GUI, because no container is ever kept, since the service doesn't fully start.

### Steps to Reproduce

1. Create a new Project in any server and add a MongoDB Instance
2. Add in the "Custom MongoDB Configuration" the `...replication..` part stated in the context
3. Attempt to start the DB
4. Error due to permissions

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04 LTS

### Additional Information

I believe this might be an issue with how Coolify applies the custom configuration to the MongoDB Instance permissions, however I've got 0 clue about PHP, and my attempts to determine what Coolify does within the source code haven't gone very far due to that reason :(
I've also tried to put a full conf file:

```
systemLog:
   destination: file
   path: "/var/log/mongodb/mongod.log"
   logAppend: true
processManagement:
   fork: true
net:
   bindIp: 127.0.0.1
   port: 27017
setParameter:
   enableLocalhostAuthBypass: false
replication:
  replSetName: "rs0"
```

to no avail either
