### ISSUE TITLE
[Bug]: Services not starting when using Docker Compose with Git

### ISSUE THREAD

**Issue by RageBrahimi** [coollabsio/coolify#3980]
### Error Message and Logs

When using the provided Docker Compose configuration with a GitHub private repository, not all services load as expected. The same configuration works fine when executed in an empty setup (without linking to a private repository). Specifically, PostgreSQL and Redis do not seem to initialize correctly when the configuration is used with a private repository.

Docker Compose File:

```yaml
services:
  directus:
    image: directus/directus:11
    volumes:
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions
      - directus-templates:/directus/templates
    environment:
      - SERVICE_FQDN_DIRECTUS_8055
      - KEY=$SERVICE_BASE64_64_KEY
      - SECRET=$SERVICE_BASE64_64_SECRET
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=$SERVICE_PASSWORD_ADMIN
      - DB_CLIENT=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_DATABASE=${POSTGRESQL_DATABASE:-directus}
      - DB_USER=$SERVICE_USER_POSTGRESQL
      - DB_PASSWORD=$SERVICE_PASSWORD_POSTGRESQL
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEBSOCKETS_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8055/admin/login"]
      interval: 5s
      timeout: 20s
      retries: 10
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgresql:
    image: postgis/postgis:16-3.4-alpine
    platform: linux/amd64
    volumes:
      - directus-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRESQL}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}
      - POSTGRES_DB=${POSTGRESQL_DATABASE:-directus}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - directus-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 20s
      retries: 10
```

### Steps to Reproduce

1.	Use the provided Docker Compose configuration in an environment without linking to a GitHub private repository.
	•	Result: All services (Directus, PostgreSQL, Redis) start correctly and the application works as expected.

2.	Use the same Docker Compose configuration but link it to a GitHub private repository (e.g., for pulling custom Directus extensions or configurations).
	•	Result: Not all services start successfully, specifically PostgreSQL and Redis fail to initialize.

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04
