### ISSUE TITLE
[Bug]: Minio special handling in services

### ISSUE THREAD

**Issue by Knight-Ops** [coollabsio/coolify#3996]
### Error Message and Logs

This is going to be a bit of a long winded explanation to provide clarity as much as possible. If you deploy Reactive Resume from the current Service list, you are deploying this service of Minio.

```
  minio:
    image: minio/minio
    command: 'server /data --console-address ":9001"'
    environment:
      - SERVICE_FQDN_MINIO_9000
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
    ...(Continued, but not important here)
```

When this is run through Coolify, the Deployable Compose ends up being (trimmed for brevity)

```
  minio:
    image: minio/minio
    command: 'server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: $SERVICE_USER_MINIO
      MINIO_ROOT_PASSWORD: $SERVICE_PASSWORD_MINIO
      COOLIFY_CONTAINER_NAME: '"minio-g4s8ccoks00wgkkgs488skgs"'
...
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.360
      - coolify.serviceId=23
      - coolify.type=service
      - coolify.name=minio-g4s8ccoks00wgkkgs488skgs
      - coolify.pullRequestId=0
      - coolify.service.subId=56
      - coolify.service.subType=application
...
```

Specifically what I wanted to bring up was the lack of SERVICE_FQDN_MINIO_9000 expansion to get automatic Traefik tags for exposure on the proxy, it seemed odd to me that this was ignored, After a bunch of digging around, I have come to the following conclusion: When generating Service specific FQDN [here](https://github.com/coollabsio/coolify/blob/5d62a46a16f252e6ece4d25fe56838e99883d91b/bootstrap/helpers/docker.php#L208) I noticed a few oddities. Code inline here to discuss more succinctly without links everywhere

I started by looking for where these magical Traefik labels are added, and I quickly found `fqdnLabelsForTraefik`. But our quest starts in `bootstrap/helpers/shared.php` [here](https://github.com/coollabsio/coolify/blob/5d62a46a16f252e6ece4d25fe56838e99883d91b/bootstrap/helpers/shared.php#L2055)

```php
                ...
                // Add labels to the service
                if ($savedService->serviceType()) {
                    $fqdns = generateServiceSpecificFqdns($savedService);
                } else {
                    $fqdns = collect(data_get($savedService, 'fqdns'))->filter();
                }
                $defaultLabels = defaultLabels($resource->id, $containerName, type: 'service', subType: $isDatabase ? 'database' : 'application', subId: $savedService->id);
                $serviceLabels = $serviceLabels->merge($defaultLabels);
                if (! $isDatabase && $fqdns->count() > 0) {
                    if ($fqdns) {
                        $shouldGenerateLabelsExactly = $resource->server->settings->generate_exact_labels;
                        if ($shouldGenerateLabelsExactly) {
                            switch ($resource->server->proxyType()) {
                                case ProxyTypes::TRAEFIK->value:
                                    $serviceLabels = $serviceLabels->merge(fqdnLabelsForTraefik(
                                        uuid: $resource->uuid,
                                        domains: $fqdns,
                                        is_force_https_enabled: true,
                                        serviceLabels: $serviceLabels,
                                        is_gzip_enabled: $savedService->isGzipEnabled(),
                                        is_stripprefix_enabled: $savedService->isStripprefixEnabled(),
                                        service_name: $serviceName,
                                        image: data_get($service, 'image')
                                    ));
                                    break;
                                case ProxyTypes::CADDY->value:
                                    ...
                            }
                        } else {
                            ...
                        }
                    }
                }
```

Looking at this code there aren't many reason that we could possibly NOT get to `fqdnLabelsForTraefik` but, it is obviously still possible. The problem here lays in the `if ($fqdns)` check of "truthiness" I believe. An empty array seems to be false in this case, so we look at how that can happen in `generateServiceSpecificFqdns`.

`bootstrap/helpers/docker.php`
```php
function generateServiceSpecificFqdns(ServiceApplication|Application $resource)
{
    ...
    $variables = collect($environment_variables);
    $payload = collect([]);
    switch ($type) {
        case $type?->contains('minio'):
            $MINIO_BROWSER_REDIRECT_URL = $variables->where('key', 'MINIO_BROWSER_REDIRECT_URL')->first();
            $MINIO_SERVER_URL = $variables->where('key', 'MINIO_SERVER_URL')->first();
            if (is_null($MINIO_BROWSER_REDIRECT_URL) || is_null($MINIO_SERVER_URL)) {
                return $payload;
            }
            if (is_null($MINIO_BROWSER_REDIRECT_URL?->value)) {
                $MINIO_BROWSER_REDIRECT_URL?->update([
                    'value' => generateFqdn($server, 'console-'.$uuid, true),
                ]);
            }
            if (is_null($MINIO_SERVER_URL?->value)) {
                $MINIO_SERVER_URL?->update([
                    'value' => generateFqdn($server, 'minio-'.$uuid, true),
                ]);
            }
            $payload = collect([
                $MINIO_BROWSER_REDIRECT_URL->value.':9001',
                $MINIO_SERVER_URL->value.':9000',
            ]);
            break;
        case $type?->contains('logto'):
            ...
    }

    return $payload;
}
```

When we look here, it seems pretty obvious how we can end up with an empty array as a return value in `$fqdns`. In the event that we don't have `MINIO_BROWSER_REDIRECT_URL` and `MINIO_SERVER_URL` assigned to the Minio env variables, we get an empty array, and no Traefik labels at all. 

That was a very long explanation, what this brings me to is my question/issue:
- Do we really need to require definition of `MINIO_BROWSER_REDIRECT_URL` AND `MINIO_SERVER_URL` (There is an || in the code, so we need both for it to work, otherwise we return [])
- Why are Minio (and logto) handled separately here as edge cases?

I am absolutely not a PHP expert so if I got something incorrect I would love to know, this seems like an odd issue that is specifically only for Minio deployments in services, that fail to have both env variables assigned. I am not sure how best to make sure all of the services have these env variables defined (and new ones), but would love to hear some options.

### Steps to Reproduce

1. Deploy Reactive Resume One-Click service prior to #3995 merge

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Additional Information

 This is related to #3995, #3762, and #3746 (Possibly more, but this is the rabbit hole that lead me here).
