### ISSUE TITLE
[Bug]: wrong volume mapping generated when up-level path is present e.g. "../dir"

### ISSUE THREAD

**Issue by ton77v** [coollabsio/coolify#4055]
### Error Message and Logs

Consider the following docker-compose:
```YAML
services:
    app:
        container_name: app
        image: alpine:latest
        restart: no
        volumes:
            - ../data:/data
        command: [ "cat", "/data/test.txt" ]
```

Coolify will generate the following:
```YAML
services:
  app:
    container_name: app-sswk0ws400sw0sg80cco4csg-082400934922
    image: 'alpine:latest'
    restart: 'no'
    volumes:
      - '/data/coolify/applications/sswk0ws400sw0sg80cco4csg./data:/data'
    # ...
```

There's an extra dot in the volumes mapping generated: "...4scg./data:/data" that breaks the functionality

### Steps to Reproduce

1. Add this repo: https://github.com/ton77v/coolify_bug
2. Select "master" branch instead of main and "/src" as the Build directory
3. Once the docker-compose loads, see the issue in "Docker Compose Content"

Alternatively, run the docker-compose locally, output: "PASSED!", while when deploy with Coolify the logs will be:
> cat: can't open '/data/test.txt': No such file or directory

### Example Repository URL

https://github.com/ton77v/coolify_bug

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

Yes (Coolify Cloud)
