### ISSUE TITLE
[Bug]: glitchtip Error 500 loading js with Traefik

### ISSUE THREAD

**Issue by kaipiyann** [coollabsio/coolify#4062]
### Error Message and Logs

I use the glitchtip template and when loading the front I had some error 500 when loading js chunks...so the frontend was buggy, sometime it display sometime not.

I checked the log from Traefik and the log said "server closed idle connection".

So I search a little and found this page with same problem : https://github.com/traefik/traefik/issues/4481
So I tried to change the settings of Traefik and I can confirm if I disable Idle connection on Traefik with this I got no more 500 :
--serversTransport.maxIdleConnsPerHost=-1

Then I just tried to put a lower Timeout and it works also , perhaps better :
--serversTransport.forwardingTimeouts.idleConnTimeout=3s
 
I think Glitchtip is using a python serve (https://www.uvicorn.org/settings/),and the default keepalive seems to be 5s.

I hope this help !

Thks

### Steps to Reproduce

1.
2.
3.
4.

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12

**Comment by kaipiyann** [comment]
Hi,

Sorry to write again about this problem but I still got difficulties connecting to Glitchtip.

It works sometimes, when I restart the proxy I works few minutes and then I got Bad Error Gateway. When I look in the proxy log it's written 
502 Bad Gateway error="dial tcp 172.31.0.4:8080: connect: connection refused"

When it works I have all sort of errors so Glitchtip is partially loaded in the browser (some JS chunks don't load) and in the log I have this kind of messages 
502 Bad Gateway error="read tcp 172.31.0.6:60000->172.31.0.5:8080: read: connection reset by pee
502 Bad Gateway error=EOF
500 Internal Server Error error="http: server closed idle connection

I really don't know how I can find a way to understand the problem and find a solution. If someone can give tips I would be very pleased.

Thks

**Comment by Yousema** [comment]
Same problem here, Glitchtip keep crashing with **Bad Gateway** error.
Maybe is there some custom domain parameters not working (cause when it works, it keeps giving me the wrong domain for api connection)

**Comment by faqndo97** [comment]
Same problem happening for various teammates on my team. I can't figure out what's happening yet but after reload a screen it show the errors and no content is rendered.

![Image](https://github.com/user-attachments/assets/4fa9efd7-0d00-4ef1-8193-a152f87f7446)

**Comment by faqndo97** [comment]
Hi! Do we have some news here? We still have this problem and can't access the service properly.

**Comment by kaipiyann** [comment]
@faqndo97 Can you check if you did check the "Connect to predefined network" in the Service Stack tab configuration. 
Because after trying it seems problem is solved...

**Comment by urtubia** [comment]
So I experienced this issue and experimented with it a bunch and was able to come up with reliable workaround for me. To summarize, **switching the proxy to Caddy** made it work without issues.

I'm sure it could be made to work with Traefik too, but since I was able to get it going with Caddy, I'm happy with where it is at.
My testing process was:
* With Traefik, the issue is not present when only using `http` ... so if that's an option for you, that might be sufficient.
* With Traefik, if I commented out `--entryPoints.https.http2.maxConcurrentStreams=50'` from the configuration file, the issue seemed to also resolve itself, but I'm not sure of the repercussions of leaving that setting commented out.
* With Traefik, if I played with the value of `--entryPoints.https.http2.maxConcurrentStreams=50` I got varying degrees of reproduction success, but never very consistently.
* Then I try Caddy, with no configuration changes from the default template and all worked no problem, so I stuck with that.

**Comment by kaipiyann** [comment]
HI @urtubia ,

Interesting ! I will try this setting, but I don't find where we can switch the proxy to Caddy...could you tell me how you did it ?

Thks

**Comment by urtubia** [comment]
Hi @kaipiyann ... yup! in Coolify v4.0.0-beta.389 go to: Servers -> [Select your server] -> Proxy and there you can switch your proxy from Traefik to Caddy. (note that you will have to temporarily stop the proxy to do the switch)

**Comment by alexturpin** [comment]
Also been trying to figure this issue out. Given what you said about the various Traefik config settings that made it work, and the large quantity of JS chunks that GlitchTip tries to load, I imagine the current Traefik config just doesn't allow it to handle all these files at once. The [default value](https://doc.traefik.io/traefik/routing/entrypoints/#maxconcurrentstreams) on a standalone Traefik instance seems to be 250, so I tried boosting it to that in Coolify and it seems to let GlitchTip load fine for me.

**Comment by 7thkey** [comment]
I would also be interested in knowing how to fix this in Traefik. Boosting this values doesnt work for me, still getting 500
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=250'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=250'
      - '--entrypoints.https.http3'

**Comment by faqndo97** [comment]
As @7thkey I configured `maxConcurrentStreams` with different values and still getting the error. Given I have multiple things deployed I'm trying to avoid the proxy change, but if there aren't more solutions I will try that one.

**Comment by 7thkey** [comment]
Not only have I had problems with 500, it seems to work with Firefox and Safari (without cache), but I have other CSP problems that I have fixed by adding the following variables by editing the docker-compose:
- "CSP_DEFAULT_SRC='self' 'unsafe-inline' https://*.glitchtip.com https://gt.whatever.com https://js.stripe.com"
- "CSP_SCRIPT_SRC='self' 'unsafe-inline' https://*.glitchtip.com https://gt.whatever.com https://js.stripe.com"
- "CSP_IMG_SRC='self' data:"

**Comment by faqndo97** [comment]
I'll share more in detail what I have so far. I added the configs suggested by @7thkey and @alexturpin 

docker-compose.yml
```
services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRESQL}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}'
      - 'POSTGRES_DB=${POSTGRESQL_DATABASE:-glitchtip}'
    volumes:
      - 'glitchtip-postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
  redis:
    image: redis
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 20s
      retries: 10
  web:
    image: glitchtip/glitchtip
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SERVICE_FQDN_GLITCHTIP_8080
      - 'DATABASE_URL=postgres://$SERVICE_USER_POSTGRESQL:$SERVICE_PASSWORD_POSTGRESQL@postgres:5432/${POSTGRESQL_DATABASE:-glitchtip}'
      - SECRET_KEY=$SERVICE_BASE64_64_ENCRYPTION
      - 'EMAIL_URL=${EMAIL_URL:-consolemail://}'
      - 'GLITCHTIP_DOMAIN=${SERVICE_FQDN_GLITCHTIP}'
      - 'DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-test@example.com}'
      - 'CELERY_WORKER_AUTOSCALE=${CELERY_WORKER_AUTOSCALE:-1,3}'
      - 'CELERY_WORKER_MAX_TASKS_PER_CHILD=${CELERY_WORKER_MAX_TASKS_PER_CHILD:-10000}'
      - 'ENABLE_USER_REGISTRATION=${ENABLE_USER_REGISTRATION}'
      - 'GLITCHTIP_DOMAIN=${GLITCHTIP_DOMAIN}'
      - "CSP_DEFAULT_SRC='self' 'unsafe-inline' https://*.glitchtip.com https://gt.whatever.com https://js.stripe.com"
      - "CSP_SCRIPT_SRC='self' 'unsafe-inline' https://*.glitchtip.com https://gt.whatever.com https://js.stripe.com"
      - "CSP_IMG_SRC='self' data:"
    volumes:
      - 'uploads:/code/uploads'
    healthcheck:
      test:
        - CMD
        - echo
        - ok
      interval: 5s
      timeout: 20s
      retries: 10
  worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - 'DATABASE_URL=postgres://$SERVICE_USER_POSTGRESQL:$SERVICE_PASSWORD_POSTGRESQL@postgres:5432/${POSTGRESQL_DATABASE:-glitchtip}'
      - SECRET_KEY=$SERVICE_BASE64_64_ENCRYPTION
      - 'EMAIL_URL=${EMAIL_URL:-consolemail://}'
      - 'GLITCHTIP_DOMAIN=${SERVICE_FQDN_GLITCHTIP}'
      - 'DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-test@example.com}'
      - 'CELERY_WORKER_AUTOSCALE=${CELERY_WORKER_AUTOSCALE:-1,3}'
      - 'CELERY_WORKER_MAX_TASKS_PER_CHILD=${CELERY_WORKER_MAX_TASKS_PER_CHILD:-10000}'
    volumes:
      - 'uploads:/code/uploads'
    healthcheck:
      test:
        - CMD
        - echo
        - ok
      interval: 5s
      timeout: 20s
      retries: 10
  migrate:
    image: glitchtip/glitchtip
    restart: 'no'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: './manage.py migrate'
    environment:
      - 'DATABASE_URL=postgres://$SERVICE_USER_POSTGRESQL:$SERVICE_PASSWORD_POSTGRESQL@postgres:5432/${POSTGRESQL_DATABASE:-glitchtip}'
      - SECRET_KEY=$SERVICE_BASE64_64_ENCRYPTION
      - 'EMAIL_URL=${EMAIL_URL:-consolemail://}'
      - 'DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-test@example.com}'
      - 'CELERY_WORKER_AUTOSCALE=${CELERY_WORKER_AUTOSCALE:-1,3}'
      - 'CELERY_WORKER_MAX_TASKS_PER_CHILD=${CELERY_WORKER_MAX_TASKS_PER_CHILD:-10000}'
```

and here the proxy configuration

```
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v3.1'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
      - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=500'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=500'
      - '--entrypoints.https.http3'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--providers.docker=true'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - coolify.managed=true
      - coolify.proxy=true
```

as mentioned, on safari it's working perfectly but it's broken on chrome (white screen not displaying anything).

This is what I see on the console and the network on chrome:

![Image](https://github.com/user-attachments/assets/e6019f31-1a94-4d89-b262-e92274c2242d)
![Image](https://github.com/user-attachments/assets/264156f0-f377-47f3-b373-ea89876ccc11)
