### ISSUE TITLE
[Bug]: Environment Variables being ignored.

### ISSUE THREAD

**Issue by Flow-dev0** [coollabsio/coolify#4092]
### Error Message and Logs

Running the default Directus with postgressql template and attempting to access it via its sdk on Nuxt. I face the following CORS issue. 
```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [https://directus.blink.lan/auth/login](https://directus.blink.lan/auth/login "https://directus.blink.lan/auth/login"). (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.```

### Steps to Reproduce

1.Deploy the basic Directus with postgres template without changing anything.

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

OpenSuse Tumbleweed

### Additional Information

For context Directus offers config options specfically related to CORS
[Directus Config](https://docs.directus.io/self-hosted/config-options.html#cors) However when passing the following values into "Environment Variables" tab

```
CORS_ENABLED=true
CORS_ORIGIN=http://void.lan:3000
```
I find that these changes are ignored and as a result still face the original issue. I am however able to get it working when manually editing the docker compose itself.

```
services:
  directus:
    image: 'directus/directus:11'
    volumes:
      - 'directus-uploads:/directus/uploads'
      - 'directus-extensions:/directus/extensions'
      - 'directus-templates:/directus/templates'
    environment:
      - SERVICE_FQDN_DIRECTUS_8055
      - KEY=$SERVICE_BASE64_64_KEY
      - SECRET=$SERVICE_BASE64_64_SECRET
      - 'ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}'
      - ADMIN_PASSWORD=$SERVICE_PASSWORD_ADMIN
      - DB_CLIENT=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
      - 'DB_DATABASE=${POSTGRESQL_DATABASE:-directus}'
      - DB_USER=$SERVICE_USER_POSTGRESQL
      - DB_PASSWORD=$SERVICE_PASSWORD_POSTGRESQL
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEBSOCKETS_ENABLED=true
      - CORS_ENABLED=true
      - CORS_ORIGIN=http://void.lan:3000
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '--spider'
        - 'http://127.0.0.1:8055/admin/login'
      interval: 5s
      timeout: 20s
      retries: 10
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgresql:
    image: 'postgis/postgis:16-3.4-alpine'
    platform: linux/amd64
    volumes:
      - 'directus-postgresql-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRESQL}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}'
      - 'POSTGRES_DB=${POSTGRESQL_DATABASE:-directus}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
  redis:
    image: 'redis:7-alpine'
    command: 'redis-server --appendonly yes'
    volumes:
      - 'directus-redis-data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 20s
      retries: 10

```

Im not sure if this is intended or if this simply a misconfiguration on coolify's end. If it helps I found a similar issue but the solutions are different as well as the use cases. [GitHub issue #2570](https://github.com/coollabsio/coolify/issues/2570#issuecomment-2333152597)
