### ISSUE TITLE
[Bug]: Plausible Analytics compose file mail service does not work on ARM

### ISSUE THREAD

**Issue by lamtonylam** [coollabsio/coolify#4131]
### Error Message and Logs

Plausible Analytics compose file mail service does not work on ARM

exec /usr/local/bin/docker-entrypoint.sh: exec format error  
On mail service logs

### Steps to Reproduce

1. Use ARM-cpu based VPS
2. Try to launch Plausible with the provided compose file https://raw.githubusercontent.com/coollabsio/coolify/main/templates/compose/plausible.yaml

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by peaklabs-dev** [comment]
A fix for this issue has been implemented and will be available in an upcoming release. Thank you for your patience.

**Comment by lamtonylam** [comment]
@peaklabs-dev 
I still get the error with mail service  


```
Saved configuration files to /data/coolify/services/p4woggskso4o8g4s48wskks8.
Creating Docker network.
3d28169aa8d531354247238bf24eae156bda65437911c0079223e5f8c78d2798
Starting service.
Pulling images.
 plausible-db Pulling 
 plausible-events-db Pulling 
 plausible Pulling 
 mail Pulling 
 plausible Pulled 
 mail Pulled 
 plausible-events-db Pulled 
 plausible-db Pulled 
Starting containers.
 Volume "p4woggskso4o8g4s48wskks8_plausible-postgres-data"  Creating
 Volume "p4woggskso4o8g4s48wskks8_plausible-postgres-data"  Created
 Volume "p4woggskso4o8g4s48wskks8_plausible-events-data"  Creating
 Volume "p4woggskso4o8g4s48wskks8_plausible-events-data"  Created
 Container mail-p4woggskso4o8g4s48wskks8  Creating
 Container plausible-db-p4woggskso4o8g4s48wskks8  Creating
 Container plausible-events-db-p4woggskso4o8g4s48wskks8  Creating
 Container mail-p4woggskso4o8g4s48wskks8  Created
 Container plausible-db-p4woggskso4o8g4s48wskks8  Created
 Container plausible-events-db-p4woggskso4o8g4s48wskks8  Created
 Container plausible-p4woggskso4o8g4s48wskks8  Creating
 Container plausible-p4woggskso4o8g4s48wskks8  Created
 Container plausible-events-db-p4woggskso4o8g4s48wskks8  Starting
 Container mail-p4woggskso4o8g4s48wskks8  Starting
 Container plausible-db-p4woggskso4o8g4s48wskks8  Starting
 Container mail-p4woggskso4o8g4s48wskks8  Started
 Container plausible-db-p4woggskso4o8g4s48wskks8  Started
 Container plausible-events-db-p4woggskso4o8g4s48wskks8  Started
 Container plausible-db-p4woggskso4o8g4s48wskks8  Waiting
 Container plausible-events-db-p4woggskso4o8g4s48wskks8  Waiting
 Container mail-p4woggskso4o8g4s48wskks8  Waiting
 Container mail-p4woggskso4o8g4s48wskks8  Error
 Container plausible-db-p4woggskso4o8g4s48wskks8  Healthy
 Container plausible-events-db-p4woggskso4o8g4s48wskks8  Healthy
dependency failed to start: container mail-p4woggskso4o8g4s48wskks8 is unhealthy
```

Logs from mail service
```
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

**Comment by pshemek** [comment]
I still have the same issue with v4.0.0-beta.370 on arm64 VPS  😞

**Comment by pshemek** [comment]
@lamtonylam I worked it around by editing the compose file and replacing the mail service image with `image: navanchauhan/smtp`, following this hint: https://github.com/BytemarkHosting/docker-smtp/issues/10#issuecomment-2408335168

It should be fine as soon as #4333 is fixed.

**Comment by peaklabs-dev** [comment]
The problem here is that the SMTP image is outdated and does not have an arm version available. So the problem is with the SMTP image and not with Coolify. I will think of a solution because there are several ways to solve this - we could enable emulation so we can run AMD images on ARM (probably our best bet because it is Coolify related) or we could switch to an alternative mail server image. Maybe I will start maintaining and updated version of the outdated mail server (I know there was a few already but just to be sure). Will have to give this some thought over the weekend though. If you guys have other suggestions let me know.

**Comment by pshemek** [comment]
Hi, I'd like to share a working setup of Plausible on ARM platform.

I just removed the email image from Docker compose entirely and added environment variables. Plausible can handle it by itself after setting up proper env vars.

Compose:
```
services:
  plausible:
    image: 'ghcr.io/plausible/community-edition:v2.1.4'
    command: 'sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"'
    environment:
      - SERVICE_FQDN_PLAUSIBLE
      - 'DATABASE_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@plausible-db:5432/${POSTGRES_DB:-plausible-db}'
      - 'CLICKHOUSE_DATABASE_URL=http://plausible-events-db:8123/plausible_events_db'
      - 'BASE_URL=${SERVICE_FQDN_PLAUSIBLE}'
      - 'SECRET_KEY_BASE=${SERVICE_BASE64_64_PLAUSIBLE}'
      - 'TOTP_VAULT_KEY=${SERVICE_REALBASE64_32_TOTP}'
      - 'MAILER_ADAPTER=${MAILER_ADAPTER}'
      - 'MAILER_EMAIL=${MAILER_EMAIL}'
      - 'MAILER_NAME=${MAILER_NAME}'
      - 'SMTP_HOST_ADDR=${SMTP_HOST_ADDR}'
      - 'SMTP_HOST_PORT=${SMTP_HOST_PORT}'
      - 'SMTP_USER_NAME=${SMTP_USER_NAME}'
      - 'SMTP_USER_PWD=${SMTP_USER_PWD}'
      - 'SMTP_HOST_SSL_ENABLED=${SMTP_HOST_SSL_ENABLED}'
    depends_on:
      plausible-db:
        condition: service_healthy
      plausible-events-db:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--tries=1'
        - '--spider'
        - 'http://127.0.0.1:8000/api/health'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s
  plausible-db:
    image: 'postgres:16-alpine'
    volumes:
      - 'plausible-postgres-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-plausible-db}'
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
  plausible-events-db:
    image: 'clickhouse/clickhouse-server:24.3.3.102-alpine'
    volumes:
      - 'plausible-events-data:/var/lib/clickhouse'
      -
        type: bind
        source: ./clickhouse/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/logging.xml
        read_only: true
        content: '<clickhouse><profiles><default><log_queries>0</log_queries><log_query_threads>0</log_query_threads></default></profiles></clickhouse>'
      -
        type: bind
        source: ./clickhouse/clickhouse-user-config.xml
        target: /etc/clickhouse-server/users.d/logging.xml
        read_only: true
        content: '<clickhouse><logger><level>warning</level><console>true</console></logger><query_thread_log remove="remove"/><query_log remove="remove"/><text_log remove="remove"/><trace_log remove="remove"/><metric_log remove="remove"/><asynchronous_metric_log remove="remove"/><session_log remove="remove"/><part_log remove="remove"/></clickhouse>'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1'
      start_period: 30s
```

Env variables (Resend SMTP in my case; 587 due to Hetzner)

```
MAILER_ADAPTER=Bamboo.Mua
MAILER_EMAIL=<valid sender email>
MAILER_NAME=Plausible Analytics
SMTP_HOST_ADDR=smtp.resend.com
SMTP_HOST_PORT=587
SMTP_USER_NAME=resend
SMTP_USER_PWD=<api key>
SMTP_HOST_SSL_ENABLED=false
```

Maybe it helps with #4333 as well.
