### ISSUE TITLE
[Bug]: Caddy proxy config ignores Strip prefix option

### ISSUE THREAD

**Issue by konstchri** [coollabsio/coolify#4206]
### Error Message and Logs

generated Docker compose uses "handle_path" instead of "handle" with "strip prefix" option diselected

``` yaml 
 appwrite-console:
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m
    container_name: appwrite-console
    image: 'appwrite/console:5.0.12'
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.364
      - coolify.serviceId=33
      - coolify.type=service
      - coolify.name=appwrite-console
      - coolify.pullRequestId=0
      - coolify.service.subId=122
      - coolify.service.subType=application
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/console*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=FQDNHERE'
      - caddy_ingress_network=NETWORKUID
    networks:
      NETWORKUID: null
    environment:
      COOLIFY_CONTAINER_NAME: '"appwrite-console"'
      COOLIFY_URL: 'FQDNHERE/console'
      COOLIFY_FQDN: FQDNHERE/console
```

### Steps to Reproduce

1. set proxy as Caddy
2. disable Strip prefix option in Service Settings
3. Service Stack > Edit Compose file > Show Deployable Compose > Caddy labels use "handle_path" instead of "handle" 

### Coolify Version

v4.0.0-beta.364

### Are you using Coolify Cloud?

No (self-hosted)

### Additional Information

https://github.com/coollabsio/coolify/blob/83f3d86922db2ae4129d8aaa93eb94d7de52e83b/bootstrap/helpers/docker.php#L271

should be 
``` php
    foreach ($domains as $loop => $domain) {
        $url = Url::fromString($domain);
        $host = $url->getHost();
        $path = $url->getPath();
        $host_without_www = str($host)->replace('www.', '');
        $schema = $url->getScheme();
        $port = $url->getPort();
        $handle = "handle_path"
        if ( ! $is_stripprefix_enabled){
            $handle = "handle"
        }
        if (is_null($port) && ! is_null($onlyPort)) {
            $port = $onlyPort;
        }
        if (is_null($port) && $predefinedPort) {
            $port = $predefinedPort;
        }
        $labels->push("caddy_{$loop}={$schema}://{$host}");
        $labels->push("caddy_{$loop}.header=-Server");
        $labels->push("caddy_{$loop}.try_files={path} /index.html /index.php");


        if ($port) {
            $labels->push("caddy_{$loop}.{$handle}.{$loop}_reverse_proxy={{upstreams $port}}");
        } else {
            $labels->push("caddy_{$loop}.{$handle}.{$loop}_reverse_proxy={{upstreams}}");
        }
        $labels->push("caddy_{$loop}.{$handle}={$path}*");
        if ($is_gzip_enabled) {
            $labels->push("caddy_{$loop}.encode=zstd gzip");
        }
        if ($redirect_direction === 'www' && ! str($host)->startsWith('www.')) {
            $labels->push("caddy_{$loop}.redir={$schema}://www.{$host}{uri}");
        }
        if ($redirect_direction === 'non-www' && str($host)->startsWith('www.')) {
            $labels->push("caddy_{$loop}.redir={$schema}://{$host_without_www}{uri}");
        }
        if (isDev()) {
            // $labels->push("caddy_{$loop}.tls=internal");
        }
    }
```

Also is there a way to disable prefix strip from an Env variable?
Like this perhaps $SERVICE_FQDN_API_NOSTRIP=/console
