### ISSUE TITLE
[Bug]: Minio template error "The string `:9001` is no a valid url."

### ISSUE THREAD

**Issue by che0one** [coollabsio/coolify#4229]
### Error Message and Logs

It seems impossible to add or save the actual MinIO template or integrate it over "New Resource -> Docker Compose Empty" with or without other containers due to an issue related to ":9001" part. The error message, "The string :9001 is not a valid URL," doesn't prevent saving the Compose configuration to Coolify Projects, but makes it impossible to save the MINIO_SERVER_URL and $MINIO_BROWSER_REDIRECT_URL variables or change other things...

Default minio template from Services list
```
services:
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_BROWSER_REDIRECT_URL=$MINIO_BROWSER_REDIRECT_URL
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 20s
      retries: 10
```
![Image](https://github.com/user-attachments/assets/9b7ec593-b761-48a3-bcbb-eaa9349c14c8)

### Steps to Reproduce

1. Copy Minio Template from Services List
2. Try to make new resource using Docker Compose Empty

### Example Repository URL

https://github.com/coollabsio/coolify/blob/main/templates/compose/minio.yaml

### Coolify Version

v4.0.0-beta.364

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04 & Alpine-Linux:Latest & Ubuntu 24.04 ARM

**Comment by chmielulu** [comment]
Changing the “:9001” part to, for example, “:8000” still gives the same error “The string :9001 is not a valid URL,” so it looks like the problem is not in the template itself. 

I tried specifying the port also using an environment variable, such as:
```yaml
services:
  minio:
    image: 'quay.io/minio/minio:latest'
    command: 'server /data --console-address ":${MINIO_CONSOLE_PORT}"'
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_BROWSER_REDIRECT_URL=$MINIO_BROWSER_REDIRECT_URL
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
      - MINIO_CONSOLE_PORT=9001
    volumes:
      - 'minio-data:/data'
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      interval: 5s
      timeout: 20s
      retries: 10
```
I then get the same error again and again, even after changing the port to a different one.
