### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by Bilge** [coollabsio/coolify#4244]
### Error Message and Logs

Having followed all the steps in [manual installation](https://coolify.io/docs/installation#2-manual-installation), the web interface returns HTTP 500 and the following information is shown in the container logs:

```
NOTICE: PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm.
Context: {"exception":{}} in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:140
Stack trace:
#0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(44): Monolog\Handler\StreamHandler->write()
#1 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(390): Monolog\Handler\AbstractProcessingHandler->handle()
#2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(645): Monolog\Logger->addRecord()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger.php(184): Monolog\Logger->error()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Logger...
```

This error repeats rapidly.

### Steps to Reproduce

I wrote the following Ansible role to reproduce the manual installation steps.

```yaml
- name: Create "coolify" user group
  group:
    name: coolify

- name: Create "coolify" user
  user:
    name: coolify
    group: coolify
    append: yes
    groups: docker
    shell: /bin/bash

- name: Create Coolify directories
  file:
    path: '{{ item }}'
    state: directory
    owner: 9999
    mode: 0700
  loop:
    - /data/coolify
    - /data/coolify/source
    - /data/coolify/ssh
    - /data/coolify/applications
    - /data/coolify/databases
    - /data/coolify/backups
    - /data/coolify/services
    - /data/coolify/proxy
    - /data/coolify/webhooks-during-maintenance
    - /data/coolify/ssh/keys
    - /data/coolify/ssh/mux
    - /data/coolify/proxy/dynamic

- name: Add "coolify" SSH authorized keys
  authorized_key:
    user: coolify
    key: '{{ lookup("file", "keyring/coolify.pub") }}'

# Necessary due to get_url bug: https://github.com/ansible/ansible/issues/64016
- name: Check Coolify sources downloaded
  check_mode: true
  file:
    path: /data/coolify/source/{{ item.name if item is mapping else item|basename }}
  loop:
    - https://cdn.coollabs.io/coolify/docker-compose.yml
    - https://cdn.coollabs.io/coolify/docker-compose.prod.yml
    - url: https://cdn.coollabs.io/coolify/.env.production
      name: .env
    - https://cdn.coollabs.io/coolify/upgrade.sh
  register: check
  failed_when: false

- name: Download missing Coolify sources
  get_url:
    url: '{{ item.item.url|default(item.item) }}'
    dest: '{{ item.path }}'
    owner: 9999
    mode: 0700
  loop: '{{ check.results }}'
  when: item.state == 'absent'
  register: sources

- name: Seed Coolify environment variables
  lineinfile:
    path: /data/coolify/source/.env
    line: '{{ item|first }}={{ lookup("pipe", "openssl rand " ~ item[item|first]) }}'
    regexp: ^{{ item|first }}=
  loop:
    - APP_ID: -hex 16
    - APP_KEY: -base64 32
    - DB_PASSWORD: -base64 32
    - REDIS_PASSWORD: -base64 32
    - PUSHER_APP_ID: -hex 32
    - PUSHER_APP_KEY: -hex 32
    - PUSHER_APP_SECRET: -hex 32
  when: sources.results|selectattr("item.item.name", "defined")|selectattr("item.item.name", "eq", ".env")|first
    is changed

- name: Create Coolify network
  community.docker.docker_network:
    name: coolify
    attachable: true

- name: Start Coolify
  community.docker.docker_compose_v2:
    project_src: /data/coolify/source/
    files:
      - docker-compose.yml
      - docker-compose.prod.yml
    pull: always
    recreate: always
    remove_orphans: true

```

### Coolify Version

latest

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04.3 LTS

### Additional Information

Indeed, even though all the directories I created are (as instructed) owned by `9999:root` on the host, and `9999:9999` in the container, the log file (`laravel.log`) is owned by `root:root`. Whatever created this, did so with the incorrect permissions.

As for the `Unsupported cipher or incorrect key length.` error, I cannot comment on why this occurs.
