### ISSUE TITLE
[Bug]: cannot access self-hosted after upgrade v4.0.0-beta.367

### ISSUE THREAD

**Issue by ryansyrl** [coollabsio/coolify#4253]
### Error Message and Logs

1. Tried with ip the page shows "404 not found"
2. Tried with sub-domain that registered to self-hosted coolify got response 502 bad gateway
3. I checked the docker inside my vm everything looks good and working, but still i cannot access it

this error occurs after i upgrade coolify to 4-beta.3.6.7

### Steps to Reproduce

1. upgrade the coolify 7to 4.0.0-bet.3.6
2.
3.
4.

### Coolify Version

v4.0.0-beta.3.6.7

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

ubuntu 22.04

**Comment by ryansyrl** [comment]
after i check again there's one service keeps restarting

![Image](https://github.com/user-attachments/assets/f6e39eef-77ac-4de3-885f-055654193890)


can someone tell me how to fix this?

**Comment by ershisan99** [comment]
Same here. Updated from 364 to 367 and am now getting 502 bad gateway @andrasbacsai

**Comment by andrasbacsai** [comment]
I will check what is going on. But until then, you can use the upgrade process provided in the link (previous comment).

**Comment by ryansyrl** [comment]
> I will check what is going on. But until then, you can use the upgrade process provided in the link (previous comment).

thank you very much!

**Comment by ershisan99** [comment]
> i found the temporary solution, install update manually using the third step from the documentation
> 
> https://coolify.io/docs/upgrade
> 
> if the manual update success, the instance will be back to normal again.


Yep, running this twice solved the issue, thank you!

**Comment by moshetanzer** [comment]
Getting 404 on everything!!!😱

**Comment by che0one** [comment]
I encounter this error frequently. Are you using dynamic middlewares? Also, is the Traefik dashboard enabled?
When i check coolify-proxy received the an error stating: 
someapp1@auth not found.
someapp2@auth not found.
someapp3@auth not found.
All from middlewares...

**Comment by Opswatch** [comment]
there is definately something funky with this update, the running the two ghost instances fix does not work im back to having the whole coolify instance crash

`root@ip-172-26-2-41:~# docker logs 885575759b6c
2024-11-12T20:19:08Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker
2024-11-12T20:19:12Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker
2024-11-12T20:24:59Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker
2024-11-12T20:33:22Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker
2024-11-12T20:42:07Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker
2024-11-12T20:42:13Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker
2024-11-12T20:42:14Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker
2024-11-12T20:42:20Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker
2024-11-12T20:49:29Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker
2024-11-12T20:59:42Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker
2024-11-12T21:37:33Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker
2024-11-12T21:37:38Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-pgwoscoooog4wckck8okk4g8-ghost@docker
2024-11-12T21:37:38Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker
2024-11-12T21:37:48Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-pgwoscoooog4wckck8okk4g8-ghost@docker
2024-11-12T21:37:48Z ERR error="middleware \"redir-ghost@docker\" does not exist" entryPointName=https routerName=https-0-v84co04040sswoo48w8ssoog-ghost@docker`

**Comment by che0one** [comment]
[Opswatch](https://github.com/Opswatch) Maybe something funky with ghost, everytime breaks something and not only on Coolify :)

**Comment by Opswatch** [comment]
@che0one its weird because with just one ghost i was getting a 404 from traffic after the update, ghost logs looked good same with sql db, then i launched the second ghost instance and everything broke, like the previous bug :(

**Comment by che0one** [comment]
@Opswatch 
There is only 2 solutions at least works:

1) Run update over coolify binary as mentioned @ershisan99 
2) Restart coolify-proxy using lazydocker. ( Restart from other points doesn't works ) 

And one works well:
1) Remove Ghost and swap to another app...

**Comment by alxhu-dev** [comment]
> i found the temporary solution, install update manually using the third step from the documentation
> 
> https://coolify.io/docs/upgrade
> 
> if the manual update success, the instance will be back to normal again.

Manual update tried to install OpenSSH although I already used a different SSH server before (which worked for months). Now I'm unable to connect to the machine via SSH at all :( I'm not at home right now, so I'm unable to fix this for the next days

**Comment by che0one** [comment]
@alxhu-dev Attempt to connect to http://ip:8000 and restart the proxy server. Ensure the connection works without using a proxy. If available, remove any dynamic middlewares before restarting the proxy server.

**Comment by alxhu-dev** [comment]
> @alxhu-dev Try to connect http://ip:8000 and restart the proxy server. Ensure the connection works without using a proxy. If available, if it show list of middlewares, remove any dynamic middlewares before restarting the proxy server. 

I'm unable to access it via IP/port

**Comment by theDanielJLewis** [comment]
I found that I have to re-enable the ports in order to access Coolify after an upgrade.

**Comment by luckydonald** [comment]
I'm having the same issue with 4.0.0-beta.370, which is what apparently is currently installed.

```shell
root@host:~# curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
Welcome to Coolify Installer!
This script will install everything for you. Sit back and relax.
Source code: https://github.com/coollabsio/coolify/blob/main/scripts/install.sh

---------------------------------------------
| Operating System  | ubuntu 20.04
| Docker            | 27.0
| Coolify           | 4.0.0-beta.370
| Helper            | 1.0.4
| Realtime          | 1.0.5
---------------------------------------------

1. Installing required packages (curl, wget, git, jq, openssl).
2. Check OpenSSH server configuration.
 - OpenSSH server is installed.
 - SSH PermitRootLogin is enabled.
3. Check Docker Installation.
 - Docker is installed.
4. Check Docker Configuration.
 - Docker configuration is up to date.
5. Download required files from CDN.
6. Make backup of .env to .env-20241118-220705
7. Propagating .env with new values - if necessary.
8. Checking for SSH key for localhost access.
9. Installing Coolify (4.0.0-beta.370)
 - It could take a while based on your server's performance, network speed, stars, etc.
 - Please wait.
 - Until then, here's a joke for you:

Four engineers get into a car. The car won't start.
The Mechanical engineer says "It's a broken starter".
The Electrical engineer says "Dead battery".
The Chemical engineer says "Impurities in the gasoline".
The IT engineer says "Hey guys, I have an idea: How about we all get out of the car and get back in".
```

But it still fails

```shell
root@host: ~# sleep 120

root@host: ~# curl https://coolify.example.com
Bad Gateway
```

**Comment by luckydonald** [comment]
I did dig a bit deeper, and will provide updates in this very post as I dig it up:
```shell
root@host:/data/coolify/source# cat upgrade-2024-11-18-22-04-18.log

 Container coolify  Stopping
 Container coolify  Stopping
 Container coolify  Stopping
 Container coolify  Stopped
 Container coolify-realtime  Recreate
 Container coolify  Stopped
 Container coolify-db  Recreate
 Container coolify  Stopped
 Container coolify-redis  Recreate
 Container coolify-realtime  Recreated
 Container coolify-redis  Recreated
 Container coolify-db  Recreated
 Container coolify  Recreate
 Container coolify  Recreated
 Container coolify-redis  Starting
 Container coolify-db  Starting
 Container coolify-realtime  Starting
 Container coolify-redis  Started
 Container coolify-db  Started
Error response from daemon: driver failed programming external connectivity on endpoint coolify-realtime (63a4511aa7e4c3da39fca68ed13c8b5b7a390735f90822824d2425a1996184bf): failed to bind port 0.0.0.0:6001/tcp: Error starting userland proxy: listen tcp4 0.0.0.0:6001: bind: address already in use
```

**Comment by luckydonald** [comment]
# Solution 1:
Follow this: https://github.com/coollabsio/coolify/issues/4253#issuecomment-2470846017,
i.e. run 
```shell
curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
```
 twice.


# Solution 2:

1. Check your logs in `/data/coolify/source`
    - the `upgrade-YYYY-MM-DD-HH-MM-SS.log` ones.
2. If it says `… failed to bind port 0.0.0.0:6001 …`, follow https://github.com/coollabsio/coolify/issues/4253#issuecomment-2484264637, which is in summary:
3. Figure out the process which uses the port 6001 from above:
    ```shell
    sudo lsof -i :6001
    ```
    ```txt
    COMMAND       PID USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
    docker-pr 2438214 root    4u  IPv4 2961781734      0t0  TCP *:x11-1 (LISTEN)
    ```
     - the `PID` (here `2438214`, yours will be different) will be needed for the next step
4. Kill the pid of the process on the port
    ```shell
    kill 2438214
    ```
5. Run the installer again, it should work now
    ```shell
    curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
    ```
    - you should get `Your instance is ready to use!` and a bunch of URLs.

**Comment by peaklabs-dev** [comment]
I am not sure what is causing this. The one error you describe is because Coolify Sentinel our metrics uses Port 6001 so that Port must be free otherwise it will fail.

**Comment by ebalder** [comment]
I was having this issue after upgrade, and it got fixed by restarting the main proxy

**Comment by hillct** [comment]
I always hate to be the one to re-open a ticket but, while I encountered this issue today upgrading from beta 355 to 389, it's more important to shed some light on the underlying issue here. The most frequent cause of this issue seems to be conflicts on port 6001 which is well defined and reserved in [RFC 1013](https://www.rfc-editor.org/rfc/rfc1013.html) as early as 1987 for X11 client server communications, so should never have been used for coolify-sentinel.

It's fair to say that most/all production deployments of Coolify will be on bare metal that will not include an X11 desktop, however, the vast majority of home lab deployments include multi-use hardware, on which a desktop environment might reasonably be installed.

The first remedial step here id one of documentation, to warn users that they should avoid colocating a coolify deployment on hardware where an X11 desktop is deployed, and if they do, to be aware that they will more than likely have to upgrade manually.

The long term solution should defiantly be to migrate coolify-sentinel to a port that is not otherwise reserved by a significant and well defined UNIX service. ALWAYS consult the RFCs before randomly grabbing up a port for a modern semi-commercial service and while I recognize that the process can be tedious, draft the needed IETF paperwork to reserve the port, if you believe your business is significant or will be long lived enough to justify it.

**Comment by Megajin** [comment]
Guys, I have had the same issue. However I am running the version v4.0.0-beta.390 . With my VPS the issue was that crowdsec used the port 8080. So I went ahead and changed the traefik config to this:

```
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v3.1'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
      - '8081:8081'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http3'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--api.insecure=false'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8081
      - coolify.managed=true
      - coolify.proxy=true
```

Just change 8080 to 8081 and it will work again.
