### ISSUE TITLE
[Bug]: Wildcard certificate not working

### ISSUE THREAD

**Issue by geovanygameros** [coollabsio/coolify#4360]
### Error Message and Logs

I've been following [this documentation](https://coolify.io/docs/knowledge-base/traefik/wildcard-certificates) to set up a wildcard domain for one application with no success.

What I want to achieve is the following setup for a SaaS application:

![Image](https://github.com/user-attachments/assets/928d4f98-513c-496f-90d3-0031ee151bdb)

I have several projects with a defined domain and they are working fine. However, I want all the rest subdomains to be sent to App 3

### Steps to Reproduce

I set up a wildcard A DNS record in Cloudflare pointing to my server's IP address (`*.mydomain.com`)

Based on [your documentation](https://coolify.io/docs/knowledge-base/traefik/wildcard-certificates), I ended up with a proxy file like this:

```yml
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v3.1'
    restart: unless-stopped
    environment:
      - CLOUDFLARE_API_KEY=xxx
      - CLOUDFLARE_DNS_API_TOKEN=xxx
      - CLOUDFLARE_EMAIL=xxx
      - CLOUDFLARE_ZONE_API_TOKEN=xxx
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
      - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http3'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0'
      - '--providers.docker=true'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.tls.domains[0].main=mydomain.com
      - traefik.http.routers.traefik.tls.domains[0].sans=*.mydomain.com
      - coolify.managed=true
      - coolify.proxy=true
```

Then in my application's container labels, I'm following the "SaaS" instructions. So I have something like this:
```yml
traefik.enable=true
traefik.http.routers.my-app-3-router.rule=HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.mydomain.com`)
traefik.http.routers.my-app-3-router.entryPoints=https
traefik.http.routers.my-app-3-router.middlewares=gzip
traefik.http.routers.my-app-3-router.service=my-app-3-service
traefik.http.services.my-app-3-service.loadbalancer.server.port=3000
traefik.http.routers.my-app-3-router.tls=true
traefik.http.routers.my-app-3-router.tls.certresolver=letsencrypt
traefik.http.routers.my-app-3-router.rule=HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.mydomain.com`)
traefik.http.routers.my-app-3-router.entryPoints=http
traefik.http.routers.my-app-3-router.middlewares=redirect-to-https
```

Then after restarting the proxy and my app, I get the following error when I go to any subdomain. E.g. `customer1.mydomain.com`
(for the subdomains that are explicitly defined like "App 1"  "App 2", they work fine)

![Image](https://github.com/user-attachments/assets/0c1dc368-b2b3-459c-a28c-06cdabd52949)

Am I missing something?

### Coolify Version

v4.0.0-beta.370

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

### Additional Information

I saw these similar discussions but none of them have a clear answer:
- [[Bug]: wildcard certificate documentation correct? ](https://github.com/coollabsio/coolify/issues/1951)
- [[Feature]: Wildcard Domains for each Project](https://github.com/coollabsio/coolify/issues/2391)
