### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by theDanielJLewis** [coollabsio/coolify#4406]
### Error Message and Logs

```
BadValue: Cannot start a configsvr as a standalone server. Please use the option --replSet to start the node as a replica set.
```

### Steps to Reproduce

1. Create a MongoDB service (version 6, 7, or 8—it doesn't matter).
2. Add the following configuration:
```
sharding:
  clusterRole: configsvr
replication:
  replSetName: "cfg0"
```
3. Save and start the service.
4. MongoDB will not start and will complain that the replica set option is missing, even though it's clearly there in the mongod.conf that Coolify creates.

### Coolify Version

v4.0.0-beta.370

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

### Additional Information

After a lot of digging and experimenting, I found the strangest cause for this. It's the `command` line of the docker-compose.yml file Coolify creates.

This is what Coolify's docker-compose.yml looks like (from `/data/coolify/databases/xs40cogkgoosggg08ckkw44o/` matching the service name):

```
services:
    xs40cogkgoosggg08ckkw44o:
        image: 'mongo:8'
        command: '--config /etc/mongo/mongod.conf'
        container_name: xs40cogkgoosggg08ckkw44o
        # ...
```

But that doesn't work with a shard config server setup no matter what I do inside the conf file (manually or through Coolify).

However, if we replace the `command` line with:

```
 command: "/bin/sh -c 'exec mongod --config /etc/mongo/mongod.conf'"
```

Or:

```
entrypoint: "/bin/sh"
command: "-c 'exec mongod --config /etc/mongo/mongod.conf'"
```

And then start the process manually with `docker compose up`, then `mongod` appears to start fine.

This seems to be primarily a Docker problem, but it's a Coolify problem, too, because Coolify is creating this faulty `docker-compose.yml` file. And even though there's a way to adjust it to work, Coolify overwrites my changes every time I press "Start" in the Coolify dashboard.

Aside: even though the error message is complaining about missing replica set configuration, adding `--replSet NAME` to the `command` line still didn't fix it. It seems the only way to use Docker to start a shard config server is by doing the shell trick as shown above.

(I will report this in the issues for the Mongo docker image, too.)
