### ISSUE TITLE
[Bug]: Traefik dynamic Middleware does not works without explicitly specifying the FQDN_PORT on Docker Compose

### ISSUE THREAD

**Issue by che0one** [coollabsio/coolify#4466]
### Error Message and Logs

For example default Maybe compose configuration from templates looks like SERVICE_FQDN_MAYBE, does not have any port number in environment variables, which prevents error on dynamic middleware and only works if explicitly specifying port number like SERVICE_FQDN_MAYBE_3000. 

Middleware works:
```
SERVICE_FQDN_MAYBE_3000
```

Middleware does not works:
```
SERVICE_FQDN_MAYBE
```

![Image](https://github.com/user-attachments/assets/abeda3af-41e5-460c-ba54-90f4c3f2104e)

### Steps to Reproduce

1. Install Maybe from templates or https://github.com/coollabsio/coolify/blob/main/templates/compose/maybe.yaml
2. Try to add some dynamic proxy middleware.

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04 x86 & ARM

**Comment by djsisson** [comment]
i cant reproduce the above bug, having no port, means coolify doesnt add any service in the labels, however traefik will generate it just fine

![Image](https://github.com/user-attachments/assets/0ce20202-aa2a-4a76-8963-5e7611974af2)

**Comment by djsisson** [comment]
@che0one you jsut add 
``` yaml
labels:
  - 'traefik.http.middlewares.myauth.basicauth.users=test:$2y$12$ci.4U63YX83CwkyUrjqxAucnmi2xXOIlEF6T/KdP9824f1Rf1iyNG'
 ```

to the compose service section

ive no idea what your above post is trying to show, you are referencing a service which doesnt exist, which explains your original error
if you are using your own dynamic files, dont reference anything in the container

**Comment by djsisson** [comment]
@che0one if you write your own dynamic files that is totally fine, you can write any combination of service/middleware routers etc

But you cant write a dynamic file and reference a service that doesn't exist, just write it out in the dynamic file yourself

Lastly, you can add any middleware to any service now, by just adding the middleware label to the service, it will be added automatically by coolify

There is no bug here

**Comment by djsisson** [comment]
@che0one 

yes, because if you don't specify a port, coolify cannot generate the required service labels, since they require a port for the loadbalancer,
and since you haven't specified a port it cannot generate them

if you are writing your own dynamic file just write your own service in the dynamic file

i will repeat there is no bug here

**Comment by che0one** [comment]
@djsisson can you explain how to do that? I just tested of course it doesn't works too

```
http:
  routers:
    convertx:
      rule: 'Host(`convert.mysite.com`) && (PathPrefix(`/`))'
      service: http-0-r4w0osksk44ws8kk0ws0kkcc-convertx@docker
      tls:
        certResolver: letsencrypt
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - 'test:$2a$05$QnuZwLw2LpFlSFYbKGky4Ow0UaQezn7wQ5HgfaoVAapFBkJiJSAXC'
services:
  http-0-r4w0osksk44ws8kk0ws0kkcc-convertx@docker:
    loadBalancer:
      servers:
        -
          url: 'http://http-0-r4w0osksk44ws8kk0ws0kkcc-convertx:3000'
```

![Image](https://github.com/user-attachments/assets/4aba44c1-1c64-4b4b-9e16-c0ce1a526696)
![Image](https://github.com/user-attachments/assets/e6a18acd-b233-4892-8277-8b06666b9e25)

**Comment by djsisson** [comment]
@che0one you are trying to mix dynamic files and container labels, thats not how it works

either add this line to your compose:

```yaml
labels:
  - 'traefik.http.middlewares.myauth.basicauth.users=test:$2y$12$ci.4U63YX83CwkyUrjqxAucnmi2xXOIlEF6T/KdP9824f1Rf1iyNG'
```

or use this dynamic file

```yaml
http:
  middlewares:
    redirect-to-https:
      redirectscheme:
        scheme: https
    gzip:
      compress: true
    myauth:
      basicAuth:
        users:
          - 'test:$2a$05$QnuZwLw2LpFlSFYbKGky4Ow0UaQezn7wQ5HgfaoVAapFBkJiJSAXC'
  routers:
    convertx-http:
      middlewares:
        - redirect-to-https
      entryPoints:
        - http
      service: convertx
      rule: Host(`subdomain.domain.com`)
    convertx-https:
      middlewares:
        - gzip
        - myauth
      entryPoints:
        - https
      service: convertx
      rule: Host(`subdomain.domain.com`)
      tls:
        certresolver: letsencrypt
  services:
    convertx:
      loadBalancer:
        servers:
          -
            url: 'http://containernam:3000'

```

tested both ways

![Image](https://github.com/user-attachments/assets/11f8e355-7fba-4906-9beb-5b8600246a07)
