### ISSUE TITLE
[Bug]: "EACCES: permission denied" at File Mount after updating Docker Compose

### ISSUE THREAD

**Issue by nickosh** [coollabsio/coolify#4490]
### Error Message and Logs

error: Config file YAML format is invalid: EACCES: permission denied, open '/app/librechat.yaml'

### Steps to Reproduce

1. Start Docker Compose. Docker Compose config not included any USER params but included file with "content:".
2. Check that everything works as expected.
3. Edit Docker Compose configuration.
4. At start, will be "EACCES: permission denied" error at mounted file.

### Coolify Version

v4.0.0-beta.375

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Rocky Linux 9.5

### Additional Information

Seems error related to these issues: https://github.com/coollabsio/coolify/issues/3970, https://github.com/coollabsio/coolify/issues/2862

Temporary workaround:

1. Copy content of File Mount and remove it from configuration.
2. Include content from 1st step inside Docker Compose, e.x.:
```
volumes:
      -
        type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
        is_directory: false
        content: |
          version: 1.0.8
      
          cache: true
      
          interface:
            # Privacy policy settings
            privacyPolicy:
              externalUrl: 'https://librechat.ai/privacy-policy'
              openNewTab: true
      
            # Terms of service
            termsOfService:
              externalUrl: 'https://librechat.ai/tos'
              openNewTab: true
      
          registration:
            socialLogins: ["discord", "facebook", "github", "google", "openid"]

      - 'libre_imgs:/app/client/public/images'
      - 'libre_logs:/app/api/logs'
```
3. File Mount will be recreated and will work till next Docker Compose editing.

**Comment by gregmuellegger** [comment]
Ran into the same issue with supabase, which also uses the volume bind to create a file with the special coolify `content` parameter:

https://github.com/coollabsio/coolify/blob/v4.x/templates/compose/supabase.yaml#L32-L39

```yml
    volumes:
      # https://github.com/supabase/supabase/issues/12661
      - type: bind
        source: ./volumes/api/kong.yml
        target: /home/kong/temp.yml
        content: |
          _format_version: '2.1'
          _transform: true
```

After server reboot (i.e. after docker restart) it ran into a state where the container was not able to read the file again:

```
sh: 0: getcwd() failed: No such file or directory
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/init.lua:553: in function 'init'
        init_by_lua:3: in main chunk
cat: can't open '/home/kong/temp.yml': Permission denied
2025/11/27 07:26:47 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
2025/11/27 07:26:47 [warn] 1#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2025/11/27 07:26:47 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:553: error parsing declarative config file /home/kong/kong.yml:
failed parsing declarative configuration: expected an object
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/init.lua:553: in function 'init'
        init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:553: error parsing declarative config file /home/kong/kong.yml:
failed parsing declarative configuration: expected an object
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/init.lua:553: in function 'init'
        init_by_lua:3: in main chunk
```

Only when deleting the file on the host system and then redeploying the service will start again (and fail again on next restart).

It might be useful to allow setting the UID:GID (chown) and permissions (chmod) for the bind mount.

---

My current workaround is to set the file permissions with a sidecar container:

```yaml
services:
  fix-supabase-kong-file-permission:
    image: alpine:latest
    # We need to fix the permission for the kong config file as coolify seems to
    # set it to 640 for coolify user, but kong operates as user 100.
    # See https://github.com/coollabsio/coolify/issues/4490#issuecomment-3584516155
    command: ash -c 'while true; do sleep 30; chown 100 /mnt/volumes/api/kong.yml ; ls -la /mnt/volumes/api/; done'
    volumes:
      - type: bind
        source: ./volumes/api/
        target: /mnt/volumes/api/
```
