### ISSUE TITLE
[Bug]: PHP FPM not starting correctly when deploying through Github Webhook

### ISSUE THREAD

**Issue by MasterPuffin** [coollabsio/coolify#4508]
### Error Message and Logs

I have a setup with a PHP app running on php:8.3-fpm-alpine. When deploying manually through the Coolify interface, everything works as it should. However when the deployment is triggered from a Github Webhook, the proxy returns a Gateway Timeout. When redeploying through the Coolify interface it works again.
Here is the docker-compose
```
version: '3.8'

services:
  app:
    image: php:8.3-fpm-alpine
    container_name: php-app
    working_dir: /var/www/html
    volumes:
      #      - ./:/var/www/html
      - /var/lib/docker/volumes/app/config:/var/www/html/config
      - /var/lib/docker/volumes/app/backup:/var/www/html/backup
      - /var/lib/docker/volumes/app/userdata:/var/www/html/userdata
      - /var/lib/docker/volumes/cofapps/.log:/var/www/html/.log
      - /var/lib/docker/volumes/app/.tmp:/var/www/html/.tmp
      - ./server/php/php.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "9000:9000"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  webserver:
    image: nginx:alpine
    container_name: nginx-web
    volumes:
      - ./server/nginx/sites:/etc/nginx/sites
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./shared_assets:/var/www/html/shared_assets
      - ./instances:/var/www/html/instances
    environment:
      - ENVIRONMENT=production
    ports:
      - "89:80"
    depends_on:
      - app
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
```
and here is the Dockerfile
```
FROM php:8.3-fpm-alpine

# Install necessary dependencies for PHP extensions and Composer
RUN apk add --no-cache \
    zip \
    curl \
    mysql-client \
    mariadb-connector-c

COPY --from=ghcr.io/mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions mysqli intl curl exif gd fileinfo mbstring zip dom

# Enable PHP OPcache
RUN docker-php-ext-install opcache

# Configure PHP-FPM to bind to 0.0.0.0:9000
RUN sed -i 's/^listen = .*/listen = 0.0.0.0:9000/' /usr/local/etc/php-fpm.d/www.conf

# Set working directory
WORKDIR /var/www/html

# Copy application code
COPY . .

# Install Composer dependencies
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
    composer install --no-dev --optimize-autoloader

```

### Steps to Reproduce

1. Merge into main branch on Github
2. Let Coolify run the automated deployment

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)
