### ISSUE TITLE
[Bug]: SSL not working with CloudFlare

### ISSUE THREAD

**Issue by johnykes** [coollabsio/coolify#4552]
### Error Message and Logs

Hey guys,

I'm not sure if that's a bug or I'm just missing something, but I'm desperate to make it work (that's why I just added a bounty too).

Steps:
- installed coolify
- created a CF tunnel as [here](https://coolify.io/docs/knowledge-base/cloudflare/tunnels/#wildcard-subdomain---all-resources), except that I used http://coolify-proxy:80 instead of http://localhost:80, as I've seen [here](https://github.com/coollabsio/coolify/discussions/2926); PS: also switched to 'Full' encryption mode & manually created the DNS CNAME for the wildcard
- created a cloudflared container with the token from the previous step:
```
services:
  cloudflared:
    container_name: cloudflare-tunnel
    image: 'cloudflare/cloudflared:latest'
    restart: unless-stopped
    command: 'tunnel --no-autoupdate run'
    environment:
      - 'TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}'
    networks:
      - coolify
networks:
  coolify:
    external: true
```

Result: If I create a web app with the domains `http://web.app.com,https://web.app.com`, the http URL will work, but the https one won't.

I tried modifying the default `Traefik` configuration, an I also tried the `Caddy` proxy, but I couldn't make it work whatever I tried.

Am I missing something?

### Steps to Reproduce

1. Mentioned above

### Coolify Version

v4.0.0-beta.376

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04
