### ISSUE TITLE
[Bug]: Unable to deploy mcuadros/ofelia: Non-string key in services.reset-monthly-subscriptions-credits.labels: 0

### ISSUE THREAD

**Issue by fstn** [coollabsio/coolify#4560]
### Error Message and Logs

When trying to deploy:
```
  reset-monthly-subscriptions-credits:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.call-endpoint.schedule: "0 0 1 * *"
      ofelia.job-local.call-endpoint.command: "./blabla"
```

Got
```

docker exec h0wswgkg8cwsg40gwk0osoo8 bash -c 'SOURCE_COMMIT=2d7ebbbb99a151f290a3930ddbcc3a64e7c6a2c8 COOLIFY_BRANCH=main  docker compose --env-file /artifacts/h0wswgkg8cwsg40gwk0osoo8/.env --project-name wswg48g8g0sgc88ssc84go0w --project-directory /artifacts/h0wswgkg8cwsg40gwk0osoo8 -f /artifacts/h0wswgkg8cwsg40gwk0osoo8/docker-compose.yaml build --pull'
2024-Dec-13 00:44:34.499706
Non-string key in services.reset-monthly-subscriptions-credits.labels: 0
2024-Dec-13 00:44:34.541239
Oops something is not okay, are you okay? 😢
2024-Dec-13 00:44:34.544809
Non-string key in services.reset-monthly-subscriptions-credits.labels: 0
```

Version: v4.0.0-beta.376

### Steps to Reproduce

  reset-monthly-subscriptions-credits:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.call-endpoint.schedule: "0 0 1 * *"
      ofelia.job-local.call-endpoint.command: "./blabla"

### Coolify Version

v4.0.0-beta.376

### Are you using Coolify Cloud?

No (self-hosted)
