### ISSUE TITLE
[Bug]: Can't add AWS S3 storage

### ISSUE THREAD

**Issue by kozmotronik** [coollabsio/coolify#4575]
### Error Message and Logs

When I enter the credentials (the credentials are correct) and hit the **Validate** button, I get the following error after a short while:
```
Unable to list contents for '', shallow listing

Reason: Error parsing response for ListObjectsV2: AWS parsing error: Error parsing XML: String could not be parsed as XML
```
![Image](https://github.com/user-attachments/assets/feaf437d-285d-4531-bb06-93370ff75f13)

PS: I think it is worth to mention that the AWS S3's secret key contains `/` character in it... 

### Steps to Reproduce

1. In the S3 Storages section click Add
2. Enter the credentials as per indicated in the [docs](https://coolify.io/docs/knowledge-base/s3/aws)
3. Click **Validate Connections & Continue** button
4.

### Coolify Version

v4.0.0-beta.379

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian 12

### Additional Information

I tried adding my AWS S3 storage in Coolify v4.0.0-beta.375 first. It was failing with the same error. Then I updated it to the latest version today, with the hope of that error would gone but no avail. So after making some research in the issue section of the Coolify repo and found nothing similar. Then I had to post this issue.

I wanna add an S3 storage to backup some important data like that of the Redmine etc. I then tried to schedule a local backup for the redmine's postgres database, but this time I get an error as following everytime the backup job get executed:
```
bash: line 2: Fe: command not found
"docker exec" requires at least 2 arguments.
See 'docker exec --help'.

Usage:  docker exec [OPTIONS] CONTAINER COMMAND [ARG...]

Execute a command in a running container
```
![Image](https://github.com/user-attachments/assets/c17609d2-64b3-4790-8cc2-cc12d22bcfb1)

Please let me know if I should open another issue for local backup error. Also please let me know if I'm doing something wrong or is it a Coolify bug as I think or if I need to elaborate futher information.

Kind regards

**Comment by peaklabs-dev** [comment]
You are using the wrong endpoint URL. The URL you are using is for static website hosting only, not for API/S3 bucket access. Please recheck the endpoint and you credentials and it should work.

**Comment by kozmotronik** [comment]
Thank you for your response @peaklabs-dev. You are right, that was it. I did not think that there were more than one end point types since I am an AWS noob. So looking at some stackoverflow posts, I noted that I should have used the **REST endpoint** type. So I removed `-website` part from the url then entered the credential and that's it. The S3 storage was successfuly added.

But the backup error in my question still persists. Is there something that I am missing? Should I post the compose file?

**Comment by peaklabs-dev** [comment]
Can you please tell me the docker and docker compose version you are running? 
Also the compose file would help.

**Comment by kozmotronik** [comment]
Sure, here is the information:
```sh
$ docker --version
Docker version 27.4.0, build bde2b89
$ docker compose version
Docker Compose version v2.31.0
```

```yaml
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    networks:
      - redmine
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_PASSWORD=mydbpassword'
      - POSTGRES_DB=redmine
  redmine:
    image: 'redmine:latest'
    restart: always
    networks:
      - redmine
    volumes:
      - 'redmine-data:/usr/src/redmine/files'
      - 'redmine-themes:/usr/src/redmine/themes'
      - 'redmine-plugins:/usr/src/redmine/plugins'
    ports:
      - '82:3000'
    environment:
      - REDMINE_DB_POSTGRES=postgres
      - REDMINE_DB_DATABASE=redmine
      - 'REDMINE_DB_PASSWORD=mydbpassword'
volumes:
  postgres-data: null
  redmine-data: null
  redmine-themes: null
  redmine-plugins: null
networks:
  redmine:
    driver: bridge
```
I've added two extra volumes for themes and plugins to make themes and plugins persistent.
