### ISSUE TITLE
[Bug]: checkmate don't work with cloudflare

### ISSUE THREAD

**Issue by louanfontenele** [coollabsio/coolify#4577]
### Error Message and Logs

Client:
[client.txt](https://github.com/user-attachments/files/18138099/client.txt)
MongoDB:
[mongodb.txt](https://github.com/user-attachments/files/18138098/mongodb.txt)
Redis:
[redis.txt](https://github.com/user-attachments/files/18138097/redis.txt)
Server:
[server.txt](https://github.com/user-attachments/files/18138100/server.txt)

### Steps to Reproduce

1. Use clouflare
2. Install checkmate
3. Try to create an account
4. Can't login

### Coolify Version

Coolify v4.0.0-beta.379

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

### Additional Information

Hello everyone, how are you? I'm having problems installing checkmate. It installs correctly, but says it's unhealthy.
![Image](https://github.com/user-attachments/assets/9d0fc2c4-f20e-4224-a58a-b9cdcbe917d7)
![Image](https://github.com/user-attachments/assets/a65586d5-15ce-4ea3-aaca-ef800209b2ae)
![Image](https://github.com/user-attachments/assets/37de2669-92a7-4278-90d7-5e54ccfc6a25)

**Comment by louanfontenele** [comment]
@ShadowArcanist found this:
![Image](https://github.com/user-attachments/assets/80513b5e-bcdb-48e7-88ec-cd799bf4330a)

![Image](https://github.com/user-attachments/assets/70da5592-928d-4c40-a209-889a8b69f724)

**Comment by gorkem-bwl** [comment]
Let's check this on our end @louanfontenele - thank you.

**Comment by louanfontenele** [comment]
> Let's check this on our end (Checkmate) - thank you [@louanfontenele](https://github.com/louanfontenele)

I really don't know if the problem is Cloudflare, but another user said that he doesn't use Cloudflare and was able to connect, all other applications work, but this one doesn't work correctly.

**Comment by TPGLLC-US** [comment]
i am having a similar issue. No console output. The login button just shows a spinner and hangs on the login screen
Coolify Cloud
I was not able to use the Coolify template for the checkmate resource because when I click it the resource templates page just reloads and does not proceed.

**Comment by louanfontenele** [comment]
> i am having a similar issue. No console output. The login button just shows a spinner and hangs on the login screen Coolify Cloud I was not able to use the Coolify template for the checkmate resource because when I click it the resource templates page just reloads and does not proceed.

The same app? Checkmate?

**Comment by TPGLLC-US** [comment]
Yes checkmate. See Docker Compose below

```
version: '3.8'
services:
  client:
    image: 'bluewaveuptime/uptime_client:latest'
    environment:
      UPTIME_APP_API_BASE_URL: 'https://myServerURL.dev:5000/api/v1'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - server
    restart: always
  server:
    image: 'bluewaveuptime/uptime_server:latest'
    ports:
      - '5000:5000'
    depends_on:
      - redis
      - mongodb
    environment:
      - 'DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db'
      - REDIS_HOST=redis
  redis:
    image: 'bluewaveuptime/uptime_redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - './redis/data:/data'
  mongodb:
    image: 'bluewaveuptime/uptime_database_mongo:latest'
    volumes:
      - './mongo/data:/data/db'
    command:
      - mongod
      - '--quiet'
    ports:
      - '27017:27017'
```

**Comment by louanfontenele** [comment]
> Yes checkmate. See Docker Compose below
> 
> ```
> version: '3.8'
> services:
>   client:
>     image: 'bluewaveuptime/uptime_client:latest'
>     environment:
>       UPTIME_APP_API_BASE_URL: 'https://myServerURL.dev:5000/api/v1'
>     ports:
>       - '80:80'
>       - '443:443'
>     depends_on:
>       - server
>     restart: always
>   server:
>     image: 'bluewaveuptime/uptime_server:latest'
>     ports:
>       - '5000:5000'
>     depends_on:
>       - redis
>       - mongodb
>     environment:
>       - 'DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db'
>       - REDIS_HOST=redis
>   redis:
>     image: 'bluewaveuptime/uptime_redis:latest'
>     ports:
>       - '6379:6379'
>     volumes:
>       - './redis/data:/data'
>   mongodb:
>     image: 'bluewaveuptime/uptime_database_mongo:latest'
>     volumes:
>       - './mongo/data:/data/db'
>     command:
>       - mongod
>       - '--quiet'
>     ports:
>       - '27017:27017'
> ```



Mine docker compose:
```
services:
  client:
    image: 'bluewaveuptime/uptime_client:latest'
    environment:
      - SERVICE_FQDN_CHECKMATE_80
      - 'UPTIME_APP_API_BASE_URL=${SERVICE_FQDN_CHECKMATESERVER_5000}/api/v1'
    depends_on:
      - server
  server:
    image: 'bluewaveuptime/uptime_server:latest'
    environment:
      - SERVICE_FQDN_CHECKMATESERVER_5000
      - 'JWT_SECRET=${SERVICE_PASSWORD_64_JWT}'
      - 'REFRESH_TOKEN_SECRET=${SERVICE_PASSWORD_64_REFRESH}'
      - 'SYSTEM_EMAIL_ADDRESS=${SYSTEM_EMAIL_ADDRESS:-test@example.com}'
      - 'SYSTEM_EMAIL_PASSWORD=${SERVICE_PASSWORD_64_EMAIL}'
      - 'SYSTEM_EMAIL_HOST=${SYSTEM_EMAIL_HOST}'
      - 'SYSTEM_EMAIL_PORT=${SYSTEM_EMAIL_PORT}'
      - 'PAGESPEED_API_KEY=${PAGESPEED_API_KEY}'
      - 'DB_CONNECTION_STRING=${DB_CONNECTION_STRING:-mongodb://mongodb:27017/uptime_db}'
      - 'REDIS_HOST=${REDIS_HOST:-redis}'
      - 'REDIS_PORT=${REDIS_PORT:-6379}'
      - 'DB_TYPE=${DB_TYPE:-MongoDB}'
      - 'TOKEN_TTL=${TOKEN_TTL:-99d}'
      - 'REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL:-99d}'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - redis
      - mongodb
  redis:
    image: 'bluewaveuptime/uptime_redis:latest'
    volumes:
      - 'redis:/data'
  mongodb:
    image: 'bluewaveuptime/uptime_database_mongo:latest'
    volumes:
      - 'mongodb:/data/db'
    command:
      - mongod
      - '--quiet'
```

**Comment by gorkem-bwl** [comment]
> i am having a similar issue. No console output. The login button just shows a spinner and hangs on the login screen Coolify Cloud I was not able to use the Coolify template for the checkmate resource because when I click it the resource templates page just reloads and does not proceed.

Do you also use Cloudflare Tunnels?

**Comment by Sh3nron** [comment]
> I was not able to use the Coolify template for the checkmate resource because when I click it the resource templates page just reloads and does not proceed.

I am having the same problem on coolify cloud.

**Comment by gorkem-bwl** [comment]
> > I was not able to use the Coolify template for the checkmate resource because when I click it the resource templates page just reloads and does not proceed.
> 
> I am having the same problem on coolify cloud.

Do you use CloudFlare Tunnels as well? @Sh3nron

**Comment by louanfontenele** [comment]
Well, I believe I discovered the problem, the issue is that I cannot edit the variables in the first image, even editing the links through the Coolify settings, due to the inconsistency, and therefore, it cannot connect, however when I leave the original link, it works normally.

![Image](https://github.com/user-attachments/assets/9ceb9e4e-fd61-4054-9f1d-95afa0102505)

![Image](https://github.com/user-attachments/assets/c661a332-ad65-44f1-a49b-3051644125b7)

**Comment by louanfontenele** [comment]
Even though I managed to edit the variables, the error still occurs, but if I leave everything normal, including the extended URLs, it works normally.

But that's it, I disabled Cloudflare, created one from scratch, editing the domains, but it didn't work.

When used normally (with that generated and extended domain), it was able to connect without any problems.

**Comment by Sh3nron** [comment]
> > > I was not able to use the Coolify template for the checkmate resource because when I click it the resource templates page just reloads and does not proceed.
> > 
> > 
> > I am having the same problem on coolify cloud.
> 
> Do you use CloudFlare Tunnels as well? [@Sh3nron](https://github.com/Sh3nron)

I do not however the domain is registered on cloudflare and they are providing a proxy. The issue appears to be related to the template having a bug.  See @louanfontenele  screenshot above.

**Comment by gorkem-bwl** [comment]
> same bug here

Thanks for confirming. One of our devs are working on it now.

**Comment by miqdadalik** [comment]
This is working fine for me.

My docker-compose

`docker-compose.yaml 
services:
  client:
    image: bluewaveuptime/uptime_client:latest
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "https://c-api.mydomain.com/api/v1"
    ports:
      - "5800:80"
      - "5443:443"
    depends_on:
      - server
  server:
    image: bluewaveuptime/uptime_server:latest
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db
      - REDIS_HOST=redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  redis:
    image: bluewaveuptime/uptime_redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  mongodb:
    image: bluewaveuptime/uptime_database_mongo:latest
    restart: always
    volumes:
      - ./mongo/data:/data/db
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
  capture:
    image: ghcr.io/bluewave-labs/capture:latest
    restart: always
    ports:
      - "59232:59232"
    volumes:
      - /etc/os-release:/etc/os-release:ro
    environment:
      - API_SECRET=MY_API_SECRET
`

Created three public hostname in cloudflare tunnel.

c-client.mydomain.com -> pointing to http://localhost:5800
c-api.mydomain.com -> pointing to http://localhost:5000
c-agent.mydomain.com -> pointing to http://localhost:59232

![Image](https://github.com/user-attachments/assets/95cc685a-f2dc-4328-82d5-c118a0e601d4)

**Comment by gorkem-bwl** [comment]
We had a look at it and we think that env variables might have been set with double quotes, which shouldn't be the case. That's something we figured out users may have an issue.

**Comment by LemDog** [comment]
![Image](https://github.com/user-attachments/assets/35f39417-7942-464a-a802-4dca786da56c)

Just providing this image seen from trying to get this to work as well. 

Also using cloud-flare tunnel. There is a particular API call made that is using some unmodifiable value. I tried everything I could think of from the Coolify dashboard but no dice. Works perfectly if I don't touch anything and leave it with the autogenerated FQDNs. 

Tried:
Recreating env variables with proper FQDNs before deploying. 
Use hard-coded static values within the docker compose for fields where FQDN is present.

**Comment by LemDog** [comment]
![Image](https://github.com/user-attachments/assets/ce620217-670e-4a71-a906-326f62cafb10)

Just providing this image seen from trying to get this to work as well.

Also using cloud-flare tunnel. There is a particular API call made that is using some unmodifiable value. I tried everything I could think of from the Coolify dashboard but no dice. Works perfectly if I don't touch anything and leave it with the autogenerated FQDNs.

Tried:
Recreating env variables with proper FQDNs before deploying.
Use hard-coded static values within the docker compose for fields where FQDN is present.

**Comment by ajhollid** [comment]
Hi @LemDog ,

When you mentioned

> There is a particular API call made that is using some unmodifiable value

do you mean all of the other API calls are working as expected?

There aren't any hardcoded values for API calls, they all use the same base API url that is specified in the env vars  🤔 

Can you share what env vars you have set up?

**Comment by gorkem-bwl** [comment]
@onigunn can you give me more context about sslip.io domain? Is this related to Checkmate?

**Comment by onigunn** [comment]
@gorkem-bwl 
If you create a new checkmate instance from the coolify instance, the sslip.io domain is prefilled in the configuration. This prefilled domain can be edited in the coolify UI but will not have an effect to the checkmate instance. The checkmate env vars are still pointing to the sslip.io domains. 

I would say its related to the checkmate coolify template.

I'm running on v4.0.0-beta.407.

**Comment by biewdev** [comment]
> > Hi [@LemDog](https://github.com/LemDog) ,
> > When you mentioned
> > > There is a particular API call made that is using some unmodifiable value
> > 
> > 
> > do you mean all of the other API calls are working as expected?
> > There aren't any hardcoded values for API calls, they all use the same base API url that is specified in the env vars 🤔
> > Can you share what env vars you have set up?
> 
> What we mean here is that there is something wrong with the base URL all API calls get to.
> 
> [coolify/templates/compose/checkmate.yaml](https://github.com/coollabsio/coolify/blob/4a1f8e925f6c6d24987b40d2d30186f35803e40f/templates/compose/checkmate.yaml#L12)
> 
> Line 12 in [4a1f8e9](/coollabsio/coolify/commit/4a1f8e925f6c6d24987b40d2d30186f35803e40f)
> 
>  - UPTIME_APP_API_BASE_URL=${SERVICE_FQDN_CHECKMATESERVER_5000}/api/v1 
> We are having trouble having this value modified and reflected in our deployment. It seems like, this value sticks to a certain one, and no matter what we did to change `SERVICE_FQDN_CHECKMATESERVER_5000` or just hardcode this value in the docker compose file, at the end of the day the base URL our deployment gets is still the original one without modification.
> 
> I am not sure if it's a checkmate problem, Coolify problem or Cloudflare problem. To me it's least likely Cloudflare and most likely Coolify.

That's exactly what's happening to me.

**Comment by kevin9092** [comment]
I ran into this issue a few minutes ago. A quick workaround for the time being is to update the front-end to use the domain name you want eg. https://checkmate.domain.com/ and then to leave the checkmate server address as the one it was created with.

While this is not ideal, it works for the time being.

**Comment by includenull** [comment]
I was also having the same issue using the checkmate template.

The frontend was insisting on trying to connect to the api using the generated domain even though I set a new domain.

The issue for me was a combination of docker compose config and Cloudflare cache.

1. Docker Compose. If you change the domain, you need to change the docker compose too.
  `'UPTIME_APP_API_BASE_URL=${SERVICE_FQDN_CHECKMATESERVER_5000}/api/v1'` will **generate** the domain here, so you need to change this line to match your new URL.
  e.g. `'UPTIME_APP_API_BASE_URL=https://your-new-url.domain.com/api/v1'`

2. The client doesn't seem to have any cache busting so the React app gets built with the same filenames each time, even if environment variables have changed. In my case, index-CO2SgZMe.js was being cached in Cloudflare with the wrong API url in the code.  
  I cleared the file from CloudFlare cache and it's working.

**Comment by kevin9092** [comment]
@includenull I think there is something wrong with the docker setup provided by Checkmate for the Coolify service.

Spin up a fresh Checkmate service in Coolify and you will notice:

- Default settings work on a fresh start, however restarting the service will randomly break the server with a CORS issue on the client side. Example:
``` Access to XMLHttpRequest at 'https://checkmateserver-ds8084o8k4cgggckos8o8wgo.domain.com/api/v1/auth/login' from origin 'https://checkmate-ds8084o8k4cgggckos8o8wgo.domain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. ```

- Changing domain does not work as intended and you need to manually edit the docker config file to fix this, but you will be hit with the same CORS issue above.
- Redis is spamming server logs with `ReplyError: NOAUTH Authentication required.` even though auth should not be required?

I did the same thing that you posted yesterday evening and it worked until I restarted my service and I got the CORS issue above, which is why I wanted to see if the same thing would happen with defaults and it did. This is an application set up issue, not a docker issue, as for some reason after a restart the application is no longer configured as a CORS allowed origin.

I may try to set this up manually instead of via the service later and report back.

**Comment by dropalltables** [comment]
This exact problem is happening to me too, fresh install with custom domains fails outright, with the exact same errors as everyone else. (Insecure Endpoint)

**Comment by gorkem-bwl** [comment]
@dropalltables was it 2.1 you deployed, or previous version ? (just released 2.1 with some fixes)

**Comment by dropalltables** [comment]
For both the server and client it's on the latest version.

Server (bluewaveuptime/uptime_server:latest)

Client (bluewaveuptime/uptime_client:latest)

**Comment by ahsan-abrar** [comment]
I am also experiencing the network error. I have manually updated the new server URL in the environment variables.

For example, I set my checkmate server URL to "checkmateserver.abc.com" and when I check these env variables are not updated, so I delete these env variables and create a new one with my new custom server URL

SERVICE_FQDN_CHECKMATE=checkmateserver.abc.com

SERVICE_FQDN_CHECKMATESERVER=checkmateserver.abc.com

SERVICE_FQDN_CHECKMATESERVER_5000=checkmateserver.abc.com


<img width="768" alt="Image" src="https://github.com/user-attachments/assets/903b8287-172c-4d6e-9abe-3d13baaf4d6a" />

**Comment by vishnusn77** [comment]
Hi @dropalltables @ahsan-abrar, can you please share your docker compose files

**Comment by jonas-klesen** [comment]
> Hi [@dropalltables](https://github.com/dropalltables) [@ahsan-abrar](https://github.com/ahsan-abrar), can you please share your docker compose files

Mine looks like this, works for me:
```

services:
  client:
    image: 'bluewaveuptime/uptime_client:latest'
    environment:
      - 'SERVICE_FQDN_CHECKMATE_80=checkmate.your-server.com'
      - 'UPTIME_APP_API_BASE_URL=https://checkmate.your-server.com/api/v1'
    depends_on:
      - server
  server:
    image: 'bluewaveuptime/uptime_server:latest'
    environment:
      - 'SERVICE_FQDN_CHECKMATESERVER_5000=checkmate.your-server.com'
```

**Comment by dropalltables** [comment]
Hi, here is my docker compose:
```
services:
  client:
    image: 'bluewaveuptime/uptime_client:latest'
    environment:
      - SERVICE_FQDN_CHECKMATE_80
      - 'UPTIME_APP_API_BASE_URL=${SERVICE_FQDN_CHECKMATESERVER_5000}/api/v1'
    depends_on:
      - server
  server:
    image: 'bluewaveuptime/uptime_server:latest'
    environment:
      - SERVICE_FQDN_CHECKMATESERVER_5000
      - 'JWT_SECRET=${SERVICE_PASSWORD_64_JWT}'
      - 'REFRESH_TOKEN_SECRET=${SERVICE_PASSWORD_64_REFRESH}'
      - 'SYSTEM_EMAIL_ADDRESS=${SYSTEM_EMAIL_ADDRESS:-test@example.com}'
      - 'SYSTEM_EMAIL_PASSWORD=${SERVICE_PASSWORD_64_EMAIL}'
      - 'SYSTEM_EMAIL_HOST=${SYSTEM_EMAIL_HOST}'
      - 'SYSTEM_EMAIL_PORT=${SYSTEM_EMAIL_PORT}'
      - 'PAGESPEED_API_KEY=${PAGESPEED_API_KEY}'
      - 'DB_CONNECTION_STRING=${DB_CONNECTION_STRING:-mongodb://mongodb:27017/uptime_db}'
      - 'REDIS_HOST=${REDIS_HOST:-redis}'
      - 'REDIS_PORT=${REDIS_PORT:-6379}'
      - 'DB_TYPE=${DB_TYPE:-MongoDB}'
      - 'TOKEN_TTL=${TOKEN_TTL:-99d}'
      - 'REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL:-99d}'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - redis
      - mongodb
  redis:
    image: 'bluewaveuptime/uptime_redis:latest'
    volumes:
      - 'redis:/data'
  mongodb:
    image: 'bluewaveuptime/uptime_database_mongo:latest'
    volumes:
      - 'mongodb:/data/db'
    command:
      - mongod
      - '--quiet'
```

My custom URLs are https://checkmate.viruus.zip:80 and https://checkmate.viruus.zip:5000. I've tried every combination of with/without the :80 and with/without https/http. Sometimes it says no available server and sometimes it says cannot get /.

**Comment by jonas-klesen** [comment]
It took me forever to figure this out..


For me, my docker-compose looks like this (excerpt, the rest is unchanged):

```
services:
  client:
    image: 'bluewaveuptime/uptime_client:latest'
    environment:
      - 'SERVICE_FQDN_CHECKMATE_80=${SERVICE_FQDN_CHECKMATE}'
      - 'UPTIME_APP_API_BASE_URL=${SERVICE_FQDN_CHECKMATESERVER_5000}/api/v1'
    depends_on:
      - server
  server:
    image: 'bluewaveuptime/uptime_server:latest'
    environment:
      - 'SERVICE_FQDN_CHECKMATESERVER_5000=${SERVICE_FQDN_CHECKMATESERVER}'
```

Then, give the client and server services these domain entries, respectively: https://checkmate.your-server.com:80 and https://checkmateserver.your-server.com (notice they are different).

Now, stop the deployment if running, delete the environment variables with the generated wrong sslip domains. Then add them back, with these entries: 

```
SERVICE_FQDN_CHECKMATE=checkmate.your-server.com
SERVICE_FQDN_CHECKMATESERVER=https://checkmateserver.your-server.com
SERVICE_FQDN_CHECKMATESERVER_5000=https://checkmateserver.your-server.com
```

That's it!

**Comment by gorkem-bwl** [comment]
New version should work, however it doesn't come with Coolify. I'll create an issue for this.

**Comment by lacymorrow** [comment]
I changed my server URL to match the server generated in the cors error, that fixed it.
`https://checkmateserver-5000-ps4cc4gsww4kw04gsssg8oww.domain.com`

**Comment by RamekhCHHOENG** [comment]
I am new here. I dont have much experience on this. I try to make this work by removing service5000. the issue is that client point to wrong backend API URL when I config cloudflare wildcard. when debug it show FE access https:://htt//mydomian. So i delete backend url  that it point to when first create project(not deploy).  remove API BASE and keep only '/api/v1'. 

```
services:
  client:
    image: 'bluewaveuptime/uptime_client:latest'
    environment:
      - SERVICE_URL_CHECKMATE_80
      - 'UPTIME_APP_API_BASE_URL=/api/v1'
    depends_on:
      - server
  server:
```
