### ISSUE TITLE
[Bug]: calcom does not work and keeps restarting

### ISSUE THREAD

**Issue by shsunmoonlee** [coollabsio/coolify#4591]
### Error Message and Logs

I simply installed on coolify. 
calcom instance keeps restarting (unhealthy) without any logs

### Steps to Reproduce

1. search calcom on self-hosted coolify(ubuntu) and install 
2. 
3.
4.

### Coolify Version

v4.0.0-beta.379

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by peaklabs-dev** [comment]
This problem you are seeing is because there is no ARM64 image available for Calcom. I am working on a very cool feature that will allow AMD64 images to run on ARM64 almost natively.

**Comment by SeriousM** [comment]
Hi! @peaklabs-dev is there any update on this? It was removed from the milestone...
Cyberchef image has the same issue..

**Comment by Cinzya** [comment]
There is already an issue https://github.com/calcom/docker/issues/358 on the Calcom GitHub about the same problem, asking the Calcom developers to support Arm64 by default. So I would recommend anyone that needs this feature to comment there as well. That would be the best case scenario if the developers of calcom already provide that support and Coolify doesn't have to come up with a workaround.

**Comment by 0xPatryk** [comment]
They have released a new image with an 'arm' tag at the end. 

v5.6.19-test-arm.

https://hub.docker.com/layers/calcom/cal.com/v5.6.19-test-arm/images/sha256-e492e846a1d94bbdb96a71255d6eb4f5b12f9681138476677e393d0952614cef

Does someone know how to implement this?

**Comment by Cinzya** [comment]
@0xPatryk you simply edit the compose file in Coolify and replace the image tag with the new arm one that you need.

**Comment by 0xPatryk** [comment]
@Cinzya  Thank you, I set this up straight away. However, I meant how we can automatically detect the platform in the settings and automatically select the new images for all other users!

@SeriousM @andrasbacsai 

Here is the Docker Compose :
```
# documentation: https://cal.com/docs/developing/introduction
# slogan: Scheduling infrastructure for everyone.
# category: productivity
# tags: calcom,calendso,scheduling,open,source
# logo: svgs/calcom.svg
# port: 3000

services:
  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com:main-arm
    environment:
      # Some variables still uses Calcom previous name, Calendso
      #
      # Full list https://github.com/calcom/cal.com/blob/main/.env.example
      - SERVICE_URL_CALCOM_3000
      - NEXT_PUBLIC_LICENSE_CONSENT=agree
      - NODE_ENV=production
      - NEXT_PUBLIC_WEBAPP_URL=${SERVICE_URL_CALCOM}
      - NEXT_PUBLIC_API_V2_URL=${SERVICE_URL_CALCOM}/api/v2
      # https://next-auth.js.org/configuration/options#nextauth_url
      # From https://github.com/calcom/docker?tab=readme-ov-file#important-run-time-variables, it should be ${NEXT_PUBLIC_WEBAPP_URL}/api/auth
      - NEXTAUTH_URL=${SERVICE_URL_CALCOM}/api/auth
      # It is highly recommended that the NEXTAUTH_SECRET must be overridden and very unique
      # Use `openssl rand -base64 32` to generate a key
      - NEXTAUTH_SECRET=${SERVICE_BASE64_CALCOMSECRET}
      # Encryption key that will be used to encrypt CalDAV credentials, choose a random string, for example with `dd if=/dev/urandom bs=1K count=1 | md5sum`
      - CALENDSO_ENCRYPTION_KEY=${SERVICE_BASE64_CALCOMKEY}
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_DB=${POSTGRES_DB:-calendso}
      - DATABASE_HOST=postgresql
      - DATABASE_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@${DATABASE_HOST:-postgresql}/${POSTGRES_DB:-calendso}
      # Needed to run migrations while using a connection pooler like PgBouncer
      # Use the same one as DATABASE_URL if you are not using a connection pooler
      - DATABASE_DIRECT_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@${DATABASE_HOST:-postgresql}/${POSTGRES_DB:-calendso}
      # GOOGLE_API_CREDENTIALS={}
      # Set this to 1 if you don't want Cal to collect anonymous usage
      - CALCOM_TELEMETRY_DISABLED=1
      # E-mail settings
      # Configures the global From: header whilst sending emails.
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      # Configure SMTP settings (@see https://nodemailer.com/smtp/).
      - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
      - NEXT_PUBLIC_APP_NAME="Cal.com"
      # More info on ALLOWED_HOSTNAMES https://github.com/calcom/cal.com/issues/12201
      - ALLOWED_HOSTNAMES=["${SERVICE_URL_CALCOM}"]
    depends_on:
      - postgresql
  postgresql:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_DB=${POSTGRES_DB:-calendso}
    volumes:
      - calcom-postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 10

```
