### ISSUE TITLE
[Bug]: Can't find Docker Compose application via GET API call

### ISSUE THREAD

**Issue by MichaelMichaelMichaelMichaelMichael** [coollabsio/coolify#4616]
### Error Message and Logs

```
/servers
[{"uuid":"h04c44sccs0ggsowc08c44gg","description":"This is the server where Coolify is running on. Don't delete this!","name":"localhost","ip":"host.docker.internal","is_reachable":true,"is_usable":true,"port":22,"proxy":{"redirect_enabled":true},"settings":{"id":1,"concurrent_builds":2,"delete_unused_networks":false,"delete_unused_volumes":false,"docker_cleanup_frequency":"0 0 * * *","docker_cleanup_threshold":80,"dynamic_timeout":3600,"force_disabled":false,"force_docker_cleanup":true,"generate_exact_labels":false,"is_build_server":false,"is_cloudflare_tunnel":false,"is_jump_server":false,"is_logdrain_axiom_enabled":false,"is_logdrain_custom_enabled":false,"is_logdrain_highlight_enabled":false,"is_logdrain_newrelic_enabled":false,"is_metrics_enabled":false,"is_reachable":true,"is_sentinel_debug_enabled":false,"is_sentinel_enabled":false,"is_swarm_manager":false,"is_swarm_worker":false,"is_usable":true,"logdrain_axiom_api_key":null,"logdrain_axiom_dataset_name":null,"logdrain_custom_config":null,"logdrain_custom_config_parser":null,"logdrain_highlight_project_id":null,"logdrain_newrelic_base_uri":null,"logdrain_newrelic_license_key":null,"sentinel_custom_url":"http:\/\/host.docker.internal:8000","sentinel_metrics_history_days":7,"sentinel_metrics_refresh_rate_seconds":10,"sentinel_push_interval_seconds":60,"sentinel_token":"eyJpdiI6Im53aXgwZy9JM3drRTZ1NHUwcC93SGc9PSIsInZhbHVlIjoiWDRPUGNMNU1SdTRlZ28vVTZCdk9ORk81NnNMZkZWS01BMUVYbytGN1F4RG1aTUk4NkxxcHZVMHE4K3dOS3JXMFNzT1RFZ3JyUHF4YkdWK2lTNS9UWUE9PSIsIm1hYyI6IjM0NzlkYjI1MTU5Yjk3YzdmMzYzNDc4NGViMjIxODJlNmU1M2FiNjQzMDFjZjQ4NmVkNWVmZDM1ZTFhNjU3YzEiLCJ0YWciOiIifQ==","server_disk_usage_notification_threshold":80,"server_id":0,"server_timezone":"UTC","wildcard_domain":null,"created_at":"2024-12-14T20:32:52.000000Z","updated_at":"2024-12-14T20:34:18.000000Z"},"user":"root"}]
HTTP Status Code: 200
/applications/dockercompose
{"message":"Application not found."}
HTTP Status Code: 404
/applications/dockercompose/wkws04wcg0sk0gsws4c4g4gc
{"message":"Not found.","docs":"https:\/\/coolify.io\/docs"}
HTTP Status Code: 404
/applications
[]
HTTP Status Code: 200
/applications/wkws04wcg0sk0gsws4c4g4gc
{"message":"Application not found."}
HTTP Status Code: 404
PATCH /applications/wkws04wcg0sk0gsws4c4g4gc
{"message":"Application not found"}
HTTP Status Code: 404
/projects
[{"id":1,"uuid":"m40wssgcs840kog4kco004s4","name":"infrastructure","default_environment":"production","description":""},{"id":2,"uuid":"l8wssgso84cw4k880kck4k4w","name":"tools","default_environment":"production","description":""},{"id":23,"uuid":"vc0sowggo8ww8k0gk8k4cg0k","name":"wordpress_project","default_environment":"production","description":null}]
HTTP Status Code: 200
/projects/vc0sowggo8ww8k0gk8k4cg0k/applications
{"message":"Environment not found."}
HTTP Status Code: 404

```

### Steps to Reproduce

```
#!/bin/bash

COOLIFYHOST=1.2.3.4
COOLIFYURL=http://${COOLIFYHOST}:8000/api/v1/

### permissions: root:
### APIKEY=3dA421uLm8mApNeWIgaFyPXygsUckOSsCjwECmH9490844db
### permissions: read write read-sensitive und deploy:
APIKEY=ezTKcCtYEikKCFz9KHAiyDOfhDPBY8wtZIMpHXSZ2e9bb58b
APPLICATION_UUID="wkws04wcg0sk0gsws4c4g4gc"
DOMAIN="https://service-wkws04wcg0sk0gsws4c4g4gc.1.2.3.4.sslip.io:8081"
PROJECT_UUID="vc0sowggo8ww8k0gk8k4cg0k"
SERVER_UUID=="h04c44sccs0ggsowc08c44gg"

echo /servers
curl -X GET "${COOLIFYURL}servers" \
  -H "Authorization: Bearer ${APIKEY}" \
  -w "\nHTTP Status Code: %{http_code}\n"

echo /applications/dockercompose
curl -X GET "${COOLIFYURL}applications/dockercompose" \
  -H "Authorization: Bearer ${APIKEY}" \
  -w "\nHTTP Status Code: %{http_code}\n"

echo /applications/dockercompose/${APPLICATION_UUID}
curl -X GET "${COOLIFYURL}applications/dockercompose/${APPLICATION_UUID}" \
  -H "Authorization: Bearer ${APIKEY}" \
  -w "\nHTTP Status Code: %{http_code}\n"

# list coolify applications
echo /applications
curl -X GET \
  "${COOLIFYURL}applications" \
  -H "Authorization: Bearer ${APIKEY}" \
  -w "\nHTTP Status Code: %{http_code}\n"

# list  application with UUID
echo /applications/${APPLICATION_UUID}
curl -X GET \
  "${COOLIFYURL}applications/${APPLICATION_UUID}" \
  -H "Authorization: Bearer ${APIKEY}" \
  -w "\nHTTP Status Code: %{http_code}\n"

# PATCH-Anfrage an die Coolify API senden
echo PATCH /applications/${APPLICATION_UUID}
curl -X PATCH \
  "${COOLIFYURL}applications/${APPLICATION_UUID}" \
  -H "Authorization: Bearer ${APIKEY}" \
  -H "Content-Type: application/json" \
  -d "{\"domains\":[\"${DOMAIN}\"]}" \
  -w "\nHTTP Status Code: %{http_code}\n"

echo /projects
curl -X GET \
  "${COOLIFYURL}projects" \
  -H "Authorization: Bearer ${APIKEY}" \
  -w "\nHTTP Status Code: %{http_code}\n"

echo /projects/${PROJECT_UUID}/applications
curl -X GET \
  "${COOLIFYURL}projects/${PROJECT_UUID}/applications" \
  -H "Authorization: Bearer ${APIKEY}" \
  -w "\nHTTP Status Code: %{http_code}\n"

```

### Coolify Version

v4.0.0-beta.379

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1

### Additional Information

Hi, I'm trying to patch a docker compose deployment with the domains field, but while trying that, I'm having trouble finding that application. 
From creating the docker compose deployment, I definitely get a uuid. I've put all known UUID values at the beginning of the script but I have not success.

The docker compose file which I've used in this application is: 
```
version: '3'
services:
  wordpress:
    image: 'wordpress:latest'
    ports:
      - '8081:80'
    environment:
      WORDPRESS_DB_HOST: mysql_service
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: mydbpassword
      WORDPRESS_DB_NAME: wordpress_db
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost'
      interval: 30s
      timeout: 10s
      retries: 3
  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: mydbpassword-for-root
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: mydbpassword
      MYSQL_DATABASE: wordpress_db
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
        - '-u'
        - wordpress_user
        - '-pmydbpassword'
      interval: 30s
      timeout: 10s
      retries: 5
  wpcli:
    image: 'wordpress:cli'
    volumes:
      - '/var/lib/docker/volumes/vc0sowggo8ww8k0gk8k4cg0k/_data:/var/www/html'
    entrypoint:
      - /bin/sh
      - '-c'
      - 'while :; do sleep 2073600; done'

```
Any help would be appreciated.
