### ISSUE TITLE
[Bug]: one of containers in docker-compose isn't available via domain

### ISSUE THREAD

**Issue by mirus-ua** [coollabsio/coolify#4650]
### Error Message and Logs

No visible errors

### Steps to Reproduce

Hard to tell

### Coolify Version

v4.0.0-beta.379

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12 (bookworm)

### Additional Information

Hello
I have a tiny pet project dockerized via docker-compose

here is the docker-compose.yml
```yaml
version: "3"
services:
  api:
    build:
      context: ./api
    ports:
      - "8090:8090"
    volumes:
      - pb-data:/pb/pb_data
      - ./api/pb_data:/pb/pb_data
    environment:
      - SERVICE_FQDN_API_8090

  client:
    working_dir: /app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - api
    environment:
      - VITE_SERVER_API_URL
      - SERVICE_FQDN_CLIENT_3001
      - NODE_ENV=production
```

This is the second resource in my project with the same stack; the only difference is the ports. The OG resource works fine, but this one has a problem with the client container; it shows 502 via domain but is accessible via a direct ip+port combination. 

What I've trie already. 
- recreate a resource from scratch 
- change `3001` port to any random one
- rename client image and `SERVICE_FQDN_` variable
- try to use node, bun, and nginx for the static server 
- add another subdomain both for API and the client, for API both work find and non of them for the client

I'll be glad to provide some debug information
