### ISSUE TITLE
[Bug]: LanceDB: Invalid ENV Settings - AnythingLLM (Includes fix)

### ISSUE THREAD

**Issue by SeveighTech-Management** [coollabsio/coolify#4658]
### Error Message and Logs

After deploying AnythingLLM, I get `LanceDB: Invalid ENV Settings`
```
2024-12-24T06:24:33.811199238Z [backend] error: Error: LanceDB::Invalid ENV settings
2024-12-24T06:24:33.811356023Z     at Object.connect (/app/server/utils/vectorDbProviders/lance/index.js:23:13)
2024-12-24T06:24:33.811364842Z     at Object.hasNamespace (/app/server/utils/vectorDbProviders/lance/index.js:147:35)
2024-12-24T06:24:33.811371772Z     at streamChatWithWorkspace (/app/server/utils/chats/stream.js:59:45)
2024-12-24T06:24:33.811394282Z     at async /app/server/endpoints/chat.js:62:9
```

The issue was the docker-compose.yml
After checking the docs, a line was missing:
` - VECTOR_DB=lancedb`

The complete working fix:
```
services:
  anything-llm:
    image: mintplexlabs/anythingllm
    environment:
      - SERVICE_FQDN_ANYTHINGLLM_3001
      - STORAGE_DIR=/app/server/storage
      - 'DISABLE_TELEMETRY=${DISABLE_TELEMETRY:-true}'
      - 'PASSWORDLOWERCASE=${PASSWORDLOWERCASE:-1}'
      - 'PASSWORDMAXCHAR=${PASSWORDMAXCHAR:-250}'
      - 'PASSWORDMINCHAR=${PASSWORDMINCHAR:-6}'
      - 'PASSWORDNUMERIC=${PASSWORDNUMERIC:-1}'
      - 'PASSWORDREQUIREMENTS=${PASSWORDREQUIREMENTS:-1}'
      - 'PASSWORDSYMBOL=${PASSWORDSYMBOL:-1}'
      - 'PASSWORDUPPERCASE=${PASSWORDUPPERCASE:-1}'
      - 'SIG_KEY=${SERVICE_PASSWORD_SIGKEY}'
      - 'SIG_SALT=${SERVICE_PASSWORD_SIGSALT}'
      - 'JWT_SECRET=${SERVICE_PASSWORD_JWTSECRET}'
      - 'AUTH_TOKEN=${SERVICE_PASSWORD_AUTHTOKEN}'
      - 'SERVER_PORT=${SERVER_PORT:-3001}'
      - VECTOR_DB=lancedb
    cap_add:
      - SYS_ADMIN
    volumes:
      - 'anythingllm-storage:/app/server/storage'
      - 'anythingllm-hot:/app/collector/hotdir'
      - 'anythingllm-outputs:/app/collector/outputs'
    user: '${UID:-1000}:${GID:-1000}'
```

### Steps to Reproduce

1. Create new project
2. Select AnythingLLM resource
3. Deploy
4. Visit deployment URL
5. Set up API Key and LLM
6. Start a chat

### Coolify Version

v4.0.0-beta.379

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04
