### ISSUE TITLE
[Bug]: COOLIFY_FQDN/COOLIFY_URL is switched preview deployments

### ISSUE THREAD

**Issue by endquote** [coollabsio/coolify#4719]
### Error Message and Logs

main container:
```
/ # echo $COOLIFY_FQDN
endquote.com,www.endquote.com
/ # echo $COOLIFY_URL
https://endquote.com,https://www.endquote.com
```
preview deployment:
```
/ # echo $COOLIFY_FQDN
https://2.dev.endquote.com
/ # echo $COOLIFY_URL
2.dev.endquote.com
```

### Steps to Reproduce

This project is using the `Dockerfile` configuration.

### Coolify Version

v4.0.0-beta.380

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

**Comment by HarleySalas** [comment]
Any updates on this? It's pretty annoying... Even just using a docker-compose file, I need access to the FQDN and it keeps giving me the FQDN, but with `https://` infront of it.... Is there any workaround or way to get the FQDN in docker compose?

**Comment by peaklabs-dev** [comment]
@HarleySalas yes use URL it is switched up

**Comment by HarleySalas** [comment]
> [@HarleySalas](https://github.com/HarleySalas) yes use URL it is switched up

Thanks for the quick reply @peaklabs-dev .

I've tried giving it a go, to modify the mailpit service, as we want to force https in order to test emails in staging with real data relatively securely.

Heres how I've modified the service:
```
services:
  mailpit:
    image: axllent/mailpit
    ports:
      - '1025:1025'
    volumes:
      - 'mailpit-data:/data'
      - './certs:/etc/mailpit/certs:ro'
      -
        type: bind
        source: ./htpasswd
        target: /data/htpasswd
        isDirectory: false
        content: ''
      -
        type: bind
        source: ./smtp.auth
        target: /data/smtp.auth
        isDirectory: false
        content: ''
    environment:
      - SERVICE_FQDN_MAILPIT_8025
      - MP_MAX_MESSAGES=${MP_MAX_MESSAGES:-5000}
      - MP_DATABASE=/data/mailpit.db
      - MP_SMTP_AUTH=${MP_SMTP_AUTH:-true}
      - MP_SMTP_AUTH_ACCEPT_ANY=${MP_SMTP_AUTH_ACCEPT_ANY:-false}
      - MP_SMTP_AUTH_ALLOW_INSECURE=${MP_SMTP_AUTH_ALLOW_INSECURE:-false}
      - MP_SMTP_REQUIRE_STARTTLS=${MP_SMTP_REQUIRE_STARTTLS:-true}
      - MP_UI_AUTH_FILE=/data/htpasswd
      - MP_SMTP_AUTH_FILE=/data/smtp.auth
      - MP_SMTP_TLS=${MP_SMTP_TLS:-true}
      - MP_SMTP_TLS_CERT=/etc/mailpit/certs/fullchain.pem
      - MP_SMTP_TLS_KEY=/etc/mailpit/certs/privkey.pem
      - CERTBOT_ADMIN_EMAIL=${CERTBOT_ADMIN_EMAIL:-example@example.com}
    depends_on:
      certbot:
        condition: service_completed_successfully
    healthcheck:
      test:
        - CMD
        - /mailpit
        - readyz
      interval: 5s
      timeout: 20s
      retries: 10

  certbot:
    image: certbot/certbot:latest
    volumes:
      - './certs:/etc/letsencrypt/live/mailpit'
      - './certbot-data:/etc/letsencrypt'
      - './certbot-webroot:/webroot'
    command: >
      certonly
      --webroot
      --webroot-path=/webroot
      --email ${CERTBOT_ADMIN_EMAIL}
      --agree-tos
      --no-eff-email
      --force-renewal
      -d ${SERVICE_URL_MAILPIT}
    entrypoint: >
      /bin/sh -c '
      trap exit TERM;
      while :; do
        certbot renew --webroot --webroot-path=/webroot;
        sleep 12h & wait $$!;
      done;'
```
Taking note of the certbot service's `-d ${SERVICE_URL_MAILPIT}`

I've tried `SERVICE_URL_MAILPIT_8025`, `SERVICE_URL_MAILPIT`, `COOLIFY_URL` and all of them are empty/do not exist when i run it. Am I just not understanding something here, or should this work?
