### ISSUE TITLE
[Bug]: Unable to add domains to certain docker compose services

### ISSUE THREAD

**Issue by Soulusions** [coollabsio/coolify#4730]
### Error Message and Logs

UI shows success, no errors in logs.

### Steps to Reproduce

I have a docker compose file with several services, some services I can add domains to and visit with no issues, while other services will seemingly add the domain successfully, but refreshing the page causes it to disappear, and even without doing that, deploying doesn't actually inject the config into the docker compose file.

### Coolify Version

v4.0.0-beta.380

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12 (bookworm)

### Additional Information

Here is a slightly cut-down version of the docker compose file, with a service that works as expected and one that fails.

```yml
version: "3.1"

services:
  app: # This service can't use domains.
    image: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "4200:8080"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_SERVICE_NAME: "app"
        
  seq: # This service is able to use domains fine!
    image: datalust/seq:2024.3
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - seq:/data
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: ${SEQ_FIRSTRUN_PASSWORDHASH}

volumes:
  seq:
``` 

I'm not using any custom advanced settings or anything on this application, I have just about everything bone-stock, which is why I'm surprised it's failing like this.

Only thing i see being the problem maybe is that the services causing issues seem to be the ones with a build step, but that's all I've got.
