### ISSUE TITLE
[Bug]: Database Error When Setting FQDN Env Variable in docker-compose

### ISSUE THREAD

**Issue by mxhffmn** [coollabsio/coolify#4805]
### Error Message and Logs

I encountered a database error when trying to deploy an application with multiple services via docker-compose. Let me first explain, how I got to this issue: I want to deploy an application with multiple different services. There is a container hosting a web frontend, a container hosting a backend service, multiple different database, and so on. Almost all of these services have some kind of UI to manage them. For example, I am using the database [Influx](https://docs.influxdata.com/influxdb/v2/visualize-data/) for time series data and want to be able to access the provided UI from a public domain. So I created a new docker-compose resource and pasted the docker-compose file with the services. I noticed that I was only able to set a custom domain for some services. The problem seems to be that Coolify detects some services (including Influx) as databases and some as applications. I could only define a custom domain for the applications. This does not make sense to me.

While trying to work around this problem, I set the FQDN env variable in the docker-compose to get any domain. This produced the following error message:

```
SQLSTATE[42703] Undefined column 7 ERROR  column fqdn of relation service_databases does not exist
LINE 1 update service_databases set fqdn = $1, updated_at = $...
                                       ^ (Connection pgsql, SQL update service_databases set fqdn = httpsinfl-kc40wc4c0wgswcgo4wc04swc.aimpera.de, updated_at = 2025-01-12 095134 where id = 13)
```

### Steps to Reproduce

1. Create a new docker-compose resource
2. Paste the following example:

```
services:
  edgedb:
    image: 'edgedb/edgedb:5'
    restart: on-failure
    environment:
      - SERVICE_FQDN_EDGEDB
      - EDGEDB_SERVER_ADMIN_UI=enabled
      - EDGEDB_SERVER_INSTANCE_NAME=main-instance
      - EDGEDB_SERVER_USER=testuser
      - EDGEDB_SERVER_PASSWORD=testuser-password
      - EDGEDB_SERVER_TLS_CERT_MODE=generate_self_signed
      - EDGEDB_SERVER_HTTP_ENDPOINT_SECURITY=optional
  influxdb:
    image: 'influxdb:2'
    restart: on-failure
    environment:
      - SERVICE_FQDN_INFLUXDB
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=testuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=testuser-password
      - DOCKER_INFLUXDB_INIT_ORG=testorg
      - DOCKER_INFLUXDB_INIT_BUCKET=main-bucket
```

3. The database error is thrown but the resource is still created.
4. Notice how the EdgeDB service (which is also a database) has a generated domain but Influx has not. This counterintuitive in my opinion.

### Coolify Version

v4.0.0-beta.380

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

### Additional Information

Apart from fixing this bug, it might be good to know if there is any way to make a service accessible via domain, even if it is recognized internally as a database.

**Comment by sandros94** [comment]
Facing the same issue. It seems like Coolify notice it is one of the supported databases and tries to add it to the `service_databases` table where `SERVICE_FQDN_*` isn't supported.

I was trying to implement a custom postgres deployment with SSL support:

```yaml
# documentation: https://www.postgresql.org/
# slogan: PostgreSQL: The World's Most Advanced Open Source Relational Database.
# tags: postgres,database
# logo: svgs/postgres.svg
# port: 5432

services:
  postgres:
    image: postgres:16-alpine
    container_name: ${COOLIFY_UUID}
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_POSTGRES_5432
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS:---data-checksums}
      - POSTGRES_SSL=on
    command: >
      postgres
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key

    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
      - type: bind
        source: /data/coolify/proxy/caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${COOLIFY_URL}/${COOLIFY_URL}.crt
        target: /var/lib/postgresql/server.crt
        read_only: true
      - type: bind
        source: /data/coolify/proxy/caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${COOLIFY_URL}/${COOLIFY_URL}.key
        target: /var/lib/postgresql/server.key
        read_only: true

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    name: postgres-data-${COOLIFY_UUID}
    external: false
```

**Comment by m1dnight** [comment]
Same issue with CouchDB. Docker compose: 

```yaml
services:
  couchdb:
    image: couchdb:3.3.3
    environment:
      - SERVICE_FQDN_COUCHDB_1234
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
```

**Comment by pharesdiego** [comment]
I tried to provision an influxdb instance and got the same error. I fixed it by going to the service's settings and clicking the `Convert to Application` button. After that I was able to deploy the service normally


1. 
<img width="1147" height="511" alt="Image" src="https://github.com/user-attachments/assets/cb70206f-6bbe-4522-824d-0682124353f7" />

2. 
<img width="1147" height="511" alt="Image" src="https://github.com/user-attachments/assets/30ea7d9d-3d8b-4c63-94f1-acdf28d2e2a5" />

3. 
<img width="1104" height="544" alt="Image" src="https://github.com/user-attachments/assets/4025a080-8fdd-47e3-8d3c-a80c060ec926" />

---


This my docker-compose:

```yml
version: '3.8'
services:
  influxdb:
    image: 'influxdb:2.7.12'
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - './data:/var/lib/influxdb2'
      - './config:/etc/influxdb2'
    environment:
      - SERVICE_FQDN_INFLUXDB_8086
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=$SERVICE_USER_INFLUXDB
      - DOCKER_INFLUXDB_INIT_PASSWORD=$SERVICE_PASSWORD_INFLUXDB
      - DOCKER_INFLUXDB_INIT_ORG=Bio
      - DOCKER_INFLUXDB_INIT_BUCKET=BioBucket
    restart: unless-stopped
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
```
