### ISSUE TITLE
[Bug]: Incorrect health status is displayed on the UI after v4.0.0-beta.383

### ISSUE THREAD

**Issue by QarthO** [coollabsio/coolify#4927]
### Error Message and Logs

After restarting a container on the new update, the health status being shown on the ui is invalid. I'll start a container, they'll start and will be stuck on unhealthy or running. However the services will be fullly functioning. I've gone into the services terminal and ran ``docker ps`` and all the containers will show healthy. 

The issue is the UI is not properly updating. Restarting instances, refreshing page, clearing cache/cookies, none of which solves the issue.
I've only tested with custom docker compose builds.

[Discord Thread](https://discord.com/channels/459365938081431553/1331328030320103486)

### Steps to Reproduce

1. Start an service
2. See health status doesn't change, or gets stuck on running/stating

### Coolify Version

v4.0.0-beta.383

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

24.04.1 LTS

**Comment by peaklabs-dev** [comment]
Can you provide us with a sample compose file so that we can better reproduce this.

**Comment by QarthO** [comment]
Just created a brand new resource using the 1-click install joomla template. Made zero changes to the compose file.

```
services:
  joomla:
    image: 'joomla:latest'
    volumes:
      - 'joomla_data:/var/www/html'
    environment:
      - SERVICE_FQDN_JOOMLA
      - JOOMLA_DB_HOST=mariadb
      - 'JOOMLA_DB_USER=${SERVICE_USER_JOOMLA}'
      - 'JOOMLA_DB_PASSWORD=${SERVICE_PASSWORD_JOOMLA}'
      - 'JOOMLA_DB_NAME=${MYSQL_DATABASE:-joomla-db}'
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10
  mariadb:
    image: 'mariadb:11'
    volumes:
      - 'joomla_mariadb_data:/var/lib/mysql'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_ROOT}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE:-joomla-db}'
      - 'MYSQL_USER=${SERVICE_USER_JOOMLA}'
      - 'MYSQL_PASSWORD=${SERVICE_PASSWORD_JOOMLA}'
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 5s
      timeout: 20s
      retries: 10

```


<img width="1163" alt="Image" src="https://github.com/user-attachments/assets/25ebfdc8-ce04-4905-bc35-7db34095512d" />
UI shows the joomla service is "running (starting)"

running ``docker ps`` on the server with both showing ``Up About a minute (healthy)``
```
CONTAINER ID   IMAGE                                       COMMAND                  CREATED              STATUS                        PORTS                                                                                                                                                        NAMES
ffded273f59d   joomla:latest                               "/entrypoint.sh apac…"   About a minute ago   Up About a minute (healthy)   80/tcp                                                                                                                                                       joomla-tco00owoos4ow80www4cw40c
e80d9d3d4172   mariadb:11                                  "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   3306/tcp                                                                                                                                                     mariadb-tco00owoos4ow80www4cw40c
```
