### ISSUE TITLE
[Bug]: Git based docker compose - property args not allowed for build

### ISSUE THREAD

**Issue by DiiiaZoTe** [coollabsio/coolify#4940]
### Error Message and Logs

Tested for a git based docker compose.
When adding args in the docker-compose, and the respective ARG in the Dockerfile, I am getting an error when deploying:
`services.xyz Additional property args is not allowed`

docker-compose snippet:
```yml
services:
  xyz:
    build: .
    args:
        - "VARIABLE_ONE=${VARIABLE_ONE}"
        - "VARIABLE_TWO=${VARIABLE_TWO}"
    container_name: xyz-app
    environment:
      - VARIABLE_ONE: ${VARIABLE_ONE}
      - VARIABLE_TWO: ${VARIABLE_TWO}
```
in my Dockerfile:
```dockerfile
ARG VARIABLE_ONE
ARG VARIABLE_TWO
```

---------
If I remove args from docker-compose file, then during my build the ARG variables are empty.
Obviously, the expected behavior is that the ARG variables would be populated with the values passed...

### Steps to Reproduce

1. create a Dockerfile and docker-compose
2. in docker-compose: add build and args
3. deploy

### Coolify Version

v4.0.0-beta.389

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12

**Comment by DiiiaZoTe** [comment]
My bad... the args has to be under the build
```yml
services:
  xyz:
    build: 
      context: .
      args:
        - "VARIABLE_ONE=${VARIABLE_ONE}"
        - "VARIABLE_TWO=${VARIABLE_TWO}"
    container_name: xyz-app
    environment:
      - VARIABLE_ONE: ${VARIABLE_ONE}
      - VARIABLE_TWO: ${VARIABLE_TWO}
```
