### ISSUE TITLE
[Bug]: Wrong status tracked by coolify in case of multiple containers in a single application/project

### ISSUE THREAD

**Issue by Vanarian** [coollabsio/coolify#4976]
### Error Message and Logs

This issue exists from release .388 and .389 (and did not in older releases of Coolify such as .335).

When deploying an application/project with multiple containers launched in sequences, i.e. have a primary container loadup credentials then exit and have a secondary container use the credentials for the main app, normal behavior was that Coolify showed the status of surviving container. 

The current issue : Coolify only tracks the "primary" container status, means if it exits after its task is done, status is stuck on "exited".

Why this is a problem : secondary container keeps running even if log shows defect or errors. That means there are no means to stop the defective container with Coolify (you can't click "stop" if there's nothing "running" from Coolify's perspective).

In case of issue you have then to fall back to CLI docker from your machine.

Older release of Coolify did't' have this issue and was always tracking the surviving "live" container.

### Steps to Reproduce

1. Write a project with two containers sequences ; first container must exit after succesful execution, second container must remain
2. Deploy with docker-compose 
3. Check status and "Log", Log should still be running for "live" container while first is exited.
4. Status should show "Exited" instead of "Running".

### Coolify Version

v4.0.0-beta.389

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Oracle Linux Server 9.4

**Comment by IZIme07** [comment]
the same problem v4.0.0-beta.390

**Comment by TanerKp** [comment]
same for me: [v4.0.0-beta.394](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.394

**Comment by ptrmtb** [comment]
Can confirm this issue still persists in Coolify v4.0.0-beta.395. I'm not sure what's causing this. Thankfully, even though it's showed 'Stopped', the rest of the containers is still active and can be viewed in Logs and by the FQDN

**Comment by IZIme07** [comment]
> Same for me: v4.0.0-beta.394
> 
> I have this problem after upgrading Coolify from (I think) v4.0.0-beta.37X



> Can confirm this issue still persists in Coolify v4.0.0-beta.395. I'm not sure what's causing this. Thankfully, even though it's showed 'Stopped', the rest of the containers is still active and can be viewed in Logs and by the FQDN



> ### Error Message and Logs
> This issue exists from release .388 and .389 (and did not in older releases of Coolify such as .335).
> 
> When deploying an application/project with multiple containers launched in sequences, i.e. have a primary container loadup credentials then exit and have a secondary container use the credentials for the main app, normal behavior was that Coolify showed the status of surviving container.
> 
> The current issue : Coolify only tracks the "primary" container status, means if it exits after its task is done, status is stuck on "exited".
> 
> Why this is a problem : secondary container keeps running even if log shows defect or errors. That means there are no means to stop the defective container with Coolify (you can't click "stop" if there's nothing "running" from Coolify's perspective).
> 
> In case of issue you have then to fall back to CLI docker from your machine.
> 
> Older release of Coolify did't' have this issue and was always tracking the surviving "live" container.
> 
> ### Steps to Reproduce
> 1. Write a project with two containers sequences ; first container must exit after succesful execution, second container must remain
> 2. Deploy with docker-compose
> 3. Check status and "Log", Log should still be running for "live" container while first is exited.
> 4. Status should show "Exited" instead of "Running".
> 
> ### Example Repository URL
> _No response_
> 
> ### Coolify Version
> v4.0.0-beta.389
> 
> ### Are you using Coolify Cloud?
> No (self-hosted)
> 
> ### Operating System and Version (self-hosted)
> Oracle Linux Server 9.4
> 
> ### Additional Information
> _No response_

**Solved
need go to Servers/configuration and click Revalidate server. Then restart the proxy**

**Comment by Cristy94** [comment]
Same problem with v4.O.O-beta.418

My [discourse installation via docker-compose](https://softuts.com/running-discourse-on-coolify/) doesn't run anymore because the Redis container shows as Exited, even though in the logs it ends with "Ready to accept connections".

After a few restarts, Redis correctly show as Running, but now Postgres is shown as exited (even though, again, it runs successfully and finishes with "Ready to accept connections").

EDIT: Not only that, but now it seems like the app is actually working/running, even though Postgres still shows as Exited.

**Comment by micheloliveira-com** [comment]
When I perform a force pull on v4.0.0-beta.418 (with Redis and two other services defined in Docker Compose), only Redis ends up in an exited or degraded state for me as well.

I’ve tried restarting the service and using both force deploy and regular deploy, but the status remains the same.

Interestingly, in my case, the application continues to work normally, even though Coolify shows Redis as “exited.” Redis appears to be running fine despite the status indication.

**Comment by NoahPerez** [comment]
wow, our checkout page it not working because of this !

**Comment by ton77v** [comment]
Coolify Cloud v4.0.0-beta.420.6

The issue exists, even though **one month ago the same setup was definitely** working without issues. However after I initiated re-deployment of the same project again, it shows "Exited" and the Logs aren't available from the UI, etc...

I created a public repo to reproduce the issue: https://github.com/ton77v/coolify_bug__exited

1. Create a new project for `main` branch and it be deployed just fine
2. But if you switch to the `add_service` branch that has a new "one time" service that's a dependency for "main one", the status breaks after successful deployment

You can check the statuses to ensure the containers are actually fine:
```
> docker ps --all | grep w4gcgcwksw8wosg8k4cw4gos

edab4d23d995   w4gcgcwksw8wosg8k4cw4gos-customer_portal               "start_service.sh"       About a minute ago   Up About a minute (healthy)       0/tcp                                                                                                                                       customer_portal-w4gcgcwksw8wosg8k4cw4gos-102158626050
e26cdb832e45   alpine:latest                                          "sh -c 'echo READY &…"   About a minute ago   Exited (0) About a minute ago                                                                                                                                                 initializer-w4gcgcwksw8wosg8k4cw4gos-102158622446
```

**Comment by ton77v** [comment]
> Coolify Cloud v4.0.0-beta.420.6
> 
> The issue exists, even though **one month ago the same setup was definitely** working without issues. However after I initiated re-deployment of the same project again, it shows "Exited" and the Logs aren't available from the UI, etc...
> 

Found a workaround. You need a service that's healthy before the first "one time" container exits, e.g. this setup works fine:
```
services:
  mailhog:
    container_name: mailhog__test_repo
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:999
      - MH_UI_BIND_ADDR=0.0.0.0:999
    healthcheck:
      interval: 30s
      retries: 3
      test: [ "CMD", "nc", "-z", "localhost", "1025" ]
      timeout: 5s
    hostname: mailhog
    image: anatomicjc/mailhog:latest
    ports:
      - "0:999"

  initializer:
    container_name: initializer
    image: alpine:latest
    # the trick is this dependency: if we exit when there's a service running, it won't be counted as "app exited"
    depends_on:
      mailhog:
        condition: service_healthy
        required: true
    # noinspection ComposeUnknownKeys
    exclude_from_hc: true  # Coolify-specific
    restart: no
    command: [ "sh", "-c", "echo READY && exit 0" ]

  customer_portal:
    # ...
    depends_on:
      initializer:
        condition: service_completed_successfully
        required: true
      postgres:
        condition: service_healthy
        required: true

  postgres:
    container_name: postgres
    depends_on:
      initializer:
        condition: service_completed_successfully
        required: true
    # ...
```
