### ISSUE TITLE
[Bug]: Adding a file or directory mount to a database, breaks defaul volume mount

### ISSUE THREAD

**Issue by benosman** [coollabsio/coolify#5034]
### Error Message and Logs

When adding file or directory mounts to a database service (tested with mariadb and mysql), the docker compose config is broken for the default volume mount (and additional ones).

This means that the db appears to lose data and is no longer persistent. Removing the mount restores the issue. It affects the config under `services.<id>.volumes`, not the root `volumes`.

Before adding mount:
```yaml
services:
    zgwg4g0kck4s8cskokos84ss:
        ...
        volumes:
            - 'app-name-db:/var/lib/mysql'
volumes:
    app-name-db:
        name: app-name-db
        external: false
```

After adding mount:
```yaml
services:
    zgwg4g0kck4s8cskokos84ss:
        ...
        volumes:
            - '/data/coolify/databases/zgwg4g0kck4s8cskokos84ss/root/.my.cnf:/root/.my.cnf'
volumes:
    app-name-db:
        name: app-name-db
        external: false
```

### Steps to Reproduce

1. Create a mariadb database
2. Start database
3. Check docker-compose.yaml and volume should be correct.
4. Add file mount and save
5. Restart database
6. Check docker-compose.yaml and volume is likely incorrect.
7. Remove file mount and save
8. Restart database
9. Check docker-compose.yaml and volume should be correct.

### Coolify Version

v4.0.0-beta.390 

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

AlmaLinux 9.5

### Additional Information

The file mounts previously didn't work and was fixed after #4668

That might be a good start to see where the cause of this issue is.
