### ISSUE TITLE
[Bug]: middleware "gzip@docker" does not exist

### ISSUE THREAD

**Issue by luantoningalvan** [coollabsio/coolify#5076]
### Error Message and Logs

I'm encountering an issue when configuring Coolify with Traefik as a reverse proxy using wildcard certificates (DNS Challenge via Cloudflare) and subdomain routing. The error message I receive is:

time="2025-02-06T05:08:07Z" level=info msg="Configuration loaded from flags."
time="2025-02-06T05:08:08Z" level=error msg="middleware \"gzip@docker\" does not exist" routerName=meuapp@docker entryPointName=https
Despite following the documentation and several suggested configurations, the middleware gzip does not seem to be available when referenced by my application.

Environment Details:

Coolify Version: v4.0.0-beta.390
Traefik Version: v2.10
DNS Provider: Cloudflare (records set as "DNS Only")
Operating System: Ubuntu

Proxy (Traefik) Configuration (docker-compose.yml):

version: '3.8'
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v2.10'
    restart: unless-stopped
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=#######
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.redirections.entryPoint.to=https'
      - '--entrypoints.http.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=10'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--providers.docker=true'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.tls.domains[0].main=luangalvan.dev
      - traefik.http.routers.traefik.tls.domains[0].sans=*.luangalvan.dev
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.middlewares.gzip.compress=true

Application Configuration:

traefik.enable=true
traefik.http.routers.meuapp.rule=HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.luangalvan.dev`)
traefik.http.routers.meuapp.entryPoints=https
traefik.http.routers.meuapp.middlewares=gzip@docker
traefik.http.routers.meuapp.service=meuapp-service
traefik.http.services.meuapp-service.loadbalancer.server.port=3000
traefik.http.routers.meuapp.tls=true
traefik.http.routers.meuapp.tls.certresolver=letsencrypt

Additional Information:

I have verified that the Cloudflare DNS records (both A and CNAME for the wildcard) are correctly configured and that the domain resolves properly.
I have restarted the containers and ensured that the dynamic configuration directory (/data/coolify/proxy/dynamic/) is correctly mounted.

Questions:

- Is there an issue with middleware sharing between the Docker provider and file provider in Coolify’s recommended configuration?
- Are there any additional configuration steps needed to ensure that a middleware defined in the Traefik container is available for applications managed by Coolify?
- Any other advice on how to resolve this error?

Thank you for your help. I look forward to any insights or fixes for this issue.

### Steps to Reproduce

1. Configure the proxy (Traefik) as above with DNS challenge for wildcard certificates.0
2. Configure an application with the above labels to use a gzip middleware.
3. Deploy the containers and monitor the Traefik logs.
4. The logs indicate that Traefik is unable to find the gzip middleware in the Docker provider context.

### Coolify Version

v4.0.0-beta.390

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by isaackoz** [comment]
I had the same issue and wasn't able to find a solution, but I did find a workaround that works better imo.

First I'd recommend adding
`- '--log.level=DEBUG'` to your static config under `command:`.

Next, I'd recommend setting up the traefik dashboard by setting `- '--api.dashboard=true'` under `command:` in the static config.
Then in coolify under dynamic configs, add a new one, e.g. `myconfig.yml`.  Then configure it according to [the docs](https://coolify.io/docs/knowledge-base/proxy/traefik/dashboard).

From here, see if between the dashboard and the proxy logs you're able to determine what the error is. You might be missing something small and it could be an easy fix. In my case, I still had the issue and had to do the following:

1. In my static config, remove all middleware. Mine looks something like 
```yml
 labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.tls.domains[0].main=example.com
      - traefik.http.routers.traefik.tls.domains[0].sans=*.example.com
      - traefik.http.services.traefik.loadbalancer.server.port=8080
```

2. In your dynamic config, add middlewares:
```yml
http:
  routers:
    http-catchall: # optional. I use this to redirect all traffic to https globally
      rule: HostRegexp(`^.+\..+$`) # match any domain
      service: traefik@docker
      entrypoints:
        - http
      middlewares:
        - redirect-to-https
      priority: 999
    dashboard:
      rule: 'Host(`enterdomainhere.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))'
      service: api@internal
      priority: 900
      tls:
        certResolver: letsencrypt
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - 'isaac:$hashedpassgoeshere'
    gzip:
      compress: # add any configuration you need here according to docs. Otherwise set this to compress: {}
        excludedContentTypes:
          - text/event-stream # if you use SSE to stream LLM outputs, this is a MUST
        defaultEncoding: gzip
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: false

```

Now, any of your middlewares you set in the dynamic config are accessible via `middlewarename@file`. For example, to use gzip, you'd do `gzip@file`. I believe either traefik or coolify automatically creates a `gzip@docker` middleware. I'm not sure where this is specified, but I don't think you can override this or configure it further. With that being said, all your containers must specify `gzip@file`. If you just do `gzip`, it will default to `gzip@docker`.

3. Finally, set your container labels. Example:
```yml
traefik.enable=true
traefik.http.routers.https-0-q8o04wkkg4c8wk04ck8ow080.entryPoints=https
traefik.http.routers.https-0-q8o04wkkg4c8wk04ck8ow080.middlewares=gzip@file # important! don't forget `@file`
traefik.http.routers.https-0-q8o04wkkg4c8wk04ck8ow080.rule=Host(`api.example.com`) && PathPrefix(`/`)
traefik.http.routers.https-0-q8o04wkkg4c8wk04ck8ow080.service=https-0-q8o04wkkg4c8wk04ck8ow080
traefik.http.routers.https-0-q8o04wkkg4c8wk04ck8ow080.tls.certresolver=letsencrypt
traefik.http.routers.https-0-q8o04wkkg4c8wk04ck8ow080.tls=true
traefik.http.routers.https-0-q8o04wkkg4c8wk04ck8ow080.priority=100
traefik.http.services.https-0-q8o04wkkg4c8wk04ck8ow080.loadbalancer.server.port=3000
```
