### ISSUE TITLE
[Bug]: Traefik - Router defined multiple times with different configurations

### ISSUE THREAD

**Issue by maximilianschmidt** [coollabsio/coolify#5189]
### Error Message and Logs

The bug report mentioned [here](https://github.com/coollabsio/coolify/issues/2096) seems to be back / not fixed.

in my case i only have a single nodejs application building from a private github repo. used to work fine prior to updating coolify to latest version (v4.0.0-beta.394)

### Steps to Reproduce

1. add a server to coolify self hosted
2. deploy a (node js / express) app
3. assign a custom domain

### Coolify Version

v4.0.0-beta.394

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

### Additional Information

Node App Settings from Coolify (default):
```
traefik.enable=true
traefik.http.middlewares.gzip.compress=true
traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
traefik.http.routers.http-0-roco8ks0kgk4ccw4kgowwkc8.entryPoints=http
traefik.http.routers.http-0-roco8ks0kgk4ccw4kgowwkc8.middlewares=gzip
traefik.http.routers.http-0-roco8ks0kgk4ccw4kgowwkc8.rule=Host(`URL_REDACTED`) && PathPrefix(`/`)
traefik.http.routers.http-0-roco8ks0kgk4ccw4kgowwkc8.service=http-0-roco8ks0kgk4ccw4kgowwkc8
traefik.http.services.http-0-roco8ks0kgk4ccw4kgowwkc8.loadbalancer.server.port=1337
caddy_0.encode=zstd gzip
caddy_0.handle_path.0_reverse_proxy={{upstreams 1337}}
caddy_0.handle_path=/*
caddy_0.header=-Server
caddy_0.try_files={path} /index.html /index.php
caddy_0=URL_REDACTED
caddy_ingress_network=coolify
```

Server Proxy Settings (default):
```
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v3.1'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=50'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--providers.docker=true'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - coolify.managed=true
      - coolify.proxy=true
```
