### ISSUE TITLE
[Bug]: Persistent storage volumes for Preview Builds

### ISSUE THREAD

**Issue by sponte** [coollabsio/coolify#5290]
### Error Message and Logs

Configured persistent storage volumes automatically append the `-pr-<number>` suffix to the source which can cause issues if user wants to mount a socket e.g. `/var/run/docker.sock`.

This is happening inside of this function `app/Jobs/ApplicationDeploymentJob.php:1915`:

```
    private function generate_local_persistent_volumes()
    {
        $local_persistent_volumes = [];
        foreach ($this->application->persistentStorages as $persistentStorage) {
            if ($persistentStorage->host_path !== '' && $persistentStorage->host_path !== null) {
                $volume_name = $persistentStorage->host_path;
            } else {
                $volume_name = $persistentStorage->name;
            }
            if ($this->pull_request_id !== 0) {
                $volume_name = $volume_name.'-pr-'.$this->pull_request_id;
            }
            $local_persistent_volumes[] = $volume_name.':'.$persistentStorage->mount_path;
        }

        return $local_persistent_volumes;
    }
```

### Steps to Reproduce

1. Create application that uses Github and enable preview deployments
2. Configure persistent storage for your application and set source and target to `/var/run/docker.sock`
3. Create a pull request in Github

Expected result: The configured bind mount is provided to the preview deployment container without changing the source path

Actual result: The `-pr-<number>` suffix is added to the source path breaking the deployment.

### Coolify Version

v4.0.0-beta.397

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

CentOS Stream 10 (Coughlan)

**Comment by dentroai** [comment]
I believe I am experiencing a variation of this bug with managed Docker volumes, not just bind mounts.


Setup:
A service deployed from a main branch (e.g., development).
Persistent storage is configured using a Volume Mount (not a Directory/Host Mount). In the UI, a Name is provided for the volume, but the Source Path is left blank. The Destination Path is set to /app/data.

The application uses a SQLite database, which is stored in this volume at /app/data/database.db.

Preview deployments are enabled for pull requests.


Problem:
When a preview deployment is created for a pull request, it appears to be mounting the exact same volume as the main development branch, instead of creating its own new, isolated volume (e.g., my-volume-pr-16).

This causes the two live deployments to interfere with each other's SQLite database file. The result is immediate database corruption and sqlite3.OperationalError crashes on both the preview and main branch applications, as their schemas become out of sync with the shared, corrupted database file.


Expected Behavior:
The preview deployment should automatically create and use a completely separate, isolated volume for its persistent storage to ensure the preview environment cannot conflict with the data of another deployment.
I have confirmed this behavior is consistently reproducible by deleting all deployments and Docker volumes to start from a clean slate. The problem reappears every time a preview deployment is created alongside a main deployment.
This shows that the volume isolation issue for preview builds also affects managed volumes, not only bind mounts.

**Comment by dentroai** [comment]
I have new information after checking my server:

Using `docker volume ls`, I can confirm that Coolify is successfully creating the correctly suffixed preview volume (e.g., my-volume-name-pr-16).

However, the data conflict between my main deployment and the preview deployment is still happening. 
This makes me think: the bug is not that the preview volume isn't being created, but that the preview container is not being mounted to it. It seems to be incorrectly mounting the main branch's volume instead, while the correct -pr-16 volume sits on the disk, unused.

This would explain why the separate volume exists, but the deployments still interfere with each other's data. It points to a bug in how the container's mount configuration is generated during a preview deployment.

**Comment by agapiospanos** [comment]
I also experienced exactly the same bug that @dentroai faced. I use docker compose for the deployment. My "main" instance seems to share the postgres database with the PR instances.

Here is my docker compose in case it helps to better understand:

```yaml
services:
  postgres:
    image: postgres:17-alpine
    networks:
      - default
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  migration:
    build:
      context: .
      dockerfile: docker/Dockerfile.migrate
    networks:
      - default
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    stdin_open: true
    tty: true

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        GIT_COMMIT_SHA: ${SOURCE_COMMIT:-unknown}
    networks:
      - default
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/app/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ui:
    build:
      context: .
      dockerfile: apps/ui/Dockerfile
      args:
        GIT_COMMIT_SHA: ${SOURCE_COMMIT:-unknown}
    networks:
      - default
    expose:
      - "8080"
    depends_on:
      - api
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/assets/email/logo.png || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

```

Unfortunately the link that @sponte provided doesn't work for me so I cannot check the fork.
