### ISSUE TITLE
[Bug]: Compose file with only bind mounts makes "Persistent Storages" tab just show a white screen with syntax error on console

### ISSUE THREAD

**Issue by sardaukar** [coollabsio/coolify#5354]
### Error Message and Logs

I have a compose file with just bind mounts:

```
services:
  forgejo:
    image: 'codeberg.org/forgejo/forgejo:10.0.1'
    environment:
      - SERVICE_FQDN_FORGEJO_3000
      - 'FORGEJO__server__ROOT_URL=${SERVICE_FQDN_FORGEJO_3000}'
      - 'FORGEJO__migrations__ALLOWED_DOMAINS=${FORGEJO__migrations__ALLOWED_DOMAINS}'
      - 'FORGEJO__migrations__ALLOW_LOCALNETWORKS=${FORGEJO__migrations__ALLOW_LOCALNETWORKS-false}'
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=postgresql
      - 'FORGEJO__database__NAME=${POSTGRESQL_DATABASE-forgejo}'
      - FORGEJO__database__USER=$SERVICE_USER_POSTGRESQL
      - FORGEJO__database__PASSWD=$SERVICE_PASSWORD_POSTGRESQL
    volumes:
      - '/mnt/nfs/docker_data/forgejo/gitea:/data'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '10022:22'
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:3000'
      interval: 2s
      timeout: 10s
      retries: 15
  postgresql:
    image: 'postgres:14.5'
    volumes:
      - '/mnt/nfs/docker_data/forgejo/postgres:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRESQL}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}'
      - 'POSTGRES_DB=${POSTGRESQL_DATABASE}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
```

Adding this as a raw compose file makes the "Persistent Storages" tab just show a white screen with this in the browser console:

```
TypeError: this is undefined 2 bootstrap-autofill.js:1857:9
Livewire: [wire:model="nkg04w8ks8wcccs0o0c4kw4w"] property does not exist on component: [project.service.file-storage] 
<input id="nkg04w8ks8wcccs0o0c4kw4w" class="input" autocomplete="off" value="/mnt/nfs/docker_data/forgejo/gitea" readonly="" wire:model="nkg04w8ks8wcccs0o0c4kw4w" wire:dirty.class.remove="dark:focus:ring-coolgray… dark:ring-coolgray-300" wire:dirty.class="dark:focus:ring-warning dark:ring-warning" wire:loading.attr="disabled" type="text" min="" max="" minlength="" maxlength="" name="nkg04w8ks8wcccs0o0c4kw4w" placeholder="">
livewire.min.js:86:5748
Livewire: [wire:model="dkogooog8scowwc004s80kso"] property does not exist on component: [project.service.file-storage] 
<input id="dkogooog8scowwc004s80kso" class="input" autocomplete="off" value="/data" readonly="" wire:model="dkogooog8scowwc004s80kso" wire:dirty.class.remove="dark:focus:ring-coolgray… dark:ring-coolgray-300" wire:dirty.class="dark:focus:ring-warning dark:ring-warning" wire:loading.attr="disabled" type="text" min="" max="" minlength="" maxlength="" name="dkogooog8scowwc004s80kso" placeholder="">
livewire.min.js:86:5748
Livewire: [wire:model="o8o00c4gok4o4ogookg8cow4"] property does not exist on component: [project.service.file-storage] 
<input id="o8o00c4gok4o4ogookg8cow4" class="input" autocomplete="off" value="/etc/timezone" readonly="" wire:model="o8o00c4gok4o4ogookg8cow4" wire:dirty.class.remove="dark:focus:ring-coolgray… dark:ring-coolgray-300" wire:dirty.class="dark:focus:ring-warning dark:ring-warning" wire:loading.attr="disabled" type="text" min="" max="" minlength="" maxlength="" name="o8o00c4gok4o4ogookg8cow4" placeholder="">
livewire.min.js:86:5748
Livewire: [wire:model="uwcsw8ww8o0oggwcogwowg88"] property does not exist on component: [project.service.file-storage] 
<input id="uwcsw8ww8o0oggwcogwowg88" class="input" autocomplete="off" value="/etc/timezone" readonly="" wire:model="uwcsw8ww8o0oggwcogwowg88" wire:dirty.class.remove="dark:focus:ring-coolgray… dark:ring-coolgray-300" wire:dirty.class="dark:focus:ring-warning dark:ring-warning" wire:loading.attr="disabled" type="text" min="" max="" minlength="" maxlength="" name="uwcsw8ww8o0oggwcogwowg88" placeholder="">
livewire.min.js:86:5748
Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    Yt https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:6
    ss https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:6
    za https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    he https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    ie https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    ie https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    Oe https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    Oe https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    Oe https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    Oe https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    Oe https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    Oe https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    Oe https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    Oe https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    Oe https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    Oe https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    ie https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    jl https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    ie https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    Na https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    t https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    Ra https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    Ra https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    t https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    Vn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    Vn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    t https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    Ra https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    t https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    whenFinished https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    Mn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    Ia https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    Nn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    Rn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    promise callback*Rn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    Nn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    Ia https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    fa https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    fa https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    Ia https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    r https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    n https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    jl https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    ie https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:5
    Na https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    t https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    Ra https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    Ra https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    t https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    Vn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    Vn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    t https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    Ra https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    t https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    whenFinished https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    Mn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    Ia https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
    Nn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    Rn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    promise callback*Rn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    Nn https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:11
    Ia https://coolify.my-redacted-domain.tld/livewire/livewire.min.js?id=13b7c601:85
livewire.min.js:6:2556
TypeError: this is undefined bootstrap-autofill.js:1857:9
```

### Steps to Reproduce

1. Add new project
2. Add new environment
3. Add new resource
3. Select "Docker Compose Empty"
4. Insert a compose file with just bind mounts
5. navigate to "Persistent Storages" tab

### Coolify Version

v4.0.0-beta.398

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian 12 on Intel Mac Mini
