### ISSUE TITLE
[Bug]: High CPU Usage

### ISSUE THREAD

**Issue by chihebnabil** [coollabsio/coolify#5355]
### Error Message and Logs

I'm experiencing consistently high CPU usage (100%) on my Coolify instance, and after investigation, I've determined that the `coolify-proxy` container is the primary culprit.

* Consistently high CPU usage on the server.
* `docker stats` shows the `coolify-proxy` container consuming a very large percentage of CPU.
* The `coolify-proxy` logs reveal numerous errors related to Let's Encrypt certificate renewal failures.

**Root Cause:**

The logs indicate that the `coolify-proxy` (which uses Traefik in my case) is repeatedly attempting to renew SSL certificates for domain names that are no longer in use

**Expected Behavior:**

Coolify should automatically remove or stop attempting to renew certificates for domains that are no longer associated with any resources in the Coolify UI.

![Image](https://github.com/user-attachments/assets/bc3d7aab-e71b-4cf6-859b-50602c889114)

I hope this information is helpful. 
Please let me know if you need any further details.

### Steps to Reproduce

/

### Coolify Version

v4.0.0-beta.397

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

24.04

**Comment by Cinzya** [comment]
What Traefik version are you running? This is at the moment a known issue with Traefik v3.1.X.
According to [this Issue](https://github.com/traefik/traefik/issues/11256) on the Traefik Github Repo, it helped for some people to downgrade Traefik to v3.0.X.

If that still doesn't work, you probably want to follow the issue I linked above, as this seems to be a problem with Traefik itself. Changing your proxy to Caddy could be ofc also a solution.

**Comment by chihebnabil** [comment]
I'm using the default Coolify Traefik config, which currently uses v3.1. 

If this is a known issue, shouldn't the default be set to a stable version like v3.0.X instead? Would downgrading be the best workaround for now?

```yaml
name: coolify-proxy
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v3.1'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
      - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=250'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=250'
      - '--entrypoints.https.http3'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--api.insecure=false'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - coolify.managed=true
      - coolify.proxy=true
      ```
