### ISSUE TITLE
[Bug]: mapping files, creating file with content doesn't work

### ISSUE THREAD

**Issue by ton77v** [coollabsio/coolify#5385]
### Error Message and Logs

1. You can't map the file you have in repo, the namesake directory would be created instead
2. You can't add a file with content and a dynamic value that is coming from an environment variable

### Steps to Reproduce

**Can't map the file you have in repo**, I tried the following syntax

```YAML
    volumes:
      - ./dev_configs/pg_servers.json:/pgadmin4/servers.json
```
or

```YAML
    volumes:
      - type: bind
        source: ./dev_configs/pg_servers.json
        target: /pgadmin4/servers.json
        read_only: true
        # noinspection ComposeUnknownKeys
        is_directory: false  # Coolify-specific
```

**Can't add a file with content and a dynamic value that is coming from an environment variable**:

Following example from docs https://coolify.io/docs/knowledge-base/docker/compose#create-a-file-with-content

The file is created, but the `echo "$POSTGRES_PASSWORD"` won't be substituted by the variable value. Instruction just stays as it is with back-ticks etc

### Coolify Version

v4.0.0-beta.398

### Are you using Coolify Cloud?

Yes (Coolify Cloud)
