### ISSUE TITLE
[Bug]:  can't specify a port to bind the domain to for PR deployments

### ISSUE THREAD

**Issue by ton77v** [coollabsio/coolify#5430]
### Error Message and Logs

In my docker-compose there's a service:
```YAML
  mailhog:
    image: registry.gitlab.com/opencity-labs/mailhog:latest-arm
    container_name: mailhog
    hostname: mailhog
```

I set the domain for it like so:
```
https://mailhog.MY_DOMAIN:8025
```

Works fine with the regular deployments, but for PR deployments with
```
{{pr_id}}.{{domain}}
```
- works fine for all the services, except mailhog

I can see that when I visit the URL, http traffic is routed to the SMTP port e.g.:
2025/03/26 10:10:28 [SMTP 172.27.0.2:45744] [PROTO: ESTABLISH] Got unknown command for ESTABLISH state: 'ACCEPT:'
2025/03/26 10:10:28 [SMTP 172.27.0.2:45744] Sent 26 bytes: '500 Unrecognised command\r\n'

### Steps to Reproduce

See above. If anyone has a workaround in mind, please advice 

### Coolify Version

v4.0.0-beta.399

### Are you using Coolify Cloud?

Yes (Coolify Cloud)
