### ISSUE TITLE
[Bug]: new persistent storages are created every time the docker compose is deployed

### ISSUE THREAD

**Issue by vladflotsky** [coollabsio/coolify#5435]
### Error Message and Logs

When you deploy an application, new persistent storages are created, breaking the application. There are no limits, so it takes a long to access the persistent storages page because of too many created storages.

### Steps to Reproduce

I'd take the pterodactyl template as an example, because I experienced issues with it
1. Deploy pterodactyl ([here's the guide](https://github.com/coollabsio/coolify/pull/3052#issue-2459592183))
2. Try to deploy it again
3. See a lot of new persistent storages

### Coolify Version

v4.0.0-beta.399

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

**Comment by tiangao88** [comment]
I have the same issue **with the latest v4.0.0-beta.399**

It seems to happen only with type bind such as

`    volumes:
      - 'n8n-data:/home/node/.n8n'
      -
        type: bind
        source: ./n8n/backup
        target: /backup
      -
        type: bind
        source: ./n8n/shared
        target: /data/shared
      -
        type: bind
        source: ./n8n/shared/custom/Dockerfile
        target: /data/shared/custom/Dockerfile
        content: "# Redacted"`

With this syntax, I do not get duplicates of persistent storage
`    volumes:
      - 'pg-data:/var/lib/postgresql/data'`

**Comment by tiangao88** [comment]
I just checked with the latest _v4.0.0-beta.400_ and the issue is still present
All file or directory mounts are recreated at restart or deploy with consequence of potentially loosing data.


> I have the same issue **with the latest v4.0.0-beta.399**
> 
> It seems to happen only with type bind such as
> 
> ` volumes: - type: bind source: ./n8n/backup target: /backup - type: bind source: ./n8n/shared target: /data/shared - type: bind source: ./n8n/shared/custom/Dockerfile target: /data/shared/custom/Dockerfile content: "# Redacted"`
> 
> With this syntax, I do not get duplicates of persistent storage ` volumes: - 'pg-data:/var/lib/postgresql/data'`

**Comment by vladflotsky** [comment]
> I just checked with the latest _v4.0.0-beta.400_ and the issue is still present All file or directory mounts are recreated at restart or deploy with consequence of potentially loosing data.
> 
> > I have the same issue **with the latest v4.0.0-beta.399**
> > It seems to happen only with type bind such as
> > ` volumes: - type: bind source: ./n8n/backup target: /backup - type: bind source: ./n8n/shared target: /data/shared - type: bind source: ./n8n/shared/custom/Dockerfile target: /data/shared/custom/Dockerfile content: "# Redacted"`
> > With this syntax, I do not get duplicates of persistent storage ` volumes: - 'pg-data:/var/lib/postgresql/data'`

Are you using the n8n template?

**Comment by Bisb** [comment]
Seems to happen on compose file reload in general (which is probably triggered during deploy / restart as well) on v4.0.0-beta.399

**Comment by tiangao88** [comment]
> > I just checked with the latest _v4.0.0-beta.400_ and the issue is still present All file or directory mounts are recreated at restart or deploy with consequence of potentially loosing data.
> > > I have the same issue **with the latest v4.0.0-beta.399**
> > > It seems to happen only with type bind such as
> > > ` volumes: - type: bind source: ./n8n/backup target: /backup - type: bind source: ./n8n/shared target: /data/shared - type: bind source: ./n8n/shared/custom/Dockerfile target: /data/shared/custom/Dockerfile content: "# Redacted"`
> > > With this syntax, I do not get duplicates of persistent storage ` volumes: - 'pg-data:/var/lib/postgresql/data'`
> 
> Are you using the n8n template?

Yes originally that application was created from the Coolify n8n template.
Then over time I had to customize n8n and created a file mount for a Dockerfile.

I also have the issue on applications created entirely from Docker Compose as well as applications created entirely from Coolify templates.

**Comment by mrcleanandfresh** [comment]
I'm seeing the same behavior. I used the Private Repo option, then selected the docker compose build pack, and was seeing this behavior. I have also been selecting the option to "Preserve Repository During Deployment" which seems to be an okay work around, but the "Persistent Storage" tab is taking forever to load

![Image](https://github.com/user-attachments/assets/6f62a4ac-bcbf-48c4-b675-224302d59093)

Then today I started getting this error.

**Comment by arxkdev** [comment]
Having the same issue. Looked at my docker registry service and saw it had like 10 volumes, constantly reduplicating every time I redeploy.

**Comment by ari-party** [comment]
Seeing at least 8 of the /data volumes on  Nextcloud. v400

**Comment by frenchmustard** [comment]
Same issue here, didnt have this issue on 398 or 399 from what I recall. 

Is it cause of the patch in bootstrap/helpers/shared.php ( #5457 , specifically https://github.com/coollabsio/coolify/commit/c2941abe572f1881bdcbe456fcabd09318995f2d)?

**Comment by frenchmustard** [comment]
Just confirmed locally version v4.0.0-beta.401 has apparently fixed this issue (see https://github.com/coollabsio/coolify/commit/c2941abe572f1881bdcbe456fcabd09318995f2d).

But Coolify wont update yet cause 401 is still in 'nightly' in the CDN but not in the versions.json (as of posting this).

**Comment by fguillen** [comment]
Same issue here:

![Image](https://github.com/user-attachments/assets/b6611f77-705f-4e07-88fa-029c4f3eac80)

This is the docker compose:

```
services:
  loki:
    image: grafana/loki
    command:
      - '-config.file=/etc/loki/loki-config.yaml'
    volumes:
      - '/etc/loki:/etc/loki'
      - 'loki-data:/loki'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget --tries=1 --spider http://localhost:3100/ready || exit 1'
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    image: 'nginx:alpine'
    volumes:
      - '/etc/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/nginx/conf.d/loki.conf:/etc/nginx/conf.d/loki.conf'
      - '/etc/nginx/.htpasswd:/etc/nginx/.htpasswd'
    depends_on:
      - loki
```

**Comment by WoefulWolf** [comment]
Same Issue on `v4.0.0-beta.400`:

Docker compose volumes:
```
volumes:
      - 'stirling-training-data:/usr/share/tesseract-ocr/5/tessdata'
      - 'stirling-configs:/configs'
      - type: bind
        source: ./customFiles
        target: /customFiles
        is_directory: true
      - 'stirling-logs:/logs/'
```
`customFiles` directory mount duplicates every restart:

![Image](https://github.com/user-attachments/assets/00931ce6-bac8-4917-afb8-42c2a7807046)
