### ISSUE TITLE
I am happy to see this being released. I am running into an error still on version 4.0.0-beta.400.

### ISSUE THREAD

**Issue by Tmmcmasters** [coollabsio/coolify#5450]
I am happy to see this being released. I am running into an error still on version 4.0.0-beta.400.

 FATAL:  could not load private key file "/var/lib/postgresql/certs/server.key": Permission denied
2025-03-27 19:55:19.728 UTC [1] LOG:  database system is shut down
2025-03-27 19:55:32.860 UTC [1] FATAL:  could not load private key file "/var/lib/postgresql/certs/server.key": Permission denied
2025-03-27 19:55:32.860 UTC [1] LOG:  database system is shut down

Steps are: 
Make publicly available on the normal port of 5432. 
Once it is started, I stop it, and click enable SSL:
![image](https://github.com/user-attachments/assets/3e0ab495-a344-4cee-b279-d6366157950c)
I get an empty Proxy Logs which showed the first weird thing. I have to hard refresh CTRL + SHIFT + R to get this page to work because it freezes my client.
After hard refresh, I start the postgres server:
 FATAL:  could not load private key file "/var/lib/postgresql/certs/server.key": Permission denied
2025-03-27 19:55:19.728 UTC [1] LOG:  database system is shut down
2025-03-27 19:55:32.860 UTC [1] FATAL:  could not load private key file "/var/lib/postgresql/certs/server.key": Permission denied
2025-03-27 19:55:32.860 UTC [1] LOG:  database system is shut down

This is in spite that the persistent storage states that the destination path is 
![image](https://github.com/user-attachments/assets/a897f20e-8179-42d6-b2be-6834180a102f)
![image](https://github.com/user-attachments/assets/6eaeb056-0d6c-45d8-8928-2fa1b69e6844)

_Originally posted by @Tmmcmasters in https://github.com/coollabsio/coolify/discussions/3976#discussioncomment-12645665_

**Comment by Tmmcmasters** [comment]
I feel like it has something to do with the Source Path and the Destination Path. I can help by taking a look in a second.

**Comment by Tmmcmasters** [comment]
> The actual files are located on the server `/data/coolify/database...`?

Will run some testing on this and let you know

**Comment by Tmmcmasters** [comment]
> The actual files are located on the server `/data/coolify/database...`?

@andrasbacsai I ran some testing and I am unable to actually change the file mount source path and destination path. I went to the root server and I am running this on localhost. It appears that it is there where it says in the source path. 

![Image](https://github.com/user-attachments/assets/6afc253e-d800-40d8-b5a6-93e30c3ca397)


I am unable to see the destination path because the Postgres server keeps shutting down and the terminal is inaccessible.

**Comment by peaklabs-dev** [comment]
Can you use SSH and then check the ssl folder and do an `ls` in the ssl folder please.

**Comment by Tmmcmasters** [comment]
> Can you use SSH and then check the ssl folder and do an `ls` in the ssl folder please.

Will take a look at this later this evening. Thank you

**Comment by FlashSkyNews** [comment]
Hey! Bumping this issue because I'm also experiencing this.

I've noticed, that when creating the postgres instance it tries to assign something to the postgres user I've defined. This user doesn't exist tho. Deploying the instance with default values (user=postgres) works tho.

(ignore the music in the background hahaha)
https://github.com/user-attachments/assets/4c582a67-ebd7-46e3-a582-e9ccf1cd4eba

**Comment by Tmmcmasters** [comment]
I think the issue is related to the user as well, the folder structure appears to be fine....

**Comment by ApoloApps** [comment]
same problem here, using custom user (maybe created custom user does not have admin access??? idk)
<details><summary>Logs</summary>
<p>
2025-04-08 13:55:57.961 UTC [1] FATAL:  could not load private key file "/var/lib/postgresql/certs/server.key": Permission denied
2025-04-08 13:55:57.961 UTC [1] LOG:  database system is shut down
</p>
</details>

**Comment by codelonesomest** [comment]
I also got this problem after regenerate ssl certificates. I assume the command cause the problem?

```yaml
volumes:
            - 'postgres-data-co000kw0c8ooos8oowcg4g4g:/var/lib/postgresql/data'
            - '/data/coolify/databases/co000kw0c8ooos8oowcg4g4g/ssl/server.pem:/var/lib/postgresql/certs/server.pem'
        command:
            - postgres
            - '-c'
            - ssl=on
            - '-c'
            - ssl_cert_file=/var/lib/postgresql/certs/server.crt
            - '-c'
            - ssl_key_file=/var/lib/postgresql/certs/server.key
```
