### ISSUE TITLE
[Bug]: Cannot use scale attribute in compose file

### ISSUE THREAD

**Issue by MelvinvanMelzen** [coollabsio/coolify#5480]
### Error Message and Logs

When you try to deploy a resource using a compose file which contains a **scale attribute** you get an error [as scale and container name can't be used together ](https://docs.docker.com/reference/compose-file/services/#container_name) and coolify automatically sets a container name. 

### Steps to Reproduce

1. Deploy compose file like so:
```
services:
(...)
  celery:
    build: ./project
    command: celery --app=django_project worker --loglevel=info
    scale: 2
(...)
```
 
2. Error:
services.scale: can't set container_name and celery as container name must be unique: invalid compose project

3. Profit  

### Coolify Version

v4.0.0-beta.400 

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.2 LTS

### Additional Information

To me the only bug is I wasn't warned about this and this could have been caught before building. My recommendation would be to check the compose file for scale attributes and/or ignore them.
