### ISSUE TITLE
[Bug]: Data not persisting in Dragonfly Database after container restart

### ISSUE THREAD

**Issue by ShadowArcanist** [coollabsio/coolify#5486]
### Error Message and Logs

![Image](https://github.com/user-attachments/assets/bb451a55-846d-4a1e-9d02-bb50b1dd68ca)

### Steps to Reproduce

1. Create a new resource on Coolify
2. Choose Dragonfly Database from the one click database list
3. Deploy the database with default settings
4. Add something data to the database
5. Restart the database from Coolify dashboard and check if the data you added to the database is still there

### Coolify Version

v4.0.0-beta.401

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12 (bookworm)

### Additional Information

The volume mounted on host had 2 files:

![Image](https://github.com/user-attachments/assets/5f420423-b34a-45e5-9b47-05945c0950bb)

The compose file:
![Image](https://github.com/user-attachments/assets/ecc82d2c-47f1-4763-ab66-446d5bdf7860)

**Comment by ShadowArcanist** [comment]
Actually not a bug, user have to setup backups: https://www.dragonflydb.io/docs/managing-dragonfly/backups#the-snapshot_cron-flag

**Comment by LaurenceJJones** [comment]
Example command setting to the persisted directory and save every 5 :

```yaml
services:
  dragonfly:
     command: 'dragonfly --requirepass XXXXXXXX --dir /data --dbfilename dragonfly-snapshot-{timestamp} --snapshot_cron "*/5 * * * *"'
```

other to note if you library you using to interact with dragonfly has the "SAVE" command then this allows for manual saving.
