### ISSUE TITLE
[Bug]: set url with ports inside the container seems go wrong

### ISSUE THREAD

**Issue by jellyfish-p** [coollabsio/coolify#5545]
### Error Message and Logs

when I tried to manage supabase through coolify.I set the url like https://xxx.example.com:8000,and when I tried to access my url,it returned nothing.However,when I expose the port,it can be accessed correctly.Is this a bug of treafik or coolify or I misunderstood the config

![Image](https://github.com/user-attachments/assets/15069c06-dedb-449f-b664-76c8d2b70cba)

### Steps to Reproduce

1.
2.
3.
4.

### Coolify Version

v4.0.0-beta405

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04-lts

**Comment by djsisson** [comment]
@jellyfish-p is the proxy running?

**Comment by jellyfish-p** [comment]
@djsisson Yes,the proxy is running and when I access the server ip it can correctly return 404

**Comment by djsisson** [comment]
check the proxy logs for certificate errors

run curl on the vps to test the proxy

```curl -v -H "host: supa.xxx.com" localhost```

**Comment by jellyfish-p** [comment]
@djsisson like this picture

![Image](https://github.com/user-attachments/assets/b34e7e67-abf4-4364-8e7b-17485f33bd14)

It reported 404

I am using multiserver and supabase is on another server

**Comment by djsisson** [comment]
@jellyfish-p this was ran on the server running supabase yes?

**Comment by jellyfish-p** [comment]
@djsisson Yes.Emmm,may be I can make another more intuitive example.

the docker-compose.yml is 
``` yml
services:
  alist:
    image: 'xhofe/alist:latest'
    container_name: alist
    volumes:
      - './alist:/opt/alist/data'
    ports:
      - 5244:5244
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    restart: unless-stopped
```

and the Domains is

```
http://alist.paperchemis.com:5244
```

then,you can see the difference in visiting the port and only the domain

**Comment by djsisson** [comment]
@jellyfish-p then there is an issue with the proxy on that server.
If the server is behind a proxy you can't generate certificates using http challenge.
But first can you run docker ps

**Comment by jellyfish-p** [comment]
@djsisson 
I ran docker ps and it's easy to see it's running

![Image](https://github.com/user-attachments/assets/16c2688e-c77e-4297-bb14-919d08a4f474)

and some service using nixpack is runninng correctly
idk why can't I access when I am using port inside the contianer

Even if I updated coolify to v4.0.0-beta405 it still exists

**Comment by djsisson** [comment]
Can you run docker logs coolify-proxy

**Comment by jellyfish-p** [comment]
like the pictrue below

![Image](https://github.com/user-attachments/assets/742b0f00-9e97-4df9-9781-233614c0b66f)

**Comment by djsisson** [comment]
@jellyfish-p can you describe your setup.

Is this server directly connected to the Internet?

As you can see the issue is it can't generate certificates , that's usually if you don't have a direct connection.

In which case you need to install cert yourself or switch to DNS challenge

**Comment by jellyfish-p** [comment]
@djsisson 
I installed coolify on another server and use multiserver added this server.
I can promise this server have the same net condition with the main server and both of them not have a http/https proxy.
I am in China but I don't think this is the reason why it can't get let's encrypt.

**Comment by djsisson** [comment]
@jellyfish-p does the public wan ip of this machine match the ip in your dns record?

**Comment by jellyfish-p** [comment]
@djsisson Yes,dns is right,I've checked many times.

**Comment by jellyfish-p** [comment]
I think it's a bug of multiple servers because if i deploy it on the server coolify running,it can run correctly but if I run it on the server controlled by ssh,it goes wrong.

**Comment by djsisson** [comment]
Who si your hosting provider and who is your dns provider.
Make sure your dns provider isn't using a dns proxy
It looks like the .wellknown request is just getting stopped before it gets to your server.
You can just switch to dns challenge tho to solve this

**Comment by djsisson** [comment]
Then there is an issue with the other server, is there an external firewall running?

**Comment by jellyfish-p** [comment]
I use cloudflare and the server is in China without external firewall and I have run `ufw allow`

**Comment by djsisson** [comment]
Just to confirm, DNS proxy is not ticked in cloudflare for your record?

**Comment by jellyfish-p** [comment]
@djsisson 
Sure,cloudflare dns proxy will make visiting my site slowly in China so I always close it.
![Image](https://github.com/user-attachments/assets/189b6b41-0e88-4dd4-b201-6ddbde536e66)

**Comment by djsisson** [comment]
Stop the proxy, find acme.json in /data/coolify/proxy rename it then restart proxy check proxy logs again.

**Comment by jellyfish-p** [comment]
It went wrong again,but I used to run certbot on this machine and it's ok.
![Image](https://github.com/user-attachments/assets/f69345ba-94c6-4b69-860f-183bf0fbd747)

**Comment by djsisson** [comment]
@jellyfish-p temp change one of the domains to be http not https save it and restart the stack

Check it works over http first

**Comment by jellyfish-p** [comment]
@djsisson I wrote and using http://alist.paperchemis.com:5244 but it didn't work.

**Comment by djsisson** [comment]
Can you run 
```
curl -v -H "host: alist.paperchemis.com" localhost
```
The same command as before but do not add port 443

**Comment by jellyfish-p** [comment]
@djsisson It correctly returned a html and header is following

```
* Host localhost:80 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:80...
* Connected to localhost (::1) port 80
> GET / HTTP/1.1
> Host: alist.paperchemis.com
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html
< Date: Sat, 05 Apr 2025 03:39:36 GMT
< Transfer-Encoding: chunked
< 
```

But if I visit it by url it will still went wrong and I visit it with port it can correctly respond

**Comment by djsisson** [comment]
OK re run the command but from where you are and replace localhost with the server ip

If you get nothing then port 80 is being blocked somewhere

**Comment by jellyfish-p** [comment]
@djsisson Thanks for your help.I can now make sure it's not a coolify's bug but something went wrong with my configuration,although I opened the port but it can't response curl.I'll try to solve it.

**Comment by jellyfish-p** [comment]
@djsisson I checked dns record and it's right.And I added server ip as one of the container domains,then I can visit it by ip but I can't visit it by url.

**Comment by djsisson** [comment]
Can you show me output from curling the ip

**Comment by jellyfish-p** [comment]
@djsisson 
```
ubuntu@VM-0-16-ubuntu:~$ http_proxy="" curl -v -H "host: alist.paperchemis.com" 111.170.19.82
*   Trying 111.170.19.82:80...
* Connected to 111.170.19.82 (111.170.19.82) port 80
> GET / HTTP/1.1
> Host: alist.paperchemis.com
> User-Agent: curl/8.5.0
> Accept: */*
> 
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
ubuntu@VM-0-16-ubuntu:~$ http_proxy="" curl -v -H "host: 111.170.19.82" 111.170.19.82
*   Trying 111.170.19.82:80...
* Connected to 111.170.19.82 (111.170.19.82) port 80
> GET / HTTP/1.1
> Host: 111.170.19.82
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html
< Date: Sat, 05 Apr 2025 04:40:15 GMT
< Transfer-Encoding: chunked
< 
```
and the domains are

![Image](https://github.com/user-attachments/assets/878e98a1-6d08-4aa3-b989-8407e9161cad)

**Comment by djsisson** [comment]
there is something wrong with the proxy still, even if you type in a random hostname, it should instantly return a 404 but it just hangs.

can you show me contents of the /data/coolify/proxy and /data/coolify/proxy/dynamic folders please

**Comment by jellyfish-p** [comment]
@djsisson 
```
root@serx1uZJD9nSnvv:/data/coolify/proxy# ls
acme.json  acme.json.bak  acme.json.bak1  docker-compose.yml  dynamic
```
```
root@serx1uZJD9nSnvv:/data/coolify/proxy/dynamic# ls
Caddyfile  default_redirect_503.yaml
```

**Comment by djsisson** [comment]
can you paste contents of
docker-compose.yml
default_redirect_503.yaml

**Comment by jellyfish-p** [comment]
```
root@serx1uZJD9nSnvv:/data/coolify/proxy/dynamic# cat default_redirect_503.yaml 
# This file is generated by Coolify, do not edit it manually.
# Disable the default redirect to customize (only if you know what are you doing).

http:
  routers:
    catchall:
      entryPoints:
        - http
        - https
      service: noop
      rule: PathPrefix(`/`)
      tls:
        certResolver: letsencrypt
      priority: -1000
  services:
    noop:
      loadBalancer:
        servers: {  }
```
```
root@serx1uZJD9nSnvv:/data/coolify/proxy# cat docker-compose.yml 
name: coolify-proxy
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v3.1'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
      - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=250'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=250'
      - '--entrypoints.https.http3'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--api.insecure=false'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - coolify.managed=true
      - coolify.proxy=true
```
