### ISSUE TITLE
[Bug]: "Non-string key in services..." when using both build args & env variables

### ISSUE THREAD

**Issue by ton77v** [coollabsio/coolify#5555]
### Error Message and Logs

2025-Apr-05 00:44:01.084076
Non-string key in services.SERVICE_NAME.environment: 0
2025-Apr-05 00:44:01.084076
exit status 1

### Steps to Reproduce

1. Add the service with both build args and env vars for instance smth like
```YAML
services:
  service_name:
    build:
      # ...
      args:
        COMMIT_SHA: '${SOURCE_COMMIT}'
        BUILD_ENV: COOLIFY
    environment:
      COOLIFY_URL: ${COOLIFY_URL}
```

2. Coolify would generate output like:
```YAML
services:
  service_name:
    build:
      # ...
      args:
        COMMIT_SHA: '${SOURCE_COMMIT}'
        BUILD_ENV: COOLIFY
    environment:
      0: 'COOLIFY_URL=${COOLIFY_URL}'
      COMMIT_SHA: '${SOURCE_COMMIT}'
      BUILD_ENV: COOLIFY
```

> 0: 'COOLIFY_URL=${COOLIFY_URL}'

This is what causes issues

### Coolify Version

v4.0.0-beta.402

### Are you using Coolify Cloud?

Yes (Coolify Cloud)

### Additional Information

As a workaround, move everything to either build args or env vars

**Comment by ton77v** [comment]
Another workaround:
```
services:
    app:
      build:
        context: .
        args:
          - BUILD_ENV=COOLIFY
      environment:
        - COMMIT_SHA=${SOURCE_COMMIT}
````

Turned out this syntax works much better in Coolify
