### ISSUE TITLE
[Enhancement]: Schema/Openapi define Proxy object on servers

### ISSUE THREAD

**Issue by LaurenceJJones** [coollabsio/coolify#5572]
### Request Type

Improvement

### Description

Hey team 👋🏻 

Whilst creating the CLI since golang is a strict typed language it best to know all fields a object can have whilst creating commands for server I can see via the definition we have:

```yaml
        proxy:
          type: object
          description: 'The proxy configuration.'
```

Currently when dumping the raw request I can see these fields, if we can incorporate them into the schema this will help make sure I keep to the same schema as coolify.
```
"proxy":{"type":"TRAEFIK","status":"running","redirect_enabled":true,"last_saved_settings":"0b6f4ac86dd6176e20d1fdacc7a6f8ca","last_applied_settings":"0b6f4ac86dd6176e20d1fdacc7a6f8ca","force_stop":false},
```
