### ISSUE TITLE
[Bug]: Coolify generates invalid Docker Compose labels with numeric keys (0: key=value)

### ISSUE THREAD

**Issue by jojo8356** [coollabsio/coolify#5580]
### Error Message and Logs

Hi Coolify team,

I'm using Coolify version `4.0.0-beta.407`, and I noticed that the generated `docker-compose.yml` files include `labels` defined with **numeric keys**, like this:

```yaml
labels:
  0: coolify.managed=true
  1: coolify.version=4.0.0-beta.407
  2: traefik.enable=true
  ...
```

However, Docker Compose expects either:

```yaml
labels:
  - coolify.managed=true
  - traefik.enable=true
```

or

```yaml
labels:
  "coolify.managed": "true"
  "traefik.enable": "true"
```

The current format causes parsing issues and breaks deployments or causes unexpected behavior, especially with strict YAML parsers.

Could this be fixed in a future release or is there a config option to generate labels as a proper list or string-based key-value pairs?

Thanks a lot for the awesome tool — keep it up! 🙌

### Steps to Reproduce

1. Install Coolify
2. Create project
3. Add Hyperswitch URL
4. Deploy with Docker Compose

### Coolify Version

v4.0.0-beta.407

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by Cinzya** [comment]
@jojo8356  Please provide the actual link to the repo to reproduce.

It looks like this is caused when the docker compose already contains labels but notated as a map instead of a list.

E.g.
```yaml
    labels:
      logs: "promtail"
```
will turn to
```yaml
    labels:
      logs: promtail
      0: coolify.managed=true
      1: coolify.version=4.0.0-beta.407
```

This is not the case if the labels are defined in a list as already mentioned.
So a temporary fix for now would be, to fork the repo and change the predefined labels to use a list over a map.
