### ISSUE TITLE
[Bug]: n8n MCP functionality doesn't work due to SSE Gzip compression

### ISSUE THREAD

**Issue by salomaoparkour** [coollabsio/coolify#5586]
### Error Message and Logs

The new MCP functionality in n8n requires SSE connection and the Gzip compression feature in Coolify prevents it from working.

I currently disabled gzip compression fully, on my n8n service, but I'm under the impression this souldn't be the final fix.

If I understand it correctly, the gzip compression should only be disabled for SSE connections, right?

Related issues:
https://github.com/coollabsio/coolify/issues/4002
https://github.com/n8n-io/n8n/issues/14539

### Steps to Reproduce

1. Install n8n version 1.88.0 or higher
2. Create an MCP Trigger
3. Activate the workflow
4. Try to connect to the MCP's production URL
5. No response

### Coolify Version

v4.0.0-beta.407

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

**Comment by gabrieljablonski** [comment]
Just to centralize the known information here, it should be possible to setup Traefik to disable compression selectively on SSE requests. See [here](https://doc.traefik.io/traefik/middlewares/http/compress/#excludedcontenttypes)

TLDR; add to server proxy config:

```yaml
labels:
  - "traefik.http.middlewares.test-compress.compress.excludedcontenttypes=text/event-stream"
```

I have not managed to make it work, but didn't have the time to test it correctly yet, so deserves some more investigation.

**Comment by salomaoparkour** [comment]
A Brazilian n8n community leader was able to fix this issue with traefik.
Details here:
https://comunidade.promovaweb.com/c/comunicados/ajuste-do-traefik-para-funcionar-com-n8n-mcp

The configurations he used:
```
# For /mcp paths in the EDITOR (main) config file
# Middleware to remove GZIP
- traefik.http.middlewares.nogzip.headers.customResponseHeaders.Content-Encoding=""
- traefik.http.routers.n8n_editor_nogzip.rule=Host(`workflows.agenciasynca.com.br`) && PathPrefix(`/mcp`)
- traefik.http.routers.n8n_editor_nogzip.entrypoints=websecure
- traefik.http.routers.n8n_editor_nogzip.tls.certresolver=letsencryptresolver
- traefik.http.routers.n8n_editor_nogzip.service=n8n_editor_nogzip
- traefik.http.routers.n8n_editor_nogzip.middlewares=nogzip
- traefik.http.routers.n8n_editor_nogzip.priority=20
```

```
# For /mcp paths in the WEBHOOK config file
# Middleware to remove GZIP
- traefik.http.middlewares.nogzip.headers.customResponseHeaders.Content-Encoding=""
- traefik.http.routers.n8n_webhook_nogzip.rule=Host(`webhooks.agenciasynca.com.br`) && PathPrefix(`/mcp`)
- traefik.http.routers.n8n_webhook_nogzip.entrypoints=websecure
- traefik.http.routers.n8n_webhook_nogzip.tls.certresolver=letsencryptresolver
- traefik.http.routers.n8n_webhook_nogzip.service=n8n_webhook_nogzip
- traefik.http.routers.n8n_webhook_nogzip.middlewares=nogzip
- traefik.http.routers.n8n_webhook_nogzip.priority=20
```

**Comment by eduwass** [comment]
Different use-case but similar thing happened to me here:
https://github.com/adonisjs/transmit/issues/31

As others above mentioned, you can tell Traefik to not gzip stream contents:


## Avoiding GZip Interference

When deploying applications that use SSE, it’s important to ensure that GZip compression does not interfere with the `text/event-stream` content type used by Server-Sent Events (SSE). Compression applied to `text/event-stream` can cause connection issues, leading to frequent disconnects or SSE failures.

If your deployment uses a reverse proxy (such as Traefik or Nginx) or other middleware that applies GZip, ensure that compression is disabled for the `text/event-stream` content type.

### Example Configuration for Traefik

```plaintext
traefik.http.middlewares.gzip.compress=true
traefik.http.middlewares.gzip.compress.excludedcontenttypes=text/event-stream
traefik.http.routers.my-router.middlewares=gzip
```

**Comment by SrJooJ** [comment]
Hi!

Following what our colleague said above, you can add the following configuration inside compose:

![Image](https://github.com/user-attachments/assets/84dfe571-d5dd-49a6-aa53-e931f6db3a0f)

This will do exactly what he asked for which is to exclude the gzip in the text/event-stream


```
    labels:
      - traefik.http.middlewares.n8n-gzip.compress=true
      - traefik.http.middlewares.n8n-gzip.compress.excludedcontenttypes=text/event-stream
      - traefik.http.routers.n8n-https.rule=Host(`${N8N_HOST}`)
      - traefik.http.routers.n8n-https.middlewares=n8n-gzip@docker
```

**Comment by jpgrandao** [comment]
Hi @SrJooJ 
Where do I put this setting in Coolify?

**Comment by jpgrandao** [comment]
@SrJooJ Thank you very much, but it didn't work. :(

On the Log shows:
McpClientTool: Failed to connect to MCP Server
Error in sub-node MCP Client

Would I have to replace any variables?

**Comment by dbjpanda** [comment]
@jpgrandao Did you able to fix it? If yes, then please comment details. @SrJooJ solution didn't help me

**Comment by alumbs** [comment]
Same @SrJooJ  just adding those values in the docker compose for the n8n service did not work

**Comment by dbjpanda** [comment]
Go to your Coolify project -> Services -> n8n settings -> General -> Advanced -> Uncheck Gzip compression

<img width="435" alt="Image" src="https://github.com/user-attachments/assets/50c36fe5-b60a-4813-aa98-b753ec83a383" />

Also check these points

- [ ] After changing the gzip, restart the services, proxies etc. 
- [ ] Try to activate the workflow and try with production url
- [ ] If using Cloudflare etc proxy, you may exclude your n8n domain/subdomain

**Comment by alumbs** [comment]
> I didn't require to change any fancy settings. One of the n8n contributor mentioned that n8n itself takes care of gzip etc, we don't need to put another service on top of it. So we can safely disable the gzip compression provided by Coolify (Traefik)
> 
> Go to your Coolify project -> Services -> n8n settings -> General -> Advanced -> Uncheck Gzip compression
> 
> <img alt="Image" width="435" src="https://private-user-images.githubusercontent.com/17483092/435296534-50c36fe5-b60a-4813-aa98-b753ec83a383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUwMDgzNTAsIm5iZiI6MTc0NTAwODA1MCwicGF0aCI6Ii8xNzQ4MzA5Mi80MzUyOTY1MzQtNTBjMzZmZTUtYjYwYS00ODEzLWFhOTgtYjc1M2VjODNhMzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE4VDIwMjczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOWUyZmU2NGE2OGE2YjRjYmYwYzBkOTUzNzA0ZTViMTA0MjJiM2VmNTMzOWMzZDVkZTlhMTEwNGUzMmRjZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wHXqYTg6zU4VFrbFEjzXKSvrDJv4PIqc_nCHhK8m4vg">
> Also check these points
> 
> * [ ]  After changing the gzip, restart the services, proxies etc.[ ]  Try to activate the workflow and try with production url[ ]  If using Cloudflare etc proxy, you may exclude your n8n domain/subdomain[ ]  Try to open the sse url in your browser, it might show you any error message

This worked for me. I just figured it out and was about to post

**Comment by SrJooJ** [comment]
Sorry for the lack of response, I can't be very present on github during the weekdays.

I'm glad it worked, the other solution here had worked, I had forgotten that it contains this gzip part in the advanced section.

Anyway, is there a troubleshooting section where we can add this? @andrasbacsai

**Comment by jpgrandao** [comment]
@dbjpanda, it worked, thank you very much, but I have another question: is there any implication in not using gzip? I ask this because it may have an impact on the greater use of memory and processing power. However, I'm thinking of using 2 services, one with gzip, the other without gzip.

Tell me below with your opinion.

**Comment by oguiisouza** [comment]
Hey guys, this is my docker-compose.yml file. I've tried many different options but nothing seems to work.
If anyone could help me, I would be really grateful. Thanks a lot!

![Image](https://github.com/user-attachments/assets/cff0fcac-5161-4771-b122-1197787d480d)

**Comment by jeevauvaraju** [comment]
Any update or fix for this issue ?
I am using self hosted n8n deployed via docker compose 
no luck still facing the same issue 
" Could not connect to your MCP server "

**Comment by daniel-marr** [comment]
Still can’t resolve also.

**Comment by tylers-username** [comment]
Inspired by N8Ns docs [**_Running the MCP Server Trigger node with a reverse proxy_**](https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-langchain.mcptrigger/#running-the-mcp-server-trigger-node-with-a-reverse-proxy), this is what I added to NGINX proxy manager, which could be slightly tweaked for any NGINX config:


```nginx.conf
# disable gzip and proxy buffering for both /mcp/ and /mcp-test/
location ~* ^/(?:mcp|mcp-test)/ {
    gzip                       off;
    proxy_buffering            off;
    chunked_transfer_encoding  off;

    # prevent upstream compression
    proxy_set_header           Connection "";
    proxy_set_header           Accept-Encoding "";

    # re‑declare NPM’s proxy headers using built‑in variables
    proxy_http_version         1.1;
    proxy_set_header           Host                 $host;
    proxy_set_header           X-Real-IP            $remote_addr;
    proxy_set_header           X-Forwarded-For      $proxy_add_x_forwarded_for;
    proxy_set_header           X-Forwarded-Proto    $scheme;

    # send to your upstream based on NPM’s variables
    proxy_pass                 $forward_scheme://$server:$port;
}
```

![Image](https://github.com/user-attachments/assets/e2ee1a0b-7753-4406-9f60-ab32c02873e7)

**Comment by jezweb** [comment]
Turning off gzip worked fine for me for this exact problem, thank you very much for explaining it

**Comment by Cisconardi** [comment]
Hello, if you still have this problem I might found a solution I shared on n8n forum: https://community.n8n.io/t/error-could-not-connect-to-your-mcp-server-when-integrating-external-tool-via-sse-in-ai-agent/100957/33

**Comment by salomaoparkour** [comment]
Hey guys, I'm running n8n in queue mode in a test setup. It's working quite well and MCP works fine too. Here's the config YAML file:

```
services:
  # This is the main n8n service that runs the UI and acts as the main instance.
  n8n:
    image: 'docker.n8n.io/n8nio/n8n:next'
    environment:
      - SERVICE_FQDN_N8N_5678
      - 'N8N_EDITOR_BASE_URL=${SERVICE_FQDN_N8N}'
      - 'WEBHOOK_URL=${SERVICE_FQDN_N8N}'
      - 'N8N_HOST=${SERVICE_URL_N8N}'
      - 'GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Berlin}'
      - 'TZ=${TZ:-Europe/Berlin}'
      - DB_TYPE=postgresdb
      - 'DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}'
      - DB_POSTGRESDB_HOST=postgresql
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=$SERVICE_USER_POSTGRES
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - EXECUTIONS_MODE=queue
      - N8N_ENCRYPTION_KEY=$N8N_ENCRYPTION_KEY
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - N8N_TRUST_PROXY=true
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
    volumes:
      - 'n8n-data:/home/node/.n8n'
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    # MCP routing & SSE-safe compression via Traefik
    labels:
      # Enable Traefik routing for this service
      - "traefik.enable=true"

      # Router: match only MCP requests on the same host, under /mcp path
      - "traefik.http.routers.n8n-mcp.rule=Host(`$SERVICE_URL_N8N`) && PathPrefix(`/mcp`)"
      # Priority: make sure MCP router is evaluated before the default n8n router
      - "traefik.http.routers.n8n-mcp.priority=100"
      # TLS: enforce HTTPS
      - "traefik.http.routers.n8n-mcp.tls=true"
      # Entrypoint: use the standard websecure entrypoint (443)
      - "traefik.http.routers.n8n-mcp.entrypoints=websecure"

      # Service: point the MCP router to the n8n container on port 5678
      - "traefik.http.routers.n8n-mcp.service=n8n-mcp"
      - "traefik.http.services.n8n-mcp.loadbalancer.server.port=5678"

      # Middleware: enable compression, but exclude SSE (Server-Sent Events) to avoid breaking MCP streams
      - "traefik.http.middlewares.n8n-mcp-compress.compress=true"
      - "traefik.http.middlewares.n8n-mcp-compress.compress.excludedcontenttypes=text/event-stream"

      # Middleware: add headers to prevent intermediaries from transforming event streams
      - "traefik.http.middlewares.n8n-mcp-headers.headers.customResponseHeaders.Cache-Control=no-transform"

      # Attach middlewares to the MCP router (order matters)
      - "traefik.http.routers.n8n-mcp.middlewares=n8n-mcp-compress@docker,n8n-mcp-headers@docker"
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/healthz'
      interval: 5s
      timeout: 20s
      retries: 10

  # Worker services for processing workflow executions. All workers are configured to handle any job type.
  worker1:
    image: 'docker.n8n.io/n8nio/n8n:next'
    command: worker --concurrency=5
    environment:
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: '${POSTGRES_DB:-n8n}'
      DB_POSTGRESDB_HOST: postgresql
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: $SERVICE_USER_POSTGRES
      DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_PASSWORD: $SERVICE_PASSWORD_POSTGRES
      EXECUTIONS_MODE: queue
      N8N_ENCRYPTION_KEY: $N8N_ENCRYPTION_KEY
      QUEUE_HEALTH_CHECK_ACTIVE: 'true'
      N8N_RUNNERS_ENABLED: 'true'
      N8N_RUNNERS_MODE: internal
      N8N_BLOCK_ENV_ACCESS_IN_NODE: 'false'
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker2:
    image: 'docker.n8n.io/n8nio/n8n:next'
    command: worker --concurrency=5
    environment:
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: '${POSTGRES_DB:-n8n}'
      DB_POSTGRESDB_HOST: postgresql
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: $SERVICE_USER_POSTGRES
      DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_PASSWORD: $SERVICE_PASSWORD_POSTGRES
      EXECUTIONS_MODE: queue
      N8N_ENCRYPTION_KEY: $N8N_ENCRYPTION_KEY
      QUEUE_HEALTH_CHECK_ACTIVE: 'true'
      N8N_RUNNERS_ENABLED: 'true'
      N8N_RUNNERS_MODE: internal
      N8N_BLOCK_ENV_ACCESS_IN_NODE: 'false'
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker3:
    image: 'docker.n8n.io/n8nio/n8n:next'
    command: worker --concurrency=5
    environment:
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: '${POSTGRES_DB:-n8n}'
      DB_POSTGRESDB_HOST: postgresql
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: $SERVICE_USER_POSTGRES
      DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_PASSWORD: $SERVICE_PASSWORD_POSTGRES
      EXECUTIONS_MODE: queue
      N8N_ENCRYPTION_KEY: $N8N_ENCRYPTION_KEY
      QUEUE_HEALTH_CHECK_ACTIVE: 'true'
      N8N_RUNNERS_ENABLED: 'true'
      N8N_RUNNERS_MODE: internal
      N8N_BLOCK_ENV_ACCESS_IN_NODE: 'false'
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # PostgreSQL database service.
  postgresql:
    image: 'postgres:16-alpine'
    volumes:
      - 'postgresql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - 'POSTGRES_DB=${POSTGRES_DB:-n8n}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10

  # Redis service for queue management.
  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  n8n-data:
  postgresql-data:
```
