### ISSUE TITLE
[Bug/Help]: All builds suddenly fail within a few seconds, nothing in the logs (even the ones that worked before)

### ISSUE THREAD

**Issue by hnykda** [coollabsio/coolify#5604]
### Error Message and Logs

Hey. I have been a happy user of coolify for the last 6 months. Unfortunately, today it just stopped building images for unknown reason, and I am lost where to look. I checked docker logs, coolify logs, UI logs, ... The build of containers works totally fine locally.

This is what I see in the UI (lightly anonymized):

```
2025-Apr-13 16:28:24.259867Starting deployment of Main deployment to localhost.
2025-Apr-13 16:28:24.463716Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:1.0.8.
2025-Apr-13 16:28:24.702475**[CMD]: docker inspect -f '{{.State.Running}}' n0kwsgcssc08sk4sko4wo08c**
2025-Apr-13 16:28:24.702475
2025-Apr-13 16:28:24.705147Error: No such object: n0kwsgcssc08sk4sko4wo08c
2025-Apr-13 16:28:24.817400**[CMD]: docker rm -f n0kwsgcssc08sk4sko4wo08c**
2025-Apr-13 16:28:24.817400Error response from daemon: No such container: n0kwsgcssc08sk4sko4wo08c
2025-Apr-13 16:28:25.016960**[CMD]: docker run -d --network coolify --name n0kwsgcssc08sk4sko4wo08c --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/coollabsio/coolify-helper:1.0.8**
2025-Apr-13 16:28:25.016960f64dff8b0e9a8a883e99e6972bca5564e5fd7819f4a77a1d87cb45803bfee8ac
2025-Apr-13 16:28:26.287274**[CMD]: docker exec n0kwsgcssc08sk4sko4wo08c bash -c 'GIT_SSH_COMMAND="ssh -o ConnectTimeout=30 -p 22 -o Port=22 -o LogLevel=ERROR -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git ls-remote https://x-access-token:[REDACTED]@github.com/[username]/[repo].git main'**
2025-Apr-13 16:28:26.28727471421d741c88d5b7ffb35839b66b2aad7380cca0 refs/heads/main
2025-Apr-13 16:28:26.497210----------------------------------------
2025-Apr-13 16:28:26.499903Importing [username]/[repo]:main (commit sha HEAD) to /artifacts/n0kwsgcssc08sk4sko4wo08c.
2025-Apr-13 16:28:26.668254**[CMD]: docker exec n0kwsgcssc08sk4sko4wo08c bash -c 'git clone -b "main" https://x-access-token:[REDACTED]@github.com/[username]/[repo].git /artifacts/n0kwsgcssc08sk4sko4wo08c && cd /artifacts/n0kwsgcssc08sk4sko4wo08c && GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git submodule update --init --recursive && cd /artifacts/n0kwsgcssc08sk4sko4wo08c && GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git lfs pull'**
2025-Apr-13 16:28:26.668254Cloning into '/artifacts/n0kwsgcssc08sk4sko4wo08c'...
2025-Apr-13 16:28:28.550927**[CMD]: docker exec n0kwsgcssc08sk4sko4wo08c bash -c 'cd /artifacts/n0kwsgcssc08sk4sko4wo08c && git log -1 71421d741c88d5b7ffb35839b66b2aad7380cca0 --pretty=%B'**
2025-Apr-13 16:28:28.550927Automate ingestion (#26)
2025-Apr-13 16:28:31.093700Gracefully shutting down build container: n0kwsgcssc08sk4sko4wo08c
2025-Apr-13 16:28:31.208978**[CMD]: docker inspect -f '{{.State.Running}}' n0kwsgcssc08sk4sko4wo08c**
2025-Apr-13 16:28:31.208978true
2025-Apr-13 16:28:31.896472**[CMD]: docker rm -f n0kwsgcssc08sk4sko4wo08c**
2025-Apr-13 16:28:31.896472n0kwsgcssc08sk4sko4wo08c
```

and the build just shows as Failed. It now does it for rollbacks and older builds as well. I tried restarting the whole machine, processes, checked for free resources (all good), nothing... The builds that worked before would continue with a line `2025-Apr-11 08:02:58.119855 Pulling & building required images.`, but that is not happening now, just dead silence.

My (lightly anonymized) docker compose also doesn't have anything weird in it (the build process doesn't seem to even get there):

```
services:
  service-A:
    build:
      context: service-a-dir
      dockerfile: Dockerfile
    environment:
      # Environment variables removed
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'node -e "http.get(\"http://0.0.0.0:3000\", res => res.statusCode < 400 ? process.exit(0) : process.exit(1)).on(\"error\", err => process.exit(1))" || exit 1',
        ]
      interval: 30s
      timeout: 3s
      retries: 2
      start_period: 2s
      start_interval: 1s
    expose:
      - "3000"

  service-B:
    build:
      context: service-b-dir
      dockerfile: Dockerfile
      target: service-b
    environment:
      # Environment variables removed
    expose:
      - "8000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python3 -c "import urllib.request; urllib.request.urlopen(''http://0.0.0.0:8000/health'').getcode() == 200 or exit(1)"',
        ]
      interval: 30s
      timeout: 3s
      retries: 2
      start_period: 2s
      start_interval: 1s

  service-C:
    build:
      context: service-b-dir
      dockerfile: Dockerfile
      target: service-c
    environment:
      # Environment variables removed
    depends_on:
      - service-D

  service-D:
    restart: always
    image: vendor/service-d:3.2.15-python3.12
    environment:
      # Environment variables removed
    labels:
      - "traefik.http.middlewares.basic-auth-chain.chain.middlewares=gzip,basic-auth@file"
      - "traefik.http.routers.https-0-v0sswsk04kgs4swscwwgo4ow-service-d.middlewares=basic-auth-chain"
    command: service-d server start --host 0.0.0.0
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python3 -c "import urllib.request; urllib.request.urlopen(''http://0.0.0.0:4200'').getcode() == 200 or exit(1)"',
        ]
      interval: 30s
      timeout: 3s
      retries: 2
    expose:
      - "4200"
    volumes:
      - service-d-data:/data
    depends_on:
      - service-E

  service-E:
    image: vendor/database:pg17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 0s
      start_interval: 1s
    restart: always
    expose:
      - "5432"
    shm_size: 1gb
    environment:
      # Environment variables removed
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql

  service-F:
    image: nginx:alpine
    ports:
      - "49831:49831"
    depends_on:
      - service-E
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf

  service-G:
    image: vendor/admin-panel:latest
    restart: always
    expose:
      - "80"
    environment:
      # Environment variables removed
    volumes:
      - "service-g-data:/var/lib/data"

  service-H:
    image: vendor/tool:latest
    expose:
      - "3000"
    labels:
      - "traefik.http.middlewares.basic-auth-chain.chain.middlewares=gzip,basic-auth@file"
      - "traefik.http.routers.https-0-v0sswsk04kgs4swscwwgo4ow-service-h.middlewares=basic-auth-chain"

volumes:
  database_data:
  service-d-data:
  service-g-data:
```

### Steps to Reproduce

(that's gonna be hard, sorry)

### Coolify Version

v4.0.0-beta.407

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Fedora 40

### Additional Information

I would be grateful for even advices where to look at!
