### ISSUE TITLE
[Bug]: "env_files" getting overwritten - requiring different environment files

### ISSUE THREAD

**Issue by creazy231** [coollabsio/coolify#5612]
### Problem Description
I've been attempting to deploy [R2R](https://github.com/SciPhi-AI/R2R) using Coolify (via public repo/docker compose) without success after many hours of troubleshooting.

I'm using the [docker compose file](https://github.com/SciPhi-AI/R2R/blob/main/docker/compose.full.yaml) which requires different .env files for different services.

The core issue is that R2R requires two separate postgres services with different environment variables defined in the [env folder](https://github.com/SciPhi-AI/R2R/tree/main/docker/env). These are attached to each service using the `env_file:` directive in the compose.yml.

However, Coolify takes these variables, puts them into the Environment Variables tab, and replaces the custom `env_file` paths with its own .env file. This approach fails when dealing with two postgres databases that use the same environment variable names.

### Questions
- Is there a workaround for this scenario?
- Will Coolify support an array of `env_file` directives in compose.yml and extend its own .env file when one already exists?

My team would greatly appreciate any assistance with this issue.

### Steps to Reproduce

1. Public Repository
2. https://github.com/SciPhi-AI/R2R
3. Base Directory `/docker` & Build Pack `Docker Compose` (`compose.full.yaml`)
4. Deploy

### Example Repository URL

https://github.com/SciPhi-AI/R2R/tree/main/docker

### Coolify Version

v4.0.0-beta.407

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04.4 LTS

**Comment by djsisson** [comment]
@creazy231 coolify does not support multiple env files, as a workaround you would do this instead:

```yaml
services:
  postgres-one:
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRESONE}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESONE}
  postgres-two:
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRESTWO}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESTWO}
 ```

the resulting env file would have 4 different entries for you, ensuring each seperate service gets its own unique value
