### ISSUE TITLE
[Bug]: Appwrite function URLs not reachable?

### ISSUE THREAD

**Issue by ktufekcic** [coollabsio/coolify#5630]
### Error Message and Logs

no available server

### Steps to Reproduce

1. Deploy Appwrite
2. Create a function
3. Try to call the function URL

### Coolify Version

v4.0.0-beta.408

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04 arm64

### Additional Information

This might be an issue on my end with DNS records or something, but I've tried everything I can think of in terms of DNS records and I'm still seeing this issue.

I've checked these out:
https://github.com/coollabsio/coolify/issues/2089
And the PR linking to some additional info: https://github.com/coollabsio/coolify/pull/4226

But this didn't seem to fix my problem.
I disabled strip prefixes for the relevant services, this allowed me to access Appwrite, I tried adding APP_FUNCTIONS_RUNTIMES_NETWORK and setting it's value to the service name (the generated ID), I tried using different values foor APP_DOMAIN_FUNCTIONS, this also didn't help any.

For some additional context, if it matters, my domain is example.com, appwrite is on appwrite.example.com, and functions are on <project ID generated by appwrite>.appwrite.example.com

I have a wildcard DNS record for *.example.com, and I tried setting an A record for *.appwrite.example.com, this didn't work, and I also tried, as Appwrite docs suggest, to set a CNAME record for *.appwrite.example.com to point to appwrite.example.com, but this didn't do anything either, so I'm pretty stumped right now, any help is appreciated

**Comment by djsisson** [comment]
@ktufekcic 
create a dynamic file for the proxy, to foward all chosen subdomains to the appwrite container:

```yaml
http:
  routers:
    appwrite-functions:
      entryPoints:
        - http
        - https
      service: appwrite-functions
      rule: HostRegexp(`^.+\.appwrite\.example\.com$`)
      tls: {}
  services:
    appwrite-functions:
      loadBalancer:
        servers:
          - url: "http://appwrite:80"
  ```
next you need to make sure you have setup dns challenge in your proxy or added a wildcard origin certificate for the above subdomains, as they will not be generated automatically

lastly, please note if youre using cloudflare  you can't use 2nd level subdomains unless you pay

**Comment by AndreaDev237** [comment]
Hi, 
I've exactly the same problem, i've followed the solution with the Dynamic file in traefik proxy inside coolify without any success.
It's a very annoyingly problem 😅
Someone has a solution about this? 
Thanks

**Comment by djsisson** [comment]
@AndreaDev237 what error do you see?

**Comment by AndreaDev237** [comment]
Hi @djsisson thanks for your time to reply! :) 

I still se the 404 not found error, this is the configuration i've added in the dynamic configuration (file called AppwriteFunctions.yaml) 

in the server proxy section:


```YAML
http:
  routers:
    appwrite-functions:
      entryPoints:
        - http
        - https
      service: appwrite-functions
      rule: HostRegexp(`^.+\.bk\.coolify\.kzubersport\.com$`)
      tls: {  }
  services:
    appwrite-functions:
      loadBalancer:
        servers:
          -
            url: 'http://appwrite-ks4gsgss4oogs4g4oc44ss00:80'

```


I've also created a DNS A record for main domain (bk.coolify.kzubersport.com) and a CNAME for *.bk.coolify.kzubersport.com 

The only thing i've still not modified is the traefik base configuration to use my DNS provider to setup the Let's Encrypt certificate generation. 

This only work if i add the domain of the function inside the domains section in the service but i find this solution not optimal because i don't know how many function i will need in the future. (and even if add domain in this way works there are still problems :( )

Thanks again!
