### ISSUE TITLE
[Bug]: Non-string key in volumes when using both nfs mounts and persistent storage bind mounts

### ISSUE THREAD

**Issue by tkodev** [coollabsio/coolify#5632]
### Error Message and Logs

```
services:
  test:
    ...
    volumes:
      - 'test_cache:/cache'
      - 'test_stores:/stores'
      - 'test_backups:/backups'
      - './configs/config.yml:/config.yml'
      - '/etc/localtime:/etc/localtime:ro'
    ...

volumes:
  test_cache:
    driver: 'local'
  test_stores:
    driver_opts:
      type: 'nfs'
      o: 'addr=192.168.68.61,rw,noatime,timeo=30,retry=3,nfsvers=4'
      device: ':/mnt/atlas/volumes/test/stores'
  test_backups:
    driver_opts:
      type: 'nfs'
      o: 'addr=192.168.68.61,rw,noatime,timeo=30,retry=3,nfsvers=4'
      device: ':/mnt/atlas/volumes/test/backups'
```

the volume properties gets turned into 

```
  ...
  volumes:
    0: 'g0ccw0gowo8484cgwow8kosg_test-cache:/cache'
    3: '/data/coolify/applications/g0ccw0gowo8484cgwow8kosg/configs/config.yml:/config.yml'
    4: '/etc/localtime:/etc/localtime'
  ...
```

The NFS mounts are gone and the array is turned into a string delimited object. **This doesn't happen if ONLY nfs mounts are present or ONLY persistent mounts are present.** Only when both are present

This obviously results in an error when deploying

```
Oops something is not okay, are you okay? 😢
Non-string key in services.test.volumes: 0
exit status 1
```

### Steps to Reproduce

1. Create a docker compose with both persistent bind mounts and nfs mounts
2. Add this from a git repo (possibly optional)
3. Reload docker compose
4. Inspect transformed docker compose output

### Coolify Version

v4.0.0-beta.409

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12 (bookworm)

### Additional Information

Appears to be some kind of merge issue, or type mismatch
