### ISSUE TITLE
[Bug]: Are NFS volumes supported?

### ISSUE THREAD

**Issue by sardaukar** [coollabsio/coolify#5675]
### Error Message and Logs

This is my compose file for Forgejo:

```yaml
services:
  forgejo:
    image: 'codeberg.org/forgejo/forgejo:10.0.1'
    environment:
      - SERVICE_FQDN_FORGEJO_3000
      - 'FORGEJO__server__ROOT_URL=${SERVICE_FQDN_FORGEJO_3000}'
      - 'FORGEJO__migrations__ALLOWED_DOMAINS=${FORGEJO__migrations__ALLOWED_DOMAINS}'
      - 'FORGEJO__migrations__ALLOW_LOCALNETWORKS=${FORGEJO__migrations__ALLOW_LOCALNETWORKS-false}'
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=postgresql
      - 'FORGEJO__database__NAME=${POSTGRESQL_DATABASE-forgejo}'
      - FORGEJO__database__USER=$SERVICE_USER_POSTGRESQL
      - FORGEJO__database__PASSWD=$SERVICE_PASSWORD_POSTGRESQL
    volumes:
      - '/mnt/nfs/docker_data/forgejo/gitea:/data'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '10022:22'
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:3000'
      interval: 2s
      timeout: 10s
      retries: 15
  postgresql:
    image: 'postgres:14.5'
    volumes:
      - '/mnt/nfs/docker_data/forgejo/postgres:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRESQL}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}'
      - 'POSTGRES_DB=${POSTGRESQL_DATABASE}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
```

I bind-mount to folders on a mounted NFS share folder, but I'd like to use NFS directly in the volumes, so I tweaked it to:

```yaml
services:
  forgejo:
    image: 'codeberg.org/forgejo/forgejo:10.0.1'
    environment:
      - SERVICE_FQDN_FORGEJO_3000
      - 'FORGEJO__server__ROOT_URL=${SERVICE_FQDN_FORGEJO_3000}'
      - 'FORGEJO__migrations__ALLOWED_DOMAINS=${FORGEJO__migrations__ALLOWED_DOMAINS}'
      - 'FORGEJO__migrations__ALLOW_LOCALNETWORKS=${FORGEJO__migrations__ALLOW_LOCALNETWORKS-false}'
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=postgresql
      - 'FORGEJO__database__NAME=${POSTGRESQL_DATABASE-forgejo}'
      - FORGEJO__database__USER=$SERVICE_USER_POSTGRESQL
      - FORGEJO__database__PASSWD=$SERVICE_PASSWORD_POSTGRESQL
    volumes:
      - forgejo_data:/data
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '10022:22'
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:3000'
      interval: 2s
      timeout: 10s
      retries: 15
  postgresql:
    image: 'postgres:14.5'
    volumes:
      - forgejo_db_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRESQL}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}'
      - 'POSTGRES_DB=${POSTGRESQL_DATABASE}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  forgejo_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.11,rw,nfsvers=4"
      device: ":/volume1/nfs_root/docker_data/forgejo/gitea"
  forgejo_db_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.11,rw,nfsvers=4"
      device: ":/volume1/nfs_root/docker_data/forgejo/postgres"
```

Which validates fine, but then when clicking the "Show Deployable Compose" the volumes are set to `1.` and `2.` in the yaml, which makes the deployment fail because the numbers aren't valid keys.

Is this supported?

### Steps to Reproduce

1. Add new service
2. Use empty compose
3. Paste my first compose yaml (change to valid bind mount folders)
4. Deploy, works
5. Tweak the compose to the second yaml I posted, with NFS volumes
6. Deployment fails due to `non-string key`

### Coolify Version

v4.0.0-beta.409

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian 12 on Intel Mac Mini (T2 kernel)

**Comment by blockloop** [comment]
I believe this is related:

```yaml
volumes:
  - '/mnt/volume:/mnt/volume:rshared'
```

The propagation is stripped entirely leaving only `'/mnt/volume:/mnt/volume'`


The same happens with the explicit definition:

```yaml
    volumes:
      - type: bind
        source: /mnt/volume
        target: /mnt/volume
        bind:
          propagation: rshared
```

is stripped and turned into `'/mnt/volume:/mnt/volume'`
