### ISSUE TITLE
[Bug]: Coolify magic environment variables are not applied in traefik config

### ISSUE THREAD

**Issue by janwiebe-jump** [coollabsio/coolify#5686]
### Error Message and Logs

The release notes of v4.0.0-beta.411 say that magic env's should work with git based deployments.
I see the variables created in the environments view, but the FQDN is not applied to traefik.

![Image](https://github.com/user-attachments/assets/7e2aa56c-1abe-4fd3-a36e-942997818e4d)

```
services:
  backend:
    build:
      # coolify context is from the root directory of the repo
      context: ./src/backend
    container_name: backend
    environment:
      - SERVICE_FQDN_BACKEND
      - SERVICE_FQDN_BACKEND_80
      - SERVICE_URL_BACKEND      
      - Cors__AllowedOrigins=http://$SERVICE_URL_FRONTEND      
    # ports:
    #   - "8000:80"  # change as needed
    restart: unless-stopped

  frontend:
    build:
      # coolify context is from the root directory of the repo
      context: ./src/frontend
    container_name: frontend
    environment:
      - SERVICE_FQDN_FRONTEND
      - SERVICE_FQDN_FRONTEND_3000
      - SERVICE_URL_FRONTEND
      - NEXT_PUBLIC_API_URL=http://$SERVICE_URL_BACKEND
    # ports:
    #   - "8001:3000"  # adjust as necessary
    restart: unless-stopped
```

I use this, because the frontend needs to know the backend url for the NEXT_PUIBLIC_API_URL and the backend needs the frontend url for the CORS settings.

However, when I inspect the generated labels in the docker container, the FQDN for frontend and backend is not applied to the traefik labels, so I cannot access the service via its generated domain.

Env and labels of the frontend container:
```
"Env": [
	"Cors__AllowedOrigins=frontend-ac4k4ggwsowsc0804oo0s444.127.0.0.1.sslip.io",
	"COOLIFY_RESOURCE_UUID=ac4k4ggwsowsc0804oo0s444",
	"NEXT_PUBLIC_API_URL=http://backend-ac4k4ggwsowsc0804oo0s444.127.0.0.1.sslip.io",
	"COOLIFY_BRANCH=\"feature/deploy-local\"",
	"COOLIFY_FQDN=mission.127.0.0.1.sslip.io",
	"SERVICE_FQDN_BACKEND=http://ac4k4ggwsowsc0804oo0s444.127.0.0.1.sslip.io",
	"COOLIFY_CONTAINER_NAME=frontend-ac4k4ggwsowsc0804oo0s444-084504543900",
	"SERVICE_URL_FRONTEND=frontend-ac4k4ggwsowsc0804oo0s444.127.0.0.1.sslip.io",
	"FRONTEND_URL=http://mission.127.0.0.1.sslip.io",
	"SERVICE_URL_BACKEND=backend-ac4k4ggwsowsc0804oo0s444.127.0.0.1.sslip.io",
	"SOURCE_COMMIT=08197dd9d37045d9f78a2561a6dd713aa13fd7cb",
	"SERVICE_FQDN_FRONTEND=http://ac4k4ggwsowsc0804oo0s444.127.0.0.1.sslip.io",
	"HOST=0.0.0.0",			
	"COOLIFY_URL=http://mission.127.0.0.1.sslip.io",			
	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
	"NODE_VERSION=18.20.8",
	"YARN_VERSION=1.22.22",
	"NODE_ENV=production",
	"NEXT_TELEMETRY_DISABLED=1",
	"PORT=3000",
	"HOSTNAME=0.0.0.0"
],

"Labels": {
	"caddy_0": "http://mission.127.0.0.1.sslip.io",
	"caddy_0.encode": "zstd gzip",
	"caddy_0.handle_path": "/*",
	"caddy_0.handle_path.0_reverse_proxy": "{{upstreams}}",
	"caddy_0.header": "-Server",
	"caddy_0.try_files": "{path} /index.html /index.php",
	"caddy_ingress_network": "ac4k4ggwsowsc0804oo0s444",
	"com.docker.compose.config-hash": "cfe77ffe3c5cb369386ef27fa5fb3b98e71717c1216a92c42d95b82b656f1b9b",
	"com.docker.compose.container-number": "1",
	"com.docker.compose.depends_on": "",
	"com.docker.compose.image": "sha256:d3c60be6d0a1fa9745d7c945e1a22c3b6523db87561e597dbcde477e6ca8677f",
	"com.docker.compose.oneoff": "False",
	"com.docker.compose.project": "ac4k4ggwsowsc0804oo0s444",
	"com.docker.compose.project.config_files": "/artifacts/n8o000ksk448ws4c48sg8c0g/build/docker-compose.coolify.yml",
	"com.docker.compose.project.environment_file": "/artifacts/n8o000ksk448ws4c48sg8c0g/.env",
	"com.docker.compose.project.working_dir": "/artifacts/n8o000ksk448ws4c48sg8c0g",
	"com.docker.compose.service": "frontend",
	"com.docker.compose.version": "2.34.0",
	"coolify.applicationId": "4",
	"coolify.environmentName": "production",
	"coolify.managed": "true",
	"coolify.name": "frontend-ac4k4ggwsowsc0804oo0s444-084504543900",
	"coolify.projectName": "dataf",
	"coolify.pullRequestId": "0",
	"coolify.resourceName": "mission-coolify",
	"coolify.serviceName": "mission-coolify",
	"coolify.type": "application",
	"coolify.version": "4.0.0-beta.412",
	"traefik.enable": "true",
	"traefik.http.middlewares.gzip.compress": "true",
	"traefik.http.middlewares.redirect-to-https.redirectscheme.scheme": "https",
	"traefik.http.routers.http-0-ac4k4ggwsowsc0804oo0s444-frontend.entryPoints": "http",
	"traefik.http.routers.http-0-ac4k4ggwsowsc0804oo0s444-frontend.middlewares": "gzip",
	"traefik.http.routers.http-0-ac4k4ggwsowsc0804oo0s444-frontend.rule": "Host(`mission.127.0.0.1.sslip.io`) && PathPrefix(`/`)"
}

```

Besides that, de SERVICE_FQDN_BACKEND does not generate a service specific FQDN, like http://backend-[domain], but only http://[domain]

So defining SERVICE_FQDN_BACKEND in service backend, and SERVICE_FQDN_FRONTEND in the service frontend results in the same url.

The URL type of the magic env, results in a service specific URL.
However, this is not actually an url, since it does not contain the scheme.

I would expect the FQDN to be not an url (hence 'domain name'), but it contains the scheme.

### Steps to Reproduce

1. Create a git based deployment with 2 services, that reference each other (e.g. react frontend service and api service)
2.
3.
4.

### Coolify Version

v4.0.0-beta.412

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Mac os x

**Comment by Cinzya** [comment]
You can only have 1 FQDN per service. You are defining two at the moment. E.g. here for your backend:
```yaml
- SERVICE_FQDN_BACKEND
- SERVICE_FQDN_BACKEND_80
```
If your backend runs on port 80, then you only need to keep the second env variable with the defined port.

You also don't need to define the `SERVICE_URL` in a seperate line again for Coolify to generate it.

So I would recommend you change your environment variables to the following:
```yaml
services:
  backend:
    ...
    environment:
      - SERVICE_FQDN_BACKEND_80   
      - Cors__AllowedOrigins=http://$SERVICE_URL_FRONTEND      
    ...

  frontend:
    ...
    environment:
      - SERVICE_FQDN_FRONTEND_3000
      - NEXT_PUBLIC_API_URL=http://$SERVICE_URL_BACKEND
```

Not 100% sure if that fixes the problem though, as I don't have a compose project by hand to test this against it. If you could provide a reproducable example repository I could take a deeper look into it.
