### ISSUE TITLE
[Bug]: Pretended as DB once the image name contains mysql

### ISSUE THREAD

**Issue by mucan54** [coollabsio/coolify#5724]
### Error Message and Logs

I'm trying to use this zabbix/zabbix-web-apache-mysql docker image, but once I try to deploy it in my yml file, coolify pretends it as Db. So I'm not able to assign domain and reach it on frontend.

### Steps to Reproduce

1.
2.
3.
4.

### Coolify Version

v4.0.0-beta.414

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS (Noble Numbat)

**Comment by andrasbacsai** [comment]
I guess this is a docker-compose based application, right?

**Comment by andrasbacsai** [comment]
I added a small feature that enables to manually convert between db/apps in docker-compose based resources.

**Comment by mucan54** [comment]
All ports are not listed, and also once I try to make a port public for my container I receive this error "Unsupported database type: standalone-zabbix/zabbix-web-apache-mysql"

<img width="1284" alt="Image" src="https://github.com/user-attachments/assets/2ebc9566-09c8-4d64-8dde-31b40c88b4e6" />

<img width="1289" alt="Image" src="https://github.com/user-attachments/assets/bfa4af3f-eee1-4621-b030-8957ced4a6ec" />

<img width="945" alt="Image" src="https://github.com/user-attachments/assets/4512ddc0-c630-4117-93d4-e6136f672103" />


```
version: '3.8'

networks:
  network-zabbix:
    driver: bridge
    name: network-zabbix

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    networks:
      - network-zabbix
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=carryontech
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --log-bin-trust-function-creators=1
    restart: unless-stopped
    stop_grace_period: 1m 

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-7.0-latest
    restart: always
    networks:
      - network-zabbix
    ports:
      #- '10050:10050'
      - '10051:10051'
    volumes:
      - alertscripts:/usr/lib/zabbix/alertscripts
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
      - ZBX_ENABLE_VMWARECOLLECTORS=true
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      mysql:
        condition: service_started
    healthcheck:
      test: ["CMD", "pidof", "zabbix_server"]
      interval: 30s
      timeout: 5s
      retries: 3

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-7.0-latest
    networks:
      - network-zabbix
    restart: always
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=carryontech
      - PHP_TZ=America/Sao_Paulo
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - mysql
      - zabbix-server

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    networks:
      - network-zabbix
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - zabbix-server

volumes:
  mysql:
  alertscripts:
  grafana-data:

```

**Comment by mucan54** [comment]
I have converted it to Application 

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/39526a44-47f2-4032-8e3a-2cc2fe1c1bbc" />

But it still labeled as database, and also I'm not able to reach it
```
services:
  mysql:
    container_name: mysql-ccwoc4g0sc8w8w0s0wwk8gkg
    image: 'mysql:8.0'
    networks:
      network-zabbix: null
      ccwoc4g0sc8w8w0s0wwk8gkg: null
    volumes:
      - 'ccwoc4g0sc8w8w0s0wwk8gkg_mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: carryontech
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: carryontech
      COOLIFY_RESOURCE_UUID: ccwoc4g0sc8w8w0s0wwk8gkg
      COOLIFY_CONTAINER_NAME: mysql-ccwoc4g0sc8w8w0s0wwk8gkg
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_bin'
      - '--log-bin-trust-function-creators=1'
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.416
      - coolify.serviceId=51
      - coolify.type=service
      - coolify.name=mysql-ccwoc4g0sc8w8w0s0wwk8gkg
      - coolify.resourceName=zabbix-services-asd
      - coolify.projectName=monitor
      - coolify.serviceName=mysql
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - coolify.service.subId=56
      - coolify.service.subType=database
      - coolify.service.subName=mysql
  zabbix-server:
    container_name: zabbix-server-ccwoc4g0sc8w8w0s0wwk8gkg
    image: 'zabbix/zabbix-server-mysql:ubuntu-7.0-latest'
    restart: always
    networks:
      network-zabbix: null
      ccwoc4g0sc8w8w0s0wwk8gkg: null
    ports:
      - '10051:10051'
    volumes:
      - 'ccwoc4g0sc8w8w0s0wwk8gkg_alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: carryontech
      ZBX_ENABLE_VMWARECOLLECTORS: 'true'
      COOLIFY_RESOURCE_UUID: ccwoc4g0sc8w8w0s0wwk8gkg
      COOLIFY_CONTAINER_NAME: zabbix-server-ccwoc4g0sc8w8w0s0wwk8gkg
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      mysql:
        condition: service_started
    healthcheck:
      test:
        - CMD
        - pidof
        - zabbix_server
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.416
      - coolify.serviceId=51
      - coolify.type=service
      - coolify.name=zabbix-server-ccwoc4g0sc8w8w0s0wwk8gkg
      - coolify.resourceName=zabbix-services-asd
      - coolify.projectName=monitor
      - coolify.serviceName=zabbix-server
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - coolify.service.subId=58
      - coolify.service.subType=database
      - coolify.service.subName=zabbix-server
  zabbix-frontend:
    container_name: zabbix-frontend-ccwoc4g0sc8w8w0s0wwk8gkg
    image: 'zabbix/zabbix-web-apache-mysql:ubuntu-7.0-latest'
    networks:
      network-zabbix: null
      ccwoc4g0sc8w8w0s0wwk8gkg: null
    restart: always
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: carryontech
      PHP_TZ: America/Sao_Paulo
      ZBX_SERVER_HOST: zabbix-server
      COOLIFY_RESOURCE_UUID: ccwoc4g0sc8w8w0s0wwk8gkg
      COOLIFY_CONTAINER_NAME: zabbix-frontend-ccwoc4g0sc8w8w0s0wwk8gkg
    depends_on:
      - mysql
      - zabbix-server
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.416
      - coolify.serviceId=51
      - coolify.type=service
      - coolify.name=zabbix-frontend-ccwoc4g0sc8w8w0s0wwk8gkg
      - coolify.resourceName=zabbix-services-asd
      - coolify.projectName=monitor
      - coolify.serviceName=zabbix-frontend
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - coolify.service.subId=109
      - coolify.service.subType=database
      - coolify.service.subName=zabbix-frontend
  grafana:
    container_name: grafana-ccwoc4g0sc8w8w0s0wwk8gkg
    image: 'grafana/grafana-oss:latest'
    networks:
      network-zabbix: null
      ccwoc4g0sc8w8w0s0wwk8gkg: null
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - 'ccwoc4g0sc8w8w0s0wwk8gkg_grafana-data:/var/lib/grafana'
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
      COOLIFY_RESOURCE_UUID: ccwoc4g0sc8w8w0s0wwk8gkg
      COOLIFY_CONTAINER_NAME: grafana-ccwoc4g0sc8w8w0s0wwk8gkg
    depends_on:
      - zabbix-server
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.416
      - coolify.serviceId=51
      - coolify.type=service
      - coolify.name=grafana-ccwoc4g0sc8w8w0s0wwk8gkg
      - coolify.resourceName=zabbix-services-asd
      - coolify.projectName=monitor
      - coolify.serviceName=grafana
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - coolify.service.subId=100
      - coolify.service.subType=application
      - coolify.service.subName=grafana
volumes:
  ccwoc4g0sc8w8w0s0wwk8gkg_mysql:
    name: ccwoc4g0sc8w8w0s0wwk8gkg_mysql
  ccwoc4g0sc8w8w0s0wwk8gkg_alertscripts:
    name: ccwoc4g0sc8w8w0s0wwk8gkg_alertscripts
  ccwoc4g0sc8w8w0s0wwk8gkg_grafana-data:
    name: ccwoc4g0sc8w8w0s0wwk8gkg_grafana-data
networks:
  network-zabbix:
    driver: bridge
    name: network-zabbix
  ccwoc4g0sc8w8w0s0wwk8gkg:
    name: ccwoc4g0sc8w8w0s0wwk8gkg
    external: true
configs: {  }
secrets: {  }
```

<img width="1235" alt="Image" src="https://github.com/user-attachments/assets/4af104ac-a03a-49a3-adce-e6f050c19168" />
<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/5bb790b6-72a5-4a30-a14f-6826754a8c19" />
