### ISSUE TITLE
[Bug]: Can't connect to supabase-kong via IPv6 from internal Coolify Network

### ISSUE THREAD

**Issue by luishugoooo** [coollabsio/coolify#5780]
### Error Message and Logs

When trying to connect to `http://supabase-kong-<uuid>:8000` from the the internal Network, it only accepts IPv4 connections. Otherwise you get errors like this (Node):
```
TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handle (file:///app/build/server/chunks/hooks.server-DuEzhg_p.js:13:18)
    at async respond (file:///app/build/server/index.js:4004:22)
    at async Array.ssr (file:///app/build/handler.js:1284:3) {
  cause: Error: connect ECONNREFUSED fd01:7833:f9ef::2:8000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: 'fd01:7833:f9ef::2',
    port: 8000
  }
}
```

I noticed this with Node, since it does not have a proper IPv4-Fallback strategy.

### Steps to Reproduce

1. Deploy a Supabase Instance
2. Connect it to the predefined Network
3. Try to access it over IPv6 via the internal Network (`curl -6 http://supabase-kong-<uuid>:8000`)

### Coolify Version

V4.0.0-beta.416

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian 12

### Additional Information

How to fix: 
add the following line to the docker-compose of supabase:
`- KONG_PROXY_LISTEN=0.0.0.0:8000, [::]:8000`

in the environment section for kong, so it looks like this:

```
supabase-kong:
    image: 'kong:2.8.1'
    entrypoint: 'bash -c ''eval "echo \"$$(cat ~/temp.yml)\"" > ~/kong.yml && /docker-entrypoint.sh kong docker-start'''
    depends_on:
      supabase-analytics:
        condition: service_healthy
    environment:
      - SERVICE_FQDN_SUPABASEKONG_8000
      - 'KONG_PORT_MAPS=443:8000'
      - 'JWT_SECRET=${SERVICE_PASSWORD_JWT}'
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/home/kong/kong.yml
      - 'KONG_DNS_ORDER=LAST,A,CNAME'
      - 'KONG_PLUGINS=request-transformer,cors,key-auth,acl,basic-auth'
      - KONG_NGINX_PROXY_PROXY_BUFFER_SIZE=160k
      - 'KONG_NGINX_PROXY_PROXY_BUFFERS=64 160k'
      - 'SUPABASE_ANON_KEY=${SERVICE_SUPABASEANON_KEY}'
      - 'SUPABASE_SERVICE_KEY=${SERVICE_SUPABASESERVICE_KEY}'
      - 'DASHBOARD_USERNAME=${SERVICE_USER_ADMIN}'
      - 'DASHBOARD_PASSWORD=${SERVICE_PASSWORD_ADMIN}'
      - KONG_PROXY_LISTEN=0.0.0.0:8000, [::]:8000
    volumes:
...
```
