### ISSUE TITLE
[Bug]: Git + docker-compose + docker build is using old Dockerfile, but build has latest code

### ISSUE THREAD

**Issue by christopherpickering** [coollabsio/coolify#5791]
### Error Message and Logs

Hi,
I have git + docker-compose, which specifies a dockerfile:
```yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
```

I can click "Reload Compose File" to pick up changes in the compose file, but it never updates the dockerfile that is used for building.

### Steps to Reproduce

1. create a docker compose, something like this, in a git repo + dockerfile
```yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
```

2. run a failing build
3. update the dockerfile with a correction
4. new dockerfile is not used, even after clicking "reload compose file"

The new dockerfile does show in the code/latest code is pulled for the build.

### Coolify Version

v4.0.0-beta.416

### Are you using Coolify Cloud?

No (self-hosted)
