### ISSUE TITLE
[Bug]: Open Preview URL in GH bot post for Preview Deployments with multiple services

### ISSUE THREAD

**Issue by ton77v** [coollabsio/coolify#5804]
### Error Message and Logs

Consider the following docker-compose:
```
services:
  customer_portal:
    build:
      context: ..
      dockerfile: Dockerfile
   # ...

# ...

  listmonk:
    image: listmonk/listmonk:latest
    # ...
```

Configuration/General/Domains as expected list them in the same order:
Domains:
  Domains for Customer Portal
  ...
  Domains for Listmonk

While when the Preview Deployment is finished, the bot posts the following:

The preview deployment is ready. 🟢

Open Preview | Open Build Logs
^^^^^^^^^ this is a link to the Listmonk suddenly

Ideally there could be another select in Configuration/General after the domains to choose the one that will appear there. 

Or at least make it obvious how this URL works. And IMO it makes much more sense to use either
- the first service with domain
- the first service with build & domain

### Steps to Reproduce

1. Add a stack with several services
2. Add several domains
3. Enable Preview Deployments
4. Create PR
5. Check the bot post

### Coolify Version

v4.0.0-beta.416

### Are you using Coolify Cloud?

Yes (Coolify Cloud)
