### ISSUE TITLE
[Bug]: Firefly installation failed

### ISSUE THREAD

**Issue by anandbhaskaran** [coollabsio/coolify#5847]
### Error Message and Logs

**Docker file:** templates/compose/firefly.yaml
**Failing container:** Cron
**Error:**
```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/entrypoint.sh": permission denied: unknown
```

**Solution**

```yaml
cron:
  image: alpine
  command: ["/bin/sh", "-c", "chmod +x /entrypoint.sh && /entrypoint.sh"]
  volumes:
    - type: bind
      source: ./entrypoint.sh
      target: /entrypoint.sh
      content: |
        #!/bin/sh
        # Substitute the environment variable into the cron command
        CRON_COMMAND="0 3 * ** wget -qO- http://firefly:8080/api/v1/cron/${STATIC_CRON_TOKEN}"
        # Add the cron command to the crontab
        echo "$CRON_COMMAND" | crontab -
        # Start the cron daemon in the foreground with logging to stdout
        crond -f -L /dev/stdout
  environment:
    - STATIC_CRON_TOKEN=$SERVICE_BASE64_CRONTOKEN
```

### Steps to Reproduce

1.
2.
3.
4.

### Coolify Version

v4.0.0-beta.418

### Are you using Coolify Cloud?

No (self-hosted)

### Additional Information

The proposed fix solved the issue
