### ISSUE TITLE
[Bug]: Cannot restart proxy

### ISSUE THREAD

**Issue by Signum** [coollabsio/coolify#5856]
### Error Message and Logs

In version 4.0.0beta-418 I cannot restart the proxy any more. The proxy configuration screen shows two buttons labelled "Stop Proxy":

![Image](https://github.com/user-attachments/assets/383a1adf-b13d-4af4-860c-9fc21e1b560a)

When reloading this screen, the left button briefly turns into "Reload Proxy" but quickly turns into "Stop Proxy" again.

### Steps to Reproduce

1. Install v4.0.0-beta.418
2. Log in
3. Go to "Servers"
4. Choose "localhost"
5. Go to "Proxy" (Traefik)
6. Do any change (I tried to add       - '--accesslog=true' to the command's parameters)
7. "Save"
8. Realize that there is no "Restart Proxy" button

### Coolify Version

v4.0.0-beta.418

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian 12

**Comment by Cinzya** [comment]
I sadly can not reproduce. Do you have any other custom configurations applied to Traefik outside of the accesslog command?

Try pressing `Refresh` at the top. If that doesn't make a difference, you can manually restart the proxy through your servers terminal by running `docker restart coolify-proxy`.

**Comment by Signum** [comment]
Thanks. I wish I could submit the state of the system here to help reproduce it.

"Refresh" did not do much.

Restarting the "coolify-proxy" container did not apply the changed configuration either.

Proxy config in the web UI:

```yaml
version: '3.8'
networks:
  coolify:
    external: true
services:
  traefik:
    container_name: coolify-proxy
    image: 'traefik:v2.11'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - coolify
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/coolify/proxy:/traefik'
    command:
      - '--ping=true'
      - '--ping.entrypoint=http'
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.http.http.encodequerysemicolons=true'
      - '--entryPoints.http.http2.maxConcurrentStreams=50'
      - '--entrypoints.https.http.encodequerysemicolons=true'
      - '--entryPoints.https.http2.maxConcurrentStreams=50'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/traefik/dynamic/'
      - '--providers.file.watch=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--providers.docker=true'
      - '--accesslog=true'

    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - coolify.managed=true
```

(Note the "accesslog=true").

Checking the traefik process shows that this option was not added:

```
root     3910818  2.7  1.7 1452228 142724 ?      Ssl  11:40   0:07 traefik traefik --ping=true --ping.entrypoint=http --api.dashboard=true --api.insecure=true --entrypoints.http.address=:80 --entrypoints.https.address=:443 --entrypoints.http.http.encodequerysemicolons=true --entryPoints.http.http2.maxConcurrentStreams=50 --entrypoints.https.http.encodequerysemicolons=true --entryPoints.https.http2.maxConcurrentStreams=50 --providers.docker.exposedbydefault=false --providers.file.directory=/traefik/dynamic/ --providers.file.watch=true --certificatesresolvers.letsencrypt.acme.httpchallenge=true --certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http --providers.docker=true
```

However when changing the config (e.g. adding an empty line) and clicking "Save" I see a popup reading "Proxy configuration saved.".

The page keeps reading "Configuration out of sync. Restart the proxy to apply the new configurations.".
