### ISSUE TITLE
[Bug]: Backup of docker-compose mongodb doesn't work

### ISSUE THREAD

**Issue by racso-dev** [coollabsio/coolify#5915]
### Error Message and Logs

When I create a **daily** scheduled backup for the Compose-based MongoDB -> No backup job ever triggers (even after waiting >24 h).
When I Click **Backup Now** -> Coolify shows the green toast “Backup added to queue”, **but nothing appears in the queue** and no job starts.

### Steps to Reproduce

1. Deploy MongoDB with a custom docker-compose (see the attached compose used)
2. Open the database → **Backups** tab.  
3. Add a daily schedule.  
4. Wait or press **Backup Now**.  
5. Observe that no backup job reaches the queue.

---

### Expected

- Scheduled backups should execute at the configured time.
- “Backup Now” should enqueue a job that becomes visible in *Queues ▸ Database Backups* and then runs.

### Actual

- Neither scheduled nor manual backups ever reach the queue for Compose-based databases.

### Coolify Version

v4.0.0-beta.418

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

### Environment  
- **Coolify version:** v4.0.0-beta.418
- **Host OS:** Ubuntu 22.04 LTS
- **Database:** MongoDB 8.04 (deployed via **Docker Compose**)  
- **Backup provider / storage:** s3 BackBlaze

---

### Control test (works)

To rule out user error I spun up **a fresh MongoDB using Coolify’s one-click deployment**:

1. Set up identical daily schedule.  
2. Hit **Backup Now**.  
3. Job immediately appears in the queue and starts (it fails later because I haven’t configured TLS certs, but that’s expected).

This suggests the scheduler/queue logic works for one-click databases but **not** for databases deployed via Docker Compose.

---

Relevant parts of docker-compose :
```yml
services:
  mongodb:
    image: 'mongo:8.0.4'
    container_name: mongodb-b0co8ock4gcocwg8ckoko4gs
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD}'
      MONGODB_USERNAME: tendiz_app
      MONGODB_PASSWORD: some_password
      COOLIFY_RESOURCE_UUID: b0co8ock4gcocwg8ckoko4gs
      COOLIFY_CONTAINER_NAME: mongodb-b0co8ock4gcocwg8ckoko4gs
    ports:
      - '27017:27017'
    volumes:
      - 'b0co8ock4gcocwg8ckoko4gs_mongodb-data:/data/db'
    networks:
      tendiz_core_network: null
      b0co8ock4gcocwg8ckoko4gs: null
    healthcheck:
      test:
        - CMD
        - mongosh
        - '--eval'
        - "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.418
      - coolify.serviceId=27
      - coolify.type=service
      - coolify.name=mongodb-b0co8ock4gcocwg8ckoko4gs
      - coolify.resourceName=tendiz-core-data-service
      - coolify.projectName=tendiz-core
      - coolify.serviceName=mongodb
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - coolify.service.subId=24
      - coolify.service.subType=database
      - coolify.service.subName=mongodb
volumes:
  mongodb_data:
    name: tendiz_core_mongodb_data
  b0co8ock4gcocwg8ckoko4gs_mongodb-data:
    name: b0co8ock4gcocwg8ckoko4gs_mongodb-data
networks:
  tendiz_core_network:
    name: tendiz_core_network
  b0co8ock4gcocwg8ckoko4gs:
    name: b0co8ock4gcocwg8ckoko4gs
    external: true
configs: {  }
secrets: {  }
```

Thanks in advance for the time taken to investigate this.
