### ISSUE TITLE
[Bug]: compose deployment ignores includes

### ISSUE THREAD

**Issue by terion-name** [coollabsio/coolify#5921]
### Error Message and Logs

docker-compose.yml:
```yml
include:
  - compose/services.compose.yml

services:
  api:
    image: nginx # whatever
```
compose/services.compose.yml:
```yml
services:
  postgres:
    image: postgres:17
```

Coolify ignores included services and generates internal compose file only with ones specified directly in docker-compose.yml

### Steps to Reproduce

1. Create a compose setup splitted in several files with includes
2. Deploy to coolify

### Coolify Version

v4.0.0-beta.418

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04
