### ISSUE TITLE
[Bug]: coolify does not start correctly when the machine/host restart

### ISSUE THREAD

**Issue by neyunse** [coollabsio/coolify#5933]
### Error Message and Logs

Something that has been happening to me after upgrading to version 4-beta.418 is that the coolify container does not start correctly after the machine reboots. 

Although the container is unhealthy, the services and webs already deployed work correctly. However, it is not possible to access the panel from both the domain and the Ip.

the command I use to reboot is: `sudo shutdown -r`. 

so looking at some issues and looking at coolify I discovered a way to fix it temporarily and that is to stop docker, and delete the coolify-redis data. And finally reboot the machine.

`sudo systemctl stop docker.socket && sudo systemctl stop docker && sudo rm -f /var/lib/docker/volumes/coolify-redis/_data/* && sudo shutdown -r `

### Steps to Reproduce

1. use  sudo shutdown -r
2. docker ps --format "table {{.Names}}\t{{.Status}}"
3.
4.

### Coolify Version

v4.0.0-beta.418

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.2 LTS

## Normal reboot without deleting “coolify-redis/_data/”

Coolify dashboard

![Image](https://github.com/user-attachments/assets/d90be3fa-e2b8-4293-9955-3b3a9fbb6ec3)

![Image](https://github.com/user-attachments/assets/734d98bf-a20e-46cf-b7ba-ce8f7f75fe48)

## Stoping docker & Cleaning the coolify-redis data folder

![Image](https://github.com/user-attachments/assets/4cd609c7-9eeb-4605-8d4c-8ea5629e08a5)

Note: all sites, services work correctly, only the dashboard don't work.

**Extra Note:** sometimes deleting /coolify-redis/_data/ doesn't seem to work, but repeating the process works and the dashboard is available again.

**Extra Note:** sometimes, just by restarting docker, the container becomes healthy again. But this is very rare to happen according to my tests.

**Comment by andrasbacsai** [comment]
Does the redis cleanup solved the issue?

**Comment by neyunse** [comment]
> Does the redis cleanup solved the issue?

Clearing the redis data as I mentioned above is a temporary solution, as it happens again later. So I had to force it with every reboot with the above command.

my machine reboots at night to free up memory, so I added the comand to crono also to clear the redis data before every reboot.


So, I think there is some problem with redis or with the coolify container.

**Comment by neyunse** [comment]
issue updated

**Comment by djsisson** [comment]
@Neyunse the coolify compose has the redis service named as just 'redis' and this will be in the coolify network

do you also happen to have a standalone redis service or a stack like 'owncloud' that you have ticked 'Connect to Predefined Networks'?

the reason is, depending what service comes up first, it's possible your other service connects to coolifys redis first, which prevents coolify from using it

This is a small possibility, but it's my first thought when seeing your container list

ps. there is no need for coolify containers to be in the public network, or even the service name to be called just redis since i believe it uses the container name of coolify-redis

the redis/coolify logs would also be useful to see what the issue is after a restart

**Comment by neyunse** [comment]
> [@Neyunse](https://github.com/Neyunse) the coolify compose has the redis service named as just 'redis' and this will be in the coolify network
> 
> do you also happen to have a standalone redis service or a stack like 'owncloud' that you have ticked 'Connect to Predefined Networks'?
> 
> the reason is, depending what service comes up first, it's possible your other service connects to coolifys redis first, which prevents coolify from using it
> 
> This is a small possibility, but it's my first thought when seeing your container list
> 
> ps. there is no need for coolify containers to be in the public network, or even the service name to be called just redis since i believe it uses the container name of coolify-redis
> 
> the redis/coolify logs would also be useful to see what the issue is after a restart

I am not using the ‘Predefined Network’ option in any service or containers.

[coolify.log](https://github.com/user-attachments/files/20619106/coolify.log)

**Comment by djsisson** [comment]
well i cant see anything in those logs suggesting why coolify would be unhealthy, other than you have jobs taking 5+ seconds

was this taken while coolify was showing unhealthy?

can you run htop and show when coolify is running unhealthy

**Comment by neyunse** [comment]
> well i cant see anything in those logs suggesting why coolify would be unhealthy, other than you have jobs taking 5+ seconds
> 
> was this taken while coolify was showing unhealthy?
> 
> can you run htop and show when coolify is running unhealthy


yes.


![Image](https://github.com/user-attachments/assets/b7bc4a9e-0b04-45ea-aef3-0157d5afdb29)

![Image](https://github.com/user-attachments/assets/aaea8ca7-5c97-4119-a2da-e4dd434edaae)


i tried filtering the coolify container
![Image](https://github.com/user-attachments/assets/e618d70a-0c8b-40c6-bd46-5a54c9f8f755)


![Image](https://github.com/user-attachments/assets/18b4815e-4369-4dd7-adef-d68fb52a87b4)

**Comment by djsisson** [comment]
can you run

```journalctl -u docker.service -S "15 minutes ago"```

you might just need to delete and recreate your redis container

**Comment by neyunse** [comment]
> can you run
> 
> `journalctl -u docker.service -S "15 minutes ago"`
> 
> you might just need to delete and recreate your redis container

```
$ journalctl -u docker.service -S "15 minutes ago"
-- No entries --
```

`$ journalctl -u docker.service --no-pager --since today`

[docker.service.log](https://github.com/user-attachments/files/20634107/docker.service.log)

**Comment by djsisson** [comment]
Can you run
```docker system df```

Also if possible the redis logs

**Comment by neyunse** [comment]
> Can you run `docker system df`
> 
> Also if possible the redis logs

```
▶  docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          21        20        9.686GB   683.8MB (7%)
Containers      20        20        7.602MB   0B (0%)
Local Volumes   19        7         417.3MB   76.04MB (18%)
Build Cache     0         0         0B        0B
```

the coolify-redis from container? 

@djsisson if the problem is owncloud, what can i do?

```
services:
  owncloud:
    image: 'owncloud/server:latest'
    depends_on:
      owncloud-mariadb:
        condition: service_healthy
      owncloud-redis:
        condition: service_healthy
    environment:
      - SERVICE_FQDN_OWNCLOUD_8080
      - 'OWNCLOUD_DOMAIN=${SERVICE_FQDN_OWNCLOUD}'
      - 'OWNCLOUD_TRUSTED_DOMAINS=${SERVICE_URL_OWNCLOUD}'
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_HOST=mariadb
      - 'OWNCLOUD_DB_NAME=${DB_NAME:-owncloud}'
      - 'OWNCLOUD_DB_USERNAME=${SERVICE_USER_MARIADB}'
      - 'OWNCLOUD_DB_PASSWORD=${SERVICE_PASSWORD_MARIADB}'
      - 'OWNCLOUD_ADMIN_USERNAME=${ADMIN_USER:-owncloud}'
      - 'OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD:-owncloud}'
      - 'OWNCLOUD_MYSQL_UTF8MB4=${MYSQL_UTF8MB4:-true}'
      - 'OWNCLOUD_REDIS_ENABLED=${REDIS_ENABLED:-true}'
      - OWNCLOUD_REDIS_HOST=owncloud-redis
    healthcheck:
      test:
        - CMD
        - /usr/bin/healthcheck
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - 'owncloud-data:/mnt/data'
  owncloud-mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_MARIADBROOT}'
      - 'MYSQL_USER=${SERVICE_USER_MARIADB}'
      - 'MYSQL_PASSWORD=${SERVICE_PASSWORD_MARIADB}'
      - 'MYSQL_DATABASE=${DB_NAME:-owncloud}'
      - TZ=auto
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_bin'
      - '--max-allowed-packet=128M'
      - '--innodb-log-file-size=64M'
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 5s
      timeout: 20s
      retries: 10
    volumes:
      - 'owncloud-mysql-data:/var/lib/mysql'
  owncloud-redis:
    image: 'redis:6'
    command:
      - '--databases'
      - '1'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
```
