### ISSUE TITLE
[Bug]: isDatabaseImage() overmatches image names like mongoexpress

### ISSUE THREAD

**Issue by calvinrbnspiess** [coollabsio/coolify#5939]
### Error Message and Logs

Today I experienced a strange issue. Normally, coolify would offer the ability to set up a domain for each service within an application.

<img width="1176" alt="Image" src="https://github.com/user-attachments/assets/1189c68c-a4cd-4cd4-b8f3-67f918afdf5e" />

However, for some services this option is hidden. I looked into the code and there is a function called isDatabaseImage() to determine whether to show or hide the custom domain option. This works in most cases, but images like "mongo-express:latest" are overmatched.

The [isDatabaseImage() function](https://github.com/coollabsio/coolify/blob/fc5138fdef1cdcc97050378a49e5ffdf9d05a883/bootstrap/helpers/docker.php#L740) checks if an image is a database by using `str($imageName)->contains($database_docker_image)`, which can lead to false positives. For example, mongoexpress and mongodb both match 'mongo' in the list, even though mongoexpress is not a database.

**Suggested fix:**
Use exact match (==) or stricter pattern matching to avoid unintended matches on substrings.
Provide an option to disable the automatic database detection.

### Steps to Reproduce

1. Create a new resource based on "Docker Compose empty"
2. Paste the following docker-compose.yaml content:

```yaml
services:
  nginx-hello:
    image: nginxdemos/hello
  mongodb:
    image: 'mongo:latest'
  mongoexpress:
    image: 'mongo-express:latest'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
```

3. You can see the domain input is available for nginx-hello, but not for mongodb and not for mongoexpress. Although mongoexpress is database related, the frontend might be configured accessible for administrative purposes.

### Coolify Version

v4.0.0-beta.418

### Are you using Coolify Cloud?

No (self-hosted)
