### ISSUE TITLE
[Bug]: .env file not created

### ISSUE THREAD

**Issue by abdullahseba** [coollabsio/coolify#6018]
### Error Message and Logs

Hi,

I'm trying to install Teable, and the Docker composer from their Docs includes the following line:

```
  env_file:
      - .env
```
I have tried removing that line and adding the environment variables via Coolify's UI, but this doesn't work. I had the same issue in Portainer, but Portainer creates `stack.env`, which I'm able to substitute for `.env` in the compose file.  It would be useful if Coolify did something similar - unless there are any other workarounds.  Portainer have some details on this in a blog post. https://www.portainer.io/blog/using-env-files-in-stacks-with-portainer 

#2125 is similar to this. 

### Steps to Reproduce

1. Deploy an empty Docker Compose
2. Paste the Docker compose of any project that relies on an .env file being created.  In this case, it was Teable https://help.teable.io/en/deploy/docker#installing-the-application

### Example Repository URL

https://github.com/teableio/teable

### Coolify Version

v4.0.0-beta.419

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debain 12 Bookwork

**Comment by djsisson** [comment]
@abdullahseba the .env is created with the compose file, you will find it next to the compose file in its service directory

you would still need to enter all the env on the ui tab inorder to populate the .env file

if you remove the .env_file line in the first service you would need to enter all the env in the environment section for that service, the .env_file line just means pass all .env into this service, so without it, it won't get any unless you add them all

the portainer link is for swarm stacks, since docker stack won't interpolate, usually you would run compose config, so interpolate and pass the resulting compose into docker stack with an overide to remove a couple of things not compatible, but portainer will just manually add the env lines instead.

**Comment by abdullahseba** [comment]
Thanks for the response.  Not sure why it doesn't work then. I tried lots of things - including deploying from scratch with that line included and all the variables populated in the UI.  In Portainer, the error was identical, and as soon as I changed the line to `stacks.env`, and restarted, the Teable database migration went through successfully.  I was using the stacks in Portainer, although not in a swarm, because that's what allows a Docker Compose file to be pasted in for deployment.

**Comment by djsisson** [comment]
can you list the contents of the directory for this service

/data/coolify/services/uuid/

**Comment by abdullahseba** [comment]
Ah, this is interesting, so there is a `.env` file there but where there should be variables, these areas are blank:

![Image](https://github.com/user-attachments/assets/d9e2367d-49a6-4e7a-8457-2bec9b5cfbcb)

I try setting the redis and DB URL as literals in the UI and restart, but they are still blank.

**Comment by djsisson** [comment]
just add those 2 to the environment section for the teable service.

```yaml
environment:
  - PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  - BACKEND_CACHE_REDIS_URI=redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
```
make sure you remove them from the env tab

also can you check the env tab in dev mode, were those 2 the ones at the bottom?

**Comment by abdullahseba** [comment]
Same issue, tried removing them via the UI, verified that it was removed from the terminal, then added it to the Docker Compose file.  But the migration still fails with an invalid URL.   I did add them to the bottom via the dev view, and that's how I copied them over initially.  They show at the bottom in the UI too, but in the `.env`, they get reordered (alphabetically, I think).  That, in theory, is fine for the DB variables, but not for Redis.

**Comment by djsisson** [comment]
@abdullahseba can you run printenv in the teable container as well as ```docker compose config``` in the service directory

If you can't get it to work then just remove the env_file line and add each env you want to use to that section, like all the templates.

I think adding it to the compose file then makes coolify add it to the env file which then overrides what's in the compose file, 
Although I was sure coolify would keep env in the order they were entered as long as you don't tick alphabetical, but can't check this now

**Comment by abdullahseba** [comment]
I can't run anything in the container because it restarts constantly and the terminal won't connect.  Below is the config.
<details>

<summary>config result</summary>

```
root@debian:/data/coolify/services/w4swcgk8swo4wks8c0w4wgw4# docker compose config
name: w4swcgk8swo4wks8c0w4wgw4
services:
  teable:
    container_name: teable-w4swcgk8swo4wks8c0w4wgw4
    depends_on:
      teable-cache:
        condition: service_healthy
        required: true
      teable-db:
        condition: service_healthy
        required: true
    environment:
      BACKEND_CACHE_REDIS_URI: redis://default:replace_this_password@teable-cache:6379/0
      COOLIFY_CONTAINER_NAME: teable-w4swcgk8swo4wks8c0w4wgw4
      COOLIFY_RESOURCE_UUID: w4swcgk8swo4wks8c0w4wgw4
      NEXT_ENV_IMAGES_ALL_REMOTE: "true"
      PRISMA_DATABASE_URL: postgresql://teable:Replace_this_password#1@teable-db:5432/teable
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:3000/health
      timeout: 3s
      interval: 5s
      retries: 3
      start_period: 5s
    image: ghcr.io/teableio/teable:latest
    labels:
      coolify.environmentName: production
      coolify.managed: "true"
      coolify.name: teable-w4swcgk8swo4wks8c0w4wgw4
      coolify.projectName: tables
      coolify.pullRequestId: "0"
      coolify.resourceName: service-coo444s8ko8o0wcoc0swkw8c
      coolify.service.subId: "112"
      coolify.service.subName: teable
      coolify.service.subType: application
      coolify.serviceId: "42"
      coolify.serviceName: teable
      coolify.type: service
      coolify.version: 4.0.0-beta.419
    networks:
      teable: null
      w4swcgk8swo4wks8c0w4wgw4: null
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: w4swcgk8swo4wks8c0w4wgw4_teable-data
        target: /app/.assets
        volume: {}
  teable-cache:
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - replace_this_password
    container_name: teable-cache-w4swcgk8swo4wks8c0w4wgw4
    environment:
      COOLIFY_CONTAINER_NAME: teable-cache-w4swcgk8swo4wks8c0w4wgw4
      COOLIFY_RESOURCE_UUID: w4swcgk8swo4wks8c0w4wgw4
    expose:
      - "6379"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - --raw
        - incr
        - ping
      timeout: 3s
      interval: 10s
      retries: 3
    image: redis:7.2.4
    labels:
      coolify.environmentName: production
      coolify.managed: "true"
      coolify.name: teable-cache-w4swcgk8swo4wks8c0w4wgw4
      coolify.projectName: tables
      coolify.pullRequestId: "0"
      coolify.resourceName: service-coo444s8ko8o0wcoc0swkw8c
      coolify.service.subId: "36"
      coolify.service.subName: teable-cache
      coolify.service.subType: database
      coolify.serviceId: "42"
      coolify.serviceName: teable-cache
      coolify.type: service
      coolify.version: 4.0.0-beta.419
    networks:
      teable: null
      w4swcgk8swo4wks8c0w4wgw4: null
    restart: always
    volumes:
      - type: volume
        source: w4swcgk8swo4wks8c0w4wgw4_teable-cache
        target: /data
        volume: {}
  teable-db:
    container_name: teable-db-w4swcgk8swo4wks8c0w4wgw4
    environment:
      COOLIFY_CONTAINER_NAME: teable-db-w4swcgk8swo4wks8c0w4wgw4
      COOLIFY_RESOURCE_UUID: w4swcgk8swo4wks8c0w4wgw4
      POSTGRES_DB: teable
      POSTGRES_PASSWORD: Replace_this_password#1
      POSTGRES_USER: teable
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c 'pg_isready -U teable -d teable'
      timeout: 3s
      interval: 10s
      retries: 3
    image: postgres:15.4
    labels:
      coolify.environmentName: production
      coolify.managed: "true"
      coolify.name: teable-db-w4swcgk8swo4wks8c0w4wgw4
      coolify.projectName: tables
      coolify.pullRequestId: "0"
      coolify.resourceName: service-coo444s8ko8o0wcoc0swkw8c
      coolify.service.subId: "35"
      coolify.service.subName: teable-db
      coolify.service.subType: database
      coolify.serviceId: "42"
      coolify.serviceName: teable-db
      coolify.type: service
      coolify.version: 4.0.0-beta.419
    networks:
      teable: null
      w4swcgk8swo4wks8c0w4wgw4: null
    ports:
      - mode: ingress
        target: 5432
        published: "42345"
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: w4swcgk8swo4wks8c0w4wgw4_teable-db
        target: /var/lib/postgresql/data
        volume: {}
networks:
  teable:
    name: teable-network
  w4swcgk8swo4wks8c0w4wgw4:
    name: w4swcgk8swo4wks8c0w4wgw4
    external: true
volumes:
  w4swcgk8swo4wks8c0w4wgw4_teable-cache:
    name: w4swcgk8swo4wks8c0w4wgw4_teable-cache
  w4swcgk8swo4wks8c0w4wgw4_teable-data:
    name: w4swcgk8swo4wks8c0w4wgw4_teable-data
  w4swcgk8swo4wks8c0w4wgw4_teable-db:
    name: w4swcgk8swo4wks8c0w4wgw4_teable-db
```


</details>
