### ISSUE TITLE
[Bug]: Preview Deployments does not work with multi Docker Compose files

### ISSUE THREAD

**Issue by arthur-fontaine** [coollabsio/coolify#6070]
### Error Message and Logs

When a preview deployment is triggered, this is the logs I get:

```log
2025-Jun-27 00:17:06.798662 [CMD]: docker exec f84k0kok0gskg0gg0kg0cokg bash -c 'cd /artifacts/f84k0kok0gskg0gg0kg0cokg && docker compose --project-directory /artifacts/f84k0kok0gskg0gg0kg0cokg -f docker/dependencies.docker-compose.yml -f docker/metrics.docker-compose.yml -f docker/prod.docker-compose.yml build'
2025-Jun-27 00:17:06.798662 service "tempo-pr-64" has neither an image nor a build context specified: invalid compose project
2025-Jun-27 00:17:06.804064 exit status 1
2025-Jun-27 00:17:06.870218 Oops something is not okay, are you okay? 😢
2025-Jun-27 00:17:06.874310 service "tempo-pr-64" has neither an image nor a build context specified: invalid compose project
2025-Jun-27 00:17:06.874310 exit status 1 
```

### Steps to Reproduce

1. Create a Coolify instance with multi files Docker Compose
2. In one `docker-compose.yaml` define the services, in the other just reference them without specifying any image or build.
3. Enable Preview Deployments and trigger one
4. You will see the error

### Coolify Version

v4.0.0-beta.420.1

### Are you using Coolify Cloud?

No (self-hosted)

#### My current setup

My application builds with the following command

```sh
docker compose -f docker/dependencies.docker-compose.yml -f docker/metrics.docker-compose.yml -f docker/prod.docker-compose.yml build
```

I set the `Docker Compose Location` to `prod.docker-compose.yaml`.

This is my `prod.docker-compose.yml`:

```yml
name: ripste-prod

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
      target: api
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - OTLP_URL=http://tempo:4317
    env_file:
      - path: .env
        required: false

  # Reference services from dependencies and metrics
  # Making services available in all other services
  # Making services available to reference in Coolify
  grafana:
  prometheus:
  tempo:
  loki:
  postgres:
  redis:
```

Real definition of the services (except api) is in `dependencies.docker-compose.yml` and `metrics.docker-compose.yml` where the images are specified.

#### Normal behavior

So what Coolify does (I think) in a "normal" deployment:

 - treat the services available in my prod config by adding some Coolify specific configuration
 - replace the `prod.docker-compose.yml` by the newly generated file

#### Cause of the bad behavior

In preview deployments, in addition to the original edits, the service names (keys under the `services` entry) are also renamed to `{container_name}-pr-{id_pr}` (it's also the new `container_name`).

However, as the images for Postgres or all services are set in `dependencies.docker-compose.yml` and `metrics.docker-compose.yml`, and that those files are not modified because they are not specified in `Docker Compose Location`, the service names do not match anymore, and the newly generated `prod.docker-compose.yml` does not have the image information (that came from the other compose files).

I think the issue is here:

https://github.com/coollabsio/coolify/blob/abde78094a2b50df769691b944fe040817736162/app/Jobs/ApplicationDeploymentJob.php#L1766

I know that Coolify does not officially support multi files Docker Compose, however I think this issue with multi files Docker Compose and Preview Deployments could be fixed by remove the renaming of the services.

I think this will not have an impact on other features like rolling updates, because we would still keep the `container_name` value edit and will just change/"let as it is" the service name with which Docker Compose reference between them.
