### ISSUE TITLE
Ability to add existing Docker/docker-compose apps to coolify

### ISSUE THREAD

**Issue by Soneji** [coollabsio/coolify#81]
If you have an existing docker/docker-compose app with a bunch of your own data, it would be great to be able to link it to traefik so you can use it with your coolify instance

**Comment by andrasbacsai** [comment]
Currently, you can manually add the required service labels to your docker service. 

_Note: This is not a supported way to use Coolify atm (you won't see this service in Coolify), but I like it so that I will add such a feature to the next version!_

Add the following labels to your service.

```bash
docker service update --label-add "traefik.enable": "true" <ServiceName>
docker service update --label-add "traefik.http.routers.<SomeRandomNameHere>.entrypoints=websecure" <ServiceName>
docker service update --label-add "traefik.http.routers.<SomeRandomNameHere>.middlewares=global-compress" <ServiceName>
docker service update --label-add "traefik.http.routers.<SomeRandomNameHere>.rule=Host(`<YourDomainName>`)" <ServiceName>
docker service update --label-add "traefik.http.routers.<SomeRandomNameHere>.tls.certresolver=letsencrypt" <ServiceName>
docker service update --label-add "traefik.http.services.<SomeRandomNameHere>.loadbalancer.server.port=<Port>" <ServiceName>
```

Where:
**SomeRandomNameHere** => It could be anything. It just needs to be unique between docker services.
**ServiceName** => The service name you would like to add labels.
**YourDomainName** => The domain name you would like your app to be hosted.
**Port** => The port number your application is listening on.

The reverse proxy will detect this change and configures itself automatically.

**Comment by Soneji** [comment]
Thanks so much for the help @andrasbacsai 
I am new to swarm so I've documented the process here to get it working :)

Steps to setup

Add this to your `docker-compose.yml` for whatever service you want to add to coolify
```yml
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.XXX.entrypoints=websecure'
        - 'traefik.http.routers.XXX.middlewares=global-compress'
        - 'traefik.http.routers.XXX.rule=Host(`XXX.com`)'
        - 'traefik.http.routers.XXX.tls.certresolver=letsencrypt'
        - 'traefik.http.services.XXX.loadbalancer.server.port=XXX'
    networks:
      - coollabs
      - default
```
replacing XXX with appropriate info (see above)

Then run: 
```sh
docker stack deploy --compose-file docker-compose.yml NAME_OF_STACK
```
and choose any name you like to refer to the stack later.

You can use `docker stack ls` to see the stacks (like a set of compose files) and `docker service ls` to see all the services (list of containers in swarm)

@andrasbacsai Feel free to close this if you think that's best, or let me know if you want to leave it open until an integration can be implemented into coolify to view these non-standard stacks, or until this is properly documented.
