### ISSUE TITLE
Enabling traefik dashboard

### ISSUE THREAD

**Issue by Soneji** [coollabsio/coolify#82]
I thought I'd leave this here in case anybody else needed it, since there's no documentation. Feel free to close

To enable traefik dashboard you must first modify `/root/coollabs/coolify/install/coolify-template.yml`

Edit the traefik service to include this in the ports section
```yml
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
```
and change the values from `false` to `true`
```yml
      - --api.insecure=true
      - --api.dashboard=true
```

Then make sure you're in the `/root/coollabs/coolify` directory and run:
```sh
docker stack rm coollabs-coolify &&
    set -a &&
    source .env &&
    set +a &&
    envsubst < install/coolify-template.yml | docker stack deploy -c - coollabs-coolify
```
