### ISSUE TITLE
[Bug]: Cannot set IP in networks: with Docker compose

### ISSUE THREAD

**Issue by usr3** [coollabsio/coolify#928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

https://github.com/usr3/mailu-coolify

### Description

I'm running [Mailu](https://github.com/Mailu/Mailu) with coolify. Mailu comes with a pre-configured Unbound DNS resolver to provide DNSSEC and anti-spam features. Unbound needs to set a static IP in the network. Importing the _docker-compose.yml_ throws the following error in Coolify:

`[9:30:57.603] Configuration changed`
`[9:30:59.994] {}`
`[9:30:59.998] (value.networks || "") is not iterable`

Excerpt of the docker-compose.yml:
```
  front:
      image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
      ports:
        - "465:465"
        ...
      depends_on:
        - resolver
      dns:
        - 172.16.31.254

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    networks:
      default:
        ipv4_address: 172.16.31.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
    ...
    dns:
      - 172.16.31.254

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.16.0/20
```

### Steps To Reproduce

1. Load the repository containing the docker-compose.yml
2. Click Docker Compose
3. Add secrets from .env
4. Click Deploy

### Version

3.12.17
