### ISSUE TITLE
[Bug]: docker compose NODE_ENV provlem

### ISSUE THREAD

**Issue by deecewan** [coollabsio/coolify#962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

deecewan/coolify-node-env-docker-compose-example

### Description

Check the repo for an example `docker-compose.yml`.

For this docker-compose.yml:

```yml
services:
  first:
    image: node
    command: node -e 'console.log("env", process.env.NODE_ENV)'
  second:
    image: node
    environment:
      NODE_ENV: production
    command: node -e 'console.log("env", process.env.NODE_ENV)'
```

the coolify builds fails with this error:

```
[10:35:39.177] Cloning deecewan/coolify-node-env-docker-compose-example:main...
[10:35:44.058] {}
[10:35:44.068] Cannot read properties of undefined (reading 'port')
```

If there is just 1 service, the issue doesn't happen.

For example, this docker-compose.yml:

```yml
services:
  second:
    image: node
    environment:
      NODE_ENV: production
    command: node -e 'console.log("env", process.env.NODE_ENV)'
```

builds fine.

### Steps To Reproduce

- Create a new coolify application from a github repo
- Use `deecewan/coolify-node-env-docker-compose-example`
- The build will fail

### Version

v3.12.21
